### ISSUE TITLE
Documentation discrepancy between official documentation and types

### ISSUE THREAD

**Issue by LinusU** [stripe/stripe-node#1004]
On the official API documentation, `net` on a `BalanceTransaction` is documented as being in cents:

https://stripe.com/docs/api/balance_transactions/object?lang=node#balance_transaction_object-net

But in the TypeScript definitions for this library it's documented as percents:

https://github.com/stripe/stripe-node/blob/9bab8b6e4d20b13c7135232456f1d1e894b1e49d/types/2020-08-27/BalanceTransactions.d.ts#L58-L61

**Comment by remi-stripe** [comment]
@LinusU  Thanks for reaching out. This is unfortunately a known bug we hope to fix in the future. Going to tag as future

**Comment by pakrym-stripe** [comment]
This is [now fixed](https://github.com/stripe/stripe-node/blob/master/types/BalanceTransactions.d.ts#L63)
