### ISSUE TITLE
Documentation gives card expiration dates in numbers

### ISSUE THREAD

**Issue by jackHedaya** [stripe/stripe-node#1008]
The Stripe documentation <a href="https://stripe.com/docs/api/tokens/create_card">here</a> displays `exp_month` and `exp_year` as numbers while `TokenCreateParams.Card` expects `exp_month` and `exp_year` to be strings.

**Comment by remi-stripe** [comment]
@jackHedaya Both just work fine but our spec expects strings by default which is what the types recommend, but you can send both without issues.
