### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Received unknown parameter: object

### ISSUE THREAD

**Issue by vishnutm** [stripe/stripe-node#1009]
```function createCustomerAndSubscription(requestBody) {
  return stripe.customers.create({
    source: requestBody.stripeToken,
    email: requestBody.customerEmail,

  }).then(customer => {
    stripe.subscriptions.create({
      object: customer.object,
      customer: customer.id,

      items: [
        {
          plan: requestBody.planId
        }
      ],
      collection_method: 'send_invoice',
      days_until_due: 30
    });
    console.log("customerDetails ", customer);
  });

}
```
when I tried to create customer and subscription using the above function I got the same error. my payment method card number is 4242 4242.etc

> The source hash must include an 'object' key indicating what type of source to create." something like this" . i don't know what is happening..?. Help needed.

**Comment by remi-stripe** [comment]
@vishnutm Github issues should be limited to bugs with the stripe-node library. Unfortunately this is not a support forum and you need to talk to our support team for help on this instead.

The code you shared is not the same as what the error covers and you must be mixing a few things here so our support team is the best avenue. Please contact them here: https://support.stripe.com/contact
