### ISSUE TITLE
The Amount field Shows Null when tiered Subscription created.But Normal plans work fine.

### ISSUE THREAD

**Issue by vishnutm** [stripe/stripe-node#1015]
I created a function for subscription plans, when I pass the normal plan id it will show the correct amount and invoices part. but when I pass the tier plan id the invoice part the amount always shows null.
The function which I am using this 
```
async function createSubscription(requestBody) {

  try {
    const subscription = await  stripe.subscriptions.create({

      customer : requestBody.customerId,
      items:[
        {
          plan:requestBody.planID,
        }
      ],
      expand:['latest_invoice.payment_intent'],
      collection_method:requestBody.collection_method,
      days_until_due:requestBody.days_until_due

    })
    console.log("subscription details",subscription);
    return subscription
  } catch (error) {
    console.log(error);
  }
}
```

OUTPUT: receiving  : 
![Screenshot from 2020-09-24 11-44-17](https://user-images.githubusercontent.com/30982642/94107657-8bd9b080-fe5b-11ea-96cd-1fad04638870.png)

![Screenshot from 2020-09-24 11-48-39](https://user-images.githubusercontent.com/30982642/94107870-ec68ed80-fe5b-11ea-80eb-66f7975b9e69.png)

Help needed. How do I rectify this problem?

**Comment by remi-stripe** [comment]
@vishnutm I'm going to close this issue as it's a simple support question about our API and unrelated to an issue with the stripe-node library. Please work with our support team for questions like this instead: https://support.stripe.com/contact
