### ISSUE TITLE
Passing App Info without using SDK

### ISSUE THREAD

**Issue by yusuf-musleh** [stripe/stripe-node#1017]
Hello!

I wanted to ask if it's possible to pass in the AppInfo (specifically the `partner_id`) without using the SDK. I noticed that the app info is passed in the `User-Agent` header of the request in addition to other things like the API and package versions:

https://github.com/stripe/stripe-node/blob/e4fdc7a15e2c3449b8f518985cba450014e25f95/lib/StripeResource.js#L358-L365

Would it work if I'm making my own HTTP requests (without using the SDK) by passing the app info in the `User-Agent` header of my requests in the same format (minus the first part `Stripe/v1 NodeBindings/${packageVersion}`)? Or is there another way you'd recommend?

Thanks!

**Comment by paulasjes-stripe** [comment]
Can I ask what your use case is for passing in AppInfo without using the SDK? 

As you noticed the app info is just a header in the request, so there's nothing stopping you from making API requests with that header without the stripe-node library.

**Comment by paulasjes-stripe** [comment]
Either way please be sure to pass in all information about your plugin alongside the user-agent as that really helps us out if we need to get in touch with you later: https://stripe.com/docs/building-plugins#setappinfo

**Comment by yusuf-musleh** [comment]
Hi @paulasjes-stripe thanks for the quick response!

The reason why I'm not using the SDK is because I'm generating the code from the OpenAPI spec and I have a standard way of making requests to APIs, that way I wouldn't have to implement custom logic for different APIs when going through different providers' OpenAPI Specs.

I'll pass in all the app info in the same format in the user-agent header as you mentioned.

Thanks!

**Comment by yusuf-musleh** [comment]
@paulasjes-stripe another quick question. I just noticed that the `partner_id` is not actually passed in the `user-agent` header along with the other app info stuff. I can't seem to find it being used or sent to Stripe anywhere in the code. Is there something I am missing?

**Comment by paulasjes-stripe** [comment]
@yusuf-musleh It gets sent as part of the `userAgent.application` object here: https://github.com/stripe/stripe-node/blob/c778a4b03e98386b59664b31b9f786ddf3bc22c7/lib/stripe.js#L435-L437

**Comment by yusuf-musleh** [comment]
@paulasjes-stripe I see, got it, thanks for pointing it out for me.
