### ISSUE TITLE
Error getting account link

### ISSUE THREAD

**Issue by sloanbholzman** [stripe/stripe-node#1047]
Hi,

From my node server, I tried the following:

```
const stripe = new Stripe(<secretKey>, { apiVersion: '2020-03-02' })

stripe.accountLinks.create({
      account: <linkedAccountId>,
      refresh_url: <html>,
      return_url: <html>,
      type: 'account_update',
    })

```

for certain accounts, I get this error:

```
You must have a client application set in order to make this request.
```
and for other accounts, I get this error:

```
Invalid type: must be one of ["account_onboarding"]
```

Could you please assist?

Thank you.

**Comment by remi-stripe** [comment]
@sloanbholzman The first error likely indicates that this account is not a Connect platform, and the second error indicates that you are trying to create an AccountLink for an account that isn't a Custom account (and `connect_onboarding` is only allowed for those specific accounts).

This isn't really an issue with stripe-node itself and github issues here should be limited to bugs with the library. I'm going to close this out but you should reach out to our support team if you have any follow up questions: https://support.stripe.com/contact
