### ISSUE TITLE
TypeScript: Updating a subscriptions default_tax_rates is incomplete

### ISSUE THREAD

**Issue by Bene-Graham** [stripe/stripe-node#1051]
Node: 14.13.1
Stripe Lib: 8.116.0

The type `SubscriptionUpdateParams` has a field called `default_tax_rates` with the following comment: 

```
The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription. Pass an empty string to remove previously-defined tax rates.
```

It states to pass an empty string to remove the tax rates, which the typings don't allow.

**Comment by richardm-stripe** [comment]
Hi @Bene-Graham, sorry about the confusion here. You ought to use `null` here. `stripe-node` converts null to empty string over the wire (null is a more idiomatic way of deleting something in Javascript, but Stripe's API uses URL encoding, which has no concept of null), and we generate the docstring from a source that describes the parameter from the API's perspective, not node's.

**Comment by Bene-Graham** [comment]
@richardm-stripe Perfect, that worked. Thank you for your help.
