### ISSUE TITLE
maxNetworkRetries setting does not work

### ISSUE THREAD

**Issue by rilian** [stripe/stripe-node#1058]
environment: node v10.x on AWS Lambda
package version `"stripe": "^8.84.0"`

we have the following code in our checkout lambda function, as suggested in official docs https://www.npmjs.com/package/stripe#network-retries

```js
const stripe = require('stripe')(process.env.STRIPE_API_KEY, {
  maxNetworkRetries: 3,
  timeout: 4000,
  telemetry: false,
})

module.exports = async (req, res) => {
  // ...
  await stripe.invoices.pay(invoice.id)
  // ...
}
```

in one of executions it thrown exception

```
Request aborted due to timeout being reached (4000ms)
```

we expected request would be retried at least 3 times, but it *did not*, cause Lambda function duration was ~5000ms

<img width="969" alt="_scr_ 2020-10-28 at 14 34 44" src="https://user-images.githubusercontent.com/155563/97489568-15d2d880-1936-11eb-95f3-344a0db83723.png">

**Comment by ctrudeau-stripe** [comment]
Hello @rilian, I think stripe node works as you expect with respect to **request** timeouts but not **socket** timeouts. Presently the timeout applies only to a request after a connection has been successfully established. Under the hood we set [req.setTimeout](https://github.com/stripe/stripe-node/blob/master/lib/StripeResource.js#L463) and use the value passed into the timeout in the config object. It can also happen that your host OS can not successfully establish a connection in the first place and the timeout here is the socket timeout that is specified by your operating system. Can you give us more details around the error happening where it's printing 'Could not pay Invoice Request aborted due to timeout being reached`? Thank you!

**Comment by rilian** [comment]
hi @ctrudeau-stripe do you have any updates regarding fixing this issue ? we got it again, in a slightly different scenario

in new case, our lambda service was only requesting `stripe.subscriptions.list`, and our stripe configuration is

```
const stripe = require('stripe')(process.env.STRIPE_API_KEY, {
  maxNetworkRetries: 2,
  timeout: 10000,
  telemetry: false,
})
```

and Lambda execution duration was definitely less than time of 2 retries - it ended after 10 sec meaning there was NO retry at all

```
REPORT RequestId: 772f57a3-d020-4788-aba4-70d1d98cdf85	Duration: 10183.32 ms	Billed Duration: 10184 ms	Memory Size: 1024 MB	Max Memory Used: 180 MB	
```

i would like to add that this is a test stripe key, and we did many requests in a loop in parallel, but in any case, even if request was rate limited it had to receive a 429 HTTP status instead of timeout that was not retried

the exception that we got is

```
Error trace: Error: Request aborted due to timeout being reached (10000ms)
    at ClientRequest.<anonymous> (/var/task/node_modules/stripe/lib/StripeResource.js:106:9)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by ctrudeau-stripe** [comment]
Hello @rilian, are you able to verify that you were able to establish a socket? If you were not able to establish a socket the maxNetworkRetries parameter will not work. I'm wondering from your stack trace if the socket was able to establish or not. 

`at TLSSocket.Socket._onTimeout (net.js:443:8)`

**Comment by rilian** [comment]
@ctrudeau-stripe how would you recommend verifying that ?

other 1000s requests today were fine (did not timeout in 10sec)..

**Comment by rilian** [comment]
@ctrudeau-stripe please review ^^

**Comment by remi-stripe** [comment]
@rilian Sorry for the delays! I tagged internally and we'll review this after the holidays!

**Comment by ctrudeau-stripe** [comment]
Hello @rilian sorry for the delays. We've looked into this more and we were not retrying a request that had timed out. We believe we should be respecting the retries for those as you expect. The above PR #1104 will be merged in the next major release.

**Comment by rilian** [comment]
@ctrudeau-stripe thank you, i'll subscribe to that PR and will watch for release

**Comment by rilian** [comment]
hi @ctrudeau-stripe . i watched for stripe-node releases and this was not merged in last 2 releases. Can you please clarify what you mean by "next major version". Do you plan to fix it in v9 ? ... thank you! It's very important fix for stability of payments for all customers

**Comment by richardm-stripe** [comment]
Hi @rilian, thanks for following up. After some internal discussion, we've decided to consider this change a non-breaking bugfix, since the API is preserved, and this has been released in [v8.131.1](https://github.com/stripe/stripe-node/releases/tag/v8.131.1).

**Comment by rilian** [comment]
@richardm-stripe fantastic, thank you!

**Comment by rilian** [comment]
@richardm-stripe 
today we again got `Error: Error: ESOCKETTIMEDOUT` in the request to create InvoiceItem

using `    "stripe": "^8.132.0",`

request timed out after 10 sec, with this configuration:
```
const stripe = require('stripe')(process.env.STRIPE_API_KEY, {
  maxNetworkRetries: 2,
  timeout: 10000,
  telemetry: false,
})
```

and was not retried.

with configuration above we expected it to be retried at least 2 times

timing report from Lambda:
```
REPORT RequestId: 1d25bfe9-1661-4351-a741-cb462da76199	Duration: 10697.11 ms	Billed Duration: 10698 ms	
```
