### ISSUE TITLE
Feature Request: Uncheck 'Billing address is same as shipping' by default option

### ISSUE THREAD

**Issue by JaffaKetchup** [stripe/stripe-node#1059]
Hello,

I have a feature request that I think would just be nice to have and easy to implement.

At the current time, if you have shipping address collection on and billing address collection set to 'required' it only shows a checkbox 'Billing address is same as shipping' that can be unchecked to enter a different billing address. In my circumstance, the default behaviour is to send the goods somewhere else that the billing address.

I would like a new setting for 'billing_address_collection': 'forceWithShipping'. This would only apply if shipping information is being collected else it would act as 'auto'. It would uncheck the 'Billing address is same as shipping' by default, but leave it checkable so if the customer wants it sent to the same address, they still can.

Thank you,
Luka S

**Comment by remi-stripe** [comment]
@JaffaKetchup Thanks for reaching out. Github issues should be limited to bugs in the library itself. Since your question is a feature request about the API instead, we recommend that you reach out to our support team directly to raise your interest for this feature. You can contact support here: https://support.stripe.com/contact

**Comment by JaffaKetchup** [comment]
> @JaffaKetchup Thanks for reaching out. Github issues should be limited to bugs in the library itself. Since your question is a feature request about the API instead, we recommend that you reach out to our support team directly to raise your interest for this feature. You can contact support here: https://support.stripe.com/contact

Hello and thank you for replying. I have previously contacted Stripe support about this, and whilst they are normally great, the agent kept giving me a useless link to extensions for Stripe. I asked "Could he just leave a feature request for this?", and he just came back with the link.
