### ISSUE TITLE
StripeConnectionError: An error occurred with our connection to Stripe.

### ISSUE THREAD

**Issue by akesling** [stripe/stripe-node#1062]
**Node Version**:  v10.21.0 (necessary for running as a [Firebase Function](https://firebase.google.com/docs/functions))
**Node Platform**: MacOS 10.15.1
**Node Environment**: mocha w/ ts-node (though this is unlikely to be relevant, I figured I'd include it for completeness)

**Setup**:
I'm trying to use stripe-node with [stripe-mock](https://github.com/stripe/stripe-mock).  I've verified that stripe-mock is available on ports `12111` and `12112` (https) via telnet.  If I use `setHost`/`setPort` as per the recommendation in https://github.com/stripe/stripe-node/issues/472, I get the following:
```
(node:18416) Stripe: `setHost` is deprecated. Use the `host` config option instead.
(node:18416) Stripe: `setPort` is deprecated. Use the `port` config option instead.
```
Thus, I'm trying to use the [`host`](https://github.com/stripe/stripe-node/blob/f8b31945ab4cfb9fe0ee375e3308d719eb5be593/types/lib.d.ts#L88) and [`port`](https://github.com/stripe/stripe-node/blob/f8b31945ab4cfb9fe0ee375e3308d719eb5be593/types/lib.d.ts#L90) fields of the [`Stripe.StripeConfig`](https://github.com/stripe/stripe-node/blob/f8b31945ab4cfb9fe0ee375e3308d719eb5be593/types/lib.d.ts#L48) option object.

**Expectation**:
That I'd be able to connect to the stripe-mock server from within tests.

**Minimal failing example (TypeScript)**:
```typescript
    it('connects to stripe mock', async function () {
      const stripeHandle = new Stripe(
        ACTUAL_STRIPE_TEST_ENVIRONMENT_SECRET,
        {
          host: '127.0.0.1',
          port: 12111,
        } as Stripe.StripeConfig)

      await stripeHandle.customers.create({
        email: 'test-user-id--stripe-mock@testdomain.com',
      });
    });
```

This example succeeds if I replace `stripeHandle` with the following:
```typescript
const stripeHandle = new Stripe(ACTUAL_STRIPE_TEST_ENVIRONMENT_SECRET, {} as Stripe.StripeConfig)
```

Though then I'm not trying to connect to the stripe-mock server at all....  At least this demonstrates it's not strictly an environment issue.

**Error readout**:
```
Error: An error occurred with our connection to Stripe.
      at /<PROJECT_PATH_ELIDED>/node_modules/stripe/lib/StripeResource.js:234:9
      at ClientRequest.req.on (node_modules/stripe/lib/StripeResource.js:489:67)
      at TLSSocket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:91:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

I get the same error whether I provide the port `12111` or `12112`, whether I provide a real Stripe secret or an arbitrary string, and whether I provide `127.0.0.1` or `localhost`.

Any ideas?

**Comment by remi-stripe** [comment]
@akesling Thanks for reaching out! Our stripe-node library will use HTTPS by default. What you should do here is choose the port 12111 and switch the protocol to HTTP instead. Here's what works for me:

```
const stripe = require('stripe')(
  'sk_test_123',
  {
    host: '127.0.0.1',
    protocol: 'http',
    port: '12111',
  }
);

// Create a new customer and then a new charge for that customer:
stripe.customers.create({
  email: 'foo-customer@example.com'
}).then(function(customer) {
  console.log(customer.id);
}, function(err) {
  console.log("Error :(\n", JSON.stringify(err));
});
```

When I try to use the port 12112 I get a cryptic error `DEPTH_ZERO_SELF_SIGNED_CERT`. This can be solved by disabling TLS verification but I wouldn't recommend this (though it's easy to google!). Hopefully switching to HTTP though works for you!

**Comment by akesling** [comment]
Excellent, thank you.

For posterity, here's a working version of the previously failing example:
```typescript
    it('connects to stripe mock', async function () {
      const stripeHandle = new Stripe(
        'sk_test_123-FAKE-TEST-KEY',
        {
          host: '127.0.0.1',
          protocol: 'http',
          port: 12111,
        } as Stripe.StripeConfig)

      await stripeHandle.customers.create({
        email: 'test-user-id--stripe-mock@testdomain.com',
      });
    });
```

**Comment by songshiqiang** [comment]
I encountered the same error on Cloudflare Workers, and the root cause is that **[unenv] https.request is not implemented yet!** . The stripe-node library will use HTTPS by default. I changed it to:

`const stripe = new Stripe(process.env.STRIPE_PRIVATE_KEY || "", {
    httpClient: Stripe.createFetchHttpClient()
});`

And it worked!
