### ISSUE TITLE
Add negative amount in line_items (as discount)

### ISSUE THREAD

**Issue by anthonycluse** [stripe/stripe-node#1065]
Hello,

I need to add an items as a discount with a negative amount.

Is that possible to pass a new object in `line_items` with a negative amount ? Or, is there any solution to reduce the total price only on a few products ?

**Comment by remi-stripe** [comment]
Hello. Github issues should be limited to bugs or feature requests with the library itself and your question is more a question about the product/API itself. I'm going to close this out and redirect you to our support team instead: https://support.stripe.com/contact

To unblock you though it isn't possible to pass a negative line item today. If you want to discount the amount associated with a Checkout Session, you should use Coupons or PromotionCodes as documented here: https://stripe.com/docs/payments/checkout/discounts
