### ISSUE TITLE
Webhook signing does not work express JS

### ISSUE THREAD

**Issue by kondricz** [stripe/stripe-node#1067]
Hello everyone,

One more ticket about webhooks...
Obviously I researched most of the existing github and stackoverflow tickets, but I keep receiving the very same error message. 

```
❌ Error message: No signatures found matching the expected signature for payload. Are you passing the raw request  body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
--
```

I am pretty sure it is familiar for many of You 😄. But with this screenshot, it gets really interesting:

![image](https://user-images.githubusercontent.com/30053409/99317154-daa53480-2865-11eb-968a-40bd1403cc17.png)

- Right side => WEBHOOK test payload from stripe dashboard
- Left side => incoming WH payload logged (after converting it from Buffer)

In the code, everything else is commented out but the raw data parser:

```
  // appObject.use(cors({ origin: true }));
  // appObject.use((req, res, next) => (req.originalUrl === routes.WH_STRIPE ? next() : bodyParser.json()(req, res, next)));
  // appObject.use((req, res, next) => (req.originalUrl === routes.WH_STRIPE ? next() : bodyParser.urlencoded({ extended: false })(req, res, next)));
  // appObject.use(limiter);
  // appObject.use(fileMiddleware);
  // appObject.use(morgan('combined'));
  appObject.use(bodyParser.raw({ type: '*/*' }));
```

And the `constructEvent` method:

```
const constructEvent = async (req, res, next) => {
  if (!provider) {
    init();
  }

  const raw = Buffer.from(req.body, 'base64').toString('utf8');
  console.log(raw);

  try {
    const stripeEvent = provider.webhooks.constructEvent(
      raw,
      req.headers['stripe-signature'],
      process.env.STRIPE_SECRET_KEY
    );
    console.log('EVENT success: ', stripeEvent);
    res.locals.stripeEvent = stripeEvent;
    return next();
  } catch (err) {
    console.log(`❌ Error message: ${err.message}`);
    return next(serverStatuses.STATUS_ERROR);
  }
};
```

Any idea? I tried to exclude every aspect, but already giving it up.

I am using GCP functions, but my local environment is plain express JS.
Thank You for your time and effort in advance,

PS: You guys are making a great product! 💸

**Comment by richardm-stripe** [comment]
Hi @kondricz. Something that sticks out to me is the `process.env.STRIPE_SECRET_KEY`,
```javascript
    const stripeEvent = provider.webhooks.constructEvent(
      raw,
      req.headers['stripe-signature'],
      process.env.STRIPE_SECRET_KEY
    );
```

You usually want to pass a webhook signing key (begins with `whsec_`) to constructEvent (see [here](https://stripe.com/docs/webhooks/signatures#verify-official-libraries).

If that's not it, I recommend contacting Stripe support. I don't *think* this is a bug in stripe-node, and support can help you get to the root of the problem a bit more interactively than we can here.

**Comment by kondricz** [comment]
Thank You, it makes sense. I was so focused about the incoming request's body, that I did not see that the third argument is no the SECRET_KEY but another type of secret. I will confirm You, if it solves the problem.

**Comment by kondricz** [comment]
This was it. Thank You!
