### ISSUE TITLE
Versions have gone backwards

### ISSUE THREAD

**Issue by chrisvariety** [stripe/stripe-node#1071]
Latest version is v7.63.0, but the version before that was v8.121.0? 

https://github.com/stripe/stripe-node/commit/e421d4bc6ca4074e4fbf15b5fa32441c11d541c5

**Comment by paulasjes-stripe** [comment]
Thanks for the report! This has now been fixed here: https://github.com/stripe/stripe-node/commit/cae8494bff018e30a92e5bea06d25545e81601d3
