### ISSUE TITLE
You may only specify one of these parameters: allow_promotion_codes, discounts.

### ISSUE THREAD

**Issue by Frenchcooc** [stripe/stripe-node#1076]
While implementing a Black Friday discount for my company, I've encountered something strange in Stripe for Node.js. The SDK throws an error when the checkout session has both `allow_promotion_codes` and `discounts` properties, even if one of these is set to `null`

Here's a minimal reproducible snippet using Stripe Checkout and Express.js: 

```js
// Initialize Stripe
const stripe = require('stripe')('sk_test_xxx');

// Apply global discount if the request body has a "blackfriday" input 
const discounts = req.body.blackfriday ? [{ coupon: '{{BF_COUPON_ID}}' }] : null;

// Allow for promotion code by default, except if a discount is already provided
const allow_promotion_codes = !Array.isArray(discounts) ? true : null

// Create Stripe Checkout's session
const session = await stripe.checkout.sessions.create({
  payment_method_types: ['card'],
  line_items: [{
    price: '{{PRICE_ID}}',
    quantity: 1,
  }],
  mode: 'subscription',
  discounts, // -> will be an "array" or "null"
  allow_promotion_codes, // -> will be a "boolean" (true) or "null"
  success_url: 'https://example.com/success',
  cancel_url: 'https://example.com/cancel',
});
```

This snippet throws the following error message: `You may only specify one of these parameters: allow_promotion_codes, discounts.`.

While the error message is very self-descriptive (as always with Stripe), the expected output would be that the SDK accepts `discounts` and `allow_promotions_code` if one of these is set to `null` (or `false`). But that doesn't work. To make it work, to explicitly delete one of the property such as follow:

```js
// ...
// Prepare Stripe Checkout's session options
const sessionOptions = {
  payment_method_types: ['card'],
  line_items: [{
    price: '{{PRICE_ID}}',
    quantity: 1,
  }],
  mode: 'subscription',
  discounts, // -> will be an "array" or "null"
  allow_promotion_codes, // -> will be a "boolean" (true) or "null"
  success_url: 'https://example.com/success',
  cancel_url: 'https://example.com/cancel',
};

// Delete discounts or allow_promotion_codes properties
if (discounts.length) {
  delete sessionOptions.allow_promotion_codes
} else {
  delete sessionOptions.discounts
}

// Create Stripe Checkout's session
const session = await stripe.checkout.sessions.create(sessionOptions);
```

**Comment by Frenchcooc** [comment]
Seems to work as expected if you use `undefined` instead of `null`. ¯\_(ツ)_/¯

**Comment by remi-stripe** [comment]
@Frenchcooc passing `null` in your code makes stripe-node send `allow_promotion_codes: ""`. This is how you unset properties in the API today. Because of this, our API sees both parameters but they are exclusive. If you only sent `allow_prmotion_codes: null`, you'd see a different error message `Invalid boolean:` though it's more confusing.

We do expect you to only send the correct parameter that you want to enable though it's definitely not easy to discover by yourself.

Since it's not really a bug with stripe-node and more a quirk of the API and how we encode parameters, I'm going to close this but let me know if you have more questions!
