### ISSUE TITLE
What's the recommended way to manage the default payment method?

### ISSUE THREAD

**Issue by xinghul** [stripe/stripe-node#1081]
I have a backend setup to add multiple payment methods per customer using `SetupIntent`, everything works great.

However, I need to charge the customer regularly(not through a subscription), so I need to figure out which card is the default one. I know I can assign the default payment method from the Stripe console:
![Screen Shot 2020-11-29 at 3 48 25 PM](https://user-images.githubusercontent.com/6555861/100556906-60f44a00-325a-11eb-9ca3-e421aae2735c.png)

My questions:
1. Is there a way to set the default payment method using the Stripe API?
2. Even better, is there a config I can set so that the latest added payment method(using `SetupIntent`) is going to be the default payment method?
3. When listing the payment methods for a given customer(stripe.paymentMethods.list), how do I find out which payment method is the default?

Thank you!

**Comment by paulasjes-stripe** [comment]
This isn't an issue relating to the stripe-node library so I'm going to close it. Please reach out to Stripe support directly if you have questions concerning the API: https://support.stripe.com/contact

To unblock you however, there's no concept of a default PaymentMethod in the API. When creating PaymentIntents you must always specify a PaymentMethod to use, even if you also pass in a Customer ID. 

A customer does have an invoicing default PaymentMethod, which is the PaymentMethod that will be used by default for subscriptions: https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method

**Comment by xinghul** [comment]
@paulasjes-stripe that actually answered my question, thank you!
