### ISSUE TITLE
Setup Intents for 3D Secure Testing Cards have status: "succeeded" instead of ""requires_action"

### ISSUE THREAD

**Issue by natedx** [stripe/stripe-node#1083]
Hello,

### Issue Description

I am testing my integration, which allows users to create subscriptions using cards. I am following the Metered Billing Guide with Elements available here:  [Metered Billing Guide](https://stripe.com/docs/billing/subscriptions/metered). 
I use Node 14.15.0 and stripe.js 8.125.0.

On step 9, [Manage Payment Authentication](https://stripe.com/docs/billing/subscriptions/metered#manage-payment-authentication), I have run into two issues.

Firstly, the response from `createSubscription` no longer contains the Setup Intent object in `pending_setup_intent` , but rather just the Setup Intent Id. To solve that, I have used the Node API to fetch the Setup Intent object using `stripe.setupIntents.retrieve(
        'seti_1HrRiXDD19gY9maJ76ppfl9P');`

Secondly, the main issue is that when testing my integration with the cards available at  [stripe.com/docs/testing](https://stripe.com/docs/testing), all the 3D secure testing cards return a Setup Intent object with status "succeeded" instead of "requires_action".
My understanding from the [Testing the 3D secure flow guide](https://stripe.com/docs/payments/3d-secure#when-to-use-3d-secure) is that if the API returns a setup intent with status: "requires_action", one can validate the card using 
`stripe.confirmCardSetup(setupIntent.client_secret, {
                    payment_method: paymentMethodId,
                })` which will show a modal allowing 3D secure authentication.

### Example Response

Here is an example response of my `pending_setup_intent` request when I create a subscription for the card `4000000000003220`
with description: "3D Secure 2 authentication must be completed for the payment to be successful. By default, your Radar rules will request 3D Secure authentication for this card."

```
"pending_setup_intent": {
    "id": "seti_1HrRiXAD19gY9FaJ76wpfl9P",
    "object": "setup_intent",
    "application": null,
    "cancellation_reason": null,
    "client_secret": "seti_1HrRiXAD19gY9FaJ76wpfl9P_secret_ISMRdmJn2RL6AHJAHalBFwNov3SaVII",
    "created": 1606325025,
    "customer": "cus_IRyfV1P51CKkHE",
    "description": null,
    "last_setup_error": null,
    "latest_attempt": "setatt_1HrRiXAD19gY9FaJgKaRyZCv",
    "livemode": false,
    "mandate": null,
    "metadata": {},
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": "card_1HrRiDAD19gY9FaJxwIfbwmS",
    "payment_method_options": {
      "card": {
        "request_three_d_secure": "automatic"
      }
    },
    "payment_method_types": [
      "card"
    ],
    "single_use_mandate": null,
    "status": "succeeded",
    ^^^^^^^^^^^^^^^^^^^^^^
    "usage": "off_session"
  }
```
I observe the same responses for all the other 3D secure test cards meant to succeed after authentication. In the TestMode Dashboard, these payment methods and their associated subscriptions are all properly validated and working. 

Therefore, I believe there is an issue with the [Metered Billing with Elements Guide](https://stripe.com/docs/billing/subscriptions/metered), and possibly with the Testing Cards API, unless this is somehow the desired behavior.

I would be happy to move this issue to a different repo if this doesn't belong here. Thank you for your answers.

**Comment by remi-stripe** [comment]
@natedx Thanks for the detailed bug report. Unfortunately, this isn't really a bug with the stripe-node library and is more a list of questions about your integration. This is more suited for our support team that you can contact at https://support.stripe.com/contact. Developers are also available on IRC in #stripe on Freenode if you want to chat there.

To unblock you quickly though here are some pointers while I close this issue:

> Firstly, the response from createSubscription no longer contains the Setup Intent object in pending_setup_intent , but rather just the Setup Intent Id

This is expected behaviour, we always return the id by default. If you want the full object you have to use the [Expand feature](https://stripe.com/docs/expand). This means passing `expand: ['pending_setup_intent']` on `Subscription` creation.

> Secondly, the main issue is that when testing my integration with the cards available at stripe.com/docs/testing, all the 3D secure testing cards return a Setup Intent object with status "succeeded" instead of "requires_action".

You likely haven't enabled the Radar rule to run 3DS on SetupIntents. You need to enable it here: https://dashboard.stripe.com/test/settings/radar
