### ISSUE TITLE
'card' does not exist in type 'RequestOptions'

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#1085]
```
node v14.7.0
typescript v4.1.2
stripe v8.127.0
```

Hi Stripe team,

I'm seeing a Typescript error when copying a code sample from [stripe.tokens.create](https://stripe.com/docs/api/tokens/create_card).

I've made a minimal reproducible example here: [Archive.zip](https://github.com/stripe/stripe-node/files/5648224/Archive.zip)

```javascript
import Stripe from 'stripe';
const stripe = new Stripe("key", {
    // @ts-ignore stripe-version-2020-08-27
    apiVersion: '2020-08-27'
});

const token = stripe.tokens.create({
    card: {
        number: '4242424242424242',
        exp_month: 12,
        exp_year: 2021,
        cvc: '314',
    },
});
```
**Error**:

```
No overload matches this call.
  Overload 2 of 2, '(options?: RequestOptions | undefined): Promise<Response<Token>>', gave the following error.
    Argument of type '{ card: { number: string; exp_month: number; exp_year: number; cvc: string; }; }' is not assignable to parameter of type 'RequestOptions'.
      Object literal may only specify known properties, and 'card' does not exist in type 'RequestOptions'.
```

![image](https://user-images.githubusercontent.com/7410770/101270602-84cafa80-3748-11eb-8153-6b411d61bd70.png)

**Comment by remi-stripe** [comment]
@davidbielik Card details should be collected client-side with [Elements](https://stripe.com/docs/stripe-js#elements) or [Checkout](https://stripe.com/docs/payments/checkout) for security and [PCI compliance](https://stripe.com/docs/security/guide#validating-pci-compliance) reasons. There's almost never a valid use-case to pass those server-side in stripe-node, especially to the `Token` creation endpoint.
The API does support it, but the Typescript definitions don't to ensure that most developers don't incorrectly use this approach by default. You can just disable type signature verification for that line of code if you absolutely need to pass card details server-side though.

I'm going to close this out but if you have any follow up questions about PCI compliance or our products, make sure to talk to our support team: https://support.stripe.com/contact

**Comment by davidbielik** [comment]
Thanks @remi-stripe, understood and makes sense! This is part of some integration tests, so I generate [test cards](https://stripe.com/docs/testing#cards-responses) to play out different scenarios. Normally these tokens do come from the client-side, but I mock those server-side to test my API endpoints.

Are there other methods I should use instead to assign a specific card (i.e. `4242...` vs. `4000000000000259` to simulate a payment that will be disputed)?

**Comment by remi-stripe** [comment]
You can use the tokens already built for those cards such as `tok_visa` or `tok_chargeDeclined` and they are all covered in https://stripe.com/docs/testing#cards!
