### ISSUE TITLE
TypeScript - Create card - Property 'brand' does not exist on type 'Response<CustomerSource>'. 

### ISSUE THREAD

**Issue by alan345** [stripe/stripe-node#1086]
With TypeScript, 
after creating a card using `stripe.customers.createSource()` Documentation: https://stripe.com/docs/api/cards/create

I need to acces to the card created. like (`brand ` or `address_line1 `) but I cannot. Only `object` is available

```
   const source = await stripe.customers.createSource(stripeCusId, {
      source: tokenCardId,
    })

    console.log(source.brand)
// error is: 
// Property 'brand' does not exist on type 'Response<CustomerSource>'.
// Property 'brand' does not exist on type 'AccountDebitSource & { headers: { [key: string]: string; }; lastResponse: { // requestId: string; statusCode: number; apiVersion?: string; idempotencyKey?: string; stripeAccount?: string; }; }'.ts(2339)
```

When I check wha is available I just have access to: 

![image](https://user-images.githubusercontent.com/15246526/101556216-39466580-396f-11eb-9749-683ed8bcf86e.png)

**Comment by remi-stripe** [comment]
@alan345 The `createSource` method can return different objects because it's polymorphic. It can be a `Card`, a `Source` or a `BankAccount` for example. For that reason we created the interface `CustomerSource` which is defined [here](https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/types/shared.d.ts#L174-L180).  You need to cast the returned value to the type you expect, or based on the `object` value.

**Comment by alan345** [comment]
thanks @remi-stripe , can you provide me an example to cast based on `object` ? thanks

**Comment by paulasjes-stripe** [comment]
@alan345 In this case since you want a `Card` object, you can cast the source to a card:

```
const source = await stripe.customers.createSource(cust.id,  {
  source: tokenCardId,
}) as Stripe.Card;

console.log(source.brand);
```

If you don't know what type of object `createSource` will return beforehand (e.g. you are using the same code to create `Card` and `BankAccount` sources) you can use a switch statement:

```
const source = await stripe.customers.createSource(cust.id,  {
    source: tokenId,
});

console.log(source.object);

switch (source.object) {
  case 'card':    
    const card = source as Stripe.Card;
    console.log(card.brand);
    break;

  // ...other object types
}
```

**Comment by alan345** [comment]
Thanks fro your help!
