### ISSUE TITLE
TypeScript: Attribute "type" of object stripe.Response<stripe.PaymentMethod> has the wrong type

### ISSUE THREAD

**Issue by Spixmaster** [stripe/stripe-node#1106]
# My machine
Operating System: Arch Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.10.5-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
node -v: v15.5.1
stripe-node version: v8.130.0

# The problem

**TypeScript complains about the line `type: stripe_payment_method.type`. It it the third last line of the posted code.**
```
const stripe_payment_method:stripe_tmp.Response<stripe_tmp.PaymentMethod> = await stripe.paymentMethods.retrieve(String(req.query.id));

const stripe_payment_methods:stripe_tmp.Response<stripe_tmp.ApiList<stripe_tmp.PaymentMethod>> = await stripe.paymentMethods.list(
{
    customer: stripe_customers[0].id,
    type: stripe_payment_method.type,
    limit: 100
});
```

## Error message
```
Type 'import("stripe").Stripe.PaymentMethod.Type' is not assignable to type 'import("stripe").Stripe.PaymentMethodListParams.Type'. Type '"interac_present"' is not assignable to type 'Type'.
```

The code worked before and with an update of stripe-node this error suddenly appeared.

**Comment by richardm-stripe** [comment]
Hello @Spixmaster, thanks for the report.

I think the types are working as intended. The code you posted makes an assumption that any value of `type` on the response of `stripe.paymentMethods.retrieve` can validly be sent in the `type` field of `stripe.paymentMethods.list`. This is not an invariant we guarantee -- it was true once, but in [8.54.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#8540---2020-05-20) we changed the types to reflect how the Stripe API might start returning payment methods with type `interac_present`, which would cause an error if you sent it to `stripe.paymentMethods.list`.

It could be in practice you never see `interac_present`. My recommendation is either to manually do the type narrowing to confirm that the value is a valid `PaymentMethodListParams.Type`, or cast it to `any` here and bypass this type check if you never expect to receive an `interac_present` payment intent.
