### ISSUE TITLE
Consider retrying on 429 Too Many Requests?

### ISSUE THREAD

**Issue by jli** [stripe/stripe-node#1110]
I expected that setting `maxNetworkRetries` would result in retries when rate limited (429 Too Many Requests errors), but in testing, I noticed this isn't the case. Would the team consider adding 429 as a condition that gets retried automatically (e.g. [here, in _shouldRetry](https://github.com/stripe/stripe-node/blob/v8.131.1/lib/StripeResource.js#L251))?

I think the typical "right" thing to do when rate limited is automatic retries with exponential backoff, which is why it would be nice to have it be part of the built-in retry mechanism (though having a higher max delay than 2s might also be nice in this particular use case as well).

Thanks!

**Comment by paulasjes-stripe** [comment]
The reason we don't automatically retry on 429 errors is that getting that error usually means there's something up with your application. It's actually quite difficult to reach Stripe's rate limit with normal traffic, so getting that error usually means you need to review your application to make sure you aren't making unnecessary requests.

Getting rate limited shouldn't be solved by automatically retrying within the SDK, as that will obfuscate the actual underlying problem.

**Comment by jli** [comment]
Thanks @paulasjes-stripe, that makes sense!

FWIW, what prompted this is that my team gets alerted for errors in our staging environment which uses the Stripe test environment, which I know has lower rate limits[1]. (The error occasionally gets triggered during server startup, when many processes spin up at the same time and make a Stripe API call as part of initialization.)

I guess I'll find some other workaround for our staging environment. Thanks!


[1] per the Stripe error message: `Testmode request rate limit exceeded, the rate limits in testmode are lower than livemode. You can learn more about rate limits here https://stripe.com/docs/rate-limits.`

**Comment by remi-stripe** [comment]
@jli The way we approach rate limits is that we expect the vast majority of integrations to never hit this, even at scale. In Test mode the rate limits are 25 requests per second which is extremely high overall for a test suite. If we were retrying the requests automatically for you, you might not even notice that your test suite is making that many requests to our API per second (which is a pretty high load for our servers and yours).

In this world, we would expect no test integrations to go over a few of rps other than random peaks. Otherwise you should actively look into adding mocks to your tests and not hit the API directly in test suites!

**Comment by theredcat** [comment]
@remi-stripe @paulasjes-stripe IMHO You should at least provide an option `retryOnRateLimit` because you have small clients, but you have big clients too : @ work we can trigger 1000+ payment in a few seconds because we are doing time-limited auctions and our clients often program all their items to end at a specific time (often Sunday evening)

**Comment by remi-stripe** [comment]
@theredcat the large clients are even more reasons not to retry automatically or provide that option in my opinion. Rate limits are something you need to handle carefully and how to handle them depends on your own approach and business models and a "permanent retry" for all your requests is likely a bad idea. We implement various logic in rate limiting, dropping reads before writes for example and prioritizing some requests over others internally and most advanced/large users should do the same on their end when they start hitting rate limits, on top of alerting for it.

**Comment by acomagu** [comment]
I created auto retry mechanism by httpClient shim.

```typescript
class StripeHttpClient implements Stripe.HttpClient {
  baseHttpClient = Stripe.createNodeHttpClient();
  retryCounts: Record<string, number> = {};
  async makeRequest(
    host: string,
    port: string | number,
    path: string,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    headers: Record<string, string>,
    requestData: string | null,
    protocol: Stripe.HttpProtocol,
    timeout: number,
  ): Promise<Stripe.HttpClientResponse> {
    const originalIdempotencyKey = headers['Idempotency-Key'];
    let idempotencyKey: string | undefined;
    if (originalIdempotencyKey) {
      if (this.retryCounts[originalIdempotencyKey] !== undefined) {
        this.retryCounts[originalIdempotencyKey] = (this.retryCounts[originalIdempotencyKey] ?? 0) + 1;
        idempotencyKey = `${originalIdempotencyKey}-rate-limit-retry-${this.retryCounts[originalIdempotencyKey]}`;
      } else {
        this.retryCounts[originalIdempotencyKey] = 0;
        idempotencyKey = originalIdempotencyKey;
      }
    }

    const resp = await this.baseHttpClient.makeRequest(
      host,
      port,
      path,
      method,
      headers,
      requestData,
      protocol,
      timeout,
    );
    if (resp.getStatusCode() === 429) {
      console.log('retried');
      await new Promise(r => setTimeout(r, 500));
      return this.makeRequest(
        host,
        port,
        path,
        method,
        idempotencyKey ? { ...headers, 'Idempotency-Key': idempotencyKey } : headers,
        requestData,
        protocol,
        timeout,
      );
    }
    return resp;
  }
  getClientName() {
    return this.baseHttpClient.getClientName();
  }
}

const stripe = new Stripe('...', {
  apiVersion: '2020-08-27',
  maxNetworkRetries: 2,
  httpClient: new StripeHttpClient(),
});
```

**Comment by isaachinman** [comment]
Here's a more lightweight approach, using `p-throttle`:

```tsx
import pThrottle from 'p-throttle'
import { Stripe } from 'stripe'

const httpClient = Stripe.createNodeHttpClient()

httpClient.makeRequest = pThrottle({
  interval: 1000,
  limit: 100,
})(httpClient.makeRequest)

export const stripeClient = new Stripe(apiKeys, { httpClient })
```

**Comment by kirillgroshkov** [comment]
Hello, coming here with the same question/request - we consider ourselves a Stripe client "on a larger side", we do have serious legitimate spikes of user registrations/payments, similar to this described use case:

> because we are doing time-limited auctions and our clients often program all their items to end at a specific time (often Sunday evening)

Of course, we can rollout our own "task queue" / asynchronous processing / throttling, but that would significantly complicate the implementation, which is currently "sync" (same backend endpoint does all the necessary processing).

I don't currently understand why Stripe sdk decides to not auto-retry-with-backoff on 429, which sounds to me like a general practice.
What should we do instead?

If we roll out "our own task queue / retry" - we would just retry the same way (with the same intensity) as a built-in retry would. What's the difference?

Currently we'll be monkey/patching the stripe sdk, but this also sounds very wrong and brittle, and may create larger problems.

**Comment by remi-stripe** [comment]
@kirillgroshkov Your explanation does make sense but I feel like making those rate limits errors invisible could be risky for large businesses. In your example of an auction, being aware that you are hitting rate limits and making changes to your integration to stay under those and avoid making as many parallel payments is important to take into account versus sending too much load to our API.

An alternative would also be to contact our support team at https://support.stripe.com/contact to ask for a higher rate limit to be granted to you though the first thing they'd ask is why this background job can't be run at a slower pace on your end so it takes a bit longer while staying under our default rate limits.
