### ISSUE TITLE
Getting a list of customers using metadata

### ISSUE THREAD

**Issue by virus2016** [stripe/stripe-node#1113]
Hi there,

I am trying to get back a list of users that have specfic metadata. Is this possible?

```
curl --location --request GET 'https://api.stripe.com/v1/customers?limit=3&metadata[tag]=test' \
--data-urlencode 'limit=3'
```

**Comment by paulasjes-stripe** [comment]
Hi there, please only use this issue page for issues with the stripe-node library itself. For issues with the Stripe API you should reach out to Stripe support directly: https://support.stripe.com/contact

To unblock you however, listing customer objects by metadata isn't possible right now. You'd have to list all customers and filter through the metadata yourself.
