### ISSUE TITLE
Add Typescript Definition for Creating a File

### ISSUE THREAD

**Issue by NathanWenslaff** [stripe/stripe-node#1116]
Node Version: 13.9.0
Stripe Version: 8.76.0

The Typescript definition for `FileCreateParams` in `Files.d.ts` appears to be incomplete.

Source:
```
interface FileCreateParams {}
```

**Comment by remi-stripe** [comment]
@NathanWenslaff Thanks for the report! I'm going to tag as "future" for now as I don't think we'll get to it immediately but I'll track internally to make sure it gets done!

**Comment by remi-stripe** [comment]
Closing as this has been resolved in [this commit](https://github.com/stripe/stripe-node/commit/6776f3541cef6c5692a94665efb1b089f4222e25)
