### ISSUE TITLE
Always having empty metadata in my PaymentIntent

### ISSUE THREAD

**Issue by lionelrudaz** [stripe/stripe-node#1126]
Hi folks,

I'm using the latest version of stripe-node 8.137.0, upgraded from 8.119.0.

I want to send metadata while creating my Stripe Checkout session. I'm doing it this way:

```
const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      shipping_address_collection: {
        allowed_countries: ['CH'],
      },
      line_items: lineItems,
      metadata: {'order_id': '6735'},
      mode: 'payment',
      success_url: `${successUrl}?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: cancelUrl,
    });
```

I think I do it properly, but the metadata is always empty in Stripe dashboard when checking the payment intent. I've done a similar integration with the Ruby library and it's working out of the box this way.

What do I do wrong? Is there a bug somewhere?

Let me know if you need more information.

**Comment by paulasjes-stripe** [comment]
Your code sets metadata on the Checkout Session object. If you want to instead have metadata on the underlying PaymentIntent you'd use the `payment_method_data.metadata` property: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-metadata
