### ISSUE TITLE
Typescript error: Property 'redirectToCheckout' does not exist on type 'Stripe'.

### ISSUE THREAD

**Issue by surferjeff** [stripe/stripe-node#1128]
I'm following the instructions for the firebase extension.  The instructions show this code:
```.js
const docRef = await db
  .collection('customers')
  .doc(currentUser.uid)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
// Wait for the CheckoutSession to get attached by the extension
docRef.onSnapshot((snap) => {
  const { error, sessionId } = snap.data();
  if (error) {
    // Show an error to your customer and 
    // inspect your Cloud Function logs in the Firebase console.
    alert(`An error occured: ${error.message}`);
  }
  if (sessionId) {
    // We have a session, let's redirect to Checkout
    // Init Stripe
    const stripe = Stripe('pk_test_1234');
    stripe.redirectToCheckout({ sessionId });
  }
});
```
I copied it into my project Typescript project, so the code looks like this:
```.ts
import Stripe from 'stripe';
...
        if (sessionId) {
          // We have a session, let's redirect to Checkout
          // Init Stripe
          const stripe = new Stripe('pk_test_1234', {apiVersion: '2020-08-27'});
          stripe.redirectToCheckout({ sessionId });
        }

```

However, it fails to compile with this error:

```
103:18 Property 'redirectToCheckout' does not exist on type 'Stripe'.
    101 |           // Init Stripe
    102 |           const stripe = new Stripe('pk_test_1234', {apiVersion: '2020-08-27'});
  > 103 |           stripe.redirectToCheckout({ sessionId });
        |                  ^
    104 |         }
    105 |       });
    106 |     }
Version: typescript 3.9.7

% node --version
v14.9.0
% cat package.json | grep stripe
    "stripe": "^8.137.0",
%

**Comment by remi-stripe** [comment]
@surferjeff The `redirectToCheckout()` method is part of Stripe.js which is a client-side library that you load and run in the browser. The code/error you shared seems to run server-side based on stripe-node though which is separate.

You need to change your integration to send the checkout session id client-side to your app/browser integration where you would load Stripe.js and redirect to Checkout from there. It's not possible to redirect from the server directly at the moment and we always require a client-side redirect. This is documented here: https://stripe.com/docs/payments/accept-a-payment#redirect-customers

**Comment by surferjeff** [comment]
Thank you for taking the time to understand my question and provide a thorough reply.  Few organizations or so responsive.

I'm actually writing code for the client, but had accidentally stumbled into the server side code here.  I found the code in @stripe/stripe-js worked for me.

Thanks for your help.

**Comment by remi-stripe** [comment]
@surferjeff Glad to hear that it solved the problem! I also got thrown off looking at the code because of the way you initialize stripe-node and how close it is to the initialization of Stripe.js. Sometimes I wish the two leads didn't use "Stripe" as the main package/class name to make that more explicit!
