### ISSUE TITLE
Support checkout decimals

### ISSUE THREAD

**Issue by antoine-pous** [stripe/stripe-node#1135]
Hi!

For a project I have been able to setup a tiered product with unit price between 0.001$ to 0.005$ which is really cool. I would appreciate if the library can let us do that too.

![Selection_147](https://user-images.githubusercontent.com/7486600/112723203-ad504d80-8f0d-11eb-8ed2-e9c3d21b1ed4.png)

I would like move away from product system to a backend managed product pricing for convenience, but the library throw an exception when using `unit_amount_decimal`.

> Error: Checkout does not currently support usd prices with more than 2 decimal places in `line_items[0]`. You passed `0.1` corresponding to `$0.001`, which is not supported. You can round your price and pass in `unit_amount: 0` or `unit_amount: 1` instead.

Do you have any ETA about this feature ?
Do you have any workaround ?

Another thing, the error message is wrong. Putting `unit_amount: 0` will probably lead to an error too, how can we be able to sell something for 0$ without a coupon ?

**Comment by remi-stripe** [comment]
@antoine-pous Thanks for reaching out. Github issues should be limited to bugs with the library itself stripe-node. Your ask is a feature request about the product though so I'm going to close this out. Instead, make sure to reach out to our support team directly: https://support.stripe.com/contact

We don't have plans for supporting decimal amounts at the moment but I'll also flag internally.
