### ISSUE TITLE
stripe Invalid API Key provided: undefined process.env

### ISSUE THREAD

**Issue by MuttakinHasib** [stripe/stripe-node#1136]
Stripe v8.140.0
node v14.15.1

### ``` But secretKey is logging in console ```

![Screen Shot 2021-03-28 at 10 14 18 AM](https://user-images.githubusercontent.com/44552983/112742246-b04f4a80-8fae-11eb-9e55-de77779aa32e.png)

![Screen Shot 2021-03-28 at 10 15 35 AM](https://user-images.githubusercontent.com/44552983/112742248-b6452b80-8fae-11eb-84f4-9549c2b2727a.png)

### I'm getting error like this

![Screen Shot 2021-03-28 at 10 16 14 AM](https://user-images.githubusercontent.com/44552983/112742261-c78e3800-8fae-11eb-936c-e774db22c3ac.png)

**Comment by remi-stripe** [comment]
@MuttakinHasib the error really seems to point to `process.ENV.STRIPE_SECRET` being undefined. This is unlikely to be a bug with stripe-node and instead an issue with your code or set up. I'd recommend explicitly logging `secretKey` right after it's initialized to confirm. Overall, you should discuss this with our support team instead: https://support.stripe.com/contact
