### ISSUE TITLE
stripe.customers is undefined

### ISSUE THREAD

**Issue by esiao** [stripe/stripe-node#1149]
Hello, I'm having an issue with the Stripe Node library.

```
const STRIPE_API_KEY = process.env.STRIPE_API_KEY // sk_test_...aOfB
const stripe = require('stripe', STRIPE_API_KEY)
console.log(stripe.customers) // undefined
```

I don't understand why but I can't get the stripe.customers object, I initially thought it might have been a permissions issue so I tried to create a Restricted Key with Customers Read access but still, it remains undefined.
I'm using Stripe 8.145 in an Express with Node JS environment.

I'm using Stripe webhooks with success and I need to retrieve the information from the customer.
`const customer = await stripe.customers.retrieve(subscription.customer)`
I do have `TypeError: Cannot read property 'retrieve' of undefined` being thrown.

I'm sure, I missed something and I would appreciate the help.
Thank you.

**Comment by richardm-stripe** [comment]
Hello @esiao!

Try `require('stripe')(STRIPE_API_KEY)` instead of `require('stripe', STRIPE_API_KEY)`.

**Comment by esiao** [comment]
@richardm-stripe Thank you so much for the quick answer. That was it...
