### ISSUE TITLE
stripe.prices.create type: "one_time"

### ISSUE THREAD

**Issue by taylorchance** [stripe/stripe-node#1164]
I'm following the docs to a tee and it says to pass either type: "one_time" or "recurring", Im getting an error on my stripe dashboard about type being an unknown parameter.

So how do I create a price which is one time?

**Comment by richardm-stripe** [comment]
I've closed this out, because I verified that the [API Reference](https://stripe.com/docs/api/prices/create?lang=node) is correct, but please provide a link if you are viewing a different doc with incorrect instructions.
