### ISSUE TITLE
Types for refunds.create do not include payment_intent

### ISSUE THREAD

**Issue by NGTOne** [stripe/stripe-node#1165]
The API documentation lists [this parameter](https://stripe.com/docs/api/refunds/create?lang=node#create_refund-payment_intent) for the `POST /v1/refunds` endpoint:

> payment_intent optional
> ID of the PaymentIntent to refund.

However, the TypeScript types do not contain it.

I'm using library version `8.150.0` with API version `2020-08-27`.

**EDIT**: Realized that I was accidentally passing `undefined` for the `payment_intent`. It _is_ passed on, but the types don't match.

**Comment by remi-stripe** [comment]
Confirming that the types do support this and it's defined [here](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Refunds.d.ts#L110) so I'm going to close after your edit.
