### ISSUE TITLE
WeChat Pay not a valid payment method type for Checkout

### ISSUE THREAD

**Issue by abhijeet-toptal** [stripe/stripe-node#1171]
We have been informed that Wechat Pay has been enabled for our account for Stripe Checkout, but while creating the checkout session with wechatpay, we get an obvious error that it's not yet supported. Can you please sync with the product team and make sure SDKs are up to date?

**Comment by remi-stripe** [comment]
@abhijeet-toptal Github issues should be limited to bugs with stripe-node itself. Your question is a product question about a secret feature and not something we can help with here. You should talk to our support team directly instead: https://support.stripe.com/contact/email
