### ISSUE TITLE
getApiField use case

### ISSUE THREAD

**Issue by superguineapig** [stripe/stripe-node#1176]
#### note: this is not a bug report; just documenting my use of this function
per:
https://github.com/stripe/stripe-node/blob/9b58b95e2fbd0296ceb43aa6b1854785edbc3561/lib/stripe.js#L319

I'm using Google Cloud Functions/Firebase (NodeJS) for Stripe Connect account creation. Since cloud functions are stateless, I am following Google's recommendations on using global vars for initializing common APIs/objects. Essentially, this prevents re-initialization on every invocation of the cloud function endpoint during periods of moderate to high traffic.

I'm using `getApiField` in order to determine if the global reference to the Stripe API object is already initialized and using the currently configured API key.

The approach is as follows:

```javascript
// global section of cloud function js file
// GCP requires/init
const admin = require("firebase-admin");
const functions = require("firebase-functions");
try {
  admin.initializeApp();
} catch (e) {...}

const STRIPE_SK = "my secret api key...";

// stripe require
const Stripe = require("stripe");

// lazy init-ed stripe api obj ref
let SAPI;
...

// cloud function entry point
exports = module.exports = functions.https.onRequest(
  async (req, res) => {
      // LAZY INIT STRIPE API
      try {
          if (SAPI && SAPI.getApiField) {
              // USE 'getApiField' HERE --v--
              const _sauth = SAPI.getApiField("auth");
              if (!_sauth || _sauth.indexOf(STRIPE_SK) < 0) {
                   console.log("RE-INIT STRIPE CLIENT API");
                   SAPI = Stripe(STRIPE_SK);
               }
          } else {
              SAPI = Stripe(STRIPE_SK);
          }
      } catch (e) {
          console.error(e);
          // handle error...
      }

      // use Stripe Api
      const account = await SAPI.accounts.create({...});
      // ...
  }
);

```

This approach seems to serve my use case well as I'd like both to not pass in the auth key for each invocation of the Stripe api, and keep the initialized reference alive as long as the GCP has a virtual instance dedicated to the cloud function.

I'm not sure if there would be another way to verify the api object reference exists and had been initialized with a particular key without using `getApiField`. Though I'm not super comfortable relying on a *private* method for this.

Perhaps this could be better encapsulated with an additional top-level utility function on the Stripe object, instead of exposing the entire `_api` hash through `getApiField`.

For example:

```javascript
Stripe.prototype.isCurrentKey = function(key) {
  return this._api["auth"] === `Bearer ${key}`;
};
```

This way the client's key, which is presumably already available can be passed as an argument and checked with whatever private implementation is appropriate; also not exposing additional internal fields or the currently configured key, if it exists.

Anyway, just wanted to document this somewhere.

Thanks for all the hard work. Stripe api has been really easy to use + great docs!

**Comment by richardm-stripe** [comment]
Hello @superguineapig, thanks for documenting your use case. I think you can (and ought) to avoid asking the stripe client what api key it is using via keeping track yourself of the API key you used to initialize it - something like:

```javascript
let SAPI;
let SAPI_KEY;
const getStripe = (api_key) => {
    if (SAPI && SAPI_KEY && SAPI_KEY === api_key) {
      return SAPI;
    }
    SAPI = SAPI = Stripe(STRIPE_SK);
    SAPI_KEY = api_key;
    return SAPI;
}

// Then just call "getStripe(SK_KEY)" and you will get the lazily-initialized Stripe client you desire, and the check for API key equality will still happen.
```

**Comment by richardm-stripe** [comment]
I am closing this issue as there is no action required for right now.
