### ISSUE TITLE
Customer preferred_locales have no impact on invoice PDF documents

### ISSUE THREAD

**Issue by ClaudeROSSI** [stripe/stripe-node#1183]
node: 14.15.5
stripe: 8.149.0
API version: 2020-08-27

I'm responsible for integrating STRIPE as the invoicing solution in our eMobility app.
We have been able to deliver a first version generating invoices but so far the invoice header is always in english (or more precisely in the locale defined at the stripe account settings).
One of our first customer is Spanish and would like that the generated invoices take into account the user preferred language.

Our app sets the preferred_locales array when creating the customers. We have for instance:
 
`preferred_locales: {
  'es-ES'
}`

Unfortunately this has no impact on the final invoice PDF document when we download it using the 'invoice.downloadUrl' property.

Can you help?
Is there anything to do during the invoice creation to specify the user language/locale?

Thanks in advance for your help,
Claude

**Comment by remi-stripe** [comment]
@ClaudeROSSI Github issues should be limited to bugs with the library itself. I recommend reaching out to our support team directly instead and they can help investigate: https://support.stripe.com/contact/email I'll also flag internally myself!
