### ISSUE TITLE
Type Stripe.Charge contains an empty interface StripeAccount under PaymentMethodDetails.

### ISSUE THREAD

**Issue by chrskerr** [stripe/stripe-node#1184]
Hello,

Type Stripe.Charge contains an empty interface StripeAccount under PaymentMethodDetails `node_modules/stripe/types/2020-08-27/Charges.d.ts` (line 1573) and the documentation https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-stripe_account is unclear about what to expect to be contained within this object, so I'm reluctant to ignore the error.

Can you please add types here? Thank you!

```
// check no existing fee in stripeTransfers
const existingCharges: Stripe.Charge[] = stripeCharges.filter( charge => (
    charge.payment_method_details.type === "stripe_account"
    && typeof charge.payment_method_details.stripe_account === "object"
    && charge.payment_method_details.stripe_account.id === destination // this line has an error that property id does not exist. Ideally I want to find charges which have a stripe_account.id equalling the user I'm currently looking at (their stripe_id === const destination)
    && typeof charge.metadata === "object"
    && charge.metadata.type === "monthly-fee"
));
```

**Comment by remi-stripe** [comment]
@chrskerr the documentation indicates that there is nothing inside that object today, it's just an empty object. It's here for consistency as all charges has an object based on the payment method type associated with that charge, but some are empty as they don't need any specific information. We don't have plans to add types further since there's nothing to type

**Comment by chrskerr** [comment]
@remi-stripe "If this is a stripe_account payment, this hash contains a snapshot of the transaction specific details of the stripe_account payment method." from the API page

That sounds like it will contain something to me? 

If this isn't the right way to get the information, then can you please let me know how I get the Connected Account ID for a charge against a stripe_account?

**Comment by remi-stripe** [comment]
@chrskerr that's just a generic sentence for the doc that is automatically generated for all payment method types. It's still an empty object and always has been. The account id is inside `source` today on `Charge` though it's undocumented as we deprecated it.

I agree we should improve this and put the relevant information inside `payment_method_details[stripe_account]` but we haven't yet as we're working on re-designing this on top of `PaymentMethod` instead. Hopefully in the near future we can improve this

**Comment by chrskerr** [comment]
Thanks @remi-stripe I really appreciate you running through this for me. I think I'll stick the source stripe_account id into Charge.metadata and worry about formalising the process later.

Cheers!
