### ISSUE TITLE
retrieve Applicable Products from PromotionCodes

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [stripe/stripe-node#1209]
I'm using `stripe.promotionCodes.retrieve` to get promo details but I noticed that  `Applicable Products ` is not found

**Comment by remi-stripe** [comment]
@MoatazAbdAlmageed Github issues should be limited to bugs with the library itself. Your question is an integration question and you should instead talk to our [support team](https://support.stripe.com/contact/email) or talk to developers on [Discord](https://stripe.com/go/developer-chat).

To unblock you though, this information lives on a `Product` in the `applies_to[products]` [property](https://stripe.com/docs/api/coupons/object#coupon_object-applies_to-products) which is includable. You can use the [Expand feature](https://stripe.com/docs/expand) to get to all of this.

```
const promotionCode = await stripe.promotionCodes.retrieve(
  'promo_1HMxuf2eZvKYlo2CmGXSyhRx',
  {
    expand: ['coupon.applies_to.products']
);

const productsLimitation = promotionCode.coupon.applies_to.products;
```

**Comment by MoatazAbdAlmageed** [comment]
@remi-stripe Thanks

**Comment by MoatazAbdAlmageed** [comment]
@many thanks @ramon-stripe you saved my day
