### ISSUE TITLE
Is it possible to decrease the usage in Metered Billing Plan ( using Node - Stripe)

### ISSUE THREAD

**Issue by daniyalkukda1997** [stripe/stripe-node#1225]
I have a system where customer subscribe our product and pay according to usage but some times customer cancel subscription in that case we need to refund some amount kindly help how can i achieve this. Thank You

sample code to create billing usage =.
await stripe.subscriptionItems.createUsageRecord(
            'subscriptionItemID',
            {
                quantity,
                timestamp: (Date.now() / 1000).toFixed(),
                action: 'increment',
            }
        );

**Comment by remi-stripe** [comment]
@daniyalkukda1997 Github issues should be limited to bugs with the library itself. Your question is an integration question and you should talk to our support team for help instead: https://support.stripe.com/contact/email or use our Discord server https://stripe.com/go/developer-chat
