### ISSUE TITLE
chrome prevents to download hosted invoice url in stripe

### ISSUE THREAD

**Issue by vishnutm** [stripe/stripe-node#1240]
When an invoiced URL attached to a HTML page it shows the "  net::ERR_HTTP2_PROTOCOL_ERROR 200" error.
when i try other browser like Firefox it's working perfectly .
![image](https://user-images.githubusercontent.com/30982642/132944026-754b058a-ba75-49f4-a37f-4e5140abd35d.png)

i also send a mail to the "support@stripe.com" for a sample mail . the from address of that mail is "cpa@netobjex.com".
i think chrome security feature prevents to download the "hosted_invoiceurl". kindly check it

version: 
stripe:^8.156.0
nodejs : 14.17.0
langugae: typescript

**Comment by remi-stripe** [comment]
@vishnutm Github issues should be limited to bugs with the stripe-node library. Your bug report is about the hosted invoice page and we recommend talking to our support team instead (which you are doing)
