### ISSUE TITLE
Update Stripe Quantity in Trial Period

### ISSUE THREAD

**Issue by sarikarathod20** [stripe/stripe-node#1246]
Ok, so here is the thing, I have an application with stripe integration which includes

 - Create customer 
 - Create subscription 
 - 30 days trial period 
 - Option to Update Quantity

1 Quantity here is 99$

Now if i am in active period everything works fine in regards to updating quantity in the middle of the month it creates invoice immediately, but if i am in trial period and i am updating the quantity from 1 to 2
the invoice generated next month is of the quantity 1 only, why is that?

And what is the ideal way of handling this?

Here is the code to update quantity

    await this.stripeClient.subscriptions.update(stripe_subscription_id, {
                    proration_behavior: 'create_prorations',
                    items: [{
                        id: subscriptionItemId,
                        price: price,
                        quantity: quantity, //New increased quantity
                    }],
                    metadata: {
                        user_id: user_id,
                        locations: locations,
                        subscription_type: plan.recurring.interval,
                        stripe_price_id: price,
                    },
                });

I now doubt, is it possible to update quantity in trial periods, in a way that it remains free in trial period and then get added when next month invoice is created.

**Comment by remi-stripe** [comment]
@sarikarathod20 your ask is more an integration/support question and Github issues are limited to bugs with the library itself. We recommend that you contact our support team for help instead: https://support.stripe.com/contact or try our Discord server for developers: https://stripe.com/go/developer-chat

What I can tell you is that updating the quantity during a trial period is supported. We'd record the new quantity and use that new quantity for the next invoice at the end of the trial. There must be a bug in your code somewhere where the quantity is not updated as you think but our support team can help you debug this!

**Comment by sarikarathod20** [comment]
@remi-stripe , I talked to the support team of stripe, the bug is not with my code but with stripe, atleast that's what they told me, yes stripe support updating quantity in trial period, but that's it, when the trial period is over it goes back to the original quantity because of some scheduled update

**Comment by remi-stripe** [comment]
I'm confident it's not a bug in our API and some confusion overall. Discussing this with our support team is the right flow here and they can help. Reporting here is not going to work unfortunately as this repo is only for stripe-node and we'd need detailed information for you and account information that you shouldn't share here. Try the Discord server, my team helps there and you'll talk to an engineer who can investigate this with you!
