### ISSUE TITLE
WeChat QR Code disappear after 3-5 seconds

### ISSUE THREAD

**Issue by xbaha** [stripe/stripe-node#1262]
after the QR code appears, i can scan it and test the payment, but it disappears so quickly, and no messages are received on the client-side.

```
        stripe.confirmWechatPayPayment(
            clientSecret,
            {
                payment_method_options: {
                    wechat_pay: {
                        client: 'web',
                    },
                }
            },
        ).then(function (result) {
            if (result.error) {
                paymentFailed(result.error);
            } else {
                if (result.paymentIntent.status === 'succeeded') {
                    paymentSucceeded();
                }
            }
        });
```

**Comment by remi-stripe** [comment]
@xbaha Github issues should be limited to bugs with the stripe-node library. Your code is about client-side code with Stripe.js instead which is different and is more an integration. Please reach out to our support team for help instead: https://support.stripe.com/contact

**Comment by xbaha** [comment]
For anyone having similar issue, this is a normal behavior while in test mode.
Wish it was documented. Wasted few hours on this.

**Comment by AdiechaHK** [comment]
@xbaha  thanks for updating information here, it really saved my time 👍🏼

**Comment by xbaha** [comment]
I apologize for the misinformation, 
It seems WeChat pay is still disappearing even on the live mode after a few seconds.
