### ISSUE TITLE
Reporting Stripe usage has incorrect types

### ISSUE THREAD

**Issue by dan003400** [stripe/stripe-node#1281]
When using Typescript, the `stripe.subscriptionItems.createUsageRecord` is not accepting correct types based upon both the docs and the examples.

`timestamp` should be optional, but is is required.

`timestamp` will not allow "now" to be passed.

**Comment by richardm-stripe** [comment]
Hello @dan003400, thanks for reaching out.

I believe that the types reflect this as of [v8.183.0](https://github.com/stripe/stripe-node/releases/tag/v8.183.0)
([commit](https://github.com/stripe/stripe-node/commit/4b5873eec852bb40027584946bedec042fa3be7b)).

Can you upgrade your library and report back if this fixes the issue?

**Comment by dan003400** [comment]
Yes, upgrading has resolve the issue. The argument is now optional.
