### ISSUE TITLE
NextJS - Error: construction of webhook event returned an error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

### ISSUE THREAD

**Issue by wicka-aus** [stripe/stripe-node#1294]
Hi 

I am pulling my hair out trying to pass raw JSON to NextJS 12 endpoint.

I have tried sooo many solutions and I just cant get it to work.

Please help as I have wasted half a day on this and I am at a loss.

Create test webhook in stripe and passing in Secret Signing key from webhook test dashboard "whsec ..."
I get a signature from the test webhook I trigger in the dashboard but I am constantly getting:

Error: construction of webhook event returned an error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

The code below is from Reddit, where some had a similar issue.

I have tried all of these solutions here: [https://github.com/vercel/next.js/discussions/13405](https://github.com/vercel/next.js/discussions/13405)

Seems to be an issue in a lot of forums.

Please help.

Exhausted!

```
import getRawBody from "raw-body";

const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

const webhookSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET;

export const config = {
  api: {
    bodyParser: false,
  },
};

const webhookHandler = async (req, res) => {
  if (req.method === "POST") {
    const rawBody = await getRawBody(req);

    // Extract Stripe signature from header
    const signature = req.headers["stripe-signature"];
    console.log(rawBody)
    console.log(signature)
    console.log(webhookSecret)

    let event;

    // Attempt to reconstruct and validate passed event
    try {
      event = stripe.webhooks.constructEvent(rawBody, signature, webhookSecret);
    } catch (err) {
      res
        .status(400)
        .send(
          `Error: construction of webhook event returned an error: ${err.message}`,
        );
      return;
    }

    console.log("success!")

    res.json({ received: true });
  } else {

    res.setHeader("Allow", "POST");
    res.status(405).end("Method Not Allowed");
    
  }
};

export default webhookHandler;

```

**Comment by wicka-aus** [comment]
Also trying code below and having the same issue

```
import { buffer } from 'micro';
import Cors from 'micro-cors';

const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

const webhookSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET;

// Stripe requires the raw body to construct the event.
export const config = {
  api: {
    bodyParser: false,
  },
};

const cors = Cors({
  allowMethods: ['POST', 'HEAD'],
});

const webhookHandler = async (req, res) => {
  if (req.method === 'POST') {
    const buf = await buffer(req);
    const sig = req.headers['stripe-signature'];

    let event;

    try {
      event = stripe.webhooks.constructEvent(
        buf.toString(),
        sig,
        webhookSecret
      );
    } catch (err) {
      console.log(`❌ Error message: ${err.message}`);
      res.status(400).send(`Webhook Error: ${err.message}`);
      return;
    }


    if (event.type === 'payment_intent.succeeded') {
      const paymentIntent = event.data.object;
      console.log(`💰 PaymentIntent status: ${paymentIntent.status}`);
    } else if (event.type === 'payment_intent.payment_failed') {
      const paymentIntent = event.data.object;
      console.log(
        `❌ Payment failed: ${paymentIntent.last_payment_error?.message}`
      );
    } else if (event.type === 'charge.succeeded') {
      const charge = event.data.object;
      console.log(`💵 Charge id: ${charge.id}`);
    } else {
      console.warn(`🤷‍♀️ Unhandled event type: ${event.type}`);
    }

    res.json({ received: true });
  } else {
    res.setHeader('Allow', 'POST');
    res.status(405).end('Method Not Allowed');
  }
};

export default cors(webhookHandler);
```

**Comment by TyrisDavidLopez** [comment]
I had the same Issue, until read this article:
https://dev.to/mahnuh/how-to-access-the-raw-body-of-a-stripe-webhook-request-in-nestjs-41kj

the problem is the express parser.

**Comment by remi-stripe** [comment]
@wicka-aus Adding to the recommendation above, there's also https://github.com/stripe/stripe-node/issues/341 which has numerous solutions for this problem that depend on your exact stack/version of frameworks/etc.

Github issues should be limited to bugs with the library itself and the issue right now is in your code and how to access the real raw body JSON. Whenever your code/framework/helpers change/touch the body, it will prevent webhook signature from working since we need the same exact payload we used to generate the signature when we want to verify it. I'm going to close this out but you can ask for help to our support team [here](https://support.stripe.com/contact) or on our Discord server for developers [here](https://stripe.com/go/developer-chat)

**Comment by wicka-aus** [comment]
Thanks to the Stripe team, who pointed me to some code, this worked for me:

```
async function buffer(readable) {
  const chunks = [];
  for await (const chunk of readable) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}


const webhookHandler = async (req, res) => {
  if (req.method === 'POST') {
    const buf = await buffer(req);
   .....
```

**Comment by pascuflow** [comment]
@wicka-aus So what does the complete webhook file look like? What imports? Thanks.

**Comment by adimaralimuddin** [comment]
i have tried all of your suggestions above, but still nothings works. i'm really disappointed by this.

**Comment by adimaralimuddin** [comment]
after scratching my head for a half day, i finally figured it out.

install micro npm i micro
my code on /project/pages/api/stripe-webhook.js
`import initStripe from "stripe";
import { buffer } from "micro";

export const config = { api: { bodyParser: false } };

export default async function handler(req, res) {
const stripe = initStripe(process.env.STRIPE_SECRET_KEY);
const signature = req.headers["stripe-signature"];
const signingSecret =process.env.STRIPE_SIGNING_SECRET;
const reqBuffer = await buffer(req);

let event;

try {
event = stripe.webhooks.constructEvent(reqBuffer, signature, signingSecret);
} catch (error) {
console.log(error);
return res.status(400).send(webhook error: ${error.message});
}

console.log("event ", event);

res.send({ received: true });
}
`

**Comment by hemeda3** [comment]
Thanks all this helped me, want to share with everybody: 

1-  disable body-parser

```
export const config = {
  api: {
    bodyParser: false,
  },
};
```
2- after using micro.buffer,  pay attention to` rawBody.toString()` !!
 ` const rawBody = await buffer(req);`. and   `event = stripe.webhooks.constructEvent( ***rawBody.toString()***, .signtaure..., ..secret. )`
3- use correct webhook signing secret ( secret generated by CLI vs secret generated by Dashboard)
in my case I was using this command 
```
$ stripe listen --forward-to http://localhost:3000/api1/stripe/hooks > Ready! You are using Stripe API Version [2020-03-02].
````
```
 Your -->>> webhook signing secret is whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (^C to quit)

```
but another mistake I made, that I was using `webhook test secret` generated by dashboard not the one generated by `dashboard` 



Here is my code after getting correct secret

```

import Stripe from 'stripe';
import { buffer } from 'micro';
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

export const config = {
  api: {
    bodyParser: false,
  },
};

export default async function handler(req, res) {
  if (req.method === 'POST') {
    let event;

    try {
      // 1. Retrieve the event by verifying the signature using the raw body and secret
      const rawBody = await buffer(req);
      const signature = req.headers['stripe-signature'];

      event = stripe.webhooks.constructEvent(
        rawBody.toString(),
        signature,
        process.env.STRIPE_WEBHOOK_SECRET
      );
    } catch (err) {
      console.log(`❌ Error message: ${err.message}`);
      res.status(400).send(`Webhook Error: ${err.message}`);
      return;
    }

    // Successfully constructed event
    console.log('✅ Success:', event.id);

    // 2. Handle event type (add business logic here)
    if (event.type === 'checkout.session.completed') {
      console.log(`💰  Payment received!`);
    } else {
      console.warn(`🤷‍♀️ Unhandled event type: ${event.type}`);
    }

    // 3. Return a response to acknowledge receipt of the event.
    res.json({ received: true });
  } else {
    res.setHeader('Allow', 'POST');
    res.status(405).end('Method Not Allowed');
  }
}

````

**Comment by Bulletninja** [comment]
Tried all of this and doesn't seem to work. One thing that caught my attention is that @hemeda3 solution passes `rawBody.toString()` whereas:
- https://www.codedaily.io/tutorials/Stripe-Webhook-Verification-with-NextJS
- https://egghead.io/lessons/next-js-subscribe-to-stripe-webhooks-using-next-js-api-routes
These two use the buffer directly
This Vercel guide does convert to string: https://vercel.com/guides/getting-started-with-nextjs-typescript-stripe

None of them seem to work for me.

**Comment by Timurtek** [comment]
I am also stuck here :/ Did any of you find an answer to this? 😭

**Comment by AAlon** [comment]
> @wicka-aus Adding to the recommendation above, there's also #341 which has numerous solutions for this problem that depend on your exact stack/version of frameworks/etc.
> 
> Github issues should be limited to bugs with the library itself and the issue right now is in your code and how to access the real raw body JSON. Whenever your code/framework/helpers change/touch the body, it will prevent webhook signature from working since we need the same exact payload we used to generate the signature when we want to verify it. I'm going to close this out but you can ask for help to our support team [here](https://support.stripe.com/contact) or on our Discord server for developers [here](https://stripe.com/go/developer-chat)

What a pathetic response. Your docs are lacking - show some ownership?

**Comment by RyelBanfield** [comment]
Mine worked perfectly up until Friday.

`
import { buffer } from "micro";
import { NextApiRequest, NextApiResponse } from "next";

import { env } from "../../env/server.mjs";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const stripe = require("stripe")(env.STRIPE_SECRET_KEY);
const webhookSecret = env.STRIPE_WEBHOOK_SECRET;

export const config = {
  api: {
    bodyParser: false,
  },
};

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method === "POST") {
    const sig = req.headers["stripe-signature"] as string;

    let event;

    try {
      event = stripe.webhooks.constructEvent(
        await buffer(req),
        sig,
        webhookSecret
      );
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    switch (event.type) {
      case "checkout.session.completed": {
        break;
      }
      default: {
        console.log(`Unhandled event type ${event.type}`);
      }
    }

    res.json({ received: true });
  } else {
    res.setHeader("Allow", "POST");
    res.status(405).end("Method Not Allowed");
  }
};

export default handler;
`

I am so confused.

**Comment by RyelBanfield** [comment]
Mine worked perfectly up until Friday.


```
import { buffer } from "micro";
import { NextApiRequest, NextApiResponse } from "next";

import { env } from "../../env/server.mjs";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const stripe = require("stripe")(env.STRIPE_SECRET_KEY);
const webhookSecret = env.STRIPE_WEBHOOK_SECRET;

export const config = {
  api: {
    bodyParser: false,
  },
};

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method === "POST") {
    const sig = req.headers["stripe-signature"] as string;

    let event;

    try {
      event = stripe.webhooks.constructEvent(
        await buffer(req),
        sig,
        webhookSecret
      );
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    switch (event.type) {
      case "checkout.session.completed": {
        break;
      }
      default: {
        console.log(`Unhandled event type ${event.type}`);
      }
    }

    res.json({ received: true });
  } else {
    res.setHeader("Allow", "POST");
    res.status(405).end("Method Not Allowed");
  }
};

export default handler;
```


I am so confused.

**Comment by jgreensmith** [comment]
> Thanks all this helped me, want to share with everybody many mistakes I made while testing this for first time :
> 
> 1- disable body-parser
> 
> ```
> export const config = {
>   api: {
>     bodyParser: false,
>   },
> };
> ```
> 
> 2- after using micro.buffer, pay attention to` rawBody.toString()` !! ` const rawBody = await buffer(req);`. and `event = stripe.webhooks.constructEvent( ***rawBody.toString()***, .signtaure..., ..secret. )` 3- use correct webhook signing secret ( secret generated by CLI vs secret generated by Dashboard) in my case I was using this command
> 
> ```
> $ stripe listen --forward-to http://localhost:3000/api1/stripe/hooks > Ready! You are using Stripe API Version [2020-03-02].
> ```
> 
> ```
>  Your -->>> webhook signing secret is whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (^C to quit)
> ```
> 
> but another mistake I made, that I was using `webhook test secret` generated by dashboard not the one generated by `CLI` :(
> 
> Here is my code after getting correct secret
> 
> ```
> 
> import Stripe from 'stripe';
> import { buffer } from 'micro';
> const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
> 
> export const config = {
>   api: {
>     bodyParser: false,
>   },
> };
> 
> export default async function handler(req, res) {
>   if (req.method === 'POST') {
>     let event;
> 
>     try {
>       // 1. Retrieve the event by verifying the signature using the raw body and secret
>       const rawBody = await buffer(req);
>       const signature = req.headers['stripe-signature'];
> 
>       event = stripe.webhooks.constructEvent(
>         rawBody.toString(),
>         signature,
>         process.env.STRIPE_WEBHOOK_SECRET
>       );
>     } catch (err) {
>       console.log(`❌ Error message: ${err.message}`);
>       res.status(400).send(`Webhook Error: ${err.message}`);
>       return;
>     }
> 
>     // Successfully constructed event
>     console.log('✅ Success:', event.id);
> 
>     // 2. Handle event type (add business logic here)
>     if (event.type === 'checkout.session.completed') {
>       console.log(`💰  Payment received!`);
>     } else {
>       console.warn(`🤷‍♀️ Unhandled event type: ${event.type}`);
>     }
> 
>     // 3. Return a response to acknowledge receipt of the event.
>     res.json({ received: true });
>   } else {
>     res.setHeader('Allow', 'POST');
>     res.status(405).end('Method Not Allowed');
>   }
> }
> ```

part 3 of this fixed it for me!

**Comment by th3brink** [comment]
I mistakenly used the webhook id and not the Signing Secret for `process.env.STRIPE_WEBHOOK_SECRET`. 

You will find the secret on the webhook detail page
<img width="448" alt="Screenshot 2023-05-22 093719" src="https://github.com/stripe/stripe-node/assets/1435543/e4c3c84e-c437-4b82-8fac-68225ef6aa86">

**Comment by user061281** [comment]
I happen to have the same error using expressjs v4.17.0 no matter what I try.
`async function buffer(readable) {
  const chunks = [];
  for await (const chunk of readable) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}

app.post('/hooks/webhook', express.raw({type: 'application/json'}), async (request, response) => {
  const sig = request.headers['stripe-signature'];
  const buf = await buffer(request);
  let event;

  try {
    event = stripe.webhooks.constructEvent(buf.toString(), sig, endpointSecret);
  } catch (err) {
    response.status(400).send(`Webhook Error: ${err.message}`);
  }

  // Handle the event
  switch (event.type) {
    case 'payment_intent.succeeded':
      const paymentIntent = event.data.object;
      console.log('PaymentIntent was successful!');
      break;
    case 'payment_method.attached':
      const paymentMethod = event.data.object;
      console.log('PaymentMethod was attached to a Customer!');
      break;
      // ... handle other event types
    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  // Return a response to acknowledge receipt of the event
  response.json({received: true});
});
`

**Comment by haris-aqeel** [comment]
I am facing the same issue

**Comment by user061281** [comment]
After a lot of trial end error I have finally made it work. The issue is where you declare the endpoint in the app.... It has to be before any express.json() usages. So, in my case app is : 

`
const cors = require("cors");
const corsOptions = {
  origin: "*",
  methods: "GET,PUT,POST,DELETE",
};

const app = express();
app.use(cors(corsOptions));



app.use('/hooks', hookRouter);
app.use(express.json());
...
`

The rest routes are below app.use(express.json())

Router is: 

`
router.post('/webhook', express.raw({type: '*/*'}), async function (request, response) {
    await web.webhooksMethods(request, response);
});
`

and then the code is:

`

const endpointSecret = process.env.WEBHOOK_SECRET;

module.exports.webhooksMethods = async (request, response) => {

    console.log("~~~~~~~REQUEST PARAMS~~~~~~~~~~")
    console.log(request.params);
    console.log("~~~~~~~REQUEST PARAMS~~~~~~~~~~")
    let signature = request.headers['stripe-signature']


    let event;

    try {
        event = stripe.webhooks.constructEvent(request.body.toString(), signature, endpointSecret);
        console.log(event)
    }
    catch (err) {
        console.log(err)
       // response.status(400).send(`Webhook Error: ${err.message}`);
    }

        event = JSON.parse(request.body.toString());
        switch (event.type) {


            case 'payment_intent.requires_action':
                console.log('webhook_payment_intent.requires_action')
                const paymentIntentRequiresAction = event.data.object;
                console.log(paymentIntentRequiresAction)
                // Then define and call a function to handle the event payment_intent.succeeded
                break;
.....

`

I have currently commented out the response inside the catch block for debugging purposes.

Hope this helps anyone who faces the same issue and saves him/her some time. Express version I use is  4.17.1

Remember to use the secret your local terminal prints to you and not the secret from the webhook on stripe dashboard.

**Comment by Megajin** [comment]
Hey everyone!

I am sure, that I have the right solution. You don't need any packages at all.
The Problem was to create a working buffer out of the request. 

You have use `req.text()` and transform that into a Buffer with `Buffer.from()`.

Here is a full example:

```
import { type NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';

// export const config = { api: { bodyParser: false } };

export async function POST(req: NextRequest) {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
    apiVersion: '2022-11-15',
  });
  const sig = req.headers.get('stripe-signature') || '';
  const signingSecret = process.env.STRIPE_WEBHOOK_SIG || '';

  // Read the request body as text
  const reqText = await req.text();
  // Convert the text to a buffer
  const reqBuffer = Buffer.from(reqText);

  let event;

  try {
    event = stripe.webhooks.constructEvent(reqBuffer, sig, signingSecret);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } catch (err: any) {
    return new NextResponse(`Webhook Error: ${err.message}`, {
      status: 400,
    });
  }

  // Handle the event just an example!
  switch (event.type) {
    case 'product.created':
      const productCreated = event.data.object;
      // Then define and call a function to handle the event product.created
      break;
    case 'product.deleted':
      const productDeleted = event.data.object;
      // Then define and call a function to handle the event product.deleted
      break;
    case 'product.updated':
      const productUpdated = event.data.object;
      // Then define and call a function to handle the event product.updated
      break;
    // ... handle other event types
    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  return NextResponse.json({ received: true });
}

```

**Comment by richardsondx** [comment]
> I mistakenly used the webhook id and not the Signing Secret for `process.env.STRIPE_WEBHOOK_SECRET`.
> 
> You will find the secret on the webhook detail page <img alt="Screenshot 2023-05-22 093719" width="448" src="https://private-user-images.githubusercontent.com/1435543/239958557-e4c3c84e-c437-4b82-8fac-68225ef6aa86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjMwOTUsIm5iZiI6MTcwMTEyMjc5NSwicGF0aCI6Ii8xNDM1NTQzLzIzOTk1ODU1Ny1lNGMzYzg0ZS1jNDM3LTRiODItOGZhYy02ODIyNWVmNmFhODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjIwNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmYzExYzI5YzJhYTc2NzgxMjI2NWY3MWJjY2UwMWZkYjIwZjhhNGJkMDkwZmY1YmZhMWJkOGU3NDlkZGI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u869fjq1aD8OJt-CfZBrZiBivfS9MCPanNpRjha1z6I">

That was it for me. Thanks!

**Comment by Danieldo1** [comment]
> Hey everyone!
> 
> I am sure, that I have the right solution. You don't need any packages at all. The Problem was to create a working buffer out of the request.
> 
> You have use `req.text()` and transform that into a Buffer with `Buffer.from()`.
> 
> Here is a full example:
> 
> ```
> import { type NextRequest, NextResponse } from 'next/server';
> import Stripe from 'stripe';
> 
> // export const config = { api: { bodyParser: false } };
> 
> export async function POST(req: NextRequest) {
>   const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
>     apiVersion: '2022-11-15',
>   });
>   const sig = req.headers.get('stripe-signature') || '';
>   const signingSecret = process.env.STRIPE_WEBHOOK_SIG || '';
> 
>   // Read the request body as text
>   const reqText = await req.text();
>   // Convert the text to a buffer
>   const reqBuffer = Buffer.from(reqText);
> 
>   let event;
> 
>   try {
>     event = stripe.webhooks.constructEvent(reqBuffer, sig, signingSecret);
>     // eslint-disable-next-line @typescript-eslint/no-explicit-any
>   } catch (err: any) {
>     return new NextResponse(`Webhook Error: ${err.message}`, {
>       status: 400,
>     });
>   }
> 
>   // Handle the event just an example!
>   switch (event.type) {
>     case 'product.created':
>       const productCreated = event.data.object;
>       // Then define and call a function to handle the event product.created
>       break;
>     case 'product.deleted':
>       const productDeleted = event.data.object;
>       // Then define and call a function to handle the event product.deleted
>       break;
>     case 'product.updated':
>       const productUpdated = event.data.object;
>       // Then define and call a function to handle the event product.updated
>       break;
>     // ... handle other event types
>     default:
>       console.log(`Unhandled event type ${event.type}`);
>   }
> 
>   return NextResponse.json({ received: true });
> }
> ```

AMAZING

**Comment by tsykin** [comment]
I faced this erron when building stripe webhook with Next.js 14 app router.
In order to fix the issue, make sure to:
1. Use `request.text()` method for converting request body to string
2. Check whether you are passing correct webhook secret to `constructEvent()` function

my completed webhook (make sure to add logic for every event type):
```ts
import { NextResponse } from 'next/server';
import Stripe from 'stripe';
import { env } from '@/utils/utilities';
import { stripe } from '@/lib/stripe';

export async function POST(request: Request) {
  let event: Stripe.Event | null = null;

  try {
    // Read the raw request body as text
    const requestText = await request.text();
    // Retrieve the Stripe signature from the headers
    const sig = request.headers.get('stripe-signature');
    const signingSecret = process.env.STRIPE_WEBHOOK_SECRET as string;
    if (!sig) {
      console.error('Stripe signature is null');
      return NextResponse.json({ error: 'Webhook error' }, { status: 400 });
    }

    event = stripe.webhooks.constructEvent(requestText, sig, signingSecret);
  } catch (error) {
    if (error instanceof Error) {
      console.error('Webhook signature verification failed:', error);
      return NextResponse.json({ error: 'Webhook error' }, { status: 400 });
    }
  }

  // Handle the event
  if (event) {
    switch (event.type) {
      case 'checkout.session.completed':
        const completedSession = event.data.object;
        // Handle completed checkout session
        break;
      case 'checkout.session.async_payment_failed':
        const failedSession = event.data.object;
        // Handle failed checkout session
        break;
      default:
        // Unexpected event type
        console.log('Unhandled event type', event.type);
    }
  }

  return NextResponse.json({ received: true }, { status: 200 });
}
```

**Comment by solvionsolutions** [comment]
Since the issue is closed but still surfaces in searches, here's a plain answer for anyone landing here:

Your config is actually right — `bodyParser: false` plus `getRawBody(req)` is exactly the setup `constructEvent` expects. The one thing to watch is that the Buffer coming out of `raw-body` reaches `constructEvent` completely untouched; don't `.toString()` it, re-`JSON.parse` it, or run it through anything that normalizes bytes, because even a whitespace change breaks the HMAC.

```js
export const config = { api: { bodyParser: false } };

const buf = await getRawBody(req);            // raw Buffer, as-is
const sig = req.headers['stripe-signature'];
const event = stripe.webhooks.constructEvent(buf, sig, process.env.STRIPE_WEBHOOK_SECRET);
```

If it still throws "No signatures found matching..." after that, the code isn't your problem — it's almost always a secret mismatch. The `whsec_` that `stripe listen` prints for local forwarding is a *different* secret from the one on your Dashboard endpoint, so if you're testing locally with the CLI but reading the Dashboard secret (or vice versa), it'll fail every time even though both look valid. The other usual culprit is a proxy, tunnel, or host in front of your route that re-serializes the JSON before it hits your handler, which changes the bytes Stripe signed. I wrote up the full breakdown here: https://www.guardlayer.io/blog/stripe-webhook-signature-verification
