### ISSUE TITLE
Strange Signing Secret Issues On Vercel API (NextJS)

### ISSUE THREAD

**Issue by wicka-aus** [stripe/stripe-node#1303]
I have a Stripe account. I have two endpoints on Vercel to consumer Stripe Webhooks.

The code on both endpoints is exactly the same (literally copied and pasted) except the envir variables are different - the dev endpoint has my test stripe key and test webhook signing secret; the live endpoint has my stripe live key and live webhook signing secret.

The dev endpoint validates fine. The live endpoint fails.

I have desconstructed the Stripe Node code and signed the dev endpoint request myself and received matching signatures. On the live endpoint I received mismatched signatures (my signature does not match the one in the header that Stripe sent).

I have triple-checked the webhook signing secrets over and over and over again as this the key to getting the right signature for the payload.

I have reached out to Stripe and they dont seem to know the answer except for the signing secret.

This a NextJS 12 app on Vercel infrastructure.

The code below came from the Stripe team when I first had issues with the dev endpoint. It worked and then I tested it on Stripe live - and now it fails.

I have tried other libraries like raw-body and get the same outcomes.

Can the buffer method produce unstable output?

If the signing secrets are correct - which they are - what other problems could be causing the req to be different?

Stripe could be signing the payload with the wrong signing secret, but very unlikely.

Any input would be so helpful

TIA.

     import Stripe from 'stripe';

        export const stripe = new Stripe( process.env.STRIPE_KEY, { apiVersion: '2020-08-27' } );
        
        export const config = {
          api: {
            bodyParser: false
          }
        };
        
        async function buffer(readable) {
          const chunks = [];
          for await (const chunk of readable) {
            chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
          }
          return Buffer.concat(chunks);
        }
        
        const webhookHandler = async (req, res) => {
        
          if (req.method === 'POST') {
        
              console.log("Endpoint Stripe Key: ", process.env.STRIPE_KEY)
        
              const buf = await buffer(req);
              
              const sig = req.headers['stripe-signature'];
              console.log("Signatures on endpoint: ", sig)
              
              const webhookSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET
              console.log("Signing Secret on endpoint: ", webhookSecret)
              
              let event;
          
              try {
                
                if (!sig || !webhookSecret) return;
                event = stripe.webhooks.constructEvent(buf, sig, webhookSecret);
              
              } catch (err) {
                
                console.log(`❌ Error message: ${err.message}`);
                return res.status(400).send(`Webhook Error: ${err.message}`);
              
              }
        
              console.log(`Success!!`);
        
              res.json({ received: true });
          
          } else {
            
            res.setHeader('Allow', 'POST');
            
            res.status(405).end('Method Not Allowed');
          }
        
        
        };
        
        export default webhookHandler ;

Here is the log for the Live Endpoint (secret copied from dashboard: whsec_dAT...ewP)

```
Live Endpoint: 
Stripe Key:  sk_live_51JR...AYJv
Signatures on live endpoint:  t=1637717726,v1=1465bca07a01dbeed14385a71a40a3c165db54374fde953f663af837cc546aef
Signing Secret on live endpoint:  whsec_dAT...tewP
❌ Error message: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
```
Here is the log for the Dev Endpoint (secret copied from dashboard: whsec_P88...XEhq)

```
Development Endpoint: 
Stripe Key:  sk_test_51JR...gtJDr
Signatures on dev endpoint:  t=1637717745,v1=f7d7751941a214069d747b8d2764c36bbf88434c79d832f3df4c0136fea593e1,v0=d7262640cbe952424edec847fab5b077cee5719dda34b03188539c98b157415e
Signing Secret on dev endpoint:  whsec_P88...XEhq
Success!!
```

**Comment by wicka-aus** [comment]
Below is my code for testing the Stripe signatures, deconstructed from the Stripe Node package.

Logs from live endpoint fail (Signatures are different) (Webhook signing secret copied from dashboard: whsec_703..n0i2)

```
<Buffer 7b 0a 20 20 22 69 64 22 3a 20 22 65 76 74 5f 33 4a 7a 42 42 51 42 68 39 39 46 4c 52 44 6c 44 31 63 46 6f 4d 38 79 68 22 2c 0a 20 20 22 6f 62 6a 65 63 ... 5283 more bytes>
t=1637742871,v1=2e01ca42ca89326ba96ad33b6b0ef72474513e9c0ec133d4d63520652edd2a09
whsec_703...n0i2
sk_live_51JR...AYJv
-----------computed sig--------------
c30869078170d2ed60b9a0e7b1afea4e625aa7d244bf0b8c4d1d9e4d7995ff01
[ '2e01ca42ca89326ba96ad33b6b0ef72474513e9c0ec133d4d63520652edd2a09' ]
false
❌ Error message: failed
```

Logs from dev endpoint show success (Signatures are the same)  (Webhook signing secret copied from dashboard: whsec_P88...XEhq)

```
<Buffer 7b 0a 20 20 22 63 72 65 61 74 65 64 22 3a 20 31 33 32 36 38 35 33 34 37 38 2c 0a 20 20 22 6c 69 76 65 6d 6f 64 65 22 3a 20 66 61 6c 73 65 2c 0a 20 20 ... 5029 more bytes>
t=1637742924,v1=1cc0cb8f069a053a9ab67fd01fd116ab4dda87dcdaf2a6096275107207bf2630,v0=5af43f2d7cff9250c25f6d3a9b9fa3aeda820671df0096f072fd47487311c20d
whsec_P88...XEhq
sk_test_51JR...gtJDr
-----------computed sig--------------
1cc0cb8f069a053a9ab67fd01fd116ab4dda87dcdaf2a6096275107207bf2630
[ '1cc0cb8f069a053a9ab67fd01fd116ab4dda87dcdaf2a6096275107207bf2630' ]
true
```

**Dev endpoint code:**
```
import Stripe from 'stripe';
const crypto = require('crypto');
import utils from 'stripe/lib/utils'
export const stripe = new Stripe( process.env.STRIPE_SECRET_KEY, { apiVersion: '2020-08-27'} );

const makeHMACContent = (payload, details) => {
  return `${details.timestamp}.${payload}`;
}

const computeHMACSignature = (payload, secret) => {
  return crypto
    .createHmac('sha256', secret)
    .update(payload, 'utf8')
    .digest('hex');
}

const parseHeader = (header, scheme) => {
  if (typeof header !== 'string') {
    return null;
  }

  return header.split(',').reduce(
    (accum, item) => {
      const kv = item.split('=');

      if (kv[0] === 't') {
        accum.timestamp = kv[1];
      }

      if (kv[0] === scheme) {
        accum.signatures.push(kv[1]);
      }

      return accum;
    },
    {
      timestamp: -1,
      signatures: [],
    }
  );
}

const parseEventDetails = (encodedPayload, encodedHeader, expectedScheme) => {

  const decodedPayload = Buffer.isBuffer(encodedPayload)
    ? encodedPayload.toString('utf8')
    : encodedPayload;

  if (Array.isArray(encodedHeader)) {
    throw new Error(
      'Unexpected: An array was passed as a header, which should not be possible for the stripe-signature header.'
    );
  }

  const decodedHeader = Buffer.isBuffer(encodedHeader)
    ? encodedHeader.toString('utf8')
    : encodedHeader;

  const details = parseHeader(decodedHeader, expectedScheme);

  if (!details || details.timestamp === -1) {
    throw new Stripe.lib.StripeSignatureVerificationError({
      message: 'Unable to extract timestamp and signatures from header',
      detail: {
        decodedHeader,
        decodedPayload,
      },
    });
  }

  if (!details.signatures.length) {
    throw new Stripe.lib.StripeSignatureVerificationError({
      message: 'No signatures found with expected scheme',
      detail: {
        decodedHeader,
        decodedPayload,
      },
    });
  }

  return {
    decodedPayload,
    decodedHeader,
    details,
  };
}

// Stripe requires the raw body to construct the event.
export const config = {
  api: {
    bodyParser: false
  }
};

async function buffer(readable) {
  const chunks = [];
  for await (const chunk of readable) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}


const webhookHandler = async (req, res) => {

  if (req.method === 'POST') {
    const buf = await buffer(req);
    console.log(buf)
    const sig = req.headers['stripe-signature'];
    console.log(sig)
    const webhookSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET
    console.log(webhookSecret)
    console.log(process.env.STRIPE_SECRET_KEY)
    let event;

    try {
      if (!sig || !webhookSecret) return;

      const {
        decodedHeader: header,
        decodedPayload: payload,
        details
      } = parseEventDetails(buf, sig, 'v1')

      const expectedSignature = computeHMACSignature(makeHMACContent(payload, details), webhookSecret)

      console.log("-----------computed sig--------------")

      console.log(expectedSignature)
      console.log(details.signatures)

      const signatureFound = !!details.signatures.filter(utils.secureCompare.bind(utils, expectedSignature)).length;

      console.log(signatureFound)

      if (!signatureFound) {
        throw new Error("failed")
      }

    } catch (err) {
      console.log(`❌ Error message: ${err.message}`);
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    res.json({ received: true });
  
} else {
    
    res.setHeader('Allow', 'POST');
    res.status(405).end('Method Not Allowed');

  }
};

export default webhookHandler;
```

**Live endpoint code:**
```
import Stripe from 'stripe';
const crypto = require('crypto');
import utils from 'stripe/lib/utils'
export const stripe = new Stripe( process.env.STRIPE_SECRET_KEY_LIVE, { apiVersion: '2020-08-27' });

const makeHMACContent = (payload, details) => {
  return `${details.timestamp}.${payload}`;
}

const computeHMACSignature = (payload, secret) => {
  return crypto
    .createHmac('sha256', secret)
    .update(payload, 'utf8')
    .digest('hex');
}

const parseHeader = (header, scheme) => {
  if (typeof header !== 'string') {
    return null;
  }

  return header.split(',').reduce(
    (accum, item) => {
      const kv = item.split('=');

      if (kv[0] === 't') {
        accum.timestamp = kv[1];
      }

      if (kv[0] === scheme) {
        accum.signatures.push(kv[1]);
      }

      return accum;
    },
    {
      timestamp: -1,
      signatures: [],
    }
  );
}

const parseEventDetails = (encodedPayload, encodedHeader, expectedScheme) => {

  const decodedPayload = Buffer.isBuffer(encodedPayload)
    ? encodedPayload.toString('utf8')
    : encodedPayload;

https://github.com/expressjs/express/blob/master/lib/request.js#L31)
  if (Array.isArray(encodedHeader)) {
    throw new Error(
      'Unexpected: An array was passed as a header, which should not be possible for the stripe-signature header.'
    );
  }

  const decodedHeader = Buffer.isBuffer(encodedHeader)
    ? encodedHeader.toString('utf8')
    : encodedHeader;

  const details = parseHeader(decodedHeader, expectedScheme);

  if (!details || details.timestamp === -1) {
    throw new Stripe.lib.StripeSignatureVerificationError({
      message: 'Unable to extract timestamp and signatures from header',
      detail: {
        decodedHeader,
        decodedPayload,
      },
    });
  }

  if (!details.signatures.length) {
    throw new Stripe.lib.StripeSignatureVerificationError({
      message: 'No signatures found with expected scheme',
      detail: {
        decodedHeader,
        decodedPayload,
      },
    });
  }

  return {
    decodedPayload,
    decodedHeader,
    details,
  };
}

export const config = {
  api: {
    bodyParser: false
  }
};

async function buffer(readable) {
  const chunks = [];
  for await (const chunk of readable) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}


const webhookHandler = async (req, res) => {

  if (req.method === 'POST') {
    const buf = await buffer(req);
    console.log(buf)
    const sig = req.headers['stripe-signature'];
    console.log(sig)
    const webhookSecret = process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET_LIVE
    console.log(webhookSecret)
    console.log(process.env.STRIPE_SECRET_KEY_LIVE)
    let event;

    try {
      if (!sig || !webhookSecret) return;

      const {
        decodedHeader: header,
        decodedPayload: payload,
        details
      } = parseEventDetails(buf, sig, 'v1')

      const expectedSignature = computeHMACSignature(makeHMACContent(payload, details), webhookSecret)

      console.log("-----------computed sig--------------")

      console.log(expectedSignature)
      console.log(details.signatures)

      const signatureFound = !!details.signatures.filter(utils.secureCompare.bind(utils, expectedSignature)).length;

      console.log(signatureFound)

      if (!signatureFound) {
        throw new Error("failed")
      }

    } catch (err) {
      console.log(`❌ Error message: ${err.message}`);
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    res.json({ received: true });
  
} else {
   
    res.setHeader('Allow', 'POST');
    res.status(405).end('Method Not Allowed');
   
}
};

export default webhookHandler;
```

**Comment by wicka-aus** [comment]
Hi @richardm-stripe 

I just tested the buffer lengths and they are fine for both endpoints.

Earlier today I looked at the payloads and were JSON.

In regards to my previous post, I deconstructed the Stripe Node code and signed the live payload with my live webhook secret and ended up with a completely different signature than the one passed in by Stripe in the payload header.

The development endpoint signing test was fine - both signatures matched.

It feels like my live endpoint signing secret is wrong in the dashboard.

I have checked the secrets endlessly - logging them, copy and pasting from the dashboard - as I know this is the suspected point of failure. But they all match.

**Comment by darkgl0w** [comment]
It may be your server that's parsing your request when you need to check against a raw one in order to match the signature.

Seems a similar issue: https://github.com/fastify/help/issues/158

**Comment by richardm-stripe** [comment]
Hello @wicka-aus,

I think these are possibilities - we should try and narrow down:

1. The payload that Stripe is signing is different than the payload that you are checking.
2. The secret that Stripe is using is different than the secret you are using.
3. The signing algorithm stripe-node is using is different from the algorithm the Stripe API is using.

Some ideas:
- Have you tried creating a new webhook endpoint/signing secret and seeing if it has the same problem?
- Would it be possible to point your webhook endpoint at a server running something other than `stripe-node`? If you could were able to successfully match a webhook event using say, `stripe-ruby`, that would pretty heavily implicate `stripe-node`.

I've gone ahead and created my own Vercel account with two different webhook endpoints for production and "preview" and unfortunately was not able to trigger the behavior that you're seeing.

I do think Stripe support (https://support.stripe.com/contact) at this point are better equipped to help you, since they can actually look at details of your account and particular webhook requests and such things, if needed, and so far
I haven't had any luck in triggering the issue myself.

**Comment by wicka-aus** [comment]
Update.

Deleted all webhooks, Vercel envir variables and created new endpoint and worked fine!

Sanity salvaged! Thanks for all your help!
