### ISSUE TITLE
Cannot remove payment.billing_details.name when trying to update the payment method

### ISSUE THREAD

**Issue by AndreiBatinasVlad** [stripe/stripe-node#1304]
Hey guys!
I have a payment method that I'm trying to update. The payment method billing details looks like this right now:
`{ name: 'Batinas Andrei', address: { country: RO } }`

I've tried to call `stripe.paymentMethods.update` with billing_details.name set to null or to empty string but I got the error that says `You passed an empty string for 'billing_details[name]. We assume empty values are an attempt to unset a parameter; however 'billing_details[name]' cannot be unset. You should remove 'billing_details[name]' from your request or supply a non-empty value`.

The problem is that if I try to update the billing_details without adding the key name nothing happens, name is not removed.

**Comment by remi-stripe** [comment]
@AndreiBatinasVlad Github issues should be limited to bugs with the stripe-node library itself. This is a question about our API and should be sent to our support team instead: https://support.stripe.com/contact

To unblock you though I can explain the issue. We don't support _removing the name_ in this case. You can replace it for another name but you can't just unset it for now. I'll flag to our product team as a potential feature request though it's unlikely to happen soon and for now you should aim to only replace the name.

**Comment by remi-stripe** [comment]
@AndreiBatinasVlad We just released a change today that now lets you unset the name and other properties inside `billing_details`

**Comment by AndreiBatinasVlad** [comment]
@remi-stripe nice! Thank you 👋
