### ISSUE TITLE
stripe.customers.listSources not working

### ISSUE THREAD

**Issue by Pic2490** [stripe/stripe-node#1306]
const cards = await stripe.customers.listSources(
  'cus_KhCuxlQfyrY19q',
  {object: 'card', limit: 3}
);

I'm using the iOS SDK and I set a test card of 424242.... through the app. My app can only save if it's successful on your server and response is sent to my app so I know things should be working fine. However, when I use the customerId and try to listSources() I get an empty array. I recently switched over to .mjs also. Maybe that has something to do with it? 

The customer id  test key is live please try testing it yourselves

**Comment by richardm-stripe** [comment]
Hello @Pic2490, the issue you describe involves either the Stripe API itself or the particulars of your integration with it, and is unlikely to relate to a bug with the `stripe-node` library itself, so I am closing this issue.

Can you reach out to support with your question at https://support.stripe.com/contact? They should be able to help you more interactively and reference the particulars of your account and the requests you are sending.
