### ISSUE TITLE
There is no plan type in Subscription.

### ISSUE THREAD

**Issue by TenUchikawa** [stripe/stripe-node#1316]
I have no choice but to rewrite Subscriptions.d.ts and use it myself, but I would like you to fix it.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/63717580/147433376-3aa36cde-a436-4920-9900-8a1fcfed2a52.png">

<img width="356" alt="image" src="https://user-images.githubusercontent.com/63717580/147433456-94b756d7-fab6-435e-9f61-740f68821593.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/63717580/147433426-135fbce8-c3e8-4117-97ca-e5889b0a897f.png">

**Comment by richardm-stripe** [comment]
Hello @TenUchikawa,

`Subscription.plan` is deprecated and we deliberately choose not to expose it in the latest versions of `stripe-node`, even though the API still returns it. We recommend you [use the Prices API instead](https://stripe.com/docs/billing/migration/migrating-prices).
