### ISSUE TITLE
Checkout with promotion code issue

### ISSUE THREAD

**Issue by andreymolchanov** [stripe/stripe-node#1318]
Hi! When I create a checkout session with promotion_code = promo_1Jz2nqHYpjoWS5sJGbalQRLV, sometimes we receive a "This promotion code cannot be redeemed because the associated customer has prior transactions." error. But, first, there isn't a customer yet. And, second, if I create the same checkout session but without a promotion_code param and then enter this customer-facing code on the checkout page, it works nice. So the problem is just with the pre-filling.

Node 12
Stripe Node: ^8.145.0

P.S. The problem is quite similar with https://github.com/stripe/stripe-php/issues/1146

**Comment by richardm-stripe** [comment]
Hello @andreymolchanov, this forum is for issues with the `stripe-node` library itself, but based on the behavior you are reporting, this more likely it involves an issue with the Stripe API itself or your integration. I recommend reaching out to stripe support at https://support.stripe.com/contact - where the team will be able to more interactively diagnose with you what is going on.
