### ISSUE TITLE
listUsageRecords for subscriptions missing

### ISSUE THREAD

**Issue by mgarabedian** [stripe/stripe-node#1319]
On stripe.com, I am able to view usage records for a subscription item. The Api call is the following GET:

v1/subscription_items/SUBSCRIPTION_ITEM_ID/usage_records?current_period=true&include%5B%5D=total_count&limit=30

I do not see any place that this exists in the api.

**Comment by mgarabedian** [comment]
It seems to work on https://dashboard.stripe.com/v1, but I cannot get the same API call to work. I suppose it is not supported, which is an issue for my project. I need to be able to be able to override (set) usage records, but I cannot get the timestamps since i cannot access the individual records

**Comment by richardm-stripe** [comment]
Hello @mgarabedian. You are correct that the public API does not expose `GET /v1/subscription/{subscription}/usage_records`.

This forum is intended for issues with the `stripe-node` library in particular, whereas your question involves an aspect of the Stripe API in general -- so I am going to close out this issue and recommend reaching out to Stripe support at [https://support.stripe.com](https://support.stripe.com), or the [Stripe Developer Discord](https://discord.com/invite/stripe) to see if they can help you find another way to accomplish your goal.

I did notice that in [our documentation](https://stripe.com/docs/billing/subscriptions/metered) we state
> If you need to see the usage for a customer during a current period, you can retrieve the upcoming invoice and check the quantity for each subscription_item.
I don't think this will give you the exact timestamps of the usage records as you desire, but maybe this would still be enough information for you to accomplish what you need?
