### ISSUE TITLE
List accounts by email support

### ISSUE THREAD

**Issue by xinghul** [stripe/stripe-node#1320]
### Feature request

Is there a plan to support listing accounts by email?

I know we can list customers by email, would be great to be able to do the same for connected accounts, otherwise, we'll end up creating 'duplicate' accounts with the same email.

**Comment by remi-stripe** [comment]
@xinghul Thanks for the report. Github issues are limited to bugs or feature requests with the stripe-node library specifically. Your ask is more a product ask and I recommend reporting your interest for this with our support team directly: https://support.stripe.com/contact though I'll flag internally too!
