### ISSUE TITLE
How should errors be handled in Typescript?

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#1322]
Hi, I'm unsure how to handle errors in Typescript when following this [Error Handling Guide](https://github.com/stripe/stripe-node/wiki/Error-Handling).

For example:

```typescript
 const response = await stripe.oauth.token({
      grant_type: 'authorization_code',
      code: 'code',
 }).catch(error => {
     // error is not typed here?
     // error instanceof ??   
     // what's the proper way to safely access `error.type`?
 });
```

Sorry if I'm missing something obvious but can't find any reference to typings in the docs.

![image](https://user-images.githubusercontent.com/7410770/148656628-da475ec9-cbfd-423c-9d23-76da6c9324d5.png)

**Comment by davidbielik** [comment]
Thanks @dcr-stripe ! I don't think I can edit the error handling wiki but could be nice to add there:

```typescript
import Stripe from "stripe";

if (error instanceof Stripe.StripeError) {
    // handle stripe error safely in typescript
}
   
```

**Comment by dcr-stripe** [comment]
Great suggestion @davidbielik - updated https://github.com/stripe/stripe-node/wiki/Error-Handling#typescript. Thank you!
