### ISSUE TITLE
Typescript `charge.status` is defined as `string` instead of explicit values

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#1330]
Hi, I noticed that `charge.status` is defined as `string` instead of `"succeeded" | "pending" | "failed"`, whereas other entities like `Subscription.status` is explicitly defined.

**Comment by dcr-stripe** [comment]
Hi @davidbielik , thanks for the report! Let me see if we can change this to an enum and get back to you!

**Comment by dcr-stripe** [comment]
This is now fixed and released in https://github.com/stripe/stripe-node/releases/tag/v8.198.0.

Thanks again for the report!
