### ISSUE TITLE
Not able to use PaymentLinks

### ISSUE THREAD

**Issue by zachjonesnoel** [stripe/stripe-node#1341]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Node library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your Node version and the version of the Stripe Node library you're using, as well as any other details that may be helpful in reproducing the problem.

Whenever I'm trying to run the following code - 
```
const stripe = require('stripe')('secret_key')
const paymentLink = await stripe.paymentLinks.create({ params })
```

But I'm getting the following response
```
"errorType": "TypeError",
  "errorMessage": "Cannot read property 'create' of undefined",
```

**Comment by richardm-stripe** [comment]
Hello @zachjonesnoel, thank you for the report.

The most likely cause of this error is that your version of `stripe-node` is not new enough. Payment Links were only added i n `8.200.0`. Can you confirm your version of `stripe-node`?

```
const stripe = require('stripe')('secret_key')
console.log(stripe.version)
const paymentLink = await stripe.paymentLinks.create({ params })
```

**Comment by zachjonesnoel** [comment]
Hi @richardm-stripe thanks for your quick response.
I'm on version `8.176.0`. I will update to the latest version and check it.

**Comment by zachjonesnoel** [comment]
Thanks @richardm-stripe it's working on the latest version. Will close this issue.

**Comment by scanable-dev** [comment]
Hi @richardm-stripe 
I'm having the same issue and I'm on 9.13.

```
stripe.products.create({
                name: 'Gold Special',
            })
            .then((product) => {
                return stripe.prices.create({
                    currency: 'aud',
                    unit_amount: 1000,
                    recurring: {interval: 'day'},
                    product: product.id,
                })
            })
            .then((price) => {
                return stripe.paymentLinks.create({
                    line_items: [{price: price.id, quantity: 1}],
                })
            })
            .then((payment) => {
                console.log(payment.url)
            })
```

My error is:
`return stripe.paymentLinks.create({
                                             ^
TypeError: Cannot read properties of undefined (reading 'create')`

**Comment by paulasjes-stripe** [comment]
@scanable-dev The error you're seeing would indicate that you're still running an older version of stripde-node. Please double check your version number with the following:
```js
console.log(stripe.VERSION);
```

I just tested your code on the latest version (v9.13.0) and it works as expected.

**Comment by scanable-dev** [comment]
Thanks @paulasjes-stripe I updated in the main folder but didn't update in my Firebase functions folder.
