### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Received unknown parameter: name

### ISSUE THREAD

**Issue by xkomiks** [stripe/stripe-node#1349]
Version: 
yarn 1.22.10
node: 14.17.0
stripe: "^8.202.0"

Error occurs when updating source `UnhandledPromiseRejectionWarning: Error: Received unknown parameter: name`

Code example:
```js
const stripe = require('stripe')('sk_test_K*****O');

async function boot() {
  // https://stripe.com/docs/api/cards/update
  const card = await stripe.customers.updateSource(
    'cus_E*******b',
    'src_1*******X',
    {
      name: 'Jenny Rosen'
    }
  );
  console.log(JSON.stringify(card, null, 2));
}

boot();

```

Other methods (`.createSource`, `.listSources`, `.retrieveSource`, `.deleteSource`) work fine

**Comment by yejia-stripe** [comment]
The ID for a card should begin with `card_`. The method for updating a source (ID begins with `src_`) is [`stripe.sources.update`](https://stripe.com/docs/api/sources/update).

How are you calling `stripe.customer.createSource`, and what is the response returned?

**Comment by xkomiks** [comment]
@yejia-stripe 

```js
 await stripe.customers.createSource(
    'cus_****',
    { source: body.sourceId }
  );
```

where `body.sourceId` its `result.source.id` from https://stripe.com/docs/js/tokens_sources/create_source

**Comment by yejia-stripe** [comment]
The `stripe.createSource` method in Stripe.js refers to the [Source](https://stripe.com/docs/api/sources) object, so in stripe-node you'd want to update it with `stripe.sources.update`. stripe-node's [`stripe.customers.createSource`](https://stripe.com/docs/api/cards/create) takes in a [Token](https://stripe.com/docs/api/tokens), which you can create in Stripe.js with [`stripe.createToken`](https://stripe.com/docs/js/tokens_sources/create_token?type=cardElement).

**Comment by xkomiks** [comment]
@yejia-stripe Clear. 

Can you tell me what the essence of the Source object is, is it some kind of universal object or why is it?

**Comment by yejia-stripe** [comment]
Here is some documentation that could help: [The Sources API](https://stripe.com/docs/sources), [Sources and customers](https://stripe.com/docs/sources/customers). 

If you have further integration questions, please reach out to our support team: https://support.stripe.com/contact

**Comment by xkomiks** [comment]
@yejia-stripe how to update credit card when using source object?
