### ISSUE TITLE
stripe.accounts.listExternalAccounts does not recognize "object" property for Stripe.ExternalAccountListParams

### ISSUE THREAD

**Issue by stuyy** [stripe/stripe-node#1351]
When trying to use the `stripe.accounts.listExternalAccounts` method with TypeScript, it does not recognize the "object" property as a valid property for ExternalAccountListParams. Using ts-ignore, I am able to successfully retrieve external accounts based on the type I want, `card` or `bank_account`. After testing, I was able to get a successful response for each value.

```
this.stripe.accounts.listExternalAccounts(accountId, {
    // @ts-ignore
    object: 'card',
});
```

**Comment by remi-stripe** [comment]
@stuyy Thanks for the report! This is something we want to improve in the future so I'm going to tag as future but we likely won't get to that one soon unfortunately.
