### ISSUE TITLE
Property 'metadata' does not exist on type 'Object'

### ISSUE THREAD

**Issue by paul-uz** [stripe/stripe-node#1365]
Using the latest API version, and writing my code in Typescript, when trying to get the `metadata` object inside `data.object`, I get this error in my IDE, stopping TypeScript form compiling:

> Property 'metadata' does not exist on type 'Object'

`metadata` is 100% in the `data.object` object, so not sure why it's not including in the types?

**Comment by paul-uz** [comment]
I cannot see any type for Subscriptions, for `customer.subscription.*`

**Comment by paul-uz** [comment]
I'm still getting an error:

<img width="1198" alt="Screenshot 2022-03-07 at 16 53 36" src="https://user-images.githubusercontent.com/73826774/157080376-7f0d37ae-2d2c-4fc8-8250-4eb9abee85e4.png">

**Comment by richardm-stripe** [comment]
Hi @paul-uz. Try

```typescript
const eventData = body.data.object as Stripe.Subscription
```

We have an [end-to-end](https://github.com/stripe-samples/accept-a-payment/blob/main/custom-payment-flow/server/node-typescript/src/server.ts#L134) typescript example that might be a useful reference.

**Comment by paul-uz** [comment]
@richardm-stripe that helps to get a bit further, but now, on the `Stripe.Subscription` object, `plan` is missing.

<img width="751" alt="Screenshot 2022-03-08 at 09 47 59" src="https://user-images.githubusercontent.com/73826774/157211485-5a679e33-aaf5-4a84-a1ea-a74f1d642843.png">

See `plan` (towards the bottom of screenshot) in the object that was logged:

<img width="621" alt="Screenshot 2022-03-08 at 09 48 15" src="https://user-images.githubusercontent.com/73826774/157211556-d9e6507b-68e6-48c0-befa-cc4ae945a60f.png">

**Comment by remi-stripe** [comment]
@paul-uz None of those are bugs in the libraries though and they are more an integration question. Github issues are limited to bugs with the libraries and you likely will have more follow up questions about the API and specific quirks.

We recommend that you work directly with our support team for help. You can contact them [here](https://support.stripe.com/contact) or you can chat with developers on our Discord server [here](https://stripe.com/go/developer-chat)

**Comment by remi-stripe** [comment]
@paul-uz It's not a class bug because there's a reason, the same way there wasn't a bug with `metadata` and so it now is more an integration question about your understanding about our API and how it works. If we answer that one you'll definitely ask about others. You wouldn't be wrong to do that, but it's not really a support form and our API has existed for well over 10 years now and we've iterated a lot on it, so there are some quirks in types that are due to hiding legacy parameters or properties for new integrations to avoid relying on those.

I'm sorry to push back but you should work with our support team instead, likely on the Discord server, where you'd get faster answers and complete explanations about the discrepancies in types that are "by design" and not a bug.

**Comment by robert-nash** [comment]
I am not a TypeScript expert but I do wonder if, whilst this is how the library is designed at the moment, it is something which could possibly be improved. It seems that improving the typings in some way (perhaps with discriminated unions) might make this a bit user friendly and reduce the times when it is necessary to manually cast the object which seems to introduce the possibility for incorrectly casting when it might be possible to let TypeScript manage this by itself.

**Comment by paul-uz** [comment]
@robert-nash exactly. It is a bug, and not an integration issue, because the provided typings don't represent the data properly.

**Comment by robert-nash** [comment]
I just wanted to confirm that there was a modicum of basis to what I was saying so I attempted to modify the types I am making use of to see if it was possible. I made a small modification to types/2020-08-27/Events.d.ts implementing a base "EventBase" interface which has all of the common properties  and then two example event interfaces "PaymentIntentEvent" and "SubscriptionEvent" which extend "EventBase" but have a union of possible values for the type and specific types for data.object. This means that a simple switch on event.type allows TypeScript to correctly (in this very contrived example) infer the type of object.

I understand that actually implementing this may not be at all simple and I don't know if the way you are currently generating the types from OpenAPI even allows this but I think it is fair to say that this is at least an opportunity for improvement in the library since it seems that TypeScript is capable of representing the way the API works more accurately

Here is my example Events.d.ts (obviously I understand that this is not at all how you would implement this but is just a minimum example which I think shows that it is possible to achieve this).

```
// File generated from our OpenAPI spec

import Stripe from "stripe";

interface EventBase {
  /**
   * Unique identifier for the object.
   */
  id: string;

  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: 'event';

  /**
   * The connected account that originated the event.
   */
  account?: string;

  /**
   * The Stripe API version used to render `data`. *Note: This property is populated only for events on or after October 31, 2014*.
   */
  api_version: string | null;

  /**
   * Time at which the object was created. Measured in seconds since the Unix epoch.
   */
  created: number;

  data: Event.Data;

  /**
   * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
   */
  livemode: boolean;

  /**
   * Number of webhooks that have yet to be successfully delivered (i.e., to return a 20x response) to the URLs you've specified.
   */
  pending_webhooks: number;

  /**
   * Information on the API request that instigated the event.
   */
  request: Event.Request | null;

  /**
   * Description of the event (e.g., `invoice.created` or `charge.refunded`).
   */
  type: string;
}

interface PaymentIntentEvent extends EventBase {
  type: "payment_intent.succeeded" |"payment_intent.amount_capturable_updated";
  data: {
    object:Stripe.PaymentIntent;
    previous_attributes: Data.PreviousAttributes
  }
}

interface SubscriptionEvent extends EventBase {
  type: "customer.subscription.updated" |"customer.subscription.trial_will_end";
  data: {
    object:Stripe.PaymentIntent;
    previous_attributes: Data.PreviousAttributes
  }
}

declare module 'stripe' {
  namespace Stripe {
    /**
     * The Event object.
     */
    type Event = PaymentIntentEvent | SubscriptionEvent

    namespace Event {
      interface Data {
        /**
         * Object containing the API resource relevant to the event. For example, an `invoice.created` event will have a full [invoice object](https://stripe.com/docs/api#invoice_object) as the value of the object key.
         */
        object: Data.Object;

        /**
         * Object containing the names of the attributes that have changed, and their previous values (sent along only with *.updated events).
         */
        previous_attributes?: Data.PreviousAttributes;
      }

      namespace Data {
        interface Object {}

        interface PreviousAttributes {}
      }

      interface Request {
        /**
         * ID of the API request that caused the event. If null, the event was automatic (e.g., Stripe's automatic subscription handling). Request logs are available in the [dashboard](https://dashboard.stripe.com/logs), but currently not in the API.
         */
        id: string | null;

        /**
         * The idempotency key transmitted during the request, if any. *Note: This property is populated only for events on or after May 23, 2017*.
         */
        idempotency_key: string | null;
      }
    }

    interface EventRetrieveParams {
      /**
       * Specifies which fields in the response should be expanded.
       */
      expand?: Array<string>;
    }

    interface EventListParams extends PaginationParams {
      created?: Stripe.RangeQueryParam | number;

      /**
       * Filter events by whether all webhooks were successfully delivered. If false, events which are still pending or have failed all delivery attempts to a webhook endpoint will be returned.
       */
      delivery_success?: boolean;

      /**
       * Specifies which fields in the response should be expanded.
       */
      expand?: Array<string>;

      /**
       * A string containing a specific event name, or group of events using * as a wildcard. The list will be filtered to include only events with a matching event property.
       */
      type?: string;

      /**
       * An array of up to 20 strings containing specific event names. The list will be filtered to include only events with a matching event property. You may pass either `type` or `types`, but not both.
       */
      types?: Array<string>;
    }

    class EventsResource {
      /**
       * Retrieves the details of an event. Supply the unique identifier of the event, which you might have received in a webhook.
       */
      retrieve(
        id: string,
        params?: EventRetrieveParams,
        options?: RequestOptions
      ): Promise<Stripe.Response<Stripe.Event>>;
      retrieve(
        id: string,
        options?: RequestOptions
      ): Promise<Stripe.Response<Stripe.Event>>;

      /**
       * List events, going back up to 30 days. Each event data is rendered according to Stripe API version at its creation time, specified in [event object](https://stripe.com/docs/api/events/object) api_version attribute (not according to your current Stripe API version or Stripe-Version header).
       */
      list(
        params?: EventListParams,
        options?: RequestOptions
      ): ApiListPromise<Stripe.Event>;
      list(options?: RequestOptions): ApiListPromise<Stripe.Event>;
    }
  }
}
```
