### ISSUE TITLE
Having trouble importing Stripe constructor in TS

### ISSUE THREAD

**Issue by samatcolumn** [stripe/stripe-node#1367]
My project uses TypeScript and Stripe is one of the last libraries we're still using "without types".

What we've been doing, which works, is this:
```js
const stripe = require('stripe')('OUR_STRIPE_KEY');
```

What I want to do is this:
```ts
import Stripe from 'stripe';

// Also tried:
// import * as Stripe from 'stripe';

const stripe = new Stripe(functions.config().stripe.key, {
  apiVersion: null
});
```

However I'm getting this error in VSCode:
```
File '/<MY PROJECT>/node_modules/stripe/types/2020-08-27/index.d.ts' is not a module.ts(2306)
```

We're using TypeScript version `3.8.3` and Node version `10.x` ... any ideas? Below is a sample of our tsconfig:

```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "build",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true,
    "allowJs": true,
    "skipLibCheck": true,
    "baseUrl": "src",
    "esModuleInterop": true,
    "strictPropertyInitialization": false,
    },
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

**Comment by richardm-stripe** [comment]
Hello @samatcolumn,

Haven't looked in detail yet, but can you try this?
```diff
- import * as Stripe from 'stripe';
+ import Stripe from 'stripe';
```

**Comment by samatcolumn** [comment]
@richardm-stripe whoops sorry I should have mentioned that I've tried both forms and neither one works.

**Comment by richardm-stripe** [comment]
Hello @samatcolumn -- I've tried reproducing your setup: https://github.com/richardm-stripe/debugging-ts

but I can't reproduce the same error.

Your error message seems to indicate something is wrong with the contents of `node_modules/stripe/types/2020-08-27/index.d.ts`, which is strange. What version of `stripe` is in your package.json? Maybe wiping and reinstalling node_modules is worth a try?

**Comment by samatcolumn** [comment]
@richardm-stripe sorry this turned out to be total user error 🤦 . Thanks so much for the _super_ quick response!
