### ISSUE TITLE
How to retrieve fees that Stripe takes on each payments ?

### ISSUE THREAD

**Issue by brice-noowu** [stripe/stripe-node#1373]
Hi, I would like to retrieve the fees that Stripe takes on each payments. I'm using the Payment Intent API, but when I try to log the intent on payment success, I can see the total amount (ex:2000) but not the final amount with the fees taken. Something like : 
```
{ 
  ... payment_intent_results
  amount:2000,
  stripe_fees:53,
  final_amount:1947
}
```

Where can I get this information ? Thanks !

**Comment by remi-stripe** [comment]
Github issues should be limited to bugs with the library itself and your question is an integration question. Please work with our support team for help on this: https://support.stripe.com/contact

To give you a quick pointer, this is documented in details here: https://stripe.com/docs/expand/use-cases#stripe-fee-for-payment
