### ISSUE TITLE
Property 'charge' does not exist on type 'string | Invoice'

### ISSUE THREAD

**Issue by Voyager-Two** [stripe/stripe-node#1385]
Typescript v4.6.3
NodeJS v14

![image](https://user-images.githubusercontent.com/3676208/160497202-79e983db-36a9-46b9-8af5-fa5f5485d184.png)

```typescript
import Stripe from 'stripe';

const subscription: Stripe.Subscription = await this.stripeClient.subscriptions.retrieve(
  'subscriptionId',
  {
    expand: ['latest_invoice'],
  }
);
const refund = await this.stripeClient.refunds.create({
  charge: subscription.latest_invoice.charge,
});
```

**Comment by dcr-stripe** [comment]
Hey @Voyager-Two , thanks for the report.

As you're using an expandable field, you'll need to cast `latest_invoice` to `Invoice`. See [Using `expand` with TypeScript](https://github.com/stripe/stripe-node#using-expand-with-typescript) in the README.

Does changing it to:

```
const latestInvoice = (subscription.latest_invoice as Stripe.Invoice);
const refund = await this.stripeClient.refunds.create({
  charge: latestInvoice.charge,
});

```

solve the issue for you?

**Comment by Voyager-Two** [comment]
@dcr-stripe 
That makes sense, however now I get below error.
Are we able to chain the casting? I couldn't find any examples on the web.
I guess a work-around could be using `if` statements to narrow it down.

![image](https://user-images.githubusercontent.com/3676208/160499867-75afb825-7236-46e7-8f99-d71101173584.png)

**Comment by dcr-stripe** [comment]
Since you aren't expanding the `charge` within the invoice, you should be able to do:

```
(subscription.latest_invoice as Stripe.Invoice).charge as string
```

**Comment by Voyager-Two** [comment]
Cheers! Thanks much ❤️

**Comment by Voyager-Two** [comment]
This works:

```typescript
    const paymentIntent = (<Stripe.Invoice>subscription.latest_invoice).payment_intent as Stripe.PaymentIntent;

    return {
      subscriptionId: subscription.id,
      clientSecret: paymentIntent.client_secret,
      rawResponse: subscription,
    };
```
