### ISSUE TITLE
Subscription description not found in checkout session create.

### ISSUE THREAD

**Issue by StefanGhiban** [stripe/stripe-node#1418]
### Describe the bug

I am trying to create a checkout session and provide descriptions for both one time payments and for subscriptions as well. I am setting these descriptions via payment_intent_data.description and subscription_data.description. The description field is available for payment_intent_data but not for subscription.

### To Reproduce

1. Create a checkout session: stripe.checkout.sessions.create()
2. Provide payment_intent_data: {description: "test"} field
3. Provide subscription_data: {description: "test"} field
4. In typescript, an error will show up as description does not exist on type SubscriptionData.

### Expected behavior

Expected to set a description for both one time payment and for subscription type payments. It is only possible for me on the one time payment and not subscriptions.

### OS

macos

### Node version

v16.13.0

### Library version

v8.191.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@StefanGhiban Thanks for the heads up! `subscription_data[description]` is brand new and it hasn't yet made it into stripe-node but we're working on it!

**Comment by StefanGhiban** [comment]
> @StefanGhiban Thanks for the heads up! `subscription_data[description]` is brand new and it hasn't yet made it into stripe-node but we're working on it!

Thank you!

**Comment by remi-stripe** [comment]
This was fixed in https://github.com/stripe/stripe-node/pull/1420 and is now available in 9.1.0!
