### ISSUE TITLE
Refund API appears to be not implemented

### ISSUE THREAD

**Issue by superpan** [stripe/stripe-node#142]
According to stripe documentation, there should be a refund api set that allows you to create/capture refunds with arbitrary amounts or a charge id.  The SDK is missing that api set.  The only refund I see is hooked onto the charge api, and only allows for refunding based on a charge id.

**Comment by michelle** [comment]
You can do partial refunds like so:

`stripe.charges.refund('ch_XXX', {amount: yourPartialAmount});`

**Comment by superpan** [comment]
And if I don't have the charge id?

**Comment by michelle** [comment]
You must have the ID of the charge you're trying to refund in order to create a refund. This is the case across all of our different libraries: https://stripe.com/docs/api/curl#create_refund

**Comment by michelle** [comment]
![screen shot 2015-02-08 at 3 29 09 pm](https://cloud.githubusercontent.com/assets/928757/6099198/41150aee-afa7-11e4-84df-995e9d2b8d29.png)
Under `arguments`:

**Comment by superpan** [comment]
Got it.  Thanks a lot.  Closing.
