### ISSUE TITLE
The subscription description does not appear in the payments dashboard when creating a checkout session.

### ISSUE THREAD

**Issue by StefanGhiban** [stripe/stripe-node#1421]
### Describe the bug

In relation to #1418 . This issue was solved, I can now set a description for the subscription. The problem is, the description does not show up anywhere in the stripe dashboard. The payment intent description is showing up as the description in the payments tab, as seen below, but the description for subscription is a default one that was not supplied by me.
![image](https://user-images.githubusercontent.com/47953165/168024265-33536f2d-fc02-4d0c-b78c-d217d0507c33.png)
My questions are, what purpose does that description serve, where I can see it? And how can I set the description for a subscription when creating a checkout session in order to have have the same pattern as the one time payment description.

### To Reproduce

1. Create a checkout session with: await stripe.checkout.sessions.create()
2. Supply subscription_data: {description: "test"}

### Expected behavior

Expect the description to show up in the payments table instead of the default "Subscription creation" text.

### OS

macos

### Node version

v16.13.0

### Library version

v9.1.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@StefanGhiban Github issues should be limited to bugs with the library itself. This is a feature request for the Dashboard so I'd recommend flagging to our support team: https://support.stripe.com/contact
