### ISSUE TITLE
Missing Types on Invoice PaymentMethodType

### ISSUE THREAD

**Issue by baristikir** [stripe/stripe-node#1424]
### Describe the bug

`Invoice.d.ts` is missing payment methods on the type [`PaymentMethodType`](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Invoices.d.ts#L733). From the docs - [Invoice API Docs](https://stripe.com/docs/api/invoices/object#invoice_object-payment_settings-payment_method_types) - `eps` and `p24` payment methods are missing on type `PaymentMethodType`.

### To Reproduce

Missing types

### Expected behavior

Missing types

### OS

macOS

### Node version

node v16.13.2

### Library version

stripe v9.1.0

### API version

2020-08-27

**Comment by ahanusek** [comment]
The same issue with Payment Capabilities (missing Blik payment method).

**Comment by Praveenpn180** [comment]
upi, netbanking payment methods missing.

**Comment by remi-stripe** [comment]
@Praveenpn180 same as my last comment above, those are not payment method types that we publicly support so it's expected they are not in the library.

**Comment by pakrym-stripe** [comment]
`PaymentMethodType` now has both `eps` and `p24`.
