### ISSUE TITLE
Business type of Express Account changes automatically after generate an Account Link.

### ISSUE THREAD

**Issue by mariovillamizar** [stripe/stripe-node#1425]
### Describe the bug

First of all, I'm not sure if it's an actual bug or if I'm misunderstanding how Connected Accounts should work.
The model of our business is similar to Lyft or Uber where users can act as service providers and get paid for it. So I'm using this tutorial: https://stripe.com/docs/connect/add-and-pay-out-guide.
So basically when a user becomes a service provider, from the server I'm creating an Express Account with `business_type: 'individual',` and also I'm using the `individual` hash to pre-populute some info of the service provider like `first_name`, `last_name`, `email` and `phone`.
At this point, if the service provider updates for example the phone or email from the app, then from server I'm able to update its Express Account with the new info.
Before start offering a service in the app, the service provider has to complete the Express Account by adding the due info and a bank account in order to receive the payments. In order to do this, I'm requesting to the server an Account Link of `type: 'account_onboarding'`. The other option for this parameter is `'account_update'` but according to the docs it only works for Custom Accounts.
Immediately after the link is generated (even without opening the link url) the `business_type` parameter of the Account is unset (or at least NOT 'individual'). The proof is that if the service provider updates let's say the email from the app, then when I try to update the Express Account with this new info I get this error: `message: "This application does not have the required permissions for the parameter 'individual' on account 'abc_xyz'."`
Something weird here is that if I open the link, I'm NOT asked for the business type, so looks like for the link the Account is still individual. Anyway if I complete the forms of the Link and save, the `business_type` keeps unset, or at least not 'individual'.

This is what the account looks like after creating it:
![Screen Shot 2022-05-18 at 3 54 34 PM](https://user-images.githubusercontent.com/10704258/169154584-cc404b46-9f60-4089-a7c5-d007a50202cc.png)

This is what the account looks like after getting the Account Link:
![Screen Shot 2022-05-18 at 3 59 45 PM](https://user-images.githubusercontent.com/10704258/169154945-b6b298d6-6047-48b1-beb9-1598700fbca1.png)

As you can see the Business type is no longer present.

### To Reproduce

1. Create an account as follow:
```
await stripe.accounts.create({
  type: 'express',
  business_type: 'individual',
  email: 'email@domain.test',
  individual: {
    first_name: 'First',
    last_name: 'Last',
    email: 'email@domain.test',
    phone: '+1 9876543210'
  },
  requested_capabilities: ['transfers'],
  settings: { payouts: { schedule: { interval: 'manual' } } }
});
```

2. Generate an Account Link to complete the Account as follow:
```
await stripe.accountLinks.create({
  account: 'abc_xyz',
  refresh_url: 'https://business/refresh',
  return_url: 'https://business/return',
  type: 'account_onboarding'
});
```

3. Try to update the `individual.email` as follow:
```
await stripe.accounts.update('abc_xyz', {
  individual: {
    email: 'other_email@domain.test'
  }
});
```

4. See the error message: `message: "This application does not have the required permissions for the parameter 'individual' on account 'acct_1L0rvuPCEJRkVYWh'."`

### Expected behavior

I expect to keep the `business_type` as individual.

### OS

macOS

### Node version

Node v14.16.1

### Library version

stripe-node 8.219.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@mariovillamizar I think you are misunderstanding the issue because the error message is not super clear. The error is not that the business type is changing. It's more that after the AccountLink is created, the platform stops "owning" the account because it's an Express account. At that point, the account is going to be "claimed" by the account owner and you will not have access to the `individual` hash or the majority of the PII for the account. So as soon as you create the AccountLink the Account becomes a shell where you can't read or set most of that information anymore.

I hope this helps! I'm going to close as this is more an integration help request. If you have follow up questions, please reach out to our support team: https://support.stripe.com/contact

**Comment by mariovillamizar** [comment]
Oh thank you @remi-stripe. Yeah, your explanation is very clear. You're the man!
