### ISSUE TITLE
SubscriptionCreate.PaymentSettings save_default_payment_method

### ISSUE THREAD

**Issue by adrien-may** [stripe/stripe-node#1426]
### Describe the bug

In `subscriptions.create({payment_settings: {}})` we cannot specify `save_default_payment_method` while documentation says otherwise (see [Subscription create doc](https://stripe.com/docs/api/subscriptions/create) payment_settings, last option)

In `stripe/types/Subscription.d.ts`, paymentSettings is missing this parameter.

### To Reproduce

Try to use `save_default_payment_method` in for ex `subscriptions.create({ payment_settings: { save_default_payment_method: "off" }})`

Typescript does not allow this

### Expected behavior

Types should be up to date with documentation

### OS

macOs

### Node version

Node v14

### Library version

stripe-node 8.222

### API version

2020-08-27

**Comment by ramya-stripe** [comment]
This is now available in [version 9.2.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#920---2022-05-19) and higher of stripe-node
