### ISSUE TITLE
Error stating invalid api key while the same api key is working in curl

### ISSUE THREAD

**Issue by alan-jouhar** [stripe/stripe-node#1437]
### Describe the bug

I have this strange situation where a call to `stripe.tokens.create` will fail with the following error message:

```
 message: 'Invalid JSON received from the Stripe API',
```
After adding `console.log(response)` to `lib/net/NodeHttpClient.js` at line `116` the `response` was:

```
{
  "error": {
    "message": "Invalid API Key provided: "sk_test*************************************************************************************************JhB"",
    "type": "invalid_request_error"
  }
}
```
but what is really confusing for me is that the same api key works fine with `curl`:

```
curl https://api.stripe.com/v1/tokens \
  -u sk_test*************************************************************************************************JhB: \
  -d "card[number]"="4242424242424242" \
  -d "card[exp_month]"=12 \
  -d "card[exp_year]"=2023 \
  -d "card[cvc]"=123
{
  "id": "tok_1L43NFJNc4xthbFlm7QK68pS",
  "object": "token",
  "card": {
    "id": "card_1L43NFJNc4xthbFlhfwtwNyj",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "US",
    "cvc_check": "unchecked",
    "dynamic_last4": null,
    "exp_month": 12,
    "exp_year": 2023,
    "fingerprint": "1AlWzzpHW9IrthmL",
    "funding": "credit",
    "last4": "4242",
    "metadata": {
    },
    "name": null,
    "tokenization_method": null
  },
  "client_ip": "80.238.208.13",
  "created": 1653658721,
  "livemode": false,
  "type": "card",
  "used": false
}
```

### To Reproduce

try to run the following code:
```
const stripe = require("stripe")(process.env.STRIPE_SECRECT_KEY);
async function createStripeToken(card) {
	try {
		const token = await stripe.tokens.create({
			card: {
				number: card.cardNumber,
				exp_month: card.expairy_month,
				exp_year: card.expairy_year,
				cvc: card.cvc,
			},
		});
		if (token.id) return token;
	} catch (error) {
		console.log(error)
    // Hide the original Error and throw an ambiguous one
		throw new Error("Invalid Card");
	}
}

let card = {
	cardNumber:"4242424242424242",
	expairy_month: 12,
	expairy_year: 34,
	cvc:"123"
};

(async()=>{
	let stripe_res = await createStripeToken(card)
	console.log(stripe_res)
})();
```

I will provide the secret key if needed

### Expected behavior

to get an Object instead of an error

### OS

macOS

### Node version

v16.15.0

### Library version

"^9.5.0"

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@alan-jouhar the code you shared works for me end to end. It fails if I add a `\n` to my key or similar. Is it possible that you have an issue with reading the API key from your environment variable? Does it fail if you hardcode the API key directly?

**Comment by alan-jouhar** [comment]
Surprisingly it does not fail if i hard code it.

**Comment by remi-stripe** [comment]
I think that confirms the issue is with your API key itself and how you load it in memory. Have you tried dumping it and seeing if there are invisible characters, a new line or something similar at the end?
But looks like this isn't really a stripe-node bug right?

**Comment by alan-jouhar** [comment]
@remi-stripe you are right I had an extra space after `env` var key which caused the key to be something like `"sk****" `.
notice the double quotes and the extra space.

**Comment by remi-stripe** [comment]
Awesome I'm glad this turned out to be a config issue and not a bug in the library itself. Thanks for circling back and confirming :)

**Comment by waleedAlmubarak** [comment]
> @remi-stripe you are right I had an extra space after `env` var key which caused the key to be something like `"sk****" `. notice the double quotes and the extra space.

The space in the `.properties` file was causing the issue for me.
