### ISSUE TITLE
Response status not available on error object

### ISSUE THREAD

**Issue by pkaminski** [stripe/stripe-node#145]
The error object returned from a rejected promise doesn't appear to have the HTTP response's status code available anywhere.  I'm queuing up incoming webhook events and their handling could be arbitrarily delayed, by which point the target object might've gone away.  I'd like to distinguish 404 cases (which are OK to ignore for my system) vs other ones (which are bugs or transient errors).  Right now, it looks like the only way to do this is by scraping the error message, which I'd like to avoid.

Could you please put a status code on the error object when it originates from the REST API?  Thanks.

**Comment by michelle** [comment]
Good point--we'll look into fixing this, but in the meantime, PRs are very welcome!
