### ISSUE TITLE
Klarna not shown in capabilities list 

### ISSUE THREAD

**Issue by MuhammadHadiofficial** [stripe/stripe-node#1466]
### Describe the bug

I've enabled klarna on stripe connected account. Now when send a get request to fetch list of capabilities it shows affirm and afterpay with status active. But klarna and klarna payments status remains inactive.

### To Reproduce

1. Go to stripe dashboard for your connected account
2. Goto settings -> payment methods -> klarna and click turn on.
3. curl HTTP request to https://api.stripe.com/v1/accounts/{accountID}/capabilities
4. you will find list of capabilities showing klarna as inactive

### Expected behavior

It should show all activated methods that were enabled from dashboard.

### Code snippets

```JavaScript
paymentMethods = await stripe.accounts.listCapabilities(stripeAccount);
I also tried that with nodejs package but it didn't work
```

### OS

Windows 11

### Node version

Node 16.14

### Library version

"stripe": "^8.112.0"

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@MuhammadHadiofficial Github issues should be limited to bugs with the stripe-node library itself. This is now a bug with the library and more an integration support question. Please work directly with our support team instead: https://support.stripe.com/contact
