### ISSUE TITLE
Can @types/node be installed only on development mode?

### ISSUE THREAD

**Issue by Munawwar** [stripe/stripe-node#1474]
### Describe the bug

I see `@types/node` package being installed on yarn install --prod, which does take space on an AWS lambda package zip file (on OSX I see it to be 1.8 MB unzipped, 360 KB zipped).

### To Reproduce

1. `rm -fr node_modules`
2. `yarn install --prod`
3. Check node_modules directory

### Expected behavior

Expected behavior? I don't expect dev dependencies to make its way into production deployments.

Does it matter? since it's just 360 KB?
Well, maybe not the highest priority, but "function" services like AWS lambda is sensitive to deployment package size since it increases cold start. So trimming it down is a good thing.

### OS

macOS, linux

### Node version

v14.19.1

### Library version

8.222.0

### API version

NA

**Comment by yejia-stripe** [comment]
Oops not actually closed until we release a new version (sometime later this week!)

**Comment by yejia-stripe** [comment]
Ah, actually it seems like it does need to be in `dependencies` (see #1274). Going to revert #1475 and close this out.
