### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by mrugesh-jeeves** [stripe/stripe-node#1494]
### Describe the bug

When we call the `approve` function with `authID` we get this error. 

```
{
	"message": "An unknown error occurred",
	"stack": "Error: An unknown error occurred\n    at Function.generate (/work/node_modules/stripe/lib/Error.js:42:16)\n    at res.toJSON.then.StripeAPIError.message (/work/node_modules/stripe/lib/StripeResource.js:220:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
```

### To Reproduce

Use `approve` function of stripe module. It does not produce for all the `authId`. 

### Expected behavior

` await stripe.issuing.authorizations.approve(authID);`

This function should not return `500` status code.

### Code snippets

```JavaScript
` await stripe.issuing.authorizations.approve(authID);`
```

### OS

linux

### Node version

Node v16.15.0

### Library version

8.133.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@mrugesh-jeeves This looks like an API error and not a bug with the library. I'd recommend working with our support team directly for help as they can look at your account and the 500 errors and investigate what is happening. You can contact them here: https://support.stripe.com/contact
