### ISSUE TITLE
feature_list not present in api

### ISSUE THREAD

**Issue by jannikbuscha** [stripe/stripe-node#1495]
### Describe the bug

In the API logs for `/v1/products/prod_xxx` I get the following message:
```json
{
  "id": "prod_xxx",
  "object": "product",
  "active": true,
  "attributes": [],
  "created": 123,
  "default_price": "price_xxx",
  "description": "Basic plan.",
  "feature_list": [
    "Test 1",
    "Test 2",
    "Test 3",
    "Test 4",
    "Test 5"
  ],
  ...
}
```

However, when I do `stripe.products.list()` I don't get a `feature_list`:
![image](https://user-images.githubusercontent.com/74017697/182117111-1d503cee-9e5b-430a-8f7d-80e87a329e5a.png)

### To Reproduce

/

### Expected behavior

/

### OS

Win10

### Node version

16.14.2

### Library version

9.12.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
`features_list` is a Dashboard-only API which means only our Dashboard can set and view this and use it in hosted flows like our new [Pricing Table](https://stripe.com/docs/payments/checkout/pricing-table) product. We do want to bring this to the API in the future, it's just not ready yet.

I'm going to close this out as there's no bug with the library right now, it's just not a feat publicly available yet.

**Comment by jannikbuscha** [comment]
> `features_list` is a Dashboard-only API which means only our Dashboard can set and view this and use it in hosted flows like our new [Pricing Table](https://stripe.com/docs/payments/checkout/pricing-table) product. We do want to bring this to the API in the future, it's just not ready yet.
> 
> I'm going to close this out as there's no bug with the library right now, it's just not a feat publicly available yet.

hey, thanks for your answer it helped me a lot, however i have one more question. Is it possible to style the element more? because it is a shadow-root component. (e.g. bg-color, text-color, margin- padding...)

**Comment by remi-stripe** [comment]
Github issues are limited to bugs with the library itself. Please work with our support team for help on this: https://support.stripe.com/contact
