### ISSUE TITLE
Deprecate use of `child_process` for bun compatibility

### ISSUE THREAD

**Issue by paulasjes-stripe** [stripe/stripe-node#1514]
### Is your feature request related to a problem? Please describe.

stripe-node currently uses the `exec` function of the `child_process` library to gather usage telemetry. It does this by [running](https://github.com/stripe/stripe-node/blob/4e82ccafda2017654ac264c070e7ebfa0e662fcd/lib/stripe.js#L452) `uname -a` in a shell.

Newcomer runtime [bun](https://github.com/oven-sh/bun) doesn't have `child_process` implemented yet, preventing stripe-node from being able to be used.

Instead of using `exec`, we could just use the `os` core library to get the OS version:

```
require('os').version();
```

Here's a comparison of the two:
```
> os.version()
'Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000'

❯ uname -a
Darwin paul 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64
```

`os` is available in bun plus probably safer than having a function that can execute instructions on the command line.

### Describe the solution you'd like

Deprecate usage of `child_process` in favour of `os`. Or remove the collection of OS version data entirely if we don't need it.

### Describe alternatives you've considered

Wait for bun to implement `child_process`.

**Comment by anniel-stripe** [comment]
Hi, sorry for the wait here. It looks like `node:child_process` was implemented in [Bun v0.3.0](https://bun.sh/blog/bun-v0.3.0#node-js-compatibility). In addition, as of [v11.10.0](https://github.com/stripe/stripe-node/releases/tag/v11.10.0), stripe-node should work in Bun without relying on Node.js APIs.

Please don't hesitate to let us know if you encounter more issues with stripe-node in Bun!
