### ISSUE TITLE
Remove caption from Product type

### ISSUE THREAD

**Issue by JarrodMFlesch** [stripe/stripe-node#1518]
### Is your feature request related to a problem? Please describe.

I see [here](https://github.com/stripe/stripe-node/blob/0b76d067cab9a9628e1845c705e2139abe696d11/types/2022-08-01/Products.d.ts#L39) that caption is a required property on Product, but I do not see it in the docs [here](https://stripe.com/docs/api/products/object) and it does not seem to come back from the API.

So when I copy a response from a Products list response, and type it as `Stripe.ApiList<Stripe.Product>`, TS complains because caption is required, but is not returned.

### Describe the solution you'd like

I think caption may be incorrect or a deprecated type? If it is deprecated - should the type be optional?

### Describe alternatives you've considered

I did a search on open/closed issues for regarding `caption` but could not find anything.

**Comment by dcr-stripe** [comment]
Thanks for the report @JarrodMFlesch and sorry you're experiencing issues! 

The type should indeed be optional, since it's only included for products with `type` set to `good`. The team will look into a fix and get back to you as soon as possible!

**Comment by dcr-stripe** [comment]
This is actually a broader issue, where a number of types that are both nullable and optional should be marked as such. As an example, `Product.unit_label` is also in this category.

**Comment by dcr-stripe** [comment]
Thanks for the report again @JarrodMFlesch  - this has been fixed in [v10.6.0](https://github.com/stripe/stripe-node/releases/tag/v10.6.0).
