### ISSUE TITLE
StripeClient.customers.create doesn't accept Stripe.Customer interface as param

### ISSUE THREAD

**Issue by phlcastro** [stripe/stripe-node#1541]
### Describe the bug

Is it correct to `StripeClient.customers.create` to not accept a variable of `Stripe.Customer` as its parameter?

### To Reproduce

```
const customer: Omit<Stripe.Customer, 'id'> = {};

StripeClient.customers.create(customer); // No overload matches this call
```

```
No overload matches this call.
  Overload 1 of 2, '(params?: CustomerCreateParams | undefined, options?: RequestOptions | undefined): Promise<Response<Customer>>', gave the following error.
    Argument of type 'Omit<Customer, "id">' is not assignable to parameter of type 'CustomerCreateParams'.
      Types of property 'address' are incompatible.
        Type 'Address | null' is not assignable to type 'Emptyable<AddressParam> | undefined'.
          Type 'Address' is not assignable to type 'Emptyable<AddressParam> | undefined'.
            Type 'Address' is not assignable to type 'AddressParam'.
              Types of property 'line1' are incompatible.
                Type 'string | null' is not assignable to type 'string'.
                  Type 'null' is not assignable to type 'string'.
  Overload 2 of 2, '(options?: RequestOptions | undefined): Promise<Response<Customer>>', gave the following error.
    Type 'Omit<Customer, "id">' has no properties in common with type 'RequestOptions'.ts(2769)
```

### Expected behavior

I would expect that `StripeClient.customer.create` to accept a variable type of `Stripe.Customer` as parameter

### OS

Any

### Node version

Node V14.18.2

### Library version

8.215.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@phlcastro The Create Customer [API](https://stripe.com/docs/api/customers/create) is used to create a brand new customer with specific parameters like `email` or `phone`. There is no reason that this method should take an already existing customer as a parameter, with or without `id` in this case really. The [Customer object](https://stripe.com/docs/api/customers/object) has properties that can't be passed as parameters (like `livemode` or `created`) so it wouldn't really make sense overall and that's definitely not how any of our Create APIs are designed.

Can you let me know if that makes sense to you? If not, could you give a clear example of what code you would like to run that would require having a `Customer` instance in this situation as the parameter?

**Comment by phlcastro** [comment]
hi @remi-stripe ! thanks for you quickly response!

> There is no reason that this method should take an already existing customer as a parameter, with or without id in this case 

if the `Customer` interface intention is exclusively to be used for existing customers, that does makes sense. :+1: 

to me, the Customer entity representation would be the same independent if it already exists or not (except for the `id` obviously)

as you can see bellow, the discrepancies between `CustomerCreateParams` and `Customer` are all optional attributes or attributes that can have `null` values (except for `livemode`)

IMO this makes sense, since they should look pretty much the same independent if the Customer object exists or not.

cheers!

```
interface CustomerCreateParams {
  address?: Stripe.Emptyable<Stripe.AddressParam>;
  balance?: number;
  coupon?: string;
  description?: string;
  email?: string;
  expand?: Array<string>;
  invoice_prefix?: string;
  invoice_settings?: CustomerCreateParams.InvoiceSettings;
  metadata?: Stripe.Emptyable<Stripe.MetadataParam>;
  name?: string;
  next_invoice_sequence?: number;
  payment_method?: string;
  phone?: string;
  preferred_locales?: Array<string>;
  promotion_code?: string;
  shipping?: Stripe.Emptyable<CustomerCreateParams.Shipping>;
  source?: string;
  tax?: CustomerCreateParams.Tax;
  tax_exempt?: Stripe.Emptyable<CustomerCreateParams.TaxExempt>;
  tax_id_data?: Array<CustomerCreateParams.TaxIdDatum>;
  test_clock?: string;
}

interface Customer {
  id: string;
  object: 'customer';
  address: Stripe.Address | null;
  balance: number;
  created: number;
  currency: string | null;
  default_source: string | Stripe.CustomerSource | null;
  deleted?: void;
  delinquent: boolean | null;
  description: string | null;
  discount: Stripe.Discount | null;
  email: string | null;
  invoice_prefix: string | null;
  invoice_settings: Customer.InvoiceSettings;
  livemode: boolean;
  metadata: Stripe.Metadata;
  name: string | null;
  next_invoice_sequence?: number;
  phone: string | null;
  preferred_locales: Array<string> | null;
  shipping: Customer.Shipping | null;
  sources?: ApiList<Stripe.CustomerSource>;
  subscriptions?: ApiList<Stripe.Subscription>;
  tax?: Customer.Tax;
  tax_exempt?: Customer.TaxExempt | null;
  tax_ids?: ApiList<Stripe.TaxId>;
  test_clock?: string | Stripe.TestHelpers.TestClock | null;
}

livemode: boolean;

currency: string | null;
default_source: string | Stripe.CustomerSource | null;
deleted?: void;
discount: Stripe.Discount | null;
sources?: ApiList<Stripe.CustomerSource>;
subscriptions?: ApiList<Stripe.Subscription>; 
```

**Comment by phlcastro** [comment]
Closing it as I understood this was an intentional decision :+1:

**Comment by remi-stripe** [comment]
Thanks for clarifying! I can see how you'd imagine `Customer` could be for both, but for many resources the set of accepted parameters is wildly different from the set of properties that the resource can have!
