### ISSUE TITLE
Yarn outdated suddenly jumped our wanted package version from 7.63.1 > 10.8.0

### ISSUE THREAD

**Issue by nypinstripes** [stripe/stripe-node#1550]
### Describe the bug

We check our apps for outdated packages EVERY SINGLE DAY, and have done so for the past 4 years. Which is why we were shocked when last week we VERY SUDDENLY saw our version updates list contain an entry for stripe that was almost 3 years of (breaking) updates behind the current release. 

We have a heavy reliance on this library, and before I task my team with rummaging through the changelog for 3 years and breaking things in our app I would like to know why this happened, and if this is correct.

Also why is our library package called stripe and not stripe-node.

### To Reproduce

run `yarn outdated`

### Expected behavior

incremental updates should have been appearing here for the past 2 and half years.

### Code snippets

```JavaScript
Package             Current  Wanted   Latest       Package Type    URL
stripe              7.63.1   7.63.1   10.8.0       dependencies    https://github.com/stripe/stripe-node
```

### OS

macOS

### Node version

Node v18.0.0

### Library version

stripe 7.63.1

### API version

now I have no idea

**Comment by kamil-stripe** [comment]
We are sorry this has happened to you. This seems like an issue with yarn itself as we don't do anything special in our release pipeline. The command has skipped three major updates which is quite concerning. Please create a bug for the yarn project to learn more.

The NPM package is called "stripe" but the repository is called "stripe-node" to distinguish between different languages that publish packages called "stripe" (e.g. "stripe-python" is published as "stripe" to PyPi).

To successfully upgrade the library, please refer to our migration guides available in the [Wiki](https://github.com/stripe/stripe-node/wiki) (e.g. https://github.com/stripe/stripe-node/wiki/Migration-guide-for-v10) and feel free to reach out in case you have more questions.
