### ISSUE TITLE
Stripe account creating is taking long time nodejs

### ISSUE THREAD

**Issue by ashutoshbitcanny** [stripe/stripe-node#1555]
### Describe the bug

1. Stripe account creating is taking time (More than 10s)

 const account = await stripe.accounts.create({
    type: "standard",
    email: "abc@example.com",
  });
  res.send(account);

### To Reproduce

Just try to create stripe connect account similar to code below:

 const account = await stripe.accounts.create({
    type: "standard",
    email: "abc@example.com",
  });
  res.send(account);

### Expected behavior

it should not take such long time.

### Code snippets

```JavaScript
const account = await stripe.accounts.create({
    type: "standard",
    email: "abc@example.com",
  });
  res.send(account);
```

### OS

macOs

### Node version

Node v16.15.1

### Library version

 "stripe": "^10.5.0",

### API version

 "stripe": "^10.5.0",

**Comment by kamil-stripe** [comment]
Hi @ashutoshbitcanny! stripe-node issues should be limited to issues with the libraries itself which isn't really the case here. Our support team is better equipped to answer questions like this. Please contact them at  https://support.stripe.com/contact.

Regarding the sample code you have provided, `stripe.accounts.create` will create account by itself. There is no need to send the result again, which actually makes your integration slower.
