### ISSUE TITLE
Stripe Config Change Optional Arg 

### ISSUE THREAD

**Issue by TeaRog** [stripe/stripe-node#1573]
I see that there are some members of the Stripe object that have become deprecated by the config object. Shouldn't the config arg be marked as optional until they are fully deprecated?
![Screenshot from 2022-10-06 12-12-06](https://user-images.githubusercontent.com/51102056/194399189-0d5833c3-041a-4f37-a2a5-7cf9941f8aa3.png)
Should become,
![Screenshot from 2022-10-06 12-12-19](https://user-images.githubusercontent.com/51102056/194399873-74ac8018-b51a-48e4-a8f3-64ecf8dda354.png)
So that this doesn't happen,
![Screenshot from 2022-10-06 11-59-40](https://user-images.githubusercontent.com/51102056/194400039-07601bc4-b5d3-4418-a0da-9e52901ca2ba.png)

### To Reproduce

1. fetch types/2022-08-01/index.s.ts
2. look at line 137 constructor(apiKey: string, config: Stripe.StripeConfig);

### Expected behavior

We should be able to say,
![Screenshot from 2022-10-06 12-22-23](https://user-images.githubusercontent.com/51102056/194400811-ff46adac-d481-40f0-9e91-7631846a1817.png)
until the members that the config object are replacing become fully deprecated.

### OS

Ubuntu 22.04

### Node version

16.14.2

### Library version

10.13.0

### API version

2022-08-01

### Additional context
Using Svelte and TypeScript with https://www.sveltestripe.com/#creating-a-payment-intent
I'd open a PR but I don't understand how types/2022-08-01/index.s.ts gets auto generated.

**Comment by kamil-stripe** [comment]
Thank you for your report. I have adjusted the generator to make the parameter optional. If you want to make a PR in this repository, feel free to do so and the change won't be overridden by our tooling. If you don't feel like creating a PR, that change is going to be included in the next release.

**Comment by anniel-stripe** [comment]
Hi! Sorry for the delayed follow-up here, but closing this issue since those setter methods were removed in [v11.0.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#1100---2022-11-16), and the config object will remain required.
