### ISSUE TITLE
Add JSDoc @deprecated instead of [deprecated]

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#1576]
### Is your feature request related to a problem? Please describe.

I noticed the comments on API fields prefix `[deprecated]`, for example:

https://github.com/stripe/stripe-node/blob/db94c299ce2fa1eeaad8123830ee3108153d5a6c/types/2022-08-01/Checkout/Sessions.d.ts#L1727

This makes it hard to miss when looking in VScode at what's deprecated

### Describe the solution you'd like

If you add `@deprecated` to the jsdoc comment:

```
/**
  * @deprecated
  * [Deprecated] Some description 
  */
```

Then the property will show a strike-through in the editor which should make it more obvious to developers when using deprecated properties/methods.

**Before**

<img width="407" alt="image" src="https://user-images.githubusercontent.com/7410770/194711682-8d5d8304-fed3-49e3-a9e6-0f12bd6bac6d.png">

**After**

<img width="875" alt="image" src="https://user-images.githubusercontent.com/7410770/194711673-da15d3f6-d346-4b29-8be1-63648a637359.png">

It also makes it easier when referencing properties (for example, I added `@deprecated` in the definitions):

<img width="287" alt="image" src="https://user-images.githubusercontent.com/7410770/194711771-2134b619-3387-4e91-a05d-0de60ad3e7d7.png">

**Comment by davidbielik** [comment]
looks like there are already `/** @deprecated */` fields, and maybe just a few are missing

**Comment by richardm-stripe** [comment]
Hi @davidbielik, I agree with you though I suspect we will take no action here. The only docstrings with `[Deprecated]` are the ones that you have already noted in #1575 should be removed from the library, so likely that is how we will resolve this.
