### ISSUE TITLE
app.js:86599 [Vue warn]: Error in mounted hook: "Error: Cannot find module 'crypto'"

### ISSUE THREAD

**Issue by edenramoneda** [stripe/stripe-node#1577]
### Describe the bug

When I tried to initialize the stripe library it returns "Cannot find module 'crypto'
I tried to install crypto library but the error still appeared. 

This is my code for initialization.
```
  const stripe = require('stripe')('sk_test_...');

    console.log(stripe)
```

### To Reproduce

1. Run the command `npm install stripe --save `
2. Add require('stripe') in app.js this is immediately reproduce an error.

### Expected behavior

There's should no error appeared.. 

### OS

windows

### Node version

Node v16.0.0

### Library version

"stripe": "^10.13.0",

### API version

2022-08-01

**Comment by remi-stripe** [comment]
@edenramoneda Can you give a bit more context about what you are trying to do? Your title mentioned an error with Vue which is usually a client-side library. stripe-node is a server-side library for your server-side code. It can not work client-side in a browser. If so you are likely looking for Stripe.js instead: https://stripe.com/docs/js

**Comment by bh0mbalziyad** [comment]
> @edenramoneda Can you give a bit more context about what you are trying to do? Your title mentioned an error with Vue which is usually a client-side library. stripe-node is a server-side library for your server-side code. It can not work client-side in a browser. If so you are likely looking for Stripe.js instead: https://stripe.com/docs/js

Yeah this is most likely caused by trying to use this in a browser/client side app.
