### ISSUE TITLE
Subscription Custom Invoice Field missing on the API

### ISSUE THREAD

**Issue by ozgur-dogan** [stripe/stripe-node#1586]
### Describe the bug

I can add/edit custom invoice fields of a subscription on the dashboard (on create and on update). 
But this is not exist on the Stripe.js library.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/6137523/196438126-ac48ec9f-77dc-4e2d-a554-21fc800a51fb.png">

When I do that on the dashboard, I can see the API request on the logs, so I know it exists on the API. 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/6137523/196437948-95e92847-92c0-495b-a806-e0634afe52d5.png">

This should be fixed on the Stripe.js library because we are unable to do the same thing programatically and we are unable to show custom information on the invoices created as a result of subscription.

### To Reproduce

Go the a customer on the dashboard , press Actions button on top and select Create Subscption.

### Expected behavior

The option that exists on the Dashboard should be on the Stripe.js

### OS

Web

### Node version

Node 16

### Library version

stripe-node v 10.14.0

### API version

2022-08-01

**Comment by born3am** [comment]
Hi There @ozgur-dogan, regarding this issue, were you able to find a workaround? Based on the changelog description of #1995 I thought they would fix that, but no....

**Comment by remi-stripe** [comment]
@born3am We haven't shipped support for it yet. Please work with our support team for help if you want to also register your interest for this feature. For now this is still not available on the Subscription API.
