### ISSUE TITLE
Include an option when retrieving an invoice to retrieve the latest revision

### ISSUE THREAD

**Issue by ryan-saffer** [stripe/stripe-node#1613]
### Is your feature request related to a problem? Please describe.

Recently stripe updated the invoice object to include a `latest_revision` field.
When retrieving an invoice, it would be nice to provide an option to the sdk to retrieve this latest revision.

Without this, the consumer must check the result for `latest_revision`, and if included, make a second call to the api. This could be reduced to a single call.

### Describe the solution you'd like

Add an additional parameter such as `retrieveLatest` to the `InvoiceRetrieveParams` interface:
```typescript
interface InvoiceRetrieveParams {
    /**
     * Specifies which fields in the response should be expanded.
     */
    expand?: Array<string>;

    /**
     * If set to true, will return the latest revision.
     */
    retrieveLatest?: boolean;
}
```

And using it will look like:
```typescript
const invoice = await stripe.invoices.retrieve(invoiceId, {
    retrieveLatest: true
});
```

### Describe alternatives you've considered

IMHO this should be the default behaviour, and if the user specifically wants this invoice (and not the latest revision), they should provide `false` to this param - however could see this breaking backwards compat.

At this point there doesn't seem to be any way to handle this except checking for `latest_revision` inside the consumer, and rerunning the `retrieve()` method on the sdk.

### Additional context

N/A

**Comment by pakrym-stripe** [comment]
Hi, @ryan-saffer,

`Invoice.latest_revision` is an expandable field. This means that by passing its name in the `expand` parameter you'll tell the service to return a full object instead of just an id.

``` node
const invoice = await stripe.invoices.retrieve(invoiceId, {
    expand: ["latest_revision"]
});
```

**Comment by ryan-saffer** [comment]
hi @pakrym-stripe ,

thanks for looking into this.

while this makes it possible to retrieve all the info needed in a single API request, it still requires a check client side on every invoice retrieval:
```typescript
if(invoice.latest_revision) {
  // use latest_revision
} else {
  // use original
}
```
if supplying `retrieveLatest` as a parameter as proposed, the SDK should handle this and simply return the latest revision.

**Comment by pakrym-stripe** [comment]
@ryan-saffer, this definitely can be a good improvement to the Invoices product in the future. 
Adding the parameter to REST API (as opposed to a particular SDK) will make it available across all languages. I'll share the request with the product team internally.


I also encourage you to raise this feedback with our support team so that they can track it: https://support.stripe.com/contact
