### ISSUE TITLE
Version Number inconsistencies

### ISSUE THREAD

**Issue by matthewarkin** [stripe/stripe-node#163]
NPM lists a version 3.3.2, that version doesn't exist in Github :( 
The current VERSION file lists version 3.3.0, but the Github releases lists an additional 3.3.1 version. 

Can we keep the Github releases and NPM releases in line?

**Comment by kyleconroy** [comment]
Yep, we'll be releasing 3.3.3 today, which will be on GitHub and NPM. We're also updating some tooling to make sure these inconsistencies don't happen again.

**Comment by mmcgrana** [comment]
@kyleconroy are we all set here now? We do at least have the most recent GitHub and NPM versions matching, and some better tooling now I believe. 

We never did cut a 3.3.2 in GitHub, but I'm not sure it's worth going back for that at this point?

Thanks @matthewarkin for flagging this!

**Comment by kyleconroy** [comment]
While this inconsistencies still exist, we should be fine now as the most recent Node versions are all correct. The tooling I mentioned has been in place for months and this hasn't happened since.
