### ISSUE TITLE
Checkout session broken UI

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [stripe/stripe-node#1641]
### Describe the bug

First of all, sorry if this isn't the correct place to post this sort of bug. I wasn't able to figure out the correct place to post it.

After we open the checkout session's page and either click on details or maximize the window, the detailed information of the items being purchased get broken.
<img width="599" alt="image" src="https://user-images.githubusercontent.com/12696894/208781329-a64889cd-d499-4727-9acf-48950bc54bcc.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/12696894/208781362-d2d15a47-a40d-4968-bf61-384f1a2e8465.png">

It happens in both the test and live modes.

### To Reproduce

1. Create a checkout session.
2. Open the checkout session link.
3. If the width of the window is small, click on "Details".

### Expected behavior

The prices displayed should be vertically aligned.

### OS

macOS and Windows (Google Chrome and Safari)

### Node version

Node 16

### Library version

stripe-node v8.193.0

### API version

2020-08-27

**Comment by richardm-stripe** [comment]
Hello @rodrigoborgesdeoliveira, thank you for the report. This project is for issues with Stripe's open source node.js SDK. For UI issues, you should contact Stripe Support at https://support.stripe.com/contact/ and they can help you/file the bug report to the appropriate team on your behalf.

**Comment by rodrigoborgesdeoliveira** [comment]
Thank you, @richardm-stripe.
