### ISSUE TITLE
Stripe checkout session with auto tax calculation doesn't show Google Pay or Apple Pay when billing address collection is auto

### ISSUE THREAD

**Issue by sheldoncoates** [stripe/stripe-node#1659]
### Describe the bug

Not sure if this fully qualifies as a bug, but I'm looking for answers as to why this is the way it is.

When creating a Node js Stripe checkout session using automatic tax calculation, Google Pay and Apple Pay options aren't available when setting `billing_address_collection: 'auto'`. However, those wallet options are available if I set:

```
 shipping_address_collection: {
     allowed_countries: ['US'],
 },
```
Here is my entire create checkout configuration:
```
{
     mode: 'subscription',
     line_items: [
         {
              price: 'price_key',
              quantity: 1,
          },
      ],
      billing_address_collection: 'auto', // does not work
      // shipping_address_collection: { // works
      //     allowed_countries: ['US'],
      // },
      automatic_tax: {
          enabled: true,
      },
      allow_promotion_codes: true,
      success_url: `success_url`,
      cancel_url: 'cancel_url',
      customer: 'stripe_customer_id';
      customer_update: {
          address: 'auto', // does not work
          // shipping: 'auto', // works
       };
}
```

### To Reproduce

Create a stripe checkout sessions using the following config options:
```
{
     mode: 'subscription',
     line_items: [
         {
              price: 'price_key',
              quantity: 1,
          },
      ],
      billing_address_collection: 'auto', // does not work
      // shipping_address_collection: { // works
      //     allowed_countries: ['US'],
      // },
      automatic_tax: {
          enabled: true,
      },
      allow_promotion_codes: true,
      success_url: `success_url`,
      cancel_url: 'cancel_url',
      customer: 'stripe_customer_id';
      customer_update: {
          address: 'auto', // does not work
          // shipping: 'auto', // works
       };
}
```

See only pay by card available and no wallet options

### Expected behavior

To be able to use wallet options when collecting billing address only ie: `billing_address_collection: 'auto'`

### OS

macOS

### Node version

Node v16.18.0

### Library version

stripe v10.2.0

### API version

2020-03-02

**Comment by remi-stripe** [comment]
@sheldoncoates Github issues should be limited to bugs with the stripe-node library itself. This is an integration question better directed to our support team: https://support.stripe.com/contact

To unblock you, Apple Pay and Google Pay only appear with shipping address being collected if you have automatic tax enabled so this behaviour is expected. We're working on improving this but for now it's the way it works
