### ISSUE TITLE
conflict Stripe vs Loopback

### ISSUE THREAD

**Issue by nvcken** [stripe/stripe-node#167]
Loopback https://github.com/strongloop/loopback
When I call Stripe charge, I can not get userInfo by loopback.getCurrentContext() in Stripe charge callback
```
console.log(currentContext.get('userInfo'));  <<<    // before stripe charge , it works
stripe.charges.create({
            amount: total_price, //convert to Cents
            currency: cur,
            source: token, 
            description: ""
          }, function(err, charge) {
              console.log(currentContext.get('userInfo'));  <<<    // Got undefined       
          });
```
Important : also MyModel.findById(id, function(err, found){console.log(found);   <<<<< // return null})
If I remove stripe.charges code, everything of loopback work fine

**Comment by kyleconroy** [comment]
Hmm, I'm not very familiar with `lookback`, but I'm not sure what we would be doing that would break that. As far as I can tell, we aren't doing anything crazy here.
