### ISSUE TITLE
Can't remove CA cardholder spending limit when after has been set [TEST MODE] - Stripe Issuing

### ISSUE THREAD

**Issue by Chipzstar** [stripe/stripe-node#1678]
### Describe the bug

Passing an empty array for spending_controls.spending_limits for cardholder update function doesn't remove the spending limit for the cardholder. 

### To Reproduce

1. Create a CA account in test environment with card issuing enabled and activated
2. Create a cardholder under the CA account with a single spending limit
3. Use stripe node sdk to update that same cardholder with no spending limit i.e. provide an empty array 

### Expected behavior

Expected the cardholder  spending limit to be removed and no longer show, both in the dashboard and in the API response  when fetching the updated cardholder through the API.

### Code snippets

```JavaScript
const cardholder = await stripe.issuing.cardholders.update(
      input.cardholder_id,
      {
	      email: input.email,
	      individual: {
		      first_name: input.firstname,
		      last_name: input.lastname
	      },
	      phone_number: input.phone,
	      status: 'active',
	      billing: {
		      address: {
			      line1: input.address.line1,
			      ...(input.address.line2 && { line2: input.address.line2 }),
			      city: input.address.city,
			      state: input.address.region,
			      postal_code: input.address.postcode,
			      country: input.address.country
		      }
	      },
	      spending_controls: {
		      spending_limits: []
	      }
      }, { stripeAccount: input.stripeId }
      );
```

### OS

Windows

### Node version

Node version 16 

### Library version

stripe-node v11.9.1

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@Chipzstar This is a bit of a quirk of our API and client-libraries. To "unset" a value (scalar or hash) you have to pass an empty string explicitly in your code. Your code should look like this:

```
const cardholder = await stripe.issuing.cardholders.update(
	input.cardholder_id,
	{
		// ... other params
		spending_controls: {
			spending_limits: '',
		},
	},
	{
		stripeAccount: input.stripeId,
	}
);
```

**Comment by Chipzstar** [comment]
Thanks @remi-stripe. That solution works
