### ISSUE TITLE
BUG: Terminal Display Cart failing silently if values are floats

### ISSUE THREAD

**Issue by hrueger** [stripe/stripe-node#1692]
### Describe the bug

Hi Stripe Team,
first, thanks for this excellent library. The dev experience is great!

I've struggled to find a bug which causes the Display of the BBPOS WisePOS E to not show. It happens when providing float values for either tax or `amount` in `line_items` in the `setReaderDisplay` method of the `terminal` object.

I know that you're not supposed to send float values, however, I'd expect an error here and not just silently fail. All the requests in the dev tools also succeed, however, the just terminal shows the default background image.

### To Reproduce

1. Use the JS SDK to connect to a terminal
2. Use `setReaderDisplay` with a float value for `tax` or `line_items[0].amount`

### Expected behavior

Throw an error that float values are not supported. This would really help with debugging.

### Code snippets

```JavaScript
const display  = {
    type: "cart",
    cart: {
        currency: "eur",
        tax: 65.00000001,
        total: 500,
        line_items: [{
            description: "Test",
            amount: 500,
            quantity: 1,
        }],
    },
};
console.log(display);
await terminal.setReaderDisplay(display)
```

### OS

Windows

### Node version

v16.17.1

### Library version

stripe-node v11.11.0; @stripe/terminal-js v0.11.2

### API version

2022-11-15

**Comment by hrueger** [comment]
Oh, I just noticed that there's another repo for the terminal SDK, however, that's just the loader I believe. Maybe this issue needs to be transferred to the appropriate repository.

**Comment by pakrym-stripe** [comment]
Hi @hrueger,

Github issues should be limited to bugs with the library itself. This is an integration question better directed to our support team: https://support.stripe.com/contact

I'll transfer the issue to terminal-js repository.
