### ISSUE TITLE
YOU DID NOT PROVIDE AN API KEY. YOU NEED TO PROVIDE YOUR API KEY IN THE AUTHORIZATION HEADER, USING BEARER AUTH (E.G. 'AUTHORIZATION: BEARER YOUR_SECRET_KEY'). SEE HTTPS://STRIPE.COM/DOCS/API#AUTHENTICATION FOR DETAILS, OR WE CAN HELP AT HTTPS://SUPPORT.STRIPE.COM/.

### ISSUE THREAD

**Issue by Rahul831996** [stripe/stripe-node#1694]
### Describe the bug

i got this error  ->
 YOU DID NOT PROVIDE AN API KEY. YOU NEED TO PROVIDE YOUR API KEY IN THE AUTHORIZATION HEADER, USING BEARER AUTH (E.G. 'AUTHORIZATION: BEARER YOUR_SECRET_KEY'). SEE HTTPS://STRIPE.COM/DOCS/API#AUTHENTICATION FOR DETAILS, OR WE CAN HELP AT HTTPS://SUPPORT.STRIPE.COM/.

i have setup every things perfectly but i don't why this happening

### To Reproduce

.

### Expected behavior

bad

### Code snippets

```JavaScript
const  catchAsyncError = require("../middleware/catchAsyncError");
require("dotenv").config()

const Stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);
 

exports.processPayment = catchAsyncError(async (req, res, next) => {
    const myPayment = await Stripe.paymentIntents.create({
        amount:req.body.amount,
        currency:"inr",
        metadata: {
            company: "FoodiWE",
        },
       

    })

    res.status(200).json({
        success:true,
        client_secret: myPayment.client_secret,

    })
})

exports.sendStripeApiKey = catchAsyncError(async(req, res, next) => {
    res.status(200).json({
         stripeApiKey: process.env.STRIPE_API_KEY,
        })
})
```

### OS

windows

### Node version

v16.6

### Library version

v8.24

### API version

25/2/23

### Additional context

please write any solution

**Comment by pakrym-stripe** [comment]
Hi @hrueger,
Hi @Rahul831996 ,

Github issues should be limited to bugs with the library itself. This is an integration question better directed to our support team: https://support.stripe.com/contact
