### ISSUE TITLE
stripe.checkout.sessions.list parameter type hint does not match the documentation

### ISSUE THREAD

**Issue by Jman1080** [stripe/stripe-node#1700]
### Describe the bug

As shown in the screenshot:

The is no suggestion for `payment_link` nor does it accept it as a parameter(unless TS-ignored) however payment_link is a valid parameter (As per the docs: https://stripe.com/docs/api/checkout/sessions/list?lang=node)

![image](https://user-images.githubusercontent.com/17319743/222930908-d54049da-acea-4897-ae70-4d9f92a2a9b1.png)

![image](https://user-images.githubusercontent.com/17319743/222931034-b110d8b2-8c24-43b5-9cd2-0158f171a2e2.png)

### To Reproduce

create an API call using typescript: 
```const sessions = await stripe.checkout.sessions.list({
  limit: 3,
  payment_link
});```

after that, your ts-lint should complain that it is not a valid parameter.

### Expected behavior

payment link should be suggested and accepted as a valid parameter.

### Code snippets

_No response_

### OS

13.2.1

### Node version

16.17.0

### Library version

"stripe": "^11.13.0"

### API version

2022-11-15

### Additional context

_No response_

**Comment by remi-stripe** [comment]
Hey @Jman1080! This parameter was added recently and release in the version 11.9.0 of stripe-node ([changelog](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#1190---2023-02-02)). You likely have an older version and need to upgrade!
