### ISSUE TITLE
Better error msg

### ISSUE THREAD

**Issue by cobookman** [stripe/stripe-node#171]
Instead of the following error message: `Your card was declined. Your request was in test mode, but used a non test card. For a list of valid test cards, visit: https://stripe.com/docs/testing.`

This would have been better:
`Your card was declined. Your request was in test mode, but used a non test card. For a list of valid test cards, visit: https://stripe.com/docs/testing#cards`

**Comment by matthewarkin** [comment]
Hey @cobookman, since this error originates at the API level and not the library level, a better spot to report this would be support@stripe.com :)

**Comment by cobookman** [comment]
@matthewarkin thnx
