### ISSUE TITLE
Changelog v.3.3.4

### ISSUE THREAD

**Issue by claudiopetrini** [stripe/stripe-node#172]
I just noticed that v3.3.4 has this changelog:
```
3.3.4 Apr 2nd, 2015
- DESCRIBE CHANGES HERE (try to use the same style, tense, etc. as the other entries) 
``` 
Can you please update it?

**Comment by kyleconroy** [comment]
Fixed in 7697376df444a32531b1e39d551bcd442e193fdc, thanks for catching
