### ISSUE TITLE
Testing native purchase button using cypress

### ISSUE THREAD

**Issue by yatharthvij** [stripe/stripe-node#1725]
### Is your feature request related to a problem? Please describe.

I've been trying to test the native purchase button for a while now and there is no solution found through cypress. The problem we're facing is the button is in an iframe, with no anchor tags and it opens in a new window/tab. Any alternate solutions from your end would be really helpful.

### Describe the solution you'd like

Keeping the Native purchase button ("Pay with Link") within an anchor tag so that we could potentially give the target as self and work with it. 

### Describe alternatives you've considered

Another solution could be removing the iframe completely and directly working with it. That could make testing easier.

**Comment by remi-stripe** [comment]
@yatharthvij This repo is for stripe-node, which is for the server-side part of your code. This is not the library you use client-side to collect card details or show a purchase button. We don't really have guidance on how to test our UI flows, we usually recommend mocking them out entirely instead.

Please work with our support team instead as your ask is unrelated to stripe-node: https://support.stripe.com/contact
