### ISSUE TITLE
Stripe Checkout setup mode with Alipay - type error

### ISSUE THREAD

**Issue by BioCarmen** [stripe/stripe-node#1736]
### Describe the bug

when pass in alipay into Stripe Checkout as one of the payment_method_types in setup mode, it is expected payment_method_options[alipay][currency]
However, currency is not part of the Alipay PaymentMethodOptions.
```
stripe.checkout.sessions.create({
            payment_method_types: ['card', 'alipay'],
            payment_method_options: {
                alipay: {
                    currency: 'usd',
                },
            },
            mode: 'setup'}
})
```
![Screenshot 2023-03-28 at 3 51 27 PM](https://user-images.githubusercontent.com/60475155/228351481-973aa7f1-9c5e-4639-9543-ee8145299e93.png)

### To Reproduce

```
stripe.checkout.sessions.create({
            payment_method_types: ['card', 'alipay'],
            payment_method_options: {
                alipay: {
                    currency: 'usd',
                },
            },
            mode: 'setup',
            customer: customer,
            expires_at: Math.floor(new Date().getTime() / 1000) + 60 * 60 * 2,
            setup_intent_data: {
                metadata: {
                    customer_id: "customerid",
                    subscription_id: id,
                },
            },
            success_url: `/`,
            cancel_url: `/`,
        });
```
Type error 

### Expected behavior

No type error

### Code snippets

```JavaScript
stripe.checkout.sessions.create({
            payment_method_types: ['card', 'alipay'],
            payment_method_options: {
                alipay: {
                    currency: 'usd',
                },
            },
            mode: 'setup',
            customer: customer,
            expires_at: Math.floor(new Date().getTime() / 1000) + 60 * 60 * 2,
            setup_intent_data: {
                metadata: {
                    customer_id: "customerid",
                    subscription_id: id,
                },
            },
            success_url: `/`,
            cancel_url: `/`,
        });
```

### OS

macOS

### Node version

Node 16.18.1

### Library version

11.5.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@BioCarmen Alipay support in `setup` mode on Checkout is not a public feature right now and is instead in private beta. Your account likely has access to that secret feature, but client libraries like stripe-node don't have types for secret features so this is expected.

We don't discuss betas here so I would recommend that you reach out to our support team if you have follow up questions: https://support.stripe.com/contact
