### ISSUE TITLE
Unhandled rejection Error: Invalid array

### ISSUE THREAD

**Issue by joergd** [stripe/stripe-node#174]
I am trying to include the total_count in a charges.list call, but I get back the following error from the server: Unhandled rejection Error: Invalid array

I call it like so:

    stripe.charges.list({include: ['total_count'] }, cb)

Is this parameter not implemented on the API for charges?

**Comment by kyleconroy** [comment]
I'm unable to reproduce this. I've confirmed that calling `list` with `include` works on charges using the latest version of stripe-node. Can you upgrade to the latest version and try again?

```js
stripe.charges.list(
  {
    limit: 3,
    include: ['total_count']
  },
  function(err, charges) {
    console.log(err);
    console.log(charges);
  }
);
```
