### ISSUE TITLE
Unable to access customer timezone

### ISSUE THREAD

**Issue by vachi** [stripe/stripe-node#1741]
### Describe the bug

I get back an error `parameter_unknown - timezone` when making a POST request to customers with the body of 
` {"timezone": "Europe/Berlin" }`.

The same request for the dashboard UI using the dashboard.stripe.com endpoint vs the api.stripe.com endpoint which the stripe-node and all other libs use.

![Screen Shot 2023-04-04 at 6 03 08 PM](https://user-images.githubusercontent.com/1779636/229819975-728f8a06-571d-47af-aaca-6d98c9aafb17.png)

### To Reproduce

the Stipe lib code used is 
```
await stripe.customers .update(id, {timezone: "Europe/Berlin", })
```

Of course you can update metadata.timezone
```
curl --request POST \
  --url https://api.stripe.com/v1/customers/cus_NZZbCf9NT5uSbO \
  --header "Authorization: Bearer " \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --data "metadata[timezone]=Europe/Berlin"
```

But you cant update

```
curl --request POST \
  --url https://api.stripe.com/v1/customers/cus_NZZbCf9NT5uSbO \
  --header "Authorization: Bearer " \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --data 'timezone=Europe/Berlin'
```

### Expected behavior

I expect this parameter to be available to the api.stripe.com users. 

### OS

macOs

### Node version

Node v16

### Library version

"stripe": "^11.17.0"

### API version

2022-11-15 and  2022-08-01

**Comment by remi-stripe** [comment]
@vachi This feature is only accessible for the Dashboard and doesn't exist in the API today. Please reach out to our support team instead to raise your interest for this feature to be in the API in the future. You can contact them here: https://support.stripe.com/contact
