### ISSUE TITLE
`stripe.checkout.sessions.listLineItems` is not defined

### ISSUE THREAD

**Issue by brianfeister** [stripe/stripe-node#1748]
### Describe the bug

I want to be clear that I'm a maintainer of multiple open source projects, so I don't like opening issues about this sort of thing, but I've found zero documentation and can't explain what's going on here. 

In the Stripe API Docs there is reference to `stripe.checkout.sessions.listLineItems` here https://stripe.com/docs/api/checkout/sessions/line_items

And looking at the source code in this repo, I see what should be a matching method here https://github.com/stripe/stripe-node/blob/master/src/resources/Checkout/Sessions.ts#L28

But when I call this method after successfully instantiating an API client in my AWS Lambda function, I'm getting the following error.

```
stripe.checkout.sessions.listLineItems is not defined
```

Is this a deficiency in the Stripe API docs? Can I help by updating the docs? Has the method been moved somewhere else?

### To Reproduce

1. instantiate stripe-node, I'm doing this via
```
const stripe = require('stripe')(process.env.GATSBY_STRIPE_SECRET_KEY, {
  apiVersion: '2022-11-15',
  maxNetworkRetries: 2,
});
```
2. call the `stripe.checkout.sessions.listLineItems` method, I'm doing exactly this
```
sessionLineItems = await stripe.checkout.sessions.listLineItems(
          stripeEvent.data.object.id,
          { limit: 1 },
          (err, lineItems) => {
            if (err) {
              return reject(err);
            }
            resolve(lineItems);
          }
        );
```
Note that I realize this method might not return a promise, and so I have also tried the following, with the same result
```
sessionLineItems = await new Promise((resolve, reject) => {
          stripe.checkout.sessions.listLineItems(
            stripeEvent.data.object.id,
            { limit: 1 },
            (err, lineItems) => {
              if (err) {
                return reject(err);
              }
              resolve(lineItems);
            }
          );
        });
```
3. Observe the error `TypeError: stripe.checkout.sessions.listLineItems is not a function` in your runtime environment

### Expected behavior

The function is calle

### OS

macOS

### Node version

Node v16.14.2

### Library version

stripe-node v11.17.0

### API version

22-11-15

**Comment by richardm-stripe** [comment]
Hi @brianfeister, so far I am unable to reproduce. Can you log some values to try and narrow down what's wrong/missing?

```javascript
const stripe = ...
console.log(typeof stripe);
console.log(stripe.VERSION);
console.log(typeof stripe.checkout)
console.log(Object.keys(stripe.checkout))
console.log(typeof stripe.checkout.sessions)
console.log(typeof stripe.checkout.sessions.listLineItems)
console.log(stripe.checkout.sessions.__proto__)
```

When I run this, I see
```
> console.log(typeof stripe);
object
> console.log(stripe.VERSION);
11.17.0
> console.log(typeof stripe.checkout)
object
> console.log(Object.keys(stripe.checkout))
[ 'sessions' ]
> console.log(typeof stripe.checkout.sessions)
object
> console.log(typeof stripe.checkout.sessions.listLineItems)
function
> console.log(stripe.checkout.sessions.__proto__)
{
  create: [Function (anonymous)],
  retrieve: [Function (anonymous)],
  list: [Function (anonymous)],
  expire: [Function (anonymous)],
  listLineItems: [Function (anonymous)]
}
```

**Comment by brianfeister** [comment]
@richardm-stripe here's what I see

```
console.log(typeof stripe)
 object
console.log(stripe.VERSION)
 undefined
console.log(typeof stripe.checkout)
 object
console.log(Object.keys(stripe.checkout))
 [ 'sessions' ]
console.log(typeof stripe.checkout.sessions)
 object
console.log(typeof stripe.checkout.sessions.listLineItems)
 undefined
console.log(stripe.checkout.sessions.__proto__)
 { path: 'checkout/sessions', includeBasic: [ 'create', 'retrieve' ] }
```

... any idea why my stripe version is `undefined`? My node (aws lambda in netlify) looks like this

```
const stripe = require('stripe')(process.env.GATSBY_STRIPE_SECRET_KEY, {
  apiVersion: '2022-11-15',
  maxNetworkRetries: 2,
});
```

**Comment by brianfeister** [comment]
And my `package.json`

```
{
  "name": "functions",
  "version": "0.0.1",
  "main": "index.js",
  "author": "Brian Feister <brian.feister@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "@sendgrid/mail": "^7.0.0",
    "node-fetch": "^2.6.9",
    "stripe": "^11.17.0"
  }
}
```

**Comment by richardm-stripe** [comment]
The signs point to an old version of stripe somehow being used, despite your package.json.

`VERSION` was added in 8.103.0, and `includeBasic` was removed last year.
https://github.com/stripe/stripe-node/blob/723a00534e067d650646d4d44132dd1babed6767/CHANGELOG.md#81030---2020-09-28

You should be able to `console.log(require('stripe').PACKAGE_VERSION)` to confirm this.

**Comment by richardm-stripe** [comment]
Here's my attempt at reproducing:
https://github.com/richardm-stripe/netlify-test

My function
```
exports.handler = (event, context) => {
  return Promise.resolve().then(() => {
    return {
      statusCode: 200,
      body: JSON.stringify({ message: require('stripe').PACKAGE_VERSION, message2: typeof require('stripe')('sk_test').checkout.sessions.listLineItems }),
    };
  });
}
```
responds

```
{"message":"11.18.0","message2":"function"}
```
as expected

**Comment by richardm-stripe** [comment]
Do you have multiple package.json files that could be fighting / not working as expected? In the course of making my test project I first tried to put my package.json in the `netlify/functions` directory and it said I could use a plugin to make that work, or I could move my package.json to the top-level?

**Comment by brianfeister** [comment]
@richardm-stripe thanks! Silly on my part, but I guess nested `package.json` files will do that to you. Removing the dependency from the parent (project root, as opposed to `functions` dir in netlify) was the fix
