### ISSUE TITLE
Issue handling trial settings on Node SDK

### ISSUE THREAD

**Issue by csw531** [stripe/stripe-node#1753]
### Describe the bug

We are receiving an error when attempting to include specific trial settings with our Node SDK. The code says, 'trial_settings' property in the 'SubscriptionData' type is not valid, but I pulled the code directly from Stripe documentation.

I'm referencing the documentation here: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_settings-end_behavior-missing_payment_method

Here is my code: https://pastebin.com/4FijqGt4

Here is the error I am seeing: https://gyazo.com/9292d2eee17e0b52fa6de7bb80289374

Following the documentation, I applied the following code to subscription_data in order to not require a credit card when signing up for a free trial, but it doesn't look like these trial settings are supported.

### To Reproduce

#The code is below. I run into issues that are referenced in the error screenshot in the description. The trial settings don't seem to be supported in the subscription data.

import Stripe from 'stripe';
 
const privateKey = process.env.NODE_ENV==="production"?process.env.STRIPE_SECRET_KEY_LIVE:process.env.STRIPE_SECRET_KEY_TEST
export const stripe = new Stripe(privateKey, {
  apiVersion: '2022-11-15',
});
 
 
export const findCustomersByEmail = (email:string, params={}): Stripe.ApiSearchResultPromise<Stripe.Customer>=> {
 
  const newParams: Stripe.CustomerSearchParams = {
    ...params,
    query: `email:"${email}"`
  }
 
  const customers = stripe.customers.search(newParams);
  return customers
}
 
export const createCustomerByEmail = async (email:string): Promise<Stripe.Customer> => {
  const params: Stripe.CustomerCreateParams = {
    email,
  };
  const customer: Stripe.Customer = await stripe.customers.create(params);
  return customer
};
 
export const createOrRetrieveCustomerByEmail = async (email) => {
  const existing = await findCustomersByEmail(email)
  if(existing.data?.length>0) return {new: false, customer:existing.data[0]}
 
  return {new: true, customer: await createCustomerByEmail(email)}
 
};
 
export const createSubscribeCheckout = async (customerId:string):Promise<Stripe.Response<Stripe.Checkout.Session>> => {
  let baseUrl = process.env.NEXT_PUBLIC_VERCEL_URL || process.env.VERCEL_URL
  if(baseUrl) baseUrl = `https://${baseUrl}`
  else baseUrl='http://localhost:3000'
  const lineItems = [{
    price: process.env.STRIPE_SUBSCRIPTION_ID,
    quantity: 1,
  }]
  const session = await stripe.checkout.sessions.create({
 
    customer: customerId,
    mode: 'subscription',
    subscription_data: {
      trial_period_days:14,
      missing_payment_method: 'cancel',
    },
    payment_method_types: ['card'],
    line_items:lineItems,
    success_url: `${baseUrl}/payment/success?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `https://www.mktcal.com/calendar` ,
    allow_promotion_codes: true
  })
  return session
 
 
 
}
 
export const createUpdateCheckout = async (customerId:string, subscriptionId:string):Promise<Stripe.Response<Stripe.Checkout.Session>> => {
  let baseUrl = process.env.NEXT_PUBLIC_VERCEL_URL || process.env.VERCEL_URL
  if(baseUrl) baseUrl = `https://${baseUrl}`
  else baseUrl='http://localhost:3000'
 
  const session = stripe.checkout.sessions.create({
    payment_method_types: ['card'],
    mode: 'setup',
    customer: customerId,
    setup_intent_data: {
      metadata: {
        customer_id: customerId,
        subscription_id: subscriptionId,
      }
    },
    success_url: `${baseUrl}/profile?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `https://www.mktcal.com/calendar`,
    allow_promotion_codes: true
  })
  return session
 
 
 
}
 
export const fetchActiveSubscriptionByCustomerId = async (id:string) => {
  const customer = await stripe.customers.retrieve(id,{expand:['subscriptions']});
  if(!customer) throw new Error ("Customer not found.")
  /* @ts-ignore */
  const active = customer.subscriptions.data.filter(sub=>["active","trialing"].includes(sub.status))
 
  /* @ts-ignore */
  if(active.length>1) throw new Error ("Multiple subscriptions found.")
  // @ts-ignore
  if(active.length===0) return null
 
  // @ts-ignore
  return active[0]
 
}
 
export const fetchActiveSubscriptionByEmail = async (email:string) => {
  const customers = await findCustomersByEmail(email, {expand:['data.subscriptions']})
  console.log(email,"Here are the customers",customers)
  if(customers.data.length>1 ) throw new Error ("Duplicate customers found.")
  if(customers.data.length===0 ) throw new Error ("Customer not found.")
 
  const customer = customers.data[0]
 
  /* @ts-ignore */
  const active = customer.subscriptions.data.filter(sub=>sub.status==="active")
 
  /* @ts-ignore */
  if(active.length>1) throw new Error ("Multiple subscriptions found.")
  // @ts-ignore
  if(active.length===0) return null
 
  // @ts-ignore
  return active[0]
 
}
 
export const cancelSubscription = async (subscriptionId:string, atEndOfPaidPeriod=true):Promise<Stripe.Response<Stripe.Subscription>> => {
  if(atEndOfPaidPeriod) {
    return stripe.subscriptions.update(subscriptionId, {cancel_at_period_end: true});
  }
    return stripe.subscriptions.del(subscriptionId)
 
}

### Expected behavior

I expect for this code to allow trial sign ups without requiring credit card information.

### Code snippets

```JavaScript
const session = await stripe.checkout.sessions.create({
 
    customer: customerId,
    mode: 'subscription',
    subscription_data: {
      trial_period_days:14,
      missing_payment_method: 'cancel',
    },


I also tried this

    subscription_data: {
      trial_settings: {end_behavior: {missing_payment_method: 'cancel'}},
      trial_period_days:7,
    },
```

### OS

Windows

### Node version

Unsure

### Library version

Unsure

### API version

Unsure

**Comment by remi-stripe** [comment]
@csw531 The parameter is defined in our library [here](https://github.com/stripe/stripe-node/blob/19826fc0b901c07b8d23a711f3bae4609f0d77a6/types/Checkout/SessionsResource.d.ts#L1979-L1985) already. My guess is that your code runs an older version of stripe-node from before we added support for this parameter to our API officially. Looking at our Changelog it seems we added this in [11.9.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#1190---2023-02-02) of stripe-node so if you make sure to upgrade at least to that one it should solve the issue.

The code should be 
```
const session = await stripe.checkout.sessions.create({
  customer: customerId,
  mode: 'subscription',
  subscription_data: {
    trial_period_days: 14,
    trial_settings: {
      end_behavior: {
        missing_payment_method: 'cancel',
      },
    },
  },
  line_items: lineItems,
  success_url: `${baseUrl}/payment/success?session_id={CHECKOUT_SESSION_ID}`,
  allow_promotion_codes: true
});
```
