### ISSUE TITLE
Cannot access invoices.retrieveUpcoming using arguments

### ISSUE THREAD

**Issue by NoelBaron** [stripe/stripe-node#176]
The documentation says that I must supply a customer Id, with optional arguments to generate a prorated preview. My goal is to see what the end-balance looks like when I change from one subscription to another.

However, I have tried two different argument approaches and both result in a JSON error. 

1. ` stripe.invoices.retrieveUpcoming( customerId, {object of arguments}, callback) `
2. ` stripe.invoices.retrieveUpcoming( {object of arguments}, callback);`

```javascript
{ 
  [Error: Invalid JSON received from the Stripe API]
  type: 'StripeAPIError',
  stack: 'Error: Invalid JSON received from the Stripe API\n    
    at Error._Error (node_modules/stripe/lib/Error.js:12:17)\n    
    at Error.Constructor (node_modules/stripe/lib/utils.js:113:13)\n    
    at Error.Constructor (node_modules/stripe/lib/utils.js:113:13)\n    
    at IncomingMessage.<anonymous> (node_modules/stripe/lib/StripeResource.js:140:13)\n    
    at IncomingMessage.emit (events.js:117:20)\n    
    at _stream_readable.js:943:16\n   
    at process._tickDomainCallback (node.js:463:13)',
  rawType: undefined,
  code: undefined,
  param: undefined,
  message: 'Invalid JSON received from the Stripe API',
  detail: undefined,
  raw: 
   { 
     message: 'Invalid JSON received from the Stripe API',
     response: '',
     exception: [SyntaxError: Unexpected end of input] 
   } 
}
```

**Comment by dshorowitz** [comment]
I'm having the same problem. Any ideas?

**Comment by NoelBaron** [comment]
@dshorowitz I ended up using their live API to figure out what positive or negative balance for the customer.  As far as I know, they have no plans to fix this issue in their NodeJS bindings, because I haven't heard anything for weeks. 

This was the hack: 
- Make a request to the upcoming invoices API. 
- Used Moment.JS for easy time formatting.
- Set the quantity to 0 to simulate a complete cancellation of the subscription. 

Happy hacking.

```javascript
    var url = 
          "https://"+self.deps.stripe.getKey()+
          "@api.stripe.com/v1/invoices/upcoming"+
          "?customer="+account.customerId+
          "&subscription_prorate=true"+
          "&subscription="+account.subscriptionId+
          "&subscription_proration_date="+self.moment.utc(Date.now()).format('X')+
          "&subscription_quantity=0";
```

**Comment by dshorowitz** [comment]
@NoelBaron Wow, thanks for the assistance! I hate to revert to hacking, especially with something as critical as my payments solution, but it looks like in this case there's no choice. Maybe the Stripe team will fix this? Seems like a pretty big bug to me.

**Comment by NoelBaron** [comment]
26 days since I posted this... the live API works really well, so just tighty up your request and make sure it's sent out over ssl.

**Comment by matthewarkin** [comment]
I can try to work on a pull request if no one at Stripe is handling it

**Comment by dshorowitz** [comment]
@matthewarkin That would be fantastic if you could, thanks!

**Comment by matthewarkin** [comment]
Discovered what was going on while working on a fix.

The parameters the current version is expecting is 
customerId (required)
subscriptionId (optional)
dataobject or callback.

So it should look like 
stripe.invoices.retrieveUpcoming( customerId, subscriptionId, {object of arguments}, callback)

This does mean the current library version requires the subscription id.

**Comment by matthewarkin** [comment]
Pull request open

**Comment by dshorowitz** [comment]
Great, let's hope this is accepted. Thanks @matthewarkin

**Comment by dshorowitz** [comment]
Thanks @michelle and @matthewarkin! Works perfectly @NoelBaron

**Comment by NoelBaron** [comment]
Fantastic, thanks @matthewarkin. I'll test this next week.
