### ISSUE TITLE
Support for clear_usage param when deleting subscription item

### ISSUE THREAD

**Issue by joeldenning** [stripe/stripe-node#1765]
### Is your feature request related to a problem? Please describe.

According to [these Stripe API docs](https://stripe.com/docs/api/subscription_items/delete#delete_subscription_item-clear_usage), the `clear_usage=true` param can be sent to the `DELETE https://api.stripe.com/v1/subscription_items/:id` endpoint.

This property is not found in the stripe-node codebase or the typescript declarations.

### Describe the solution you'd like

```ts
stripe.subscriptions.del(subscriptionId, {clear_usage: true});
```

### Describe alternatives you've considered

I looked into whether I can add custom params to requests but didn't find it

**Comment by richardm-stripe** [comment]
I think the parameter is [here](https://github.com/stripe/stripe-node/blob/19826fc0b901c07b8d23a711f3bae4609f0d77a6/types/SubscriptionItemsResource.d.ts#L306). Are you on the latest version of stripe-node?

To add a custom parameter, you can just include it and it will be sent, `stripe.subscriptions.del(subscriptionId, {clear_usage: true});` should work, even if `clear_usage` weren't defined in the library. You might have to add @ts-ignore comment to add extra parameters (but from the look of it to me, the `clear_usage` is defined in the latest version of stripe-node).

**Comment by joeldenning** [comment]
Thanks for the quick response. I am using stripe@12.1.1 and the typescript declarations do not have the `clear_usage` property. See the `SubscriptionDeleteParams` typescript interface at https://unpkg.com/browse/stripe@12.1.1/types/SubscriptionsResource.d.ts, which is missing that property.

I will try ts-ignoring it and seeing if it works.

**Comment by joeldenning** [comment]
I am using stripe@12.1.1. It looks I was confusing `stripe.subscriptions.del()` and `stripe.subscriptionItems.del()`. I have been calling `stripe.subscriptions.del()` and get the following error:

`StripeInvalidRequestError: When deleting the subscription item si_NjnTuoVC9eg0kF with a metered plan, all related usage records must be cleared too by setting clear_usage=true`.

I was trying to do `stripe.subscriptions.del(subscriptionItemId, {clear_usage: true})`, but the clear_usage param is only supported on `stripe.subscriptionItems`.

I think what I'll need to do is delete all the subscription items (with `clear_usage`) before deleting the subscription? It looks like like stripe-node supports the `clear_usage` property on the SubscriptionItemDeleteParams, but not the SubscriptionDeleteParams. And the Stripe API docs indicate that that property is only available on the subscription items api, not the subscription api

**Comment by joeldenning** [comment]
It looks like Stripe API won't let me delete all the subscription items before deleting the subscription. I am unsure how to delete the subscription since the DELETE subscription api errors due to subscription items having `metered` usage, but I can't delete those subscription items because then the subscription no longer has any items and the API errors.

**Comment by pakrym-stripe** [comment]
@joeldenning, this sounds like an integration question rather than an issue with a library. Our support team will be much better positioned to help you with it. Please reach out to them at https://support.stripe.com/contact
