### ISSUE TITLE
POST https://r.stripe.com/0 always returns 400 status code in Cypress

### ISSUE THREAD

**Issue by nibblesnbits** [stripe/stripe-node#1767]
### Describe the bug

I'm trying to test payment in my application with Cypress end-to-end testing, but when I redirect to the https://checkout.stripe.com/c/pay/ page, the AJAX calls to `POST https://r.stripe.com/0` always result in a 400 response code.  Is this a known bug?

### To Reproduce

1. Create a checkout session on the server
2. Redirect to `session.url`
3. Observe that the page never fully loads and the Network tab shows 400s for all POST https://r.stripe.com/0.
(all above done from a Cypress test)

### Expected behavior

I should be able to select the elements in the form, but (it seems) the network calls failing is causing the form to never load properly.

### OS

macOs

### Node version

Node v18.16.0

### Library version

stripe v12.0.0

### API version

2022-11-15

**Comment by nibblesnbits** [comment]
It's worth noting that this still occurs when trying to select into the iframe generated by Elements as well.

**Comment by remi-stripe** [comment]
Hey @nibblesnbits This repository is for stripe-node which is the library you use server-side for making calls to our API. It looks like your question is more related to an integration question. Please work with our support team for help instead: https://support.stripe.com/contact

**Comment by nibblesnbits** [comment]
I will contact them, but in the mean time, this repo has an easy reproduction:  https://github.com/nibblesnbits/stripe-sample-code

**Comment by nibblesnbits** [comment]
Support has confirmed this was the correct course of action; please re-open this ticket.

**Comment by nibblesnbits** [comment]
I've since submitted this to the correct repo: https://github.com/stripe/react-stripe-js/issues/396
