### ISSUE TITLE
Cannot use other credit_card_source than first in credit_cards-array for modifying a subscription

### ISSUE THREAD

**Issue by joehannes** [stripe/stripe-node#177]
I've tested heavily, but at the moment - to me - it looks like you got some error in your (testing) node-api ..

Using: stripe-test-user as in docs with test data

When creating a subscription or modifying it (using the first available credit card) everything works ...
When choosing not the first credit card, but any other in the list ... and then updating the subscription I get an error: There is no token with ID card_3245098235jlasfdlkjasdf....
It's definitely the source param and on subs update/mod (possibly on creation as well)

to make the statement a lil more technical so you might believe this could possibly be so ...
I do more or less:
- fetch credit cards
- fetch subs of customer (app is only allowing for 1 per user, but anyway)
- apply a sub mod with source: fetched_credit_cards.data[req.body.credit_card_list_nr].id

....
the funny thing is you can actually watch the output ...
fetching credit cards .... id XYZ
updateing sub ... "THERE IS NO TOKEN WITH ID XYZ" ...???!!

ok, possibly my brain to warped already, but I thought I better report this

**Comment by matthewarkin** [comment]
@joehannes could you share your test code? I think  I know what the error is but seeing the api call that is throwing that would confirm.

**Comment by joehannes** [comment]
more or less:

```javascript
stripe.customers.updateSubscription(
    _org.billing.stripe,
    subscriptions.data[0].id,
    {
        plan: PLANS.filter(function (p, i, a) { return p.name === req.body.plan; })[0].id,
        source: cards.data[req.body.stripe].id
    },
    function (err, subscription) {
        if (err) {
            console.log("Couldn't update subscription on stripe ... ");
            console.log(err);
            res
                .status(502)
                .send(fail(err));
        } else {
            console.log("Successfully updated subscription!")
            console.log(subscription);
            res
                .status(200)
                .send(ok);
        }
    }
);
```

**Comment by matthewarkin** [comment]
So when you set source to a subscription, what will actually happen is it will create a new card, set that as the default card, and the delete the old default. 

Source in this context must be a token (like the ones from Stripe.js or Stripe Checkout) or a dictionary of credit card details.

Its all explained under the `source` definition at https://stripe.com/docs/api#update_subscription

**Comment by joehannes** [comment]
yeah, cool, so the id of a stripe-registered credit-card (with one of our stripe customers) ... is not a token?

earlier in the code to clarify ...
```javascript
stripe.customers.listCards(
    _org.billing.stripe,
    function (err, cards) {
        if (err) {
            console.log("Couldn't fetch cards to check for which to delete: " + _org.billing.stripe);
            console.log(err);
            res
                .status(502)
                .send(fail(err));
        } else {
            console.log("Cards fetched, correlating and trying to create/udpate subscription: " + _org.billing.stripe);
            stripe.customers.listSubscriptions(_org.billing.stripe, function (err, subscriptions) {
```

**Comment by joehannes** [comment]
and why on earth would it work (and accept as valid token) the first of the credit cards ... but not any other?
```
req.body.stripe == 0..9 //acting as an array index in the listCardsReplyJsonO.data - array (of CC-Objs)
```

**Comment by matthewarkin** [comment]
ids of cards are not tokens. 

So 
````
stripe.customers.updateSubscription(
    _org.billing.stripe,
    subscriptions.data[0].id,
    {
        plan: PLANS.filter(function (p, i, a) { return p.name === req.body.plan; })[0].id,
        source: cards.data[0].id
    },
````
would work? (basically hardcoding the 0)

**Comment by joehannes** [comment]
yes!!!

**Comment by joehannes** [comment]
ok, anyway, I think I get it ... and I honestly think this is a design flaw in the stripe-API

* You can have many credit cards stored on a customer
* Only one credit card can be the default payment source
* Only the default payment source can serve as payment-method to subscriptions

Why design flaw?
* You can have various subscriptions for one customer ...
* Why would you not be able to use different credit cards on different subscriptions?

Probably because you guess any app has only one subscription per user ...
But why then many subscriptions?
Because you save outdated/inactive subscriptions ...

Hmmm, weird ...

Anyway.
It would save me _1_ API call if I'd know how to retrieve a valid source token for a credit card, if:
* it is possible to retrieve that token out of the data of a listCards-call

Thx, cheers, J

**Comment by joehannes** [comment]
ok, thx, I found what I wanted and I think it was a misinterpretation from my side
