### ISSUE TITLE
the PaymentMethod.CardPresent interface is empty

### ISSUE THREAD

**Issue by benjamin-pike** [stripe/stripe-node#1772]
### Describe the bug

In types/PaymentMethods.d.ts, the CardPresent interface is empty
Issue persists as of v12.2.0

### Expected behavior

The expected type should be similar to the Card interface declared in the same file. 
Currently have to solve by creating a custom declaration file (see below)

```
declare module 'stripe' {
    namespace Stripe {
        namespace PaymentMethod {
            interface CardPresent {
                brand: string;
                cardholder_name: string | null;
                country: string | null;
                exp_month: number,
                exp_year: number,
                fingerprint?: string | null;
                funding: string;
                iin?: string | null;
                issuer?: string | null;
                last4: string;
                networks: Stripe.PaymentMethod.Card.Networks;
                read_method: string;
            }
        }
    }
}
```

### OS

macOS

### Node version

Node v18.15.0

### Library version

stripe-node 12.2.0

### API version

2022-11-15

**Comment by pakrym-stripe** [comment]
Hi @benjamin-pike, 

CardPresent properties are not included in the SDK because they are currently in preview.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/99349468/234907716-6c70b847-c214-4132-ab80-d493a18a950e.png">

I contacted the team and they plan to release these APIs soon.

**Comment by remi-stripe** [comment]
Closing as types have now shipped properly [here](https://github.com/stripe/stripe-node/commit/8e143455d31195d948c142e1cd5a62741a3f3e92#diff-c7b4b7ab31acef40883d0cc36d7125c2e788d974ee8bb0ef66364077593094c0R420)
