### ISSUE TITLE
VAT ID mandatory in checkout 

### ISSUE THREAD

**Issue by ximomompo** [stripe/stripe-node#1776]
### Is your feature request related to a problem? Please describe.

In the context of the European Union, the VAT ID to create an invoice is mandatory. 

Stripe provides an option in `checkout.session.create` to ask the user about the name and vat id, but this option it's an optional checkbox. 

This situation creates a problem because after the payment/subscription is sucessed and if the user doesn't insert the VAT ID into the checkout form (it's optional) the invoice is made without this info and marked as paid.  This invoice is useless for accounting.

### Describe the solution you'd like

Understating that the logic behind API must be terrific. Simply getting a required param in the option `tax_id_collection` is enough.

```
stripe.checkout.sessions.create({
  ...
  tax_id_collection: {
    enabled: true,
    required: true
  }
})
```

### Describe alternatives you've considered

By now my only alternative it's create a form before the user enters Stripe Checkout and ask him for his VAT ID.

**Comment by anniel-stripe** [comment]
@ximomompo Github issues should be limited to bugs / feature requests with the SDK - this is a feature request for Stripe Checkout, so I'm going to close this for now. Instead, please talk to our support team and they can help you there: https://support.stripe.com/contact
