### ISSUE TITLE
Alert user when an expected header field is included in the data args

### ISSUE THREAD

**Issue by matthewarkin** [stripe/stripe-node#179]
If a user accidentally passes a header value (say `stripe_account`) into the data object of an api call, that entire data object is assumed to be a request options header. This is thanks to the lovely (isOptionsHash) [https://github.com/stripe/stripe-node/blob/77ecf4823fef0bf191fc82f838f45941914e09ad/lib/utils.js#L15]

In some cases their post request request will go through, especially if the endpoint has no required endpoints (like create refund) or if stripe_account is equal to null it would also go through under the main account. 

I don't necessarily know the best way to handle this, at a minimum checking to see that at least one of the request options parameters is not null? The way the Ruby client handles it is all request and header params can be submitted as one hash (I don't necessarily like that way). But I figure the issue can lead to some discussion.

**Comment by kyleconroy** [comment]
I don't think there is an easy check for this. Since the second hash is just a headers hash, you can pass any headers you want, meaning that a check for `stripe_account` would miss cases where that header isn't included.
