### ISSUE TITLE
Missing plan in subscription typings

### ISSUE THREAD

**Issue by markwoodward23** [stripe/stripe-node#1792]
### Describe the bug

Current behaviour
```
import Stripe from 'stripe';

const stripe = new Stripe(env.STRIPE_SECRET_KEY, {
  apiVersion: '2022-11-15',
  typescript: true
});

const subOne = await stripe.subscriptions.retrieve(subscriptionId as string, {
  expand: ['plan.product']
})

const products = subOne.plan.product;

-----

Property 'plan' does not exist on type 'Response<Subscription>'.ts(2339)
```

Workaround for now: create my own type, cast to unknown, then to correct type: 
```
type Subscription = Stripe.Subscription & {
  plan: {
    product: {
      id: string
    }
  }
}

const subTwo = await stripe.subscriptions.retrieve(subscriptionId as string, {
  expand: ['plan.product']
}) as unknown as Subscription;
```

### To Reproduce

1. Fetch a subscription
2. Attempt to access the plan
3. See error

### Expected behavior

Types are correct - plan is listed as a possible return type

### OS

macOS

### Node version

v18.0.0

### Library version

12.5.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @markwoodward23 The `plan` property on Subscription has been deprecated for many years now so it's expected that it's not in types and undocumented. See https://github.com/stripe/stripe-node/issues/1517#issuecomment-1221355535 for a longer explanation as to why.
We recommend using `items.data[xxx].price` instead!

**Comment by markwoodward23** [comment]
Thanks @remi-stripe! Suggestion: it might be better to mark the field as deprecated in the type rather than omitting?
