### ISSUE TITLE
Bug (v10.x) - `Error: Cannot assign to read only property 'lastResponse' of object `

### ISSUE THREAD

**Issue by titanism** [stripe/stripe-node#1796]
### Describe the bug

`Error: Cannot assign to read only property 'lastResponse' of object `

### To Reproduce

I think it happens here:

```sh
node_modules/stripe/lib/StripeResource.js
102:    // lastResponse.
221:            Object.defineProperty(jsonResponse, 'lastResponse', {
```

### Expected behavior

This should not throw an error.

### OS

macOS

### Node version

Node v18

### Library version

stripe-node 10.17.0

### API version

2020-08-27

**Comment by pakrym-stripe** [comment]
I'm sorry @titanism but without a stack trace, a repro and with the fact that it doesn't reproduce on latest there isn't much we can do with the issue you are seeing.
