### ISSUE TITLE
Unable to use the Test Key in Testing/localhost environment

### ISSUE THREAD

**Issue by john0630** [stripe/stripe-node#1802]
### Describe the bug

My app hit the error "You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS." when i'm using the published Test Key "pk_testxxxxxxx" + "sk_testxxxxxx" as my secret key. It just happened today, yesterday seem to be working fine.

### To Reproduce

1. Using "pk_testxxx" as published key in the frontend application
2. Using "sk_testxxx" as secret key for my nodeJs backend
3. Click on checkout page from my frontend application
4. The error "You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS." prompt in the frontend application console log.

### Expected behavior

Should able to perform the testing from localhost environment by using the Test Keys.

### OS

Windows 11

### Node version

v16.19.1

### Library version

v8.96.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@john0630 this warning happens client-side in your browser when using Stripe.js. It's been here for many years. We do this to warn developers that HTTPS will be required for live payments in production. It doesn't affect your Test mode integration at all, it's just a warning.

Github issues should be limited to bugs with the stripe-node library itself which isn't related here. I'd recommend reaching out to our support team if you need more help: https://support.stripe.com/contact
