### ISSUE TITLE
[Bug] `%s` not replaced in jsdoc descriptions

### ISSUE THREAD

**Issue by hrueger** [stripe/stripe-node#1816]
### Describe the bug

The intellisense of VSCode shows `%s` where the documentation shows `cents` for example:
![grafik](https://github.com/stripe/stripe-node/assets/18656830/28f6983a-4698-4678-a87a-09e0f6af7b9d)
vs
![grafik](https://github.com/stripe/stripe-node/assets/18656830/0ba48306-5ebb-49d1-9412-47a666923f79)
(https://stripe.com/docs/api/balance_transactions/object#balance_transaction_object-net)

This is kind of confusing, as we first though that `net` is a percentage value of `amount` which does not make a lot of sense ;-)

### To Reproduce

1. Install `stripe` via `npm i stripe`
2. Create an object of type `Stripe.BalanceTransaction`
3. Hover over the `net` property with your mouse

### Expected behavior

It correctly shows `Net amount of the transaction, in cents.`

### Code snippets

```JavaScript
let t: Stripe.BalanceTransaction;
t.net;
```

### OS

windows

### Node version

Node 18.10.0

### Library version

stripe 12.8.0

### API version

2022-11-15

**Comment by pakrym-stripe** [comment]
Thank you for the report. We are going to look into this.

**Comment by pakrym-stripe** [comment]
This is [now fixed](https://github.com/stripe/stripe-node/blob/master/types/BalanceTransactions.d.ts#L63).

**Comment by hrueger** [comment]
Perfect, thanks!
