### ISSUE TITLE
Clarify Intent of SubtleCryptoProvider Message

### ISSUE THREAD

**Issue by sundaycrafts** [stripe/stripe-node#1827]
### Is your feature request related to a problem? Please describe.

The current error message for the default SubtleCryptoProvider doesn't clearly indicate that a synchronous constructEvent cannot be used. The existing error message states, "SubtleCryptoProvider cannot be used in a synchronous context."

### Describe the solution you'd like

If there's only one context in which this error message appears, the message could be made more helpful. For example, it might suggest using 'constructEventAsync' as an alternative, or provide a link to the relevant section of the documentation.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by richardm-stripe** [comment]
Hello @sundaycrafts. Thank you for taking the time to report this and helping us improve our library.

I took a crack at this in https://github.com/stripe/stripe-node/pull/1828/files, let me know if you have any thought about it there.

**Comment by richardm-stripe** [comment]
https://github.com/stripe/stripe-node/pull/1828 has been merged. It will be bundled with our release later this week.

**Comment by sundaycrafts** [comment]
Thank you for your great work!
