### ISSUE TITLE
Stripe Express accountLink ISSUE

### ISSUE THREAD

**Issue by thedarkknight197** [stripe/stripe-node#1829]
### Describe the bug

I am following the documentation to enable express accounts on my stripe account but when I send user to accountLink.url it will sent directly to my refresh url and not on configuration of stripe-express.

Documentation: https://stripe.com/docs/connect/express-accounts 

### To Reproduce

_

### Expected behavior

_

### Code snippets

```JavaScript
const account = await stripe.accounts.create({
			country: "US",
			type: "express",
			capabilities: {
				card_payments: {
					requested: true,
				},
				transfers: {
					requested: true,
				},
			},
			business_type: "individual",
		});

		console.log(account);

		const accountLink = await stripe.accountLinks.create({
			account: account.id,
			refresh_url: "https://mysite.com/reauth",
			return_url: "https://mysite.com/return",
			type: "account_onboarding",
			collect: "eventually_due",
		});

		console.log(accountLink.url);
```
```


### OS

MacOS Big Sur 11.7.7 (20G1345)

### Node version

v16.13.0

### Library version

12.10.0

### API version

_

### Additional context

_No response_

**Comment by remi-stripe** [comment]
@thedarkknight197 Githib issues are limited to bugs or feature requests with the stripe-node library itself. Your question is an integration support question and better directed at our support team instead: https://support.stripe.com/contact

The code you shared should work fine as long as you redirect that person to the URL yourself directly in the browser. Those URLs are single use and can not be shared in Slack for example. Slack would try to fetch the URL to show a preview and invalidate the link. It's a common problem that developers experience so I'm mentioning in case that's what is happening to you. Write code to directly send the user in their browser to that exact URL and it will work. Note that the URL is one-time use and if they reload the page, copy it to another browser or anything like this they will got back to your `refresh_url` where you should create a new one for them.

**Comment by thedarkknight197** [comment]
> @thedarkknight197 Githib issues are limited to bugs or feature requests with the stripe-node library itself. Your question is an integration support question and better directed at our support team instead: https://support.stripe.com/contact
> 
> The code you shared should work fine as long as you redirect that person to the URL yourself directly in the browser. Those URLs are single use and can not be shared in Slack for example. Slack would try to fetch the URL to show a preview and invalidate the link. It's a common problem that developers experience so I'm mentioning in case that's what is happening to you. Write code to directly send the user in their browser to that exact URL and it will work. Note that the URL is one-time use and if they reload the page, copy it to another browser or anything like this they will got back to your `refresh_url` where you should create a new one for them.

thank you I am using slack, so this is the problem! Thank you so much!
