### ISSUE TITLE
v13 types incorrectly points to API Version "2022-11-15"

### ISSUE THREAD

**Issue by sushantdhiman** [stripe/stripe-node#1874]
### Describe the bug

v13 types incorrectly pins to "2022-11-15", it should pin to "2023-08-16" as mentioned in the [release notes](https://github.com/stripe/stripe-node/releases/tag/v13.0.0).

https://github.com/stripe/stripe-node/blob/3065b53f868475eee1147361b0710371df5240c3/types/lib.d.ts#L30

It gives error when trying to use api version "2023-08-16" with `new Stripe(<API_KEY>, { apiVersion: "2023-08-16" })`

```ts
src/stripe.ts:7:3 - error TS2322: Type '"2023-08-16"' is not assignable to type '"2022-11-15"'.

7   apiVersion: '2023-08-16',
    ~~~~~~~~~~
```

### To Reproduce

With `stripe@13.0.0` try running this code

```ts
const stripe = new Stripe(<API_KEY>, {
  apiVersion: "2023-08-16"
});
```

### Expected behavior

No type error

### OS

Arch Linux

### Node version

Node v20.2.0

### Library version

stripe-node v13.0.0

### API version

2023-08-16

**Comment by richardm-stripe** [comment]
Fixes #1874

**Comment by richardm-stripe** [comment]
Hello @sushantdhiman. 

Thank you so much for reporting this. I'll try to have a fix out right away.

**Comment by richardm-stripe** [comment]
Fixed in https://github.com/stripe/stripe-node/releases/tag/v13.1.0
