### ISSUE TITLE
SetupIntents: `automatic_payment_methods` is not enabled by default

### ISSUE THREAD

**Issue by Kikobeats** [stripe/stripe-node#1881]
### Describe the bug

According to the releases notes, the latest API version has `automatic_payment_methods` enabled by default for `SetupIntents`:

<img width="860" alt="CleanShot 2023-08-19 at 14 59 47@2x" src="https://github.com/stripe/stripe-node/assets/2096101/50364522-ddd6-43ef-8a9c-aa074fb3d923">

### To Reproduce

```
const { faker } = require('@faker-js/faker')
const createStripe = require('stripe')

const stripe = createStripe(TOM_STRIPE_KEY)
const email = `test_${faker.internet.exampleEmail()}`

const { id: customerId } = await stripe.customers.create({ email })
  
const tokens = await Promise.all([
  stripe.tokens.create({
    card: {
      number: '4242424242424242',
      exp_month: 12,
      exp_year: 2048,
      cvc: '123'
    }
  }),
  stripe.tokens.create({
    card: {
      number: '5555555555554444',
      exp_month: 12,
      exp_year: 2049,
      cvc: '123'
    }
  })
])

const card = await stripe.customers.createSource(customerId, {
  source: tokens[0].id
})

const setupIntent = await stripe.setupIntents.create({
  payment_method: card.id,
  customer: customerId,
  confirm: true,
  automatic_payment_methods: {
    // enabled: true,
    allow_redirects: 'never'
  }
})
```

### Expected behavior

The error message is saying:

> Missing required param: automatic_payment_methods[enabled].

### OS

macOS

### Node version

v18.17.1

### Library version

stripe-node v13.2.0

### API version

2023-08-16

**Comment by remi-stripe** [comment]
@Kikobeats If you try without `allow_redirects: 'never'` you will see it's enabled by default on the latest API version as expected.

Right now the API just expects you to be explicit when passing that parameter to also pass `enabled: true` at the same time.
We could lift that restriction in the future though but wanted to be a bit stricter to start to be careful around adoption of this newer parameter.
