### ISSUE TITLE
Subscription metadata doesn't appear on the dashboard

### ISSUE THREAD

**Issue by leen-neel** [stripe/stripe-node#1887]
### Describe the bug

When I make a subscription with `stripe.checkout.session.create()` and pass metadata to it, the metadata doesn't appear on the dashboard. But, it shows up in the logs.

### To Reproduce

1. Create a subscription intent(?) with `stripe.checkout.session.create()`
2. Set `mode` to `subscription`
3. Add whatever you want to the `metadata` and `subscription_data.metadata`
4. Complete the payment

### Expected behavior

Metadata should be available on the dashboard.

### Code snippets

```JavaScript
router.post("/create-session", async (req: Session, res: Response) => {
  const sesh = await stripe.checkout.sessions.create({
    mode: "subscription",
    success_url: "http://localhost:3000/subscribe",
    cancel_url: "http://localhost:3000/subscribe",
    line_items: [
      {
        price: "price_1NjeCBSETCMRxFoNOnMCQMdV",
        quantity: 1,
      },
    ],
    metadata: {
      uid: req.body.uid,
    },
    subscription_data: {
      metadata: {
        uid: req.body.uid,
      },
    },
  });

  res.send(sesh);
});
```

### OS

Kubuntu

### Node version

v18.13.0

### Library version

13.3.0

### API version

2023-08-29

### Additional context

![image](https://github.com/stripe/stripe-node/assets/49027876/537eee29-7ab4-4f96-a97d-2ee4b0057dec)
![image](https://github.com/stripe/stripe-node/assets/49027876/4b151c75-1645-4ac4-ad82-28d79afdf538)

**Comment by leen-neel** [comment]
So, how do I add the metadata work properly?

**Comment by remi-stripe** [comment]
Please work with our support team for integration help or Dashboard support: https://support.stripe.com/contact

**Comment by leen-neel** [comment]
Hey @remi-stripe!
I figured it out. Thank you so much, appreciate you.

Best regards,
Neel.

**Comment by josephmaxim** [comment]
@leen-neel please post how you solved this issue for people who haven't figured it out. would save us a lot of time. Thanks!

**Comment by leen-neel** [comment]
Fix:
I was looking in the wrong place all this time. I had to look under Billings => Subscriptions and select one of the new subscriptions created to get the metadata.

![image](https://github.com/stripe/stripe-node/assets/49027876/e8e7886b-7854-408d-b848-c530b4ffc934)
