### ISSUE TITLE
Error: Cannot find module './resources/Accounts' on EC2

### ISSUE THREAD

**Issue by patrizz** [stripe/stripe-node#189]
I've included stripe in my nodejs app by adding it in the package.json file as follows:
> {..."dependencies": {..."stripe": "*",...}...}

After successfully testing it on a local nodejs installation, everything is then deployed using "eb deploy" to an EC2 instance.

On the EC2 instance I get the following exception in the nodejs log:
> module.js:340
>     throw err;
>           ^
> Error: Cannot find module './resources/Accounts'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/var/app/current/node_modules/stripe/lib/stripe.js:28:12)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)

Any idea what this might be related to?

**Comment by patrizz** [comment]
Looking on the machine I see that "Accounts.js" is indeed not being gotten from the repository for some reason.  when I manually "sudo npm install stripe" on the machine the file gets downloaded and placed at the correct spot. 
Also, going back to version 3.4.0 seems to "solve" the issue.

**Comment by kyleconroy** [comment]
@patrizz were you ever able to figure this out? No one else has reported this issue.
