### ISSUE TITLE
Metadata typing not including null / undefined

### ISSUE THREAD

**Issue by goodpaul** [stripe/stripe-node#1890]
### Describe the bug

In v13.3 the `Metadata` interface does not properly include null / undefined as a value.  

shared.d.ts
```
declare module 'stripe' {
  namespace Stripe {
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    interface Metadata {
      [name: string]: string;
    }
    ...
```

This leads to unsafe typing in TS where any value metadata is assumed to exist as a string

### To Reproduce

```
const transfer = {} as Stripe.Transfer;
const importantId: string = transfer.metadata.foo;
```
This does not show a type error even though foo could be undefined / null

### Expected behavior

A type error should be thrown on importantId

### OS

macOS

### Node version

Node v16.20

### Library version

stripe-node v13.3

### API version

2023-08-16

**Comment by pakrym-stripe** [comment]
This is an expected TypeScript behavior that you can change by setting [`noUncheckedIndexedAccess` ](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in your `tsconfig`.

see https://github.com/stripe/stripe-node/issues/1553 for additional discussion

**Comment by goodpaul** [comment]
Thank you for the info and apologies for the duplicate issue!
