### ISSUE TITLE
stripe.prices.list({ currency: 'eur' }) returns usd only

### ISSUE THREAD

**Issue by mavrick** [stripe/stripe-node#1891]
### Describe the bug

i'm unable to get the additional currencies set in the dashboard using the `stripe.prices.list();` method. It will only return usd pricing, even if i specify 'eur' for the currency key.

### To Reproduce

const { data: prices = [] } = await stripe.prices.list({ currency: 'eur' })

### Expected behavior

i expect to see all currencies for a product listed, usd, eur, gbp etc.

### OS

windows

### Node version

node 16.19.1

### Library version

stripe-node v13.3.0

### API version

 2023-08-16

**Comment by mavrick** [comment]
Request POST body:

```{
  "billing_scheme": "per_unit",
  "recurring": {
    "interval": "month",
    "usage_type": "licensed",
    "interval_count": "1",
    "trial_period_days": "0"
  },
  "tax_behavior": "inclusive",
  "unit_amount_decimal": "100",
  "currency": "aud",
  "currency_options": {
    "eur": {
      "tax_behavior": "inclusive",
      "unit_amount_decimal": "59"
    },
    "gbp": {
      "tax_behavior": "inclusive",
      "unit_amount_decimal": "51"
    },
    "usd": {
      "tax_behavior": "exclusive",
      "unit_amount_decimal": "65"
    }
  },
  "product": ["prod_OYCC85fEMozoSH"](https://dashboard.stripe.com/test/products/prod_OYCC85fEMozoSH),
  "expand": [
    "tiers"
  ]
}```

Response body

```{
  "id": ["price_1Nl5oSEucRJhMyWmiCALbxlb"](https://dashboard.stripe.com/test/prices/price_1Nl5oSEucRJhMyWmiCALbxlb),
  "object": "price",
  "active": true,
  "automatic_currency_conversion_eligible": false,
  "billing_scheme": "per_unit",
  "created": 1693468872,
  "currency": "aud",
  "custom_unit_amount": null,
  "livemode": false,
  "lookup_key": null,
  "metadata": {
  },
  "never_used": true,
  "nickname": null,
  "owning_merchant": "acct_19mCKLEucRJhMyWm",
  "owning_merchant_info": "acct_19mCKLEucRJhMyWm",
  "product": ["prod_OYCC85fEMozoSH"](https://dashboard.stripe.com/test/products/prod_OYCC85fEMozoSH),
  "recurring": {
    "aggregate_usage": null,
    "interval": "month",
    "interval_count": 1,
    "trial_period_days": null,
    "usage_type": "licensed"
  },
  "tax_behavior": "inclusive",
  "tiers_mode": null,
  "transform_quantity": null,
  "type": "recurring",
  "unit_amount": 100,
  "unit_amount_decimal": "100"
}```

how do i access `currency_options` ?

**Comment by mavrick** [comment]
ok i figured it out. apologies, first time encountering an "EXPANDABLE" field.

`stripe.prices.list({ expand: ['data.currency_options'] });`

**Comment by mavrick** [comment]
but that being said `stripe.prices.list({ currency: 'eur' })` still returns 'usd' pricing. is this becuase it is finding eur pricing inside `currency_options` ? - that is a bit confusing.

**Comment by remi-stripe** [comment]
@mavrick yep that's why in this case since those Prices work in EUR and it makes sense they would be return though you're right that without expanding `currency_options` it can be confusing.

I'll close as this isn't a bug or feature request with the library and more an integration support question so if you have a follow up question make sure to contact our support team instead: https://support.stripe.com/contact
