### ISSUE TITLE
`Stripe.Event.Type` is missing Treasury events

### ISSUE THREAD

**Issue by jbwc** [stripe/stripe-node#1894]
### Describe the bug

It seems that the `Stripe.Event.Type` is missing some valid values. I don't see any `treasury.*` events. In particular, I'm trying to use `treasury.financial_account.features_status_updated` but I can't without working around the type issue.

Diffing the list of [Stripe.Event.Type](https://github.com/stripe/stripe-node/blob/86da21e351d876bca8bd80417db7938130ec9ad0/types/Events.d.ts#L116) against [WebhookEndpointsResource.EnableEvent](https://github.com/stripe/stripe-node/blob/86da21e351d876bca8bd80417db7938130ec9ad0/types/WebhookEndpointsResource.d.ts#L146) shows:

<img width="1803" alt="image" src="https://github.com/stripe/stripe-node/assets/126919187/1715387e-003f-438c-9863-8d4a79daf564">

### To Reproduce

<img width="861" alt="image" src="https://github.com/stripe/stripe-node/assets/126919187/9d111760-b481-41f5-90b9-4c50f92f0d6e">

### Expected behavior

Type should exist

### OS

n/a

### Node version

n/a

### Library version

latest

### API version

n/a

**Comment by pakrym-stripe** [comment]
This is fixed in 13.5.0.
