### ISSUE TITLE
stripe__WEBPACK_IMPORTED_MODULE_0__.default is not a constructor

### ISSUE THREAD

**Issue by stylessh** [stripe/stripe-node#1896]
### Describe the bug

I receive an error when importing stripe:

![image](https://github.com/stripe/stripe-node/assets/45767683/d114373f-0ab1-462e-9579-e3714802b261)
![image](https://github.com/stripe/stripe-node/assets/45767683/5dc860b2-714c-4ac4-b194-6f975c5fdbc8)

I'm using next 13 with app dir and latest version of stripe.

### To Reproduce

1. Create a next 13 app.
2. Create a `stripe.ts` file to initialize the library.
3. Try to use it in a server route.

### Expected behavior

The library should return the expected Stripe object since it's  not marking any apparent error.

![image](https://github.com/stripe/stripe-node/assets/45767683/bc4abbe0-6a62-4d2c-83ea-efef69a034a1)

### OS

Windows 11

### Node version

Node v18.16.0

### Library version

"stripe": "12.14.0"

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@stylessh The webpack error makes me think you are importing/using the stripe-node library in your client-side code. The stripe-node library is used server-side for API requests with your Secret API key and it is not compatible with a browser environment. For client-side API requests you would use a separate library called Stripe.js that can either be imported directly or using an npm package and the different options are covered in our docs [here](https://stripe.com/docs/js/including).

If you're confident this is only happening with your server-side code we would need a way to quickly reproduce this end to end with the exact code you're using!

**Comment by stylessh** [comment]
@remi-stripe first, thanks for helping me!

I'm pretty sure i'm importing the library on server side, next.js is server first and it executes all the files on the server unless you explicitly set it to client. I'm gonna try changing the tsconfig en let you know

**Comment by remi-stripe** [comment]
@stylessh can you give a simple end to end repro? A repo with all the info would help

**Comment by stylessh** [comment]
Invited you to the repo, check the `stripe` branch

**Comment by stylessh** [comment]
be sure to copy `.env.example` to `.env.local` keys

**Comment by stylessh** [comment]
this is the [video example](https://tmpfiles.org/dl/2269246/flow.mp4) of the user flow and error

**Comment by remi-stripe** [comment]
@stylessh Can you make a clean public repo that has the exact information needed to reproduce the issue? Sorry for the hassle but I'm not the only person helping and getting a clean repro without any manual steps would help. It really should solely be loading stripe-node and nothing specific to your own code/project beyond reproducing the error

**Comment by stylessh** [comment]
Hey, I just debugged the issue. I have a webpack custom rule to load the canvas.node module with the raw-loader.

![image](https://github.com/stripe/stripe-node/assets/45767683/4d81f7b1-369d-4ff7-a606-14c88726afb1)

This probably matched with a stripe file ending having `.node`. I changed the regex to match only `canvas.node`, seems to load the library now.

![image](https://github.com/stripe/stripe-node/assets/45767683/2528cb0e-1ea7-4c46-a0c3-5f42ba39e0d9)

**Comment by remi-stripe** [comment]
Glad you figured it out and thanks for taking the time to update us with the root cause/fix, that's really appreciated :)

**Comment by element-software** [comment]
> Hey, I just debugged the issue. I have a webpack custom rule to load the canvas.node module with the raw-loader.
> 
> ![image](https://private-user-images.githubusercontent.com/45767683/266648418-4d81f7b1-369d-4ff7-a606-14c88726afb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzE2MjEsIm5iZiI6MTcxNjA3MTMyMSwicGF0aCI6Ii80NTc2NzY4My8yNjY2NDg0MTgtNGQ4MWY3YjEtMzY5ZC00ZmY3LWE2MDYtMTRjODg3MjZhZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIyMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTA2NDFlMmY2ZmE1MWI3OGM0YTUwNjYwNTQ1OGZjN2M4ZTViZTg2YjRhYTk5OTk3ZjQxMWU4MGRkNjQ3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LdO5HxD3XvQwdVKipHjHMrVv0Ld2dCnoHpTLwrGItQE)
> 
> This probably matched with a stripe file ending having `.node`. I changed the regex to match only `canvas.node`, seems to load the library now.
> 
> ![image](https://private-user-images.githubusercontent.com/45767683/266648761-2528cb0e-1ea7-4c46-a0c3-5f42ba39e0d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzE2MjEsIm5iZiI6MTcxNjA3MTMyMSwicGF0aCI6Ii80NTc2NzY4My8yNjY2NDg3NjEtMjUyOGNiMGUtMWVhNy00YzQ2LWEwYzMtNWY0MmJhMzllMGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIyMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NjFjZTRkNTUxOGM5MGY1NWZmZThmM2IwNzE5MDhiMzBkOTkwZjIzZTcyMGY0YzU2Zjg4ZWRkY2IyZjJlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhlZj-XbfPBFRW3muUxtLtBbajyBBybYh3gtlkKXu6w)

Exactly the same issue I had, your fix worked for me. Thank you!
