### ISSUE TITLE
Property 'quantity' does not exist on type 'Response<Subscription>'

### ISSUE THREAD

**Issue by tendev-eoghan** [stripe/stripe-node#1909]
### Describe the bug

When retrieving a subscription

`const subscription = await stripe.subscriptions.retrieve(sub)`

The resulting `Stripe.Subscription` has a `quantity` key. 
However, typescript throws an error saying the value does not exist on the subscription type.

This can be avoided by adding

```    
 // eslint-disable-next-line
 // @ts-ignore
 const quantity = subscription.quantity;
```

### To Reproduce

1. Call `stripe.subscriptions.retrieve(sub)`
2. Access the quantity key on the returned subscription.
3. See the error `Property 'quantity' does not exist on type 'Response<Subscription>'.ts(2339)`

### Expected behavior

1. Call `stripe.subscriptions.retrieve(sub)`
2. Access the quantity key on the returned subscription without a TS error.

### OS

macOS

### Node version

Node v18.16.1

### Library version

stripe ^12.14.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@tendev-eoghan You can find a detailed answer in https://github.com/stripe/stripe-node/issues/1794 and https://github.com/stripe/stripe-node/issues/1517#issuecomment-1221355535 with all the context. The short answer is that this is expected as that property has been deprecated since 2017, use `items.data` instead!

**Comment by mtrabelsi** [comment]
@remi-stripe  what a joke, i keep following your links "detailed answer" which leads to another "detialed answer" and so on lol

**Comment by remi-stripe** [comment]
@mtrabelsi the second link I gave https://github.com/stripe/stripe-node/issues/1517#issuecomment-1221355535 succinctly explains the change though. And my answer also said what to change in the code. I get you're frustrated but this answer did address the original question.
If you have follow up questions, please reach out to our support team for 1:1 help: https://support.stripe.com/contact
