### ISSUE TITLE
Quantity does not exist on Subscription type

### ISSUE THREAD

**Issue by kylejw2** [stripe/stripe-node#1912]
### Describe the bug

I'm using TypeScript

### To Reproduce

Use typescript.
Retrieve a subscription via `stripe.subscriptions.retrieve`.
Try to access the quantity on the subscription and notice that you'll receive a type error saying `Property 'quantity' does not exist on type 'Subscription'.`

When I log the subscription object, I can see that there is a `quantity` field on the object. I don't want to explicitly typecast the response and say that it exists since it's not on the official `Stripe.Subscription` type.

If the `quantity` field sometimes does not exist on the subscription, I'd rather its type be `number | null` instead of nonexistent.

### Expected behavior

I expect the `Stripe.Subscription` type to accurately represent the fields of the subscription object I receive from Stripe.

### Code snippets

```JavaScript
const subscription = await this.#stripe.subscriptions.retrieve(
      params.subscriptionId
    );

    console.log(subscription);


Logged output. The part to focus on is the quantity field I'm receiving
```
{
  id: ,
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1695348132,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: { comment: null, feedback: null, reason: null },
  collection_method: 'charge_automatically',
  created: 1695348132,
  currency: 'usd',
  current_period_end: 1697940132,
  current_period_start: 1695348132,
  customer: ,
  days_until_due: null,
  default_payment_method: ,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [ [Object] ],
    has_more: false,
    total_count: 1,
    url: 
  },
  latest_invoice: ,
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    hidden
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    hidden
  },
  quantity: 3, <----------------------------
  schedule: null,
  start_date: 1695348132,
  status: 'active',
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
  trial_start: null
}
```
```

### OS

macOS

### Node version

v18.9.0

### Library version

11.12.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@kylejw2 see the answer to the same question yesterday https://github.com/stripe/stripe-node/issues/1909 this is expected
