### ISSUE TITLE
Creating Invoice Items before Invoice - No longer getting automatically added to invoice

### ISSUE THREAD

**Issue by BehrensT** [stripe/stripe-node#1918]
### Describe the bug

We just upgrade our stripe-node package to latest `13.0.8` from `8.177.0` and started having some issues with the invoice and invoice item creation logic. 

According to the [API documentation](https://stripe.com/docs/api/invoiceitems/create)
>Creates an item to be added to a draft invoice (up to 250 items per invoice). If no invoice is specified, the item will be on the next invoice created for the customer specified.

Our business logic is creating the invoice items first, then creating the invoice for a customer - which according to the API doc should be okay. But what we are seeing with the latest version are pending invoice items and an empty invoice when `stripe.invoices.create` is called. 

### To Reproduce

1. Create some InvoiceItems for a customer
2. Create an invoice for the same customer
3. Look at the invoice and see no items

### Expected behavior

Is this a bug with the latest code? Or a bug in the documentation? I realize we are coming from a pretty old version so I am unsure if something changed between 8.x to 13.x 

### Code snippets

`package.json`
```JavaScript
  "dependencies": {
    "stripe": "^13.8.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
```

`index.ts`
```
import Stripe from "stripe";
import assert from "assert"; // Node.js assert module
const stripe = new Stripe("<stripe_api_token>", {
  apiVersion: "2023-08-16",
});

const customerId = "<stripe_customer_id>";
const stripe_price_id = "<stripe_price_id>";

const createInvoice = async () => {
  return await stripe.invoices.create({
    customer: customerId,
    automatic_tax: { enabled: true },
    auto_advance: false,
  });
};

const createInvoiceItem = async (invoiceId: string | undefined) => {
  let ci: any = {
    customer: customerId,
    quantity: 1,
    price: stripe_price_id,
  };
  if (invoiceId) {
    ci.invoice = invoiceId;
  }
  return await stripe.invoiceItems.create(ci);
};

(async () => {
  let invoice1,
    invoice2: any | null = null;

  invoice1 = await createInvoice();
  createInvoiceItem(invoice1.id);
  invoice1 = await stripe.invoices.retrieve(invoice1.id);
  assert(invoice1.subtotal > 0);

  //Create the invoice item without an invoice first
  await createInvoiceItem(undefined);
  invoice2 = await createInvoice();
  invoice2 = await stripe.invoices.retrieve(invoice2.id);

  assert(invoice2.subtotal > 0);
})();




```
```


### OS

macOS Ventura 13.6 - M1 Chipset

### Node version

Node v18.17.1

### Library version

"stripe": "^13.8.0",

### API version

2023-08-16

### Additional context

_No response_

**Comment by remi-stripe** [comment]
@BehrensT The stripe-node library pins to the latest API version by default, if you don't explicitly set the older API version.

The default behaviour of not pulling in pending InvoiceItems changed over a year ago in [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01). What you need to do is either force an older API version in the code as documented [here](https://stripe.com/docs/api/versioning?lang=node) or you can pass the `pending_invoice_items_behavior` [parameter](https://stripe.com/docs/api/invoices/create#create_invoice-pending_invoice_items_behavior) set to `include` to force pull those.

I'm going to close this issue as this is more an integration support question and you can follow up with our support team if you have follow up questions: https://support.stripe.com/contact

**Comment by BehrensT** [comment]
Awesome, thanks for the information and the quick response!
