### ISSUE TITLE
Move types to separate @types npm package

### ISSUE THREAD

**Issue by damir-minkashev** [stripe/stripe-node#1923]
Hi there,

In my case, I use only typing from the `stripe` package. 
Is it possible to move the `types` folder to a separate types definition package like @types/stripe? 
I didn't find any similar issue or reason why it hasn`t been done.
 
Many thanks.

**Comment by pakrym-stripe** [comment]
Hi @damir-minkashev,

I'm  curious about your use-case. How do you use stripe where only types are useful but not the runtime logic itself?

**Comment by damir-minkashev** [comment]
In our company, we use stripe runtime logic in the main project. And also we have another project where we handle webhooks. So, for the webhook case, we need only typing. 

Maybe someone has a similar issue. It would be a great thing to separate typings.

**Comment by pakrym-stripe** [comment]
Is having both types and runtime logic somehow detrimental in your case?

**Comment by damir-minkashev** [comment]
It`s a good question. There are no detrimental effects, except memory and dependencies overhead. But it seems like it`s not crucial for us overhead is not as significant as I assumed. If this issue isn`t useful for any else I guess it could be closed. Sorry to bother you :)

**Comment by pakrym-stripe** [comment]
Never hurts to ask. I'm going to close the issue until we find a reason to split out the types.
