### ISSUE TITLE
Api version 2023-10-16 appears to not exist

### ISSUE THREAD

**Issue by Xhale1** [stripe/stripe-node#1934]
### Describe the bug

The release notes for version 14.0.0 appear to link to a non-existent api version: https://stripe.com/docs/upgrades#2023-10-16. The stripe dash also lists 2023-08-16 as the latest version.

### To Reproduce

Visit https://stripe.com/docs/upgrades#2023-10-16

### Expected behavior

The api version exists or there's a prompt to upgrade in the dash.

### OS

macOS

### Node version

Node v 20.8.1

### Library version

stripe-node v14.0.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@Xhale1 Sorry for the confusion, the link does work now!
