### ISSUE TITLE
Add Type for <stripe-pricing-table> element

### ISSUE THREAD

**Issue by michael-sumner** [stripe/stripe-node#1941]
### Is your feature request related to a problem? Please describe.

Adding a stripe pricing table no-code embed causes errors in TypeScript:

```
Property 'stripe-pricing-table' does not exist on type 'JSX.IntrinsicElements'.
```

### Describe the solution you'd like

Create a type for `<stripe-pricing-table>`

### Describe alternatives you've considered

This has been referenced on the internet:
https://stackoverflow.com/questions/73468977/property-stripe-pricing-table-does-not-exist-on-type-jsx-intrinsicelements

Although the solutions provided do not work for the given issue in TypeScript.

**Comment by remi-stripe** [comment]
@michael-sumner This repository is for the stripe-node SDK which is used server-side in your Node.JS code to make Stripe API requests. This has no information or type(s) about your client-side code. My advice is to write to our support team, provide your code and more details and they can look into this feature request but it would be unrelated to this SDK.
You can contact them here: https://support.stripe.com/contact
