### ISSUE TITLE
Checkout session create success_url should be optional?

### ISSUE THREAD

**Issue by cenzovit** [stripe/stripe-node#1944]
### Describe the bug

May be interpreting the docs incorrectly, but it looks like checkout session success_url was relatively recently changed to optional; however, when creating a checkout sessions without it, I receive an error "parameter_missing - success_url".

### To Reproduce

1. Attempt to create a checkout session without a success_url
2. Receive an error "parameter_missing - success_url"

### Expected behavior

Successfully create a checkout session which I hope upon completion the user is left at the managed payment success page.

### OS

linux

### Node version

18.11

### Library version

stripe-node 14.2.0

### API version

 2023-10-16

**Comment by remi-stripe** [comment]
Hey @cenzovit, the `success_url` is required today for creating a normal Checkout Session. It's only "optional" if you pass `ui_mode: 'embedded'` in which case you have to pass `return_url` instead. We'll improve the API Reference to make this clearer.
