### ISSUE TITLE
Unable to filter calls using startTime and endTime in the list method (please see closing comments in `Additional context` section)

### ISSUE THREAD

**Issue by thechori** [stripe/stripe-node#1949]
### Describe the bug

My code works perfectly when I run:

```ts
const calls = await twilioClient.calls.list({
  from: "+12223334444", // fake number
})
```

but when I try to add the `startTime` and `endTime`, I receive an empty array (see below in "To Reproduce")

Note: I think it might have to do with the difference between `Date` and a `string` type when being passed in? I've tried to convert my date string (e.g., "2023-11-01") to a Date object, and neither works.

![image](https://github.com/stripe/stripe-node/assets/15255538/39e92c4a-2c8d-4e62-81b7-6b02a650f1b9)

In this intellisense screenshot, the suggestion is to pass a date as `YYYY-MM-DD` but the TypeScript type is marked as `Date | undefined`

### To Reproduce

```ts
// Returns an empty array when there is lots of data
const calls = await twilioClient.calls.list({
  from: "+12223334444",
  startTime: "2023-11-01",
  endTime: "2023-12-01",
});

// Returns an empty array when there is lots of data
const calls = await twilioClient.calls.list({
  from: "+12223334444",
  startTime: new Date("2023-11-01"),
  endTime: new Date("2023-12-01"),
});
```

### Expected behavior

I'd expect to pass in the date's `string` (e.g., "2023-11-01") into the following function and have the filtered call data return properly

```ts
const calls = await twilioClient.calls.list({
      from: "+12223334444",
      startTime: "2023-11-01",
      endTime: "2023-12-01",
    });
```

### Code snippets

```JavaScript
See above
```

### OS

macOS

### Node version

Node v20.5.0

### Library version

"stripe": "^14.3.0"

### API version

2023-08-16

### Additional context

Absolutely love the work that you all have done. This is my first hiccup with the API and I'd be more than glad to help more to get this resolved because this would make my application even better.

Thank you so much!! 🔥 🙌 

### Update (as of finishing this bug report...):
I've found the issue... I was using the wrong parameters the entire time... I did not realize that there were `startTimeAfter` and `endTimeBefore`. I'd love to say that doing away with both of those in favor of consolidating into simply `startTime` and `endTime` would be the best way to improve DX, but I also don't have the context and experience of a Twilio engineer, so I don't know if that is sound advice or not. All I know is that I was incredibly confused and frustrated and I only stumbled upon these two extra parameters by throwing a hail mary pass at the intellisense to see what other things I could pass into the `.list()` function call.

I sincerely hope that you appreciate the time that I spent to provide this feedback. Once again, you guys are awesome. Thank you so much for the hard and quality work. Sorry if this comes as a waste of time to y'all, but I hope that it does not!

Cheers :)

**Comment by remi-stripe** [comment]
@thechori Your code examples should the Twilio API being used but you filed this on the stripe-node repo which is the Node.js library for Stripe's API.
I assume you meant to file this on https://github.com/twilio/twilio-node instead but since it's resolved I'm going to close it out :)

**Comment by thechori** [comment]
@remi-stripe LMAO omg.. this is when you know I was up way too late and not thinking clearly. Thank you!! 😆
