### ISSUE TITLE
Use AbortSignal for timeout in FetchHttpClient implementation

### ISSUE THREAD

**Issue by brettwillis** [stripe/stripe-node#1950]
### Is your feature request related to a problem? Please describe.

The current implementation of `FetchHttpClient` uses `Promise.race()` to reject the promise while not actually cancelling the fetch operation or releasing the underlying resources.

https://github.com/stripe/stripe-node/blob/4dd332f53652b890893e156d24e0410b670d1636/src/net/FetchHttpClient.ts#L65-L94

### Describe the solution you'd like

`Request.signal` is the standard API for cancelling an in-flight fetch request. It is supported by browser implementations, `node-fetch` and Node.js built-in fetch.

### Additional context

I suppose you'd have to rely on an `AbortController` global variable, which is available since Node.js `v14.17.0`, so you'd have to either increase the minimum supported version (currently 12.x) or more likely, fall back to `Promise.race()` if `AbortController` is not available in the global scope.

Happy to help with a PR if you wish.

**Comment by pakrym-stripe** [comment]
@brettwillis I think it's a great idea.

We'd be happy to take a PR for this. We can't drop 12.x support so it'll have to be the fallback option you outlined.
