### ISSUE TITLE
Add Parameter: Status filter to /payouts

### ISSUE THREAD

**Issue by mskenderian** [stripe/stripe-node#1963]
### Is your feature request related to a problem? Please describe.

I use this API and it would be cleaner and less data if /payouts had a parameter to filter out status: paid, in_transit

### Describe the solution you'd like

I would like your team to add this filter in the api.

### Describe alternatives you've considered

Currently i filter out the data myself after the api request.

**Comment by remi-stripe** [comment]
@mskenderian Github issues are limited to bugs an feature requests with the stripe-node SDK itself. This is more an API feature and would be better directed at our support team who can track your ask as a future improvement instead. You can contact them here: https://support.stripe.com/contact
