### ISSUE TITLE
Extend all resources w/ API mode DELETE: stripeMethod del()

### ISSUE THREAD

**Issue by jeff00seattle** [stripe/stripe-node#1970]
### Is your feature request related to a problem? Please describe.

Reviewed https://stripe.com/docs/api, several resources support mode **DELETE** are not extended with **stripeMethod del()** by this module.

### Describe the solution you'd like

Request that all resources that support **create** also support **del (delete)**.

There are **43 resources** extended with **create** stripeMethod.
`find ./src/resources -type f -exec grep -l "create: stripeMethod({method: 'POST'" {} + | wc -l`

[resourses_create.txt](https://github.com/stripe/stripe-node/files/13536486/resourses_create.txt)

Yet, only **7 resources** extended with **del** stripeMethod.
`find ./src/resources -type f -exec grep -l "del: stripeMethod({method: 'DELETE'" {} + | wc -l`

[resourses_delete.txt](https://github.com/stripe/stripe-node/files/13536512/resourses_delete.txt)

### Describe alternatives you've considered
Calling Stripe API via axios.

Reviewed https://stripe.com/docs/api, example of a few resources that support mode **POST** for **create** and mode **DELETE** for **delete**, not addresses by this module:

- https://stripe.com/docs/api/subscriptions/cancel (DELETE)
- https://stripe.com/docs/api/persons/delete
- https://stripe.com/docs/api/terminal/readers/delete

**Comment by remi-stripe** [comment]
@jeff00seattle I think your find command is incorrect and doesn't handle multiple lines maybe? For example you have the Terminal Reader API missing but if you look at its code [here](https://github.com/stripe/stripe-node/blob/master/src/resources/Terminal/Readers.ts#L20-L23) you can see DELETE is part of it, just on multiple lines. 

Similarly, you asked about Person but it doesn't have its own resource. It's nested under Account so the method exists on Account [here](https://github.com/stripe/stripe-node/blob/master/src/resources/Accounts.ts#L51-L54) as `deletePerson()`. And finally for Subscription it is expected as the API method is called `cancel()`. We use DELETE as the operation only for historical reasons.

I'd be surprised if any real method was missing as our SDK is generated automatically from our public openapi spec so for now I'm going to close but if you do find a real API method that is missing from the code please let me know.
