### ISSUE TITLE
previous_attributes on StripeEvent should be typed as Partial

### ISSUE THREAD

**Issue by pakrym-stripe** [stripe/stripe-node#1978]
### Is your feature request related to a problem? Please describe.

Created from https://github.com/stripe/stripe-node/issues/758#issuecomment-1866063063

@hayksaryan

> For me, event.data.previous_attributes is still typed as Stripe.Event.Data.PreviousAttributes.
> I would expect a generic that properly infers Partial<Something> from Stripe.SomethingUpdatedEvent.
> Otherwise, I'm forced to do it like this: event.data.previous_attributes as Partial<Stripe.Subscription>

**Comment by hayksaryan** [comment]
Thanks for the quick turnaround!
