### ISSUE TITLE
Whitespace in header signature

### ISSUE THREAD

**Issue by sepiropht** [stripe/stripe-node#1980]
### Describe the bug

I have problem with the header signature

Note: The provided signing secret contains whitespace. This often indicates an extra newline or space is in the value
t=1703329668,v1=5779e669da40f1b7959bfd3dfae96b719e0bd2a0305d4635dc0707ffcd269aaf,v0=8d51ecdaff236209024226a06c73ec381a35a60c4b1420f28d0b762d0a076e99
❌ Error message: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?

Learn more about webhook signing and explore webhook integration examples for various frameworks at https://github.com/stripe/stripe-node#webhook-signing
I keep seeing this error, withe the ctual nest code copied right from this repo

### To Reproduce

I'm using a nest project where i integrate stripe lib

### Expected behavior

Should valide the header signature

### Code snippets

```JavaScript
@Post('/webhook')
  async webhooks(
    @Headers('stripe-signature') sig: string,
    @Req() req: RawBodyRequest<Request>,
    @Res() res: Response,
  ) {
    let event: Stripe.Event;


    try {
      event = this.stripeService.webhooks.constructEvent(
        req.rawBody,
        sig.trim(),
        process.env.STRIPE_WEBHOOK_KEY,
      );
    } catch (err) {
      // On error, log and return the error message
      console.log(`❌ Error message: ${err.message}`);
      res.status(400).send(`Webhook Error: ${err.message}`);
      return;
    }
``
```

### OS

archlinux

### Node version

v21.4.0

### Library version

12.18.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@sepiropht Github issues are limited to bugs with the SDK and your question is more an integration question better directed at our support team: https://support.stripe.com/contact

To unblock you, the note at the top of the error indicates you have a problem with your webhook endpoint's secret. You need to double check the value or consider using `trim(process.env.STRIPE_WEBHOOK_KEY)` as that's the part that's wrong. Triple check by cleanly logging it to the console

**Comment by sepiropht** [comment]
Thank you @remi-stripe !
