### ISSUE TITLE
Verifying signatures: add hint about line endings

### ISSUE THREAD

**Issue by forgotPassword** [stripe/stripe-node#1981]
### Is your feature request related to a problem? Please describe.

Stripe's uses `\n` in it's payload. If you were to console.log() the raw payload, and paste into say, Postman (on windows at least), you will have a bad time since it uses `\r\n` for new lines, and you will waste a few hours trying to figure out where the problem is (ask me how I know).

**Comment by richardm-stripe** [comment]
Hi @forgotPassword, we 100% want to prevent this trouble for happening for future users. Thank you for reporting this.

Can you help me understand exactly what text you were `console.log`-ing and where you were pasting it with the extra carriage return to cause an error? Right now I'm not certain where the warning you suggest would go.

**Comment by forgotPassword** [comment]
I was just dumping the req.body of the webhook payload, in order to manually/more easily replay it from Postman. The newlines are part of the json payload itself (so there are like 100 of them).

It's more a Postman 'bug' than anything (it seems over the years it switched from \n to \r\n, perhaps OS dependent). https://github.com/postmanlabs/postman-app-support/issues/422

![postman](https://github.com/stripe/stripe-node/assets/3125689/069716ff-e937-4ecf-b72a-7dc600072397)

Right now there is already an error when there is signature mismatch: https://github.com/stripe/stripe-node/blob/master/src/Webhooks.ts#L380

Perhaps also hinting that the payload uses linux line endings by default?

**Comment by pakrym-stripe** [comment]
Opened https://github.com/stripe/stripe-node/pull/1992
