### ISSUE TITLE
Attempt to read property "last4" on null

### ISSUE THREAD

**Issue by fogbreaker** [stripe/stripe-node#1983]
### Describe the bug

Upgraded to Spark 5.0 from Spark 4.0 

### To Reproduce

Create a Subscription, visit billing portal -> code breaks.

### Expected behavior

nullcheck on $paymentMethod->card?->country

### Code snippets

```JavaScript
* @param  \Spark\Billable  $billable

208      * @return array

209      */

210     protected function paymentMethods($billable)

211     {

212         $defaultPaymentMethod = $billable->defaultPaymentMethod();

213 

214         return $billable->paymentMethods()->map(fn (PaymentMethod $paymentMethod) => [

215             'id' => $paymentMethod->id,

216             'last4' => $paymentMethod->card->last4,

217             'brand' => ucfirst($paymentMethod->card->brand),

218             'expiration' => Carbon::createFromDate($paymentMethod->card->exp_year, $paymentMethod->card->exp_month, 1)->format('M Y'),

219             'country' => $paymentMethod->card->country,

220             'default' => $defaultPaymentMethod ? $paymentMethod->id === $defaultPaymentMethod->id : false,

221         ])->toArray();

222     }
```

### OS

macos

### Node version

idk

### Library version

idk

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@fogbreaker Github issues are limited to bugs with the stripe-node SDK itself. This looks more like an integration support question about your code and is better directed to our support team: https://support.stripe.com/contact/email

To unblock you, my guess is that the PaymentMethod you are looking at is not of `type: 'card'` and might be `type: 'link'` for example. You can't access `$paymentMethod->card` if the `type` is not `card` and have to check the value first. See https://stripe.com/docs/api/payment_methods/object for all possible types and properties.
