### ISSUE TITLE
Update documentation to not use promise anti-pattern

### ISSUE THREAD

**Issue by toymachiner62** [stripe/stripe-node#199]
Looking at the documentation for handling promise errors, you're showing what is an anti-pattern according to the bluebird documenation https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-thensuccess-fail-anti-pattern

The documentation should be updated to reflect current best practices.

**Comment by kyleconroy** [comment]
Thanks! I've fixed the README.
