### ISSUE TITLE
Expandable object types used in webhooks instead of strings

### ISSUE THREAD

**Issue by ps2-controller** [stripe/stripe-node#2003]
### Describe the bug

Example handling of setup intent complete:
```
          case 'setup_intent.succeeded': {
            const setup_intent = event.data.object;
            const customer_id = setup_intent.customer;
            if (!customer_id) {
              break;
            }
            await stripe.customers.update(customer_id, {
              invoice_settings: {
                default_payment_method: setup_intent.payment_method
              }
            });
          }
...
```

`event.data.object` is of type `SetupIntentSucceededEvent`
```
    namespace SetupIntentSucceededEvent {
      interface Data extends Stripe.Event.Data {
        object: Stripe.SetupIntent;
      }
    }
```
which includes
```
      customer: string | Stripe.Customer | Stripe.DeletedCustomer | null;
```

However, per [this issue](https://github.com/stripe/stripe-node/issues/939) objects in webhooks are not expandable (and probably never should/will be), so the type definition shouldn't include Customer or DeletedCustomer types.

I'm just posting this issue to confirm that the recommended way to handle this is to typecast the objects returned by Stripe?
```
          case 'setup_intent.succeeded': {
            const setup_intent = event.data.object;
            const customer_id = setup_intent.customer;
            if (!customer_id) {
              break;
            }
            await stripe.customers.update(String(customer_id), {
              invoice_settings: {
                default_payment_method: String(setup_intent.payment_method)
              }
            });
...
```

Just wanted to make sure I'm not misunderstanding / there is no way these can _actually_ come back as objects before I do so. 

Thanks!

### To Reproduce

1. Set up a webhook handler for Stripe in a .ts file
2.  Construct the event
```
      try {
        const event: Stripe.Event = stripe.webhooks.constructEvent(
          rawBody,
          signature as string, // TypeScript needs an assertion here
          process.env.STRIPE_WEBHOOK_ENDPOINT_SECRET as string
      );
```
3. check the type of the `event.data.object` - type definition includes expandability, requiring additional custom handling on the user's end.

### Expected behavior

The `event.data.object` types generated by `stripe.webhooks.constructEvent` should not include object types where expandable (such as Customer) - because these types are not received in the webhook object, and require additional custom validation by the user. 

### Code snippets

```JavaScript
Included above
```

### OS

macOS

### Node version

18.12.1

### Library version

14.7.0

### API version

2023-10-16

### Additional context

This isn't a big issue for me; just mostly wanted to confirm that my workaround is the recommended one, and there's no situations where I might actually receive an object that I'm unaware of.

**Comment by remi-stripe** [comment]
@ps2-controller Thanks for the thorough write up and your understanding is correct! We've discussed before having more specific types such as in https://github.com/stripe/stripe-node/issues/1999 and https://github.com/stripe/stripe-node/issues/1999. Unfortunately this would make the types in the SDK quite complex so we aren't planning to change this for now. Your workaround is the best approach
