### ISSUE TITLE
Change a price

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [stripe/stripe-node#2008]
### Describe the bug

Dear all,

I cannot find any way to contact the support so I am inquiring here. How do I change a price in the dashboard? I cannot really understand it from the UI

<img width="1163" alt="Screenshot 2024-01-28 at 14 48 07" src="https://github.com/stripe/stripe-node/assets/15908060/39568336-6c96-4b6a-a21f-bba64bcd3419">

Thanks a lot,

Fra

### To Reproduce

n/a

### Expected behavior

n/a

### OS

macOS

### Node version

n/a

### Library version

n/a

### API version

2022-11-15

**Comment by remi-stripe** [comment]
You can contact support here: https://support.stripe.com/contact
Sorry we can't really help with Dashboard support question here but they will help you there!
