### ISSUE TITLE
Stripe accounts.createCard not working in Nodejs

### ISSUE THREAD

**Issue by mhinostroza** [stripe/stripe-node#201]
I'm trying to create a card for an account ... but not working.
In the console I see that the method is "undefined"
Other methods that I use are perfect ... it could be?

Thanks

**Comment by kyleconroy** [comment]
@mhinostroza there is no `accounts.createCard`. For accounts, you'll want to use the `createExternalAccount` method instead.

```js
stripe.accounts.createExternalAccount({ACCOUNT_ID}, {
  external_account: {TOKEN_ID}
});
```
