### ISSUE TITLE
stripe events resend support in stripe-node

### ISSUE THREAD

**Issue by cleve-fauna** [stripe/stripe-node#2015]
### Is your feature request related to a problem? Please describe.

I am building automated dead letter replay for stripe events. We have several processes that rely on stripe event delivery to function correctly.

Ideally, I would like to regularly check for undelivered events and automatically send them for replay while also monitoring the undelivered queue size.

With the CLI this is a cinch with a combo of the `events list` and `events resend` commands; but the stripe-node package does not support resend:

https://github.com/stripe/stripe-node/blob/master/src/resources/Events.ts

### Describe the solution you'd like

I would like the stripe-node library to support an events.resend API analogous to what the CLI has.

### Describe alternatives you've considered

I have several workarounds open to me:

- I can call our webhook directly with REST
- I can build this tooling with the CLI.

Having it in node-js would be more convenient however, as we have other integrations built with the node-js package in a single application and our operational monitoring would be easy to bake in.

### Additional context

Main context is automated replay of dead letter webhook events.

**Comment by remi-stripe** [comment]
@cleve-fauna I don't think we would add this in the near future at least. This kind of tooling is better built inside the CLI (or the Dashboard) as one-offs. I do agree it's an interesting feature request but it'd need to be supported in the API first and then would automatically be in the stripe-node SDK (and other SDKs). I'd recommend flagging that feature request to our support team who tracks all API feature requests: https://support.stripe.com/contact

The problem with "resend" is that you could cause issue on other WebhookEndpoints that are listening for it. We could ask for the WebhookEndpoint id but then when Connect gets involved it's trickier.

My advice to developers is to build their own retry mechanism internally where you can retrieve the Event in the API with its exact JSON payload and then process it as you would in your webhook endpoint's code. Definitely a bit trickier when systems are separate though. I assume that's what you meant with your first alternative.

**Comment by richardm-stripe** [comment]
See https://github.com/stripe/stripe-java/issues/1557 for some related discussion.

**Comment by cleve-fauna** [comment]
> The problem with "resend" is that you could cause issue on other WebhookEndpoints that are listening for it. We could ask for the WebhookEndpoint id but then when Connect gets involved it's trickier.

Yes, specifying a webhook endpoint would be ideal. There are only certain members of our webhooks that need this replay, for example.

Thanks for getting back so quickly. Makes sense its not fast if you are automating your SDKs. We can use one of the alternatives no issue; so consider this food for thought on improved UX. I will move to the place you suggested.
