### ISSUE TITLE
Invoice is always empty

### ISSUE THREAD

**Issue by sayem314** [stripe/stripe-node#2019]
### Describe the bug

When using the below code I get this empty data array:

```js
{
  object: 'list',
  data: [],
  has_more: false,
  url: '/v1/invoiceitems'
}
```

### To Reproduce

```ts
import Stripe from "stripe";

export const stripeAdmin = new Stripe(process.env.STRIPE_SECRET_KEY!);

export const getCustomerInvoices = async (customer_id: string) => {
  const invoices = await stripeAdmin.invoices.list({ customer: customer_id, limit: 20 });
  return invoices;
};
```

### Expected behavior

In Stripe test dashboard I can see 5 invoices from same customer (it's a test account):

![image](https://github.com/stripe/stripe-node/assets/14138401/dcdb5855-f591-473f-b5d4-00e741534122)

### OS

Linux

### Node version

v20.10.0

### Library version

stripe 14.16.0

### API version

Not using this

**Comment by remi-stripe** [comment]
@sayem314 Github issues are limited to bugs with the stripe-node SDK itself. Your ask is an integration support question, better directed at our support team instead: https://support.stripe.com/contact

To unblock you though I can tell you that you seem to mix up multiple concepts together. Your bug report started with showing the response for the List InvoiceItems [API](https://stripe.com/docs/api/invoiceitems/list) but then immediately share the code for the List Invoices [API](https://stripe.com/docs/api/invoices/list). Those are completely separate APIs. The first one list InvoiceItems which are objects you create to add lines to an Invoice, while the second call lists Invoices. 
Similarly, the screenshot in the Dashboard is for one-time payments and completely separate from Invoices. An Invoice can cause a one-time payment but the reverse is not true as many one-time payments can be taken without an Invoice being issued. I highly recommend watching [this video](https://www.youtube.com/watch?v=CUAY6IQcVQM) that describes the various objects that exist in our API related to payments.

What you likely want instead is the List PaymentIntents [API](https://stripe.com/docs/api/payment_intents/list).
