### ISSUE TITLE
Bitcoin charge fails when using application fee

### ISSUE THREAD

**Issue by iamaro** [stripe/stripe-node#202]
I have a connect application and am trying to allow users to sell files for bitcoin in addition to credit cards.

When I try to charge with the application_fee parameter / connect user id, the charge fails. When I charge the bitcoin token directly it works.

Is there some other way I should be approaching this or does bitcoin not work with connect applications yet?

I'm using stripe checkout on the frontend. The error it's failing with on the backend is 'No such token'

**Comment by matthewarkin** [comment]
This will happen if you use your publishable key to create the bitcoin receiver as opposed to using the connected account's publishable key. A bit of a weird limitation / quirk.

**Comment by iamaro** [comment]
Is there any downside to using the connected accounts publishable key for every charge on stripe checkout? I can send the tokens the same way and collect fees and everything, correct?

**Comment by matthewarkin** [comment]
yep, the only downside is your front end needs to be using the right key and now you have to charge directly to that connected account (which you're doing anyways)

**Comment by iamaro** [comment]
Okay great! Thanks a lot for your help!
