### ISSUE TITLE
invoice.will_be_due event is missing in webhook events types

### ISSUE THREAD

**Issue by larryro** [stripe/stripe-node#2024]
### Describe the bug

![image](https://github.com/stripe/stripe-node/assets/5787117/4ab6f4b3-7a8d-46f9-9524-cc51cf638bc4)

![image](https://github.com/stripe/stripe-node/assets/5787117/4a96319e-ecd6-435d-a92d-06427c79dd39)

### To Reproduce

**See:** https://docs.stripe.com/api/events/types

### Expected behavior

including the **InvoiceWillBeDueEvent** type

### OS

linux mint

### Node version

node v20.11.1

### Library version

stripe-node 14.17.0

### API version

2023-10-16

**Comment by pakrym-stripe** [comment]
Thank you for the report! This is a bug and we'll work on adding the event type to the SDKs.

**Comment by CptJJ** [comment]
Invoice.overdue is also missing!

**Comment by anniel-stripe** [comment]
Thanks for flagging @CptJJ ! I've raised the missing `invoice.overdue` type internally as well

**Comment by dkrsorenson** [comment]
@pakrym-stripe @anniel-stripe Hello! I was wondering if there are any updates on when this and the `invoice.overdue` events might be added to the Stripe library?

**Comment by prathmesh-stripe** [comment]
@dkrsorenson Thanks for reaching out again. We are still working on it and this should be available soon.

**Comment by dkrsorenson** [comment]
@prathmesh-stripe Thank you for the update!

**Comment by helenye-stripe** [comment]
This is resolved as of https://github.com/stripe/stripe-node/releases/tag/v16.5.0.
