### ISSUE TITLE
Api feature: Credit notes - filter by date

### ISSUE THREAD

**Issue by florianbepunkt** [stripe/stripe-node#2031]
### Is your feature request related to a problem? Please describe.

Working on an accounting solution, we need to get invoices and credit notes for a given date range. While it is possible to list invoices for a given range, this is not possible for the credit notes endpoint. I believe this is a valid use case and currently there is no way to get e. g. all credit notes creates in September 2023.

### Describe the solution you'd like

Add the same created query params as for the invoices endpoint.

### Describe alternatives you've considered

Starting from the present and then go back via pagination, but this is highly inefficient.

**Comment by remi-stripe** [comment]
@florianbepunkt Github issues are limited to bugs or feature requests with the SDK itself. Your ask is a feature request for the API and needs to be reported to our support team: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
@florianbepunkt Afer I shared this feedback with the product team, they were able to prioritize it quickly and have now shipped the feature. You can see it in the API Reference [here](https://docs.stripe.com/api/credit_notes/list#list_credit_notes-created). We'll add it to the SDK at the end of the week but you should already be able to use it!

**Comment by florianbepunkt** [comment]
@remi-stripe Much appreciated. Works like a charm.
