### ISSUE TITLE
Please pull through 'active' value on subscriptions, rather than putting it in a string as 'status' where that status can be overwritten by other values

### ISSUE THREAD

**Issue by Steadyon** [stripe/stripe-node#2034]
### Is your feature request related to a problem? Please describe.

I'm annoyed that the Subscription object does not have a simple, clear way to see that a subscription is currently active. If you have a subscription with a trial period, 'trialing' overwrites the 'active' status, making it a useless field for determining that. All of the other statuses can override 'active' and don't tell you whether or not the subscription is active. 

### Describe the solution you'd like

There is a field on the actual Stripe API requests, literally called 'active', that for some reason was not included. This should be pulled through.

### Describe alternatives you've considered

The implementation you're forced to do is multiple comparisons to values and what their meaning is presumed to be, or to pull the whole response as an object and index it yourself.

**Comment by remi-stripe** [comment]
Hey @Steadyon! Github issues are limited to bugs or feature requests with the stripe-node SDK itself. Your ask is more a product feature request for the API better directed at our support team instead: https://support.stripe.com/contact

I can share my opinion on this overall though. The way you view a Subscription is "active" seems different to what other developers would look at. Many would say that a trialing Subscription for example is not active. I don't see us adding such a top-level property in the future and we think the `status` or `canceled_at` is enough to differentiate what is and isn't active based on your business preferences.
