### ISSUE TITLE
Resolution for worker and other modules fails

### ISSUE THREAD

**Issue by manzoorwanijk** [stripe/stripe-node#2037]
### Describe the bug

If you try to use `import Stripe from 'stripe/worker';`, it throws an error, `Cannot resolve dependency 'stripe/worker'`

There are also some other TS types problems - https://arethetypeswrong.github.io/?p=stripe%4014.20.0

### To Reproduce

- Goto https://codesandbox.io/p/devbox/jdxrrc
- Run `npm run build`
- See the error 

### Expected behavior

The module should resolve correctly

### Code snippets

```JavaScript
import { Stripe } from "stripe/worker";

export const stripe = new Stripe("key_here", {
  appInfo: {
    name: "stripe-samples/link-with-stripe",
    version: "0.0.1",
    url: "https://github.com/stripe-samples/link-with-stripe",
  },
});
```

### OS

macOS

### Node version

v18.19.0

### Library version

^14.20.0

### API version

2023-10-16

**Comment by anniel-stripe** [comment]
Hi! `import Stripe from 'stripe/worker';` is not a supported way of importing from Stripe. stripe does not export any submodules (see our [package.json export map](https://github.com/stripe/stripe-node/blob/master/package.json)). We do export a different version of the package in `worker` environments, but the import shouldn't need changing.

**Comment by anniel-stripe** [comment]
For the types issues, can you provide more details? I went to https://arethetypeswrong.github.io/?p=stripe%4014.20.0 but am not sure what to look for.

**Comment by ramya-stripe** [comment]
Hey @manzoorwanijk 

Is the types issue of [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) causing any problems in your integration at the moment?

**Comment by manzoorwanijk** [comment]
> Is the types issue of [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) causing any problems in your integration at the moment?

No

**Comment by ramya-stripe** [comment]
In that case, we will close this issue and add the investigation of that issue to our backlog
