### ISSUE TITLE
Cannot access LatestApiVersion type in Typescript

### ISSUE THREAD

**Issue by paul-uz** [stripe/stripe-node#2041]
### Describe the bug

`LatestApiVersion` is exported as a type, but I cannot seem to be able to access it

### To Reproduce

1. create new Stripe instance
2. try to use `LatestApiVersion` for `apiVersion`

### Expected behavior

1. Can import `LatestApiVersion` as a type

### OS

macOS 14.1.1

### Node version

20

### Library version

14.21.0

### API version

latest

**Comment by ramya-stripe** [comment]
Hey @paul-uz 

I just tried out the latest stripe package.
Am able to import the type just fine...

![Screenshot 2024-03-19 at 2 50 48 PM](https://github.com/stripe/stripe-node/assets/100975018/7a9298f8-a43e-4ab7-bf8d-a304ca223522)

**Comment by ramya-stripe** [comment]
Hey @paul-uz 

We will be closing this issue as there are no action items here.
