### ISSUE TITLE
Export StripeError class

### ISSUE THREAD

**Issue by alko89** [stripe/stripe-node#2044]
### Is your feature request related to a problem? Please describe.

I'm not sure then this was changes. I'm trying to update my code to the latest stripe version and update API. Currently I'm on `11.6.0` and would like to bump to `14.21.0` and API version `2023-10-16`.

I have a nest.js app where I use the error filter middleware to catch potential Stripe errors, seems like the new version doesn't export the `StripeError` class anymore:

```typescript
import { ArgumentsHost, Catch, ExceptionFilter } from '@nestjs/common';
import { Response } from 'express';
import { StripeError } from 'stripe/lib/Error';

@Catch(StripeError)
export class StripeErrorFilter implements ExceptionFilter {
  catch(exception: StripeError, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();

    response.status(exception.statusCode).json({
      name: exception.code,
      message: exception.message,
    });
  }
}
```

### Describe the solution you'd like

Export `StripeError` to allow catching Stripe errors thrown inside the library.

### Describe alternatives you've considered

Remain on the old version.

**Comment by pakrym-stripe** [comment]
In the latest version of the library, you can reference the error type via `Stripe.errors.StripeError`.

**Comment by alko89** [comment]
Perfect! Seems to be just what I need. Thanks @pakrym-stripe
