### ISSUE TITLE
Thoughts on ES6 Refactor?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-node#205]
Would the maintainers of this module appreciate an ES6 refactor using Babel (transpile on `prepublish` since not everyone is on Node 4.x.x though it's LTS now)? I'd love to help out by sending PRs for that if of interest. It would not have any significant negative performance implications since we'd transpile via Babel and not use ES6 directly through V8, which hasn't all been optimized yet.

Some features this codebase would benefit a lot from include:
* Arrow functions
* String templating
* Enhanced object literals (notably the `foo` shorthand for `foo: foo` and setting proto right when defining an object literal)
* Destructuring syntax
* Modules (import/export wrapper over CommonJS- not a new loader)
* Promises (since it seems not many Bluebird-specific functions are used)
* Default function parameters

**Comment by kyleconroy** [comment]
My gut feeling is that we should wait on an ES6 refactor. While there are many features that would be nice, adding features to the library today is quite easy. I think if (and when) we do a larger refresh of this library, that refresh will use ES6.

**Comment by tejasmanohar** [comment]
Gotcha, @kyleconroy... if that is on a branch or anything like that, would love to help :)

The good part about an ES6 refactor is you don't have to refactor everything- working in the same language, all backwards-compatible. Can introduce feature by feature to just improve certain parts of the code.

**Comment by kyleconroy** [comment]
I think the transpiling step adds too much complexity at this stage. We'll eventually move to that world, but I don' think we're ready for it just yet.

**Comment by tejasmanohar** [comment]
@kyleconroy Fair, and maybe a year or two down the line, that won't be required since Node 4.x.x (already LTS) and 5.x.x will become a standard just like 0.10+ is today.

**Comment by SlexAxton** [comment]
I think I agree. I feel comfortable doing some things in ES6 right now, but the node community hasn't really fully come over yet, so I'll close this for the time being, but mark your calendar to ask us again in a year? Happy to take it on when it's beneficial.

Thanks!

**Comment by tejasmanohar** [comment]
Agreed, and sure thing!
