### ISSUE TITLE
stripe.checkout.sessions.create(params) stopped working between Next.js 14.1.0 and 14.1.4

### ISSUE THREAD

**Issue by ishaangandhi** [stripe/stripe-node#2063]
### Describe the bug

I get this error:

```
Internal error: Error: Missing required param: success_url.
    at StripeError.generate (./node_modules/stripe/esm/Error.js:23:20)
    at res.toJSON.then._Error_js__WEBPACK_IMPORTED_MODULE_0__.StripeAPIError.message (./node_modules/stripe/esm/RequestSender.js:109:82)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### To Reproduce

create a checkout session:

```

  const params: Stripe.Checkout.SessionCreateParams = {
    allow_promotion_codes: true,
    subscription_data: {
      trial_settings: {
        end_behavior: {
          missing_payment_method: "cancel",
        },
      },

      trial_period_days: 14,
    },
    payment_method_collection: "if_required",
    customer,
    mode: "subscription",
    line_items: [
      {
        price: process.env.STRIPE_SUBSCRIPTION_PRICE,
        quantity: 1,
      },
    ],
    cancel_url: getURL(),
    success_url: getURL(),
  };
  console.log("Making checkout session...");
  // Create a checkout session in Stripe
  const session = await stripe.checkout.sessions.create(params);
```

### Expected behavior

Successfully create the session. This worked before upgrading to Next.js 14.1.4.

### OS

macOS

### Node version

v21.6.2

### Library version

14.21.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@ishaangandhi my guess is that your `getURL()` is not working or returning an empty string. I'd recommend properly logging the parameters first and confirming that's the issue

**Comment by ishaangandhi** [comment]
No, it does have a string (I logged that.)

**Comment by remi-stripe** [comment]
I'm going to need more details to reproduce, I don't fully get what Next.js has to do with the overall issue here. Is this a typing error where the request never get even sent, or is the error returned by our Stripe API? Do you have an easy way to repro this end to end?

**Comment by ishaangandhi** [comment]
> Is this a typing error where the request never get even sent, or is the error returned by our Stripe API? 

I don't know. All I see is what stripe library printed in the console from the error it threw. I pasted that in the original ticket.

> Do you have an easy way to repro this end to end?
Do you work for Stripe? Is there a way I can enable telemetry for the app? If not, maybe just make a next.js 14.1.4 app with the snippet I included.

**Comment by remi-stripe** [comment]
Yes I work for Stripe! I'm asking for your help reproducing this quickly in Next.js which I don't use so I can figure out what's going on. We (Stripe) haven't changed anything in the SDK itself that we think could cause this, the API hasn't changed, `success_url` is still required if you don't pass `ui_mode: 'embedded'`

**Comment by ishaangandhi** [comment]
I was making a reproduction repo, when I found what I think is the source of the bug. It looks like sometimes the URL being created is a promise. I will report the issue to the Next.js team.

I think the error message printed by the Stripe API is misleading enough to be a bug. A better message would be:

```
[success_url] and [cancel_url] expected to be [string].
Got: [Promise].
```

**Comment by ishaangandhi** [comment]
Thanks!

**Comment by brendanm-stripe** [comment]
Ah glad you figured this out, and that makes sense with the possible-unresolved URL. I was able to spin up a quick next.js example to try to repro this and used static strings for the success/cancel URLs without encountering this.

Agree that if the behaviour is unexpected you should file with the next.js team.

In the interim, you should probably add an `await` on that `getUrl` and use the returned value:

```
const someUrl = await getUrl()`
...
    cancel_url: someUrl,
    success_url: someUrl,
...
```
