### ISSUE TITLE
Unnecessary dependency @types/node in non dev dependency

### ISSUE THREAD

**Issue by Dmitriyx** [stripe/stripe-node#2066]
### Describe the bug

viewing the latest version of stripe, there is a **types** on a **dependency** level instead of **devDependency** - so on production install, the types are still installed and taking up extra space (about 2.5MB+) that is not needed in production builds.
Reference: https://www.npmjs.com/package/stripe?activeTab=dependencies

### To Reproduce

1) add stripe as a dependency, ex: npm install stripe@latest
2) install production build, ex: npm install --production
3) view node modules folder and inspect size of @types+node directory

### Expected behavior

expected not to have types required in non dev dependency environments.
expected to have types found in dev dependency list instead of regular dependency list

### OS

windows 10 

### Node version

Node v21

### Library version

stripe@latest

### API version

latest

### Additional context

If this is fixed, it will save money on infrastructure costs because it is an unnecessary dependency because type inference is not needed during runtime.

_No response_

**Comment by richardm-stripe** [comment]
Hello @Dmitriyx, thank you for writing in.

We investigated this before in https://github.com/stripe/stripe-node/issues/1274 and ultimately concluded that, if we moved @types/node to devDependencies it would make typescript users unable to properly consume the types we define in stripe-node. This might be worth re-visiting as you are not the first user to suggest that this is wrong but I don't think it will be as simple as moving the dependency to devDependencies.
