### ISSUE TITLE
id type does not exist on SourceTransaction.PaperCheck

### ISSUE THREAD

**Issue by emilyhou** [stripe/stripe-node#2075]
### Describe the bug

Although the event for `source.transaction.update` provides an ID for the paper check if the transaction is a paper check transaction, the type does not include `id` under `PaperCheck`. So we get an error when trying to access the ID to store in our systems for bookkeeping purposes.

https://github.com/stripe/stripe-node/blob/master/types/SourceTransactions.d.ts#L155-L165

### To Reproduce

1. Fetch a `source.transaction.update` event with `payment_method_details.type` as `paper_check`
2. See that the `event.data.object.paper_check` object has `id` as a field
3. However, casting the event to `Stripe.SourceTransaction` and getting `paper_check` shows that the `Stripe.SourceTransaction.PaperCheck` type does not contain `id`, it only contains the other two fields, so ID is not accessible in TS.

### Expected behavior

Should be able to `.id` on `paper_check`.

### Code snippets

```JavaScript
const { id, source, status, paper_check } = event.data
        .object as Stripe.SourceTransaction;
const checkId = event.data.object.paper_check.id;
```

### OS

macOS

### Node version

Node v18

### Library version

15.4.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@emilyhou The PaperCheck payment method is in private beta so the types aren't as complete unfortunately. In theory they shouldn't even be in the SDK itself until the API feature is publicly released though that one slipped through a few years ago and we didn't remove them.
We'll look into fixing this in the future but it's unlikely to happen soon so you might need to suppress the TS error to use it in your code.
