### ISSUE TITLE
update typescript interface to include v15.0.0 changes (features => marketing_features)

### ISSUE THREAD

**Issue by HaruMiyaGi** [stripe/stripe-node#2081]
### Describe the bug

I use inbuilt types from the Stripe library, the interface for Product still has the old 'features' instead of the new 'marketing_features' which been introduced in v15.

### To Reproduce

1. Import Product interface from the 'stripe' library
2. try to access product.marketing_features.

throws a type error.

```ts
const prd: Stripe.Product = ....

console.log(prd.marketing_features) // <- type error
```

### Expected behavior

works correctly

### OS

Win10

### Node version

v20.9.0

### Library version

latest

### API version

2022-08-01

**Comment by remi-stripe** [comment]
@HaruMiyaGi The types are generated automatically from our openapi spec and should already be up to date. You can see they are defined in the code [here](https://github.com/stripe/stripe-node/blob/master/types/Products.d.ts#L84) as expected. You are either using external/third-party types (like DefinitelyTyped) or using an older version I would say.

**Comment by HaruMiyaGi** [comment]
> @HaruMiyaGi The types are generated automatically from our openapi spec and should already be up to date. You can see they are defined in the code [here](https://github.com/stripe/stripe-node/blob/master/types/Products.d.ts#L84) as expected. You are either using external/third-party types (like DefinitelyTyped) or using an older version I would say.

yes, did an `rm -rf ./node_modules/` and a fresh install, this fixed it. thank you!
