### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-node#209]
Two recommendations-
* [ESLint](http://eslint.org/) w/ rules that match the current code style as closely as possible so the diff is small
* Something like [Standard](https://github.com/feross/standard), which gives you a suggested code style / rules to follow (ironically, they're not very "standard").

Usually, if organizations I've worked with have an in-house style guide or are pretty consistent throughout projects, I've seen them like ESLint more... but I'd love to PR either :)

**Comment by kyleconroy** [comment]
Standard is going to be a non-starter (no semi-colons, really?). We use JSCS internally, so we'll probably go with that instead of ESLint.

**Comment by tejasmanohar** [comment]
Oh I see, nice, and yeah, Standard is a bit odd; lots of people seem to like it though I don't use it in my own projects just because it's actually very non-standard.

Want a PR for that? Or, I guess if JSCS is used internally, you guys already have a configuration.

**Comment by kyleconroy** [comment]
No need for a PR. Once I have the JSCS file, I'll go ahead and add it to the repository and see what needs to be changed.

**Comment by tejasmanohar** [comment]
:+1:
