### ISSUE TITLE
Add dashboard-visible Radar results to SetupIntent or SetupAttempt

### ISSUE THREAD

**Issue by VitaminTussle** [stripe/stripe-node#2097]
### Is your feature request related to a problem? Please describe.

My company applies Charges to saved Cards/PaymentMethods well after accepting payment information. Currently, we set those PaymentMethods up using SetupIntents, and while the Stripe dashboard shows the risk score and risk level under the "Risk evaluation" label as shown below, that information is not currently exposed to the API at the time of SetupIntent creation. We would like to internally notify our fraud team depending on the potential risk level at the time of PaymentMethod creation, but are currently unable to access that information in code.
<img width="560" alt="image" src="https://github.com/stripe/stripe-node/assets/56012328/2f6d4c52-04bb-44d8-a99a-222288e4e3ff">

### Describe the solution you'd like

This is a request URL I found via the Network tab of the devtools window while on the Stripe dashboard page shown in the problem section: `https://dashboard.stripe.com/v1/setup_intents/seti_[ID_SANITIZED]?expand%5B%5D=customer&expand%5B%5D=payment_method&expand%5B%5D=latest_attempt&expand%5B%5D=mandate`

Within the resulting expanded `latest_attempt` object in the response, the following property is included:
```json
"radar_results": {
  "risk_level": "elevated",
  "risk_score": 62
}
```

I cannot currently expand the `latest_attempt` property via the SetupIntent API beyond getting its ID, and even when the SetupAttempt object is fetched separately, the `radar_results` data is not included, even when targeted with the `expand` prop. I would like to see the `radar_results` information included on either the response from the creation of the SetupIntent, or on the fetch of the SetupAttempt.

### Describe alternatives you've considered

The only alternatives I've been able to find are to either completely shift our payment cycle to be able to charge customers immediately with Charge objects, which isn't very feasible at our scale, or to scrape the Stripe dashboard, which just seems excessive.

**Comment by remi-stripe** [comment]
@VitaminTussle This is a feature request for the API and is better directed at our support team who tracks all those requests instead. Please contact them here: https://support.stripe.com/contact for 1:1 help.

**Comment by VitaminTussle** [comment]
Thanks @remi-stripe. Appreciate the redirect. Here's hoping they're as responsive.
