### ISSUE TITLE
Cannot create new `default_for_currency` bank account

### ISSUE THREAD

**Issue by jrf0110** [stripe/stripe-node#213]
I'm actually not sure if this is a stripe-node issue, a stripe api issue, or just a user error, but help is appreciated either way.

I'm having trouble creating new bank accounts and having them be the default for the currency (see https://stripe.com/docs/api/node#create_bank_account).

To see what's going on, I `console.log`'d in StripeResource.js inside the `_request` method (https://github.com/stripe/stripe-node/blob/master/lib/StripeResource.js#L177)

```javascript
console.log(method, path, data);
```

When I create a new account, I see the following output:

```javascript
POST /v1/accounts/acct_16CZlbImWewFwddn/external_accounts { external_account:
   { object: 'bank_account',
     country: 'US',
     currency: 'usd',
     default_for_currency: true,
     account_number: '000123456789',
     routing_number: '110000000' } }
```

__Result__

```javascript
{ id: 'ba_176RkwImWewFwddnmngsK5iK',
  object: 'bank_account',
  account: 'acct_16CZlbImWewFwddn',
  bank_name: 'STRIPE TEST BANK',
  country: 'US',
  currency: 'usd',
  default_for_currency: false,
  fingerprint: 'NIcgUrofMfKbLrJr',
  last4: '6789',
  metadata: {},
  routing_number: '110000000',
  status: 'new' }
```

According to the Stripe API docs, this new account should be set to the default for `usd`.

> If you set this to true (or if this is the first external account being added in this currency) this bank account will become the default external account for its currency.

Thoughts?

**Comment by remistr** [comment]
@jrf0110 the issue here is that you're passing `default_for_currency` inside the `external_account` hash instead of on the same level. You need to modify your code to look like this:

```stripe.accounts.createExternalAccount(
  "acct_XYZ",
  {
    external_account: "tok_XYZ",
    default_for_currency: true
  },
  function(err, bank_account) {
    // asynchronously called
  }
);```

**Comment by jrf0110** [comment]
d'oh! Thanks @remistr! User error indeed
