### ISSUE TITLE
Connect Account Payout object does not contain stripe account payment intent or charge obj id.

### ISSUE THREAD

**Issue by mnadeem9** [stripe/stripe-node#2135]
### Describe the bug

When working with Stripe Connect, the Payout object for a connected account does not contain direct references to the original PaymentIntent or Charge object IDs from the platform account. This omission creates a challenge in tracking and associating payouts with specific payment intents or charges. The primary issue here is the difficulty in establishing a clear linkage between payouts and the originating transactions (PaymentIntents or Charges) that triggered those payouts.

Current Behavior
Payout Object: The Payout object retrieved for a connected account contains various details such as the amount, currency, status, and timing information, but lacks direct references to the original PaymentIntent or Charge object IDs from the platform account.

### To Reproduce

1. Create a payment intent with direct charges ( Save the paymentIntent Id)
2. Capture the payment intent (Receive back Charge Object, save the chargeId)
3. Stripe sends a payout webhook after 2 days, which contains the payout object (save the PayoutId)
4.  Now how will developer know payout is for which charge or paymentIntentId

### Expected behavior

The expected behavior is that the Payout object for a connected account should include direct references to the original PaymentIntent or Charge object IDs from the platform account. This enhancement would streamline tracking and reconciliation processes, allowing developers to easily correlate payouts with their corresponding payments.

Proposed Enhancements:
Include Source Payment IDs: The Payout object should include fields for source_payment_intent_id and source_charge_id, referencing the originating PaymentIntent and Charge object IDs from the platform account.
Enhanced Metadata: Automatically propagate relevant metadata from the PaymentIntent or Charge to the Payout object, ensuring key transaction details are available at every step.

### Code snippets

```JavaScript
paymentIntent = await StripeService.getInstance().capturePaymentIntent(serviceRequestModel._paymentIntentId);


async capturePaymentIntent(paymentIntentId: string) {
     const paymentIntent = await this.stripeObj.paymentIntents.capture(paymentIntentId, { expand: ["transfer"] });
    return paymentIntent;
  }

Payout Object received:
{
  "id": "po_1PXv6KPRgxGiFXI3WU2PjfBs",
  "object": "payout",
  "amount": 67300,
  "application_fee": null,
  "application_fee_amount": null,
  "arrival_date": 1719878400,
  "automatic": true,
  "balance_transaction": "txn_1PXv6KPRgxGiFXI325Sd5681",
  "created": 1719882104,
  "currency": "usd",
  "description": "STRIPE PAYOUT",
  "destination": "ba_1OvPF5PRgxGiFXI3MZbVjiod",
  "failure_balance_transaction": null,
  "failure_code": null,
  "failure_message": null,
  "livemode": false,
  "metadata": {},
  "method": "standard",
  "original_payout": null,
  "reconciliation_status": "completed",
  "reversed_by": null,
  "source_type": "card",
  "statement_descriptor": null,
  "status": "paid",
  "type": "bank_account"
}
```

### OS

macOS

### Node version

v18.17.0

### Library version

"stripe": "^14.20.0",

### API version

2023-10-16

### Additional context

Most of the time , end users are more interested in knowing whether the amount is credited in there bank accounts rather than there connected account on stripe.
Specially for the use case when a platform is handling connected account (Custom) stuff.
In my case connected account for end user is created by platform. I am also using destination charges , example charging user 100$ and specifying 90$ should go to other user connected account.
10$ for strip fees and platform itself.

**Comment by remi-stripe** [comment]
@mnadeem9 Github issues are limited to bugs with the stripe-node SDK itself and this is more an integration support question better directed to our support team: https://support.stripe.com/contact. You can also talk to Stripe developers on Discord to ask questions like this instead: https://stripe.com/go/developer-chat

To unblock you though, the behaviour you describe is expected and is no different with or without Connect. When a Payout is created, it doesn't just include one transaction and instead bundles all the transactions/money movements that were released on that day. For some businesses it could be millions of transactions.
The way to do reconciliation is to use the List BalanceTransactions API and pass `payout: 'po_123'` to see all the BalanceTransactions that were bundled into that Payout. We document this in details in [this page](https://docs.stripe.com/expand/use-cases#charges-in-payout) where we explain our Expand feature. With Connect, it works the same but you have to expand deeper to go back to the original transactions in the platform which our support team can help you with if you have follow up questions.
