### ISSUE TITLE
`plan` is missing on `Stripe.Subscription` type

### ISSUE THREAD

**Issue by jlengstorf** [stripe/stripe-node#2139]
### Describe the bug

The `Stripe.Subscription` type does not match the data returned from `stripe.subscriptions.retrieve()`.

### To Reproduce

```ts
import Stripe from 'stripe';

const stripe = new Stripe(import.meta.env.STRIPE_SECRET_KEY!);

// ... in a function
const subscription = await stripe.subscriptions.retrieve(subscriptionId);
const productId = subscription.plan.product;
/*                             ^^^^
                               TS error that plan doesn't exist on 
                               Stripe.Subscription, but it exists */
```

### Expected behavior

The `plan` data is present, so the type should reflect that.

### OS

macOS

### Node version

Node v22.1.0

### Library version

stripe-node@^16.2.0

### API version

n/a

**Comment by remi-stripe** [comment]
Hey @jlengstorf! The top-level `plan` and `quantity` properties on Subscription have been deprecated for many years. We recommend using `items.data[0][price]` instead. See my long explanation on a past issue here: https://github.com/stripe/stripe-node/issues/1794
