### ISSUE TITLE
TWINT Payment Method missing from `PaymentMethodConfigurationCreateParams`

### ISSUE THREAD

**Issue by vpontis** [stripe/stripe-node#2141]
[TWINT](https://docs.stripe.com/payments/twint) is a new payment method in Switzerland. It hasn't been added to `PaymentMethodConfigurationCreateParams`.

**Comment by helenye-stripe** [comment]
Hi @vpontis. Unfortuantely, the TWINT payment method is not yet completely public, so it is not currently available in the public OpenAPI. This is what we base our SDK generation off of.

However, the API will still accept this value if you are opted into the feature. You should be able to submit a request with your own params, including a `twint` field, and get a valid response.

**Comment by helenye-stripe** [comment]
I apologize -- the actual reason was there was a misalignment of dates. This should now be supported in https://github.com/stripe/stripe-node/releases/tag/v16.5.0.

**Comment by vpontis** [comment]
Thank you! I thought TWINT was released and is public — is it public?

**Comment by helenye-stripe** [comment]
Yes it is public. I was mistaken.
