### ISSUE TITLE
Cannot create a product with custom unit amount

### ISSUE THREAD

**Issue by raparri01** [stripe/stripe-node#2154]
### Describe the bug

[Per the Stripe API docs](https://docs.stripe.com/api/products/create), I am attempting to create a Product using the Stripe API with `default_price_data.currency_options.usd.custom_unit_amount.enabled = true`

Calling `stripe.products.create` with what I think is a valid product config object results in the following error:
`StripeInvalidRequestError: You are specifying a currency option that matches the top-level currency for this price. Please remove this currency option and it will be added automatically on creation.`

### To Reproduce

1. Setup a `stripe` client
2. Create a new product with the following code:
```
const { id } = await stripe.products.create({
    name: `Test Product`,
    description: `This is a test product`,
    images: [],
    default_price_data: {
      currency: 'usd',
      currency_options: {
        usd: {
          custom_unit_amount: {
            enabled: true,
          },
        },
      },
    },
  })
  ```
3. See error message

### Expected behavior

I expected to be able to create a product with a customizable price.

### Code snippets

```JavaScript
const { id } = await stripe.products.create({
    name: `Test Product`,
    description: `This is a test product`,
    images: [],
    default_price_data: {
      currency: 'usd',
      currency_options: {
        usd: {
          custom_unit_amount: {
            enabled: true,
            preset: 1000
          },
        },
      },
    },
  })
```

### OS

macOS

### Node version

Node v21.7.3

### Library version

v16.6.0

### API version

2024-06-20

**Comment by remi-stripe** [comment]
@raparri01 Github issues are limited to bugs with the SDK itself. The question you have is more an integration support question better directed at our support team https://support.stripe.com/contact or our Discord server where we help developers: https://stripe.com/go/developer-chat

To unblock you: the `currency_options` parameter is here to configure your pricing in alternative currencies from the default one. So you might sell a cookie box for $10 USD but also want to configure it to be $14 CAD or £8. You can't pass `currency_options` information for USD in that example as that's configured as the "default" currency/amount pair. 

Confusingly though we don't let you configure the `custom_unit_amount` inside `default_price_data` today which is likely why you ended up with the wrong parameter for the alternative currencies. I'll flag internally as we should improve this soon. In the meantime, you should instead first create a Product without `default_price_data` and then create a Price for that Product with the right information and using the `custom_unit_amount` [parameter](https://docs.stripe.com/api/prices/create#create_price-custom_unit_amount).
