### ISSUE TITLE
Webhook Error 403

### ISSUE THREAD

**Issue by Teygeta** [stripe/stripe-node#2165]
### Describe the bug

Hi, I am experiencing a problem with the Stripe webhook listener while developing locally. 
When I run my project on localhost:3000 and I am listening for Stripe webhooks, every time I try to make a payment, I get a 403 Forbidden error. 

**Further details**: 
- I have verified several times that I am accessing the correct webhook URL 
- Environment variables are configured correctly.
- I have tried changing the listening port by opening the project on a different port, but the problem persists. 
- I am using the latest version of the Stripe CLI. 
- I have verified that my server is indeed listening and reachable on the specified URL. 
 
Has anyone encountered the same problem recently? Are there any solutions or workarounds I could try? 

Thanks in advance for your help!

![Screenshot 2024-08-31 at 12 08 07](https://github.com/user-attachments/assets/5e783c78-7664-4b6d-a86d-1daf649b5f29)

### To Reproduce

Configure the webhook as per the documentation (https://docs.stripe.com/webhooks?locale=it-IT)

### Expected behavior

I expect the webhook to return code 200 to me

### Code snippets
```ts
// api/stripe/webhook
export default defineEventHandler(async (event) => {
  if (!isMethod(event, ['POST'])) {
    setResponseStatus(event, 400)

    return { ok: false }
  }

  const endpointSecret = env.STRIPE_WEBHOOK_SECRET!

  const signature = getHeader(event, 'stripe-signature')
  const payload = await readRawBody(event)

  const stripeEvent = stripe.webhooks.constructEvent(
    payload!,
    signature!,
    endpointSecret,
  )

  await handleStripeEvent({ event, stripeEvent })

  return {
    ok: true,
  }
})

async function handleStripeEvent({ stripeEvent }: { event: H3Event, stripeEvent: Stripe.Event }) {
  switch (stripeEvent.type) {
    case 'checkout.session.completed': {
```

### OS

macOS

### Node version

Node v20.12.2

### Library version

"stripe": "^16.2.0",

### API version

2024-06-20

**Comment by remi-stripe** [comment]
@Teygeta Github issues are limited to bugs with the library itself. This is more an integration support question and should instead be directed at our support team for help: https://support.stripe.com/contact/
