### ISSUE TITLE
Deleting Stripe Managed Accounts not provided

### ISSUE THREAD

**Issue by Stephn-R** [stripe/stripe-node#217]
I tried executing the following statement in my project:

```js
stripe.accounts.delete(accountID);
```

The function did not exist and this is the API endpoint I am referring to: https://stripe.com/docs/api/node#delete_account

**Comment by agentcoops** [comment]
Hi @Stephn-R, this is actually an error in our documentation. The correct method, here, is "del" as in:
```stripe.account.del(accountID)```
The reason for this discrepancy is that we wanted to avoid using "delete" which is a reserved word in JS. You can see this in the source at https://github.com/stripe/stripe-node/blob/master/lib/resources/Accounts.js#L26 and in our spec at https://github.com/stripe/stripe-node/blob/master/test/resources/Account.spec.js#L29.

We'll be sure to correct the documentation immediately. Thanks for pointing this out.

**Comment by Stephn-R** [comment]
Perfect! Thank you. Should I submit a PR then to update the docs?

**Comment by agentcoops** [comment]
Thanks for the offer, but no need. We'll take care of it on our end.

**Comment by Stephn-R** [comment]
Thank you
