### ISSUE TITLE
Prevent Instant Invoice Generation Upon Subscription Creation While Accruing Charges

### ISSUE THREAD

**Issue by dev-bilal-raza** [stripe/stripe-node#2183]
### Is your feature request related to a problem? Please describe.

I am currently using Stripe to manage subscriptions for my platform. My use case requires users to incur prorated charges from the day they sign up (e.g., September 20th), but I don't want an invoice to be generated until the end of the billing cycle (e.g., October 5th).

Currently, Stripe generates an instant invoice when a subscription is created, even if the subscription is prorated. However, my platform needs to:

- **Accrue charges** from the sign-up date to the end of the billing period (September 20th to October 5th, in this example).
- **Delay the invoice generation** until the 5th of the following month to align with our billing cycle.

### Steps to Reproduce:

1. Create a subscription with proration enabled (proration_behavior: "create_prorations").
2. Set the billing_cycle_anchor to a future date (e.g., October 5th).
3. Stripe immediately generates a prorated invoice upon subscription creation.

**Expected Behavior:**

The platform should allow charges to accrue without generating an immediate invoice. Instead, a single consolidated invoice should be generated on the next billing date (October 5th), covering both the prorated charges and the next full month's subscription.

**Current Behavior:**

- An instant invoice is generated as soon as the subscription is created, charging the user for the prorated period.
- A second invoice is generated for the upcoming billing cycle.

### Request:
Could Stripe consider implementing functionality to defer invoicing entirely until the next billing cycle anchor (e.g., October 5th), even when prorated charges are incurred? This would prevent instant invoices and allow for more flexibility in billing periods.

Thank you for your time and support!

### What I Have Tried:

- Using proration_behavior: "create_prorations" for prorated charges.
- Setting billing_cycle_anchor to a future date.
- I also tried the pending_invoice_item_interval but realized it's not applicable for this case.

**Comment by remi-stripe** [comment]
@dev-bilal-raza Github issues are limited to bugs or feature requests with the SDK itself. This is more a feature request for the API which you should flag to our support team instead: https://support.stripe.com/contact
