### ISSUE TITLE
Missing endpoint `stripe.checkout.sessions.update`

### ISSUE THREAD

**Issue by 01101sam** [stripe/stripe-node#2221]
### Describe the bug

In [Stripe Docs](https://docs.stripe.com/api/checkout/sessions/update?lang=node&shell=true&api=true&resource=checkout%20sessions&action=update) I can see the example code provided the method `stripe.checkout.sessions.update`, but that isn't the case in the source code.

https://github.com/stripe/stripe-node/blob/bc230c4cc2c89a9e100b099e7f4f3cb1b7fc4988/types/FinancialConnections/SessionsResource.d.ts#L99-L120

As you can see, the method should have
```javascript
update(
  id: string,
  options?: RequestOptions
): Promise<Stripe.Response<Stripe.Checkout.Session>>;
```

But this is not the case.

### To Reproduce

1. Import `stripe` library
2. Use `stripe.checkout.sessions.update`

Lint shows `Unresolved function or method update()`

### Expected behavior

The method is available to use, and lint is happy.

### Code snippets

```JavaScript
(Included in `Describe the bug`)
```

### OS

macOS

### Node version

Note v20

### Library version

stripe ^11.9.1

### API version

2023-08-16

**Comment by seanzhang-stripe** [comment]
Hi @01101sam The API reference that you linked is about Checkout Session, but the source code that you referenced is Financial Connection Session. They are two different kinds of resources.

Here's the source [code](https://github.com/stripe/stripe-node/blob/v17.3.1/types/Checkout/SessionsResource.d.ts#L2695) for Checkout Session update.

**Comment by 01101sam** [comment]
> Hi @01101sam The API reference that you linked is about Checkout Session, but the source code that you referenced is Financial Connection Session. They are two different kinds of resources.
> 
> Here's the source [code](https://github.com/stripe/stripe-node/blob/v17.3.1/types/Checkout/SessionsResource.d.ts#L2695) for Checkout Session update.

Thank you so much! I've overlooked the file path above; I think my lint is having a problem referencing the source code.
