### ISSUE TITLE
refund creation doesn't pass metadata to charge.refunded event

### ISSUE THREAD

**Issue by tamar-yavetz** [stripe/stripe-node#2224]
### Describe the bug

we are creating a refund using stripe version "^17.0.0".
we are calling stripe.refunds.create function and we pass some information in the metadata object.
when the refund is been created we get in the response the metadata.
however when we receive the notification for charge.refunded the metadata obj is empty obj.

### To Reproduce

we are creating a refund using stripe version "^17.0.0".
we are calling stripe.refunds.create function and we pass some information in the metadata object.
when the refund is been created we get in the response the metadata.
however when we receive the notification for charge.refunded the metadata obj is empty obj.

### Expected behavior

getting the metadata from charge.refunded event

### OS

macOs

### Node version

Node v18.19.1

### Library version

17.0.0

### API version

2024-10-28.acacia

**Comment by ramya-stripe** [comment]
@tamar-yavetz Github issues are limited to bugs with the SDK itself. The issue you have is more related to integration that is better directed at our support team https://support.stripe.com/contact or our Discord server where we help developers: https://stripe.com/go/developer-chat
