### ISSUE TITLE
The applies_to field is missing on the Coupon response object

### ISSUE THREAD

**Issue by andrew-rheingans** [stripe/stripe-node#2234]
### Describe the bug

The `applies_to` field is missing on the Coupon response object in a scenario where it should be present.

### To Reproduce

1. Create a coupon (through the web portal) and have it only apply to 1 product
2. Retrieve the coupon using the api `client.coupons.retrieve(couponId)`
3. See that coupon.applies_to is `undefined`

### Expected behavior

`applies_to` should be filled with the 1 product

### OS

macOS

### Node version

v20.10.0

### Library version

stripe-node v17.4.0

### API version

default (not specifying a version)

**Comment by seanzhang-stripe** [comment]
Hi @andrew-rheingans [applies_to](https://docs.stripe.com/api/coupons/object#coupon_object-applies_to) is an expandable field, meaning that it's not included in the response by default unless you explicitly expand it. You can refer to this [page](https://docs.stripe.com/api/expanding_objects?lang=node) to learn more about response expansion.

Let me know if it works. Feel free to re-open this ticket or raise a new ticket if you have more quetions.

**Comment by andrew-rheingans** [comment]
Ahhhhhh, thank you!
