### ISSUE TITLE
stripe.accounts.del is not a function

### ISSUE THREAD

**Issue by vlaurenlee** [stripe/stripe-node#224]
Hey Stripe,

On the official docs here: https://stripe.com/docs/api/node#delete_account, it says we're supposed to use stripe.accounts.del to delete a connected account we're managing. When I execute it, the function doesn't exist. 

I'm running stripe-node version 3.3.12.

**Comment by matthewarkin** [comment]
that was added in 3.7.0 https://github.com/stripe/stripe-node/blob/master/CHANGELOG#L23

**Comment by brandur** [comment]
> that was added in 3.7.0 https://github.com/stripe/stripe-node/blob/master/CHANGELOG#L23

+1. Thank-you Matthew! [Here's also an example of usage from the test suite](https://github.com/stripe/stripe-node/blob/e2cb165ed8d2faee2c8ba2f78919bd852da26ebb/test/resources/Account.spec.js#L31).

Vanessa, I'm closing this one out for now, but us know if you continue to experience trouble here.
