### ISSUE TITLE
Incorrect Subscription Type

### ISSUE THREAD

**Issue by incognitoai** [stripe/stripe-node#2244]
### Describe the bug

The Subscription type is missing a few of the fields which are getting returned in the api response. 

Another Issue is, I am only able to pass `apiVersion: "2023-08-16"`. If I try to pass any other latest apiVersion then also I get an type error.

### To Reproduce

1. Install "stripe": "^17.5.0"
2. Fetch the subscriptions through `stripe_client.subscriptions.list`.
3. You will see a few fields such as `plan`, `quantity` (there might be more) which are not in the type `Stripe.Subscription`. Even though the output type of the `stripe_client.subscriptions.list` is Subscription list.

### Expected behavior

The plan and quantity field should be accessible via type (if the can be undefined so please keep it Subscription | undefined).

### OS

macOS

### Node version

v20.17.0

### Library version

17.5.0

### API version

2023-08-16

### Additional context

<img width="1137" alt="Screenshot 2024-12-26 at 5 32 18 PM" src="https://github.com/user-attachments/assets/dc170180-4a06-4e95-a2d0-1ee81723ee80" />

**Comment by seanzhang-stripe** [comment]
Hi @incognitoai `quantity` isn't a top-level property for a subscription object. Instead, it belongs to the subscription item. Here's an example if you want to retrieve the quantity of the first subscription item:
```
subscription.items.data[0].quantity
```
Refer to the [API reference](https://docs.stripe.com/api/subscriptions/object?lang=node#subscription_object-items-data-quantity) for more details

**Comment by remi-stripe** [comment]
The top-level `plan` and `quantity` properties on Subscription have been deprecated for many years. They do still exist which is why you see them but we recommend using `items.data[0][price]` instead. See my long explanation on a past issue here: https://github.com/stripe/stripe-node/issues/1794 if you want more details

**Comment by incognitoai** [comment]
Thanks for the clarification @remi-stripe @seanzhang-stripe! 
Would you guys also clarify this?
> Another Issue is, I am only able to pass apiVersion: "2023-08-16". If I try to pass any other latest apiVersion then also I get an type error.

**Comment by seanzhang-stripe** [comment]
Hi @incognitoai the latest [API version](https://docs.stripe.com/changelog#2024-12-18.acacia) is `2024-12-18.acacia` . Did you include the `acacia` postfix?
