### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by jitendra00777** [stripe/stripe-node#227]
Hi,
I am using android API for charge but getting invalid token error.
steps I followed:-
1. added the API through Fabric and changed the Test publishable key to generate the token.
2. Once I got the token I am requesting for charge through android API using my Test secret key.(I tried the same from server also but getting same error).
FYI: I am using the test keys.

**Comment by matthewarkin** [comment]
As you mentioned in IRC. You're not seeing /v1/tokens requests in your Dashboard logs which means that your publishable key is not being used. I'd try first integrating with the official stripe-android library and see if that works.

**Comment by brandur** [comment]
Thanks @matthewarkin!

@jitendra00777 Hopefully Matt's advice above will help lead you a little further here. I may be missing some context here, but from the issue description I can't tell exactly how this is related to stripe-node. Could you elaborate? If unrelated, let's close this issue down, but we'll be happy to try and help out through other channels. Thanks!

**Comment by jitendra00777** [comment]
Thanks,

the issue is solved.

On Mon, Feb 1, 2016 at 8:39 PM, Brandur <notifications@github.com> wrote:

> Thanks @matthewarkin <https://github.com/matthewarkin>!
>
> @jitendra00777 <https://github.com/jitendra00777> Hopefully Matt's advice
> above will help lead you a little further here. I may be missing some
> context here, but from the issue description I can't tell exactly how this
> is related to stripe-node. Could you elaborate? If unrelated, let's close
> this issue down, but we'll be happy to try and help out through other
> channels. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stripe/stripe-node/issues/227#issuecomment-178008318>.
>



-- 
Jitendra Kumar Jaiswal
Jitendra.jswl1990@gmail.com
8892462474
