### ISSUE TITLE
Adding stripe.js methods

### ISSUE THREAD

**Issue by reggi** [stripe/stripe-node#228]
I'm very interested in including the [Client-side validation helpers](https://stripe.com/docs/stripe.js#card-validation-helpers) with a React project.

Ideally I could just use them like this:

```js
import {validateCardNumber, validateExpiry, validateCVC} from 'stripe'
```

It seems that `stripe.js` doesn't have a npm or bower version available.

Thoughts?

**Comment by reggi** [comment]
Think I found my answer https://github.com/stripe/stripe-node/issues/155

**Comment by reggi** [comment]
Reopening, Love to see if this is still the case.

**Comment by SlexAxton** [comment]
For the most part, these functions exist in https://github.com/stripe/jquery.payment -- which has bower and npm stuff included. The plugin portion requires jQuery, but you don't have to use that portion. A quick way to work around that would be to just add a `window.$={fn:{}};` somewhere, and then use it however you'd like (you'd probably have to shim it for now). You could clean up the globals immediately after you shimmed it into a module.

Not ideal, but if you're going to take one of the two libs, I'd definitely suggest taking jquery.payment over stripe-node.

**Comment by SlexAxton** [comment]
Fwiw, we plan on releasing the core parts of this stuff as mode modules some time in the next few months. So we probably won't spend a lot of time making either one of these libraries directly compatible in the way that you're looking for.

**Comment by reggi** [comment]
Thanks @SlexAxton

**Comment by reggi** [comment]
For my future self, and anyone else that wants this, just found a module that does it [card-validator](https://github.com/braintree/card-validator) from the folks at braintree (sorry Stripe)

```bash
npm i card-validator --save
```

```js
import {expirationDate, cvv, postalCode, number} from 'card-validator'
```

**Comment by lowik** [comment]
Waiting a release, I export some functions of jquery.payment to be used as npm module.
Hope it can help.
See https://github.com/lowik/stripe.js
