### ISSUE TITLE
Just curious about GET methods

### ISSUE THREAD

**Issue by MarkMurphy** [stripe/stripe-node#230]
I was just browsing through the source code and I was wondering, it looks like you write all request data to the body, how's that work when in the context of a `GET` request?

https://github.com/stripe/stripe-node/blob/master/lib/StripeResource.js#L246

**Comment by brandur** [comment]
Hey Mark, nice catch. Although, [Roy Fielding has previously recommended against interpreting a request body when received as part of a `GET` request](http://stackoverflow.com/a/983458), a `GET` is allowed a body just like any other type of verb. In addition, many web servers will interpret parameters encoded in the body for a `GET` the same way they would for a `POST`, including ours:

```
$ curl 'https://api.stripe.com/v1/charges?limit=1' -u sk_test_REDACTED:
# one result is returned

$ curl 'https://api.stripe.com/v1/charges' -u sk_test_REDACTED: -X GET -d 'limit=1'
# one result is returned
```

That said, for maximum correctness, the Node bindings should probably get using the query string for `GET` parameters.

I'm going to close this one out, but let me know us know if you have any other questions on the subject

**Comment by MarkMurphy** [comment]
Right on, didn't know that. Thanks for that.
