### ISSUE TITLE
Return SEPA charges from charges.list

### ISSUE THREAD

**Issue by AyKarsi** [stripe/stripe-node#233]
When calling 
```
  stripe.charges.list({
    	customer:customerId
    }, function(err, charge) {
```
I'd expect to also be recieving SEPA/Bank payments to be returned. Currently I'm only getting charges from customers using credit cards. 

Am I doing something wrong?

**Comment by matthewarkin** [comment]
I would expect them to be returned, but as SEPA is a private beta, I'd suggest contacting support at support.stripe.com/email

**Comment by brandur** [comment]
Hi @AyKarsi, given that this isn't a question specific to the Node bindings, would you mind doing as Matthew suggested and opening a ticket with our support team? They should be able to help find someone who can give you a more precise answer as to expectations today, and where we'll be when the feature becomes GA. Thanks!

**Comment by brandur** [comment]
Just a quick follow-up @AyKarsi: [as documented here](https://stripe.com/docs/upgrades#2015-09-23), the charges list API will not return non-card charges unless you're on API version 2015-09-23 or later, which would have the effect of filtering SEPA/bank payments. It might be worth checking the version that you're not currently locked to and making sure that you're not behind that.

**Comment by AyKarsi** [comment]
My bad. I wasn't aware of your versioning system of the api. Manually setting `stripe.setApiVersion('2016-02-29')` does the trick.

Thanks for the fast support!
