### ISSUE TITLE
support uploading files with a stream or filename

### ISSUE THREAD

**Issue by jonathanong** [stripe/stripe-node#235]
loading an entire object into memory is anti-node. might be better to use an external library to handle this vs writing the multipart body yourself

**Comment by brandur** [comment]
Yeah, this could definitely be better.

While we're more than willing to take pull requests if someone wants to tackle it, I don't think it's likely that anyone will get around to this one in the short or medium term. I'm going to close this out for now, but let me know if you have any other thoughts or ideas on the matter. Thanks!
