### ISSUE TITLE
stripe.customers.listSubscriptions - Returns Plan amount with no decimal

### ISSUE THREAD

**Issue by Rizzen1998** [stripe/stripe-node#236]
When calling stripe.customers.listSubscriptions: When a plan amount is configured through Stripe.com as $5, the "Amount" field, that comes back from stripe.customers.listSubscriptions, shows 500, not 5.00.

Thanks

**Comment by chrisvariety** [comment]
All of Stripe's amounts are in the smallest currency unit, usually cents. From the docs:

> A positive integer in the smallest currency unit (e.g 100 cents to charge $1.00, or 1 to charge ¥1, a 0-decimal currency)

**Comment by Rizzen1998** [comment]
Hey thanks man.  Didn't catch that in the docs.

**Comment by brandur** [comment]
Glad you got this figured out @Rizzen1998, and thanks for the assist @chrisvariety!
