### ISSUE TITLE
Support for 'now' value in updateSubscription function

### ISSUE THREAD

**Issue by XVincentX** [stripe/stripe-node#237]
It looks like that `stripe-node` does not support the special value `now` for `trial_end` when updating a subscription. Would it be possible to verify and eventually fix this thing?

**Comment by brandur** [comment]
@XVincentX Hey! Pretty much all the functions in the Node library are generic to the point that they all share the vast majority of their implementations, which is to say that it's not likely to be a direct bug in the library.

Can you check your request logs to verify that the parameter was passed as expected? (Under "Requests" -> "Logs" in Dashboard on the left side.) Thanks!

**Comment by XVincentX** [comment]
I just realised I made a mistake. Sorry!

**Comment by brandur** [comment]
NP! Thanks for following up.
