### ISSUE TITLE
Retrive metadata 

### ISSUE THREAD

**Issue by shengrong1987** [stripe/stripe-node#240]
follow up on #238.

Hi @matthewarkin, thank you for the quick response.
I am trying to retrieve the metadata I post it when creating a charge in behalf of a connected account. 
But when I inquire balance transaction on behalf of the connect account I don't see it, even I retrieve the payment in the source of each transaction.

**Comment by brandur** [comment]
Hi @shengrong1987, as far as I can tell, this appears to the same problem that you raised in #240. There's a lot more context over there, so let's keep the discussion on that single thread. Thanks!
