### ISSUE TITLE
Question about client-side use of stripe

### ISSUE THREAD

**Issue by ffxsam** [stripe/stripe-node#247]
Pardon the potential newbie question here, but, I'm wanting to create a token based off card data, without using the `stripe.js` code, and do it 100% in JS + React. So in one of my components, I do this:

    const stripe = require('stripe')('pk_test_xxxxxx');

And I get this error:

```
Uncaught TypeError: require(...).createServer is not a function
```

I'm assuming this is because I'm in a strictly client-side only environment here. But surely there has to be a way where I can take credit card information filled into a form, and generate a token based off that, in a PCI-compliant way?

Full code:

```jsx
import React, { Component, PropTypes } from 'react';

const stripe  = require('stripe')('pk_test_xxxxxx');

class ChargeCardForm extends Component {
  submit(event) {
    const {
      number,
      expMonth,
      expYear,
      cvc,
    } = this.refs;

    event.preventDefault();

    stripe.tokens.create({
      card: {
        number: number.value,
        exp_month: expMonth.value,
        exp_year: expYear.value,
        cvc: cvc.value,
      },
    }, (error, token) => {
      
    });
  }

  render() {
    return <div>
      <form onSubmit={this.submit.bind(this)}>
        <input ref="number" placeholder="CC#" />
        <input ref="expMonth" placeholder="Exp Mo" />
        <input ref="expYear" placeholder="Exp Year" />
        <input ref="cvc" placeholder="CVC" />

        <button type="submit">Submit</button>
      </form>
    </div>
  }
}
```

**Comment by ffxsam** [comment]
Ah, got it. Posting the solution below for anyone else who's curious:

```jsx
class ChargeCardForm extends Component {
  componentDidMount() {
    const script = document.createElement('script');

    script.async = true;
    script.src = 'https://js.stripe.com/v2';
    document.body.appendChild(script);
  }

  submit(event) {
    const {
      number,
      expMonth,
      expYear,
      cvc,
    } = this.refs;

    event.preventDefault();

    Stripe.setPublishableKey('pk_test_xxxxx');
    Stripe.card.createToken({
      number: number.value,
      exp_month: expMonth.value,
      exp_year: expYear.value,
      cvc: cvc.value,
    }, (status, response) => {
      console.log(status, response);
    });
  }

  render() {
    return <div>
      <form onSubmit={this.submit.bind(this)}>
        <input ref="number" placeholder="CC#" />
        <input ref="expMonth" placeholder="Exp Mo" />
        <input ref="expYear" placeholder="Exp Year" />
        <input ref="cvc" placeholder="CVC" />

        <button type="submit">Submit</button>
      </form>
    </div>
  }
}
```

**Comment by olivierbellone** [comment]
@ffxsam While it is technically possible to create tokens this way, that wouldn't be [PCI compliant](https://support.stripe.com/questions/do-i-need-to-be-pci-compliant-what-do-i-have-to-do).

You must use either [Stripe.js](https://stripe.com/docs/stripe.js) or [Checkout](https://stripe.com/docs/checkout), by including the file directly from Stripe's servers.

**Comment by ffxsam** [comment]
This is essentially the same thing Stripe.js is doing. [See here](https://stripe.com/docs/custom-form).

**Comment by ffxsam** [comment]
In other words, the Stripe example code is taking form data (CC info) and passing it directly to Stripe for processing:

    Stripe.card.createToken($form, stripeResponseHandler);

My code is doing the same thing.

**Comment by SlexAxton** [comment]
In the first part of your code, it looks like you have `const stripe = require('stripe')('pk_test_xxxxxx');` which would then leak your private key to anyone looking at your client-side source.

On top of that, the domain that stripe.js is served from is important for the PCI DSS 3.1 compliance. It is possible to still be compliant without it, but it's unlikely that you are, or that you'd be willing to be.

**Comment by ffxsam** [comment]
>In the first part of your code, it looks like you have const stripe = require('stripe')('pk_test_xxxxxx'); which would then leak your private key to anyone looking at your client-side source.

Yeah, disregard the very first post.. that would never work. But pk = publishable key.. that's supposed to be public.

Secondly, refer to this:

```javascript
    const script = document.createElement('script');

    script.async = true;
    script.src = 'https://js.stripe.com/v2';
    document.body.appendChild(script);
```

I'm loading the stripe.js code directly from js.stripe.com. Again, my code is doing exactly the same thing that Stripe officially recommends. Unless I'm missing something?

**Comment by SlexAxton** [comment]
PCI DSS 3.1 SAQ-A cares about (for better or for worse) the security of the server that stripe.js is served from, as well as the domain that requests are made from. Stripe.js jumps through these hoops for you by being served by a PCI compliant server/stack and by creating an iframe passthrough so the requests originate from a stripe/pci-compliant domain.

With your setup, (there's a lot I don't know, so this is the best case scenario), it'd be possible for you to fall under the PCI DSS SAQ A-EP compliance, which is somewhat more rigorous than the SAQ A. It involves scans and more process/auditing. You'd likely want to get a QSA to verify things for you at that point.

So it's *possible* for you to do it this way and *be* compliant to *a* level of PCI, but it's unlikely the path of least resistance compared to just using stripe.js from the stripe domain.

Hope that helps!

(Also make sure you don't accidentally compile secret keys into clientside source, that can be a huge fraud headache)

**Comment by SlexAxton** [comment]
Ah I was under the impression you were importing `stripe-node` and making requests from that in the initial post.

**Comment by SlexAxton** [comment]
As long as stripe.js is making the request, you should be good to go.

**Comment by SlexAxton** [comment]
I see you loading stripe.js in the second comment now, but I guess I was confused because this issue is on `stripe-node`.

**Comment by ffxsam** [comment]
@SlexAxton Thanks for the info! Yes, sorry I kind of made this off-topic since this is about the node component which is server-side. I can confirm that when I use my method of script loading above, the iframe does appear, and tokens are generated properly.

**Comment by SlexAxton** [comment]
Solid. Looks good then. Good luck!

**Comment by ffxsam** [comment]
Thanks—and thanks for all the solid work on this! Stripe rocks :)

**Comment by SlexAxton** [comment]
(for context, people try to browserify `stripe-node` a lot, but I'll read better next time)

**Comment by steffanhalv** [comment]
@SlexAxton @ffxsam I don't get it, is this still possible or was this deprecated with Stripe.js v2?

Is it actually possible to collect the card information client side and pass to elements or the latest Stripe.js without to be PCI Compliant?

**Comment by ob-stripe** [comment]
@steffanhalv You should be using either [Checkout](https://stripe.com/docs/checkout) or [Stripe.js / Elements](https://stripe.com/docs/stripe-js) to collect and tokenize payment information client-side.

Note that GitHub issues are specifically for bugs or feature requests regarding Stripe's Node.js library and are not a support channel. I recommend you reach out to Stripe's support at https://support.stripe.com/email to explain your usecase and ask your questions.
