### ISSUE TITLE
stripe.subscriptions.del returns undefined

### ISSUE THREAD

**Issue by realseanp** [stripe/stripe-node#249]
When trying to use `stripe.subscriptions.del` I get the following error:

`[TypeError: Cannot read property 'del' of undefined]`

I had to use `stripe.customers.cancelSubscription`, but that doesn't seem to be documented anywhere.

**Comment by remistr** [comment]
@realseanp: The `stripe.subscriptions` class and associated methods were added only recently. You need to make sure you upgrade your Stripe node library to at least [4.6.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG#L4) to be able to call `stripe.subscriptions.del`

**Comment by realseanp** [comment]
@remistr I thought that might've been the case so I made sure I was updated. I am using 4.7.0
