### ISSUE TITLE
Defer method in Bluebird is deprecated, and should be replaced

### ISSUE THREAD

**Issue by oronjaco** [stripe/stripe-node#257]
http://bluebirdjs.com/docs/deprecated-apis.html#promise-resolution
Currently this warning is returned : 'Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.'

**Comment by brandur** [comment]
Interesting! Thanks for the heads up @oronjaco, I'll take a look at it within the next few days.
