### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined Bluebird

### ISSUE THREAD

**Issue by valetzyzy** [stripe/stripe-node#261]
When I trying to call any API method it throws exception 
`node_modules/stripe/node_modules/bluebird/js/main/schedule.js:11`
`                ? function(fn) { GlobalSetImmediate.call(global, fn); }`

`TypeError: Cannot read property 'call' of undefined`

Node.js  v4.5.0
Stripe v4.10.0 

Please help

**Comment by floatingLomas** [comment]
Hi!  I tried to duplicate this (with Node@4.5.0 and Stripe@4.10.0) but I can't.  Would you be able to provide some more details on what's going on here, and maybe some sample code that causes the error?

**Comment by valetzyzy** [comment]
@floatingLomas 
Hi, some code simple 
`var stripe = require('stripe')(config.stripeApi);`
```
stripe.charges.create({
            amount: 100,
            currency: 'usd',
            customer: 'cus_***',
            description: 'Charge for daniel.white@example.com'
        }, function(err, charge) {
            if (err) {
                return global.triggerError(req, res, err)
            }

            console.log(charge)
        });
```

My `package.json`
```
"dependencies": {
    "body-parser": "~1.15.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.2.0",
    "express": "~4.13.4",
    "mongoose": "4.5.1",
    "morgan": "~1.7.0",
    "underscore": "^1.8.3",
    "line-by-line": "0.1.5",
    "googleplaces": "0.6.0",
    "express-fileupload": "0.0.5",
    "sync-request": "3.0.1",
    "jsonwebtoken": "7.1.9",
    "fb": "1.1.1",
    "stripe": "4.10.0"
  }
```

**Comment by valetzyzy** [comment]
I fix it
In BlueBird I found line
`var GlobalSetImmediate = global.setImmediate;`

`console.log(GlobalSetImmediate)` - undefined

In my code I just override `global` object.

Solution is remove code that override `global` object

**Comment by vjpr** [comment]
I made this type and got same error: `global = require('bluebird')`
