### ISSUE TITLE
require('http').createServer is not a function

### ISSUE THREAD

**Issue by Leletir** [stripe/stripe-node#262]
Hi,

I'm developing an application with ionic 2, but when I launch my application I have an error:
TypeError: require('http').createServer is not a function. (In 'require('http').createServer()', 'require('http').createServer' is undefined).

Do you have seen this error before ?

Thank you.

**Comment by matthewarkin** [comment]
`require('http').createServer` would be code for your server-side Node.js application. The creation of charges and anything you'd use Stripe-node for has to be done on a server and not on the client app for security reasons

**Comment by Leletir20** [comment]
Thank you for the response.

**Comment by brandur** [comment]
Cool! It looks like this one is resolved so I'm closing it out.

Thanks @matthewarkin!
