### ISSUE TITLE
Limit param doesn't work for stripe_account calls

### ISSUE THREAD

**Issue by wejrowski** [stripe/stripe-node#274]
I'm attempting to grab a list of customers for a specific stripe connect account, using my api key but passing their stripe_account param. It appears the limit parameter does not work if requesting a customer list on a stripe connect account.

```javascript
stripe.customers.list(
  { stripe_account: "acct_abc", limit: 100 },
  // ...
);
```

The limit ends up always being 10, the default. If I remove stripe_account, it respects the limit param.

**Comment by remi-stripe** [comment]
The issue is that you're not passing the `limit` parameter properly here as it can't be in the same hash as `stripe_account`. It should be:

```
stripe.customers.list(
  { limit: 100 },
  { stripe_account: "acct_abc"},
  // ...
);
```

**Comment by wejrowski** [comment]
Awesome that works. It would be helpful if that was more straightforward in the docs, I didn't see anything noting that.
