### ISSUE TITLE
Consideration of SEPA Direct Debit in the API

### ISSUE THREAD

**Issue by maku** [stripe/stripe-node#275]
It would be great if SEPA Direct Debit, which is in beta, is considered in the API.

**Comment by brandur-stripe** [comment]
Hi @maku, I've forwarded this onto the appropriate team.

In the future though, please don't open an issue for this type of request as we try to reserve them for bug reports in the client bindings.

**Comment by stan-stripe** [comment]
@maku despite not being currently documented in the SEPA Direct Debits guide, you can use the node bindings as described here: https://stripe.com/docs/api/node#sources
