### ISSUE TITLE
Bug or Feature: support of async/await pls

### ISSUE THREAD

**Issue by adamgins** [stripe/stripe-node#284]
Hi, I was using async/await successfully with MeteorJS in the past. With the later release 1.4.2.2 of Meteor I am getting "undefined" when I call `await` and it seems like Stripe API is not sending back what Node expects to a `Promise`

See https://github.com/meteor/meteor/issues/8064#issuecomment-261110915

I know this stripe API is `thenable` but given my current scenario that makes it really tough as there are multiple actions that relay on results of interim calls. 

Anyway, I am not sure if this is a) a bug with `stripe-node` or to be expected or a feature request for a later release. 

Any help appreciated.

**Comment by brandur** [comment]
@adamgins Hm, I'm afraid that I don't know the Meteor product very well so I'm not sure how much help I can be here, but do you know that stripe-node uses the [Bluebird library for promises](http://bluebirdjs.com/docs/getting-started.html)? I wouldn't be surprised if (as somewhat alluded to in that meteor thread) there's just some sort of promise impedance mismatch here.

**Comment by adamgins** [comment]
@brandur thanks. Please see here https://github.com/meteor/meteor/issues/8064#issuecomment-261406392 

I ended up rolling back to `stripe@4.9.1` which did not have `bluebird` and hey presto it works. 

Any thoughts on a way forward, pls? Also I had a quick look through the PR's since then and could not see anything major... anything major come to mind if I keep running on 4.9.1?

**Comment by brandur** [comment]
Hey @adamgins,

Stripe 4.9.1 is using Bluebird as well. The difference is that we removed the use of the deprecated `Promise.defer` according to Bluebird's latest recommendations. See this pull request for the full details:

https://github.com/stripe/stripe-node/pull/260

Unfortunately, I don't have a huge amount of extra time to investigate this right now, so I'm going to close this issue out. If there's some indication that there's a problem here that's more general beyond Meteor, please feel free to re-open and we'll dig in. Sorry about that.
