### ISSUE TITLE
Apple pay recurring payment with Stripe?

### ISSUE THREAD

**Issue by macpraveen** [stripe/stripe-node#288]
Is it possible to setup recurring payments with Apple pay using Stripe? Currently I am using createTokenWithPayment in iOS to get token and creating a charge. But I guess I cannot use that token more than once.

The way to go is by creating a customer and then charging a customer (#154). But how to create a customer with apple pay token as the token is linked with payment instead of card. Ideally I want to create 5 charges with different price with apple pay in one single call from client (iOS).

**Comment by remi-stripe** [comment]
@macpraveen: here we expect to see issues about the Node.js bindings and not questions about our API. I'd recommend that you reach out to support directly instead [here](https://support.stripe.com/email).

To answer your question though, Apple does support subscriptions with Apple Pay. You would simply store the card on a customer first and then subscribe that customer to a plan and it would just work.
