### ISSUE TITLE
How to create bank account token with bank account number and routing number

### ISSUE THREAD

**Issue by akk144** [stripe/stripe-node#289]
There is Stripe.bankAccount.createToken({ bankDetails } api but it seems its not included for node support.If not than how to add one..?

**Comment by ob-stripe** [comment]
Hi @akk144, you can find the documentation for creating bank account tokens with Node.js in our API reference: https://stripe.com/docs/api/node#create_bank_account_token.

As this is neither a bug nor a feature request for the Node.js library, I'm going to close this issue. If you have followup questions, please write to support using the form at https://support.stripe.com/email.
