### ISSUE TITLE
Updating quantity in stripe.subscriptions is not atomic

### ISSUE THREAD

**Issue by mattkrick** [stripe/stripe-node#292]
Background:
I have a SaaS with a per-seat billing model. I use `quantity` to represent seats.

When a customer adds a seat, I update the quantity. To do so, I get the quantity, and then increment it:
```
const {quantity} = await stripe.subscriptions.retrieve(subscriptionId);
await stripe.subscriptions.update(subscriptionId, {quantity: quantity + 1});
```

Since each customer can have multiple billing leaders, this call could be executed simultaneously from different servers. That means the quantity could change between fetching the quantity & updating the quantity. 

Proposed solution:
The `subscriptions.update` API shall take an integer or string. If the value is a string and it is prefixed with either `+` or `-` then stripe will respectively increment or decrement the quantity.

Example:
```
await stripe.subscriptions.update(subscriptionId, {quantity: '+1'})
```

Perfect world solution:
Add a Set called `seats` to the API. Each value in the Set is a unique user-defined ID. `quantity` is simply `seats.size`. This results in an idempotent API, which would greatly improve DX. If `quantity` is updated directly, it will return an error.

Example:

```
// seats = Set(['mark'])
await stripe.subscriptions.update(subscriptionId, {
  seatsToAdd: 'john'
}
// seats = Set(['mark', 'john'])
await stripe.subscriptions.update(subscriptionId, {
  seatsToAdd: 'john',
  seatsToRemove: ['mark', 'mark', 'mark']
}
// seats = Set(['john'])
```

**Comment by slava-stripe** [comment]
@mattkrick -- let me check with the team; I'll follow up shortly.

**Comment by slava-stripe** [comment]
Ok, checked with a few folks.

It seems hacky to solve this problem *just* for the `quantity` argument. If we were to do this, to keep the API consistent we'd want to do it for all integer values in the API. That sounds like a good idea, but it's a very non-trivial amount of work to do correctly. We'll consider getting it on the roadmap, but it'll be hard to schedule given all the other things we're currently working on.

For now I'd suggest adding an application-level lock and synchronizing the billing leaders on your servers. That should be relatively easy to do (compared to the amount of work necessary to get this into the API) and will prevent the race conditions in the interim.

Thanks for writing this up!

**Comment by ronzeidman** [comment]
Just a suggestion, you could add a "known timestamp":
1) retreive the subscription object with a "last modified" numeric value
2) update the subscription with "do so only if the last modified number matches"
3) if it doesn't match the API will throw an error "last modified doesn't match"
4) handle the error by repeating (1)
This will fix any mismatches in any kind of values without much work and you could handle them anyway you'd like (maybe you don't want to add +1 if it was already added or you want to cap it somehow or something else). The only downside is more roundtrips but I don't think this is a performance-critical flow.

**Comment by deontologician-stripe** [comment]
Closing since it seems like we aren't doing this

**Comment by manast** [comment]
An application level lock is not so trivial either, specially in a distributed application. I guess most users are just ignoring this race condition and since it probably does not happen very often gives the impression that it is working solution. Updating seats seems to me like a quite common operation for not being able to perform it out of the box.

**Comment by remi-stripe** [comment]
@manast That's definitely good feedback and we agree the atomicity part is missing. While talking with users though, it's less common for the quantity to be increased by say +1 or +2 based on its current value. In most cases, you want to set the final quantity that your customer is asking for for example, so race conditions are less common in that situation.

I'd definitely recommend reaching out to our support team with your use-case though as we're always looking for things we could improve in our API! You can reach out to them here: https://support.stripe.com/contact

**Comment by nathaniel-holder** [comment]
> Closing since it seems like we aren't doing this

@deontologician-stripe Why was this closed as "completed" instead of "not planned"?
