### ISSUE TITLE
Unknown Error - Expand source_transaction

### ISSUE THREAD

**Issue by gabrieljenik** [stripe/stripe-node#293]
Hi,

We are getting an error on an API call which used to work couple of days ago. 
At a minimum, it used to work last year.

https://api.stripe.com/v1/balance/history?limit=1000&type=payment&created[gte]=1451606400&created[lte]=1483228800&expand[]=data.source&expand[]=data.source.source_transfer&expand[]=data.source.source_transfer.source_transaction

The error we get is 
{
  "error": {
    "type": "api_error",
    "message": "An unknown error occurred"
  }
}

I see the error dissapears when we remove the expand parameter for "data.source.source_transfer.source_transaction"

Has there been any recent change?

Can you please help us on this?

**Comment by remi-stripe** [comment]
@gabrieljenik This errors sounds fairly specific to your account and not the code itself or a bug in the bindings. Can you please write in to support directly [here](https://support.stripe.com/email)? Please make sure to provide as much information as possible about the failed requests including the exact code you use to trigger this error.
