### ISSUE TITLE
Cannot query lines on upcoming invoice

### ISSUE THREAD

**Issue by mattkrick** [stripe/stripe-node#295]
There is currently no way to access this endpoint: `/v1/invoices/upcoming/lines`.
I propose `stripe.invoices.retrieveUpcomingLines` and have it take the same args as `stripe.invoices.retrieveLines`.

**Comment by jlomas-stripe** [comment]
Hi!  There actually is a way to do this:

    stripe.invoices.retrieveLines("upcoming", {
      customer: customerId,
    }, function(error, lines) {
      // Do fun stuff here
    });

In this case, you have to specify both the 'Invoice ID' of `'upcoming'` _and the Customer ID_ in order for it to work; once you've got those, you should get what you're after.
