### ISSUE TITLE
npm package has an extra 4.6 MB file

### ISSUE THREAD

**Issue by plievone** [stripe/stripe-node#302]
Hi, do you need that ctags-generated 4.6 MB `tags` file in package root, or could it be included in either `.gitignore` or `.npmignore` to reduce npm package size by 50%.

(did `npm install stripe@4.15`)

**Comment by bindings-watch** [comment]
Hey, nice find! I am seeing the same when I pull down the package from npm;
will investigate on our end to see why that tags file gets bundled as we
almost certainly don't need it.

**Comment by fred-stripe** [comment]
Hey, nice find! I am seeing the same when I pull down the package from npm;
will investigate on our end to see why that tags file gets bundled as we
almost certainly don't need it.
