### ISSUE TITLE
The card is not attached to this stripe account

### ISSUE THREAD

**Issue by charlyBerthet** [stripe/stripe-node#303]
Hi, 

I would like to send money to my customers using there cards.

Steps:
I created a card, then I created my customer, attache that customer to this card.
Then I tried to "`stripe.transfers.create`" on using this card but I got the following error : 

Error: The card card_19m7nKJMk0gvqNw3aMqw0ejp is not attached to this Stripe account. External accounts can only be attached to standalone Stripe accounts via the dashboard.

What did I missed?
How can I attache this card OR customer to my stripe account using the API?

Thanks

**Comment by remi-stripe** [comment]
@charlyBerthet When you create a `Customer` in your Stripe account, you can then **charge** their associated card (or other type of source). You can't send funds to the card though (other than refunding a previous charge that is).

If you want to send funds to someone or rather charge a customer on behalf of a third-party seller/provider, you would need to use Stripe Connect instead. You can find the full documentation [here](https://stripe.com/docs/connect).

If you have any follow up questions after reading the documentation, you should reach out to Stripe's support directly through our [contact form](https://support.stripe.com/email). Issues on Github should only be used to report bugs with our library!
