### ISSUE TITLE
Wrong "StripeInvalidRequestError, Must provide source or customer" error?

### ISSUE THREAD

**Issue by bebbi** [stripe/stripe-node#307]
If I add
```
stripe_account: 'acct_XXXX',
application_fee: 100
```
to my call to stripe.charges.create(), it consistently fails with the error in the title. If I leave these out, it consistently succeeds.

Reading the API docs I realize that coming from python I'm probably posting the "stripe_account" info in the wrong way, but the error still looks invalid.

Two examples of the full payload (some anon with dots by me):

Success:
```
{
  "source": "tok_19oF...IZNC",
  "capture": false,
  "amount": 33000,
  "currency": "EUR",
  "description": "Some description",
  "receipt_email": "my@email.com",
  "metadata": {
    [... some metadata...]
  }
```

Failure:
```
{
  "source": "tok_19oF...StPM",
  "capture": false,
  "amount": 33000,
  "currency": "EUR",
  "application_fee": 100,
  "stripe_account": "acct_18Ea...",
  "description": "Some description",
  "receipt_email": "my@email.com",
  "metadata": {
    [... some metadata...]
  }
}
```

**Comment by remi-stripe** [comment]
The `stripe_account` parameter must be passed in a separate hash. The code should be:

```
stripe.charges.create(
  {
    "source": "tok_19oF...StPM",
    "capture": false,
    "amount": 33000,
    "currency": "EUR",
    "application_fee": 100,
    "description": "Some description",
    "receipt_email": "my@email.com",
    "metadata": {
      [... some metadata...]
    }
  },
  {stripe_account: "acct_XXXXXX"}
);
```

**Comment by remi-stripe** [comment]
@bebbi I can't find that specific request but my guess is that something is not sent properly in your code so we default to the common error indicating that to charge a customer you need to pass a token or a customer id.

**Comment by jlomas-stripe** [comment]
@bebbi There's an issue in the way requests get created if you don't separate out `stripe_account` into the `options` object: what ends up happening there is that all your values disappear in the request that Stripe receives, so Stripe's API responds to what it got in that case - which is a request without a `source` or `customer`.

**Comment by staringispolite** [comment]
I'm getting this error when I just try to package it up for the very first time with grunt run/grunt package, per the README instructions. What am I missing? There shouldn't be any stripe requests triggered in setup, should there?

**Comment by jlomas-stripe** [comment]
@staringispolite This library is only for server-side use.  On the client side, you'll want to use [Checkout](https://stripe.com/docs/checkout) or [Elements](https://stripe.com/docs/elements).

**Comment by staringispolite** [comment]
Yes. Maybe I should clarify, I’m following the instructions in the README
to get the code up to AWS LAMBDA for the first time. The instructions are
to run “grunt run” then “grunt package”. For some reason both are
generating this error, when as far as I can tell, neither should be
submitting anything to Stripe

**Comment by Hasnain-110** [comment]
StripeInvalidRequestError: Funds can't be sent to accounts located in IN because it's restricted outside of your platform's region
 **can we avoid this error in stripe test mode?**

**Comment by remi-stripe** [comment]
@Hasnain-110 this is a github issue from 5 years and you provided zero information and it's irrelevant to the question at hand.

Please work with our support team for help instead https://support.stripe.com/contact
