### ISSUE TITLE
Include requestId in successful API calls as well as failed ones

### ISSUE THREAD

**Issue by rcwwilliams** [stripe/stripe-node#315]
The requestId is included in failed API calls, but not in successful ones.
It would be really helpful to have requestId included with all calls including successful ones.
I would hope it is only a very quick fix.
Thanks very much.
Robin

**Comment by brandur-stripe** [comment]
Makes sense. I've added a change in #316 to make this easier to get.

**Comment by brandur-stripe** [comment]
New version available in 4.16.0.

**Comment by rcwwilliams** [comment]
Thank you so much for dealing with this so amazingly quickly - I look forward to trying it out.

**Comment by rcwwilliams** [comment]
Until I loaded this update, I wasn't aware of the lastResponse property of response.  Would it be worth adding something to the documentation?

**Comment by brandur-stripe** [comment]
> Until I loaded this update, I wasn't aware of the lastResponse property of response. Would it be worth adding something to the documentation?

Sounds like a good idea. Added a section in our README in #320.

**Comment by rcwwilliams** [comment]
I think there is a bug in line 136 of StripeResource

I believe

response.error.requestId = response.requestId;

should be 

response.error.requestId = res.requestId;

Please could you have a look

Thanks

**Comment by brandur-stripe** [comment]
Thanks for catching this! Fixed in #322 and released as 4.16.1.
