### ISSUE TITLE
Received unknown parameter: name

### ISSUE THREAD

**Issue by damarnez** [stripe/stripe-node#317]
npm version 4.16.0
node version 6.10
This worked until three days ago.

When I create a customer, I recieve this error from Stripe :

```
 stripe.customers.create({
      card: data.card_token,
      name: data.name ,
      description: data.description
    }).catch((err) => { console.error(' STRIPE ERROR: ', error); })
```

 ```
{ Error: Received unknown parameter: name
    at Error._Error (/home/ubuntu/payment/node_modules/stripe/lib/Error.js:12:17)
    at Error.Constructor (/home/ubuntu/payment/node_modules/stripe/lib/utils.js:97:13)
    at Error.Constructor (/home/ubuntu/payment/node_modules/stripe/lib/utils.js:97:13)
    at Function.StripeError.generate (/home/ubuntu/payment/node_modules/stripe/lib/Error.js:56:14)
    at IncomingMessage.<anonymous> (/home/ubuntu/payment/node_modules/stripe/lib/StripeResource.js:145:39)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  type: 'StripeInvalidRequestError',
  stack: 'Error: Received unknown parameter: name\n    at Error._Error (/home/ubuntu/payment/node_modules/stripe/lib/Error.js:12:17)\n    at Error.Constructor (/home/ubuntu/payment/node_modules/stripe/lib/utils.js:97:13)\n    at Error.Constructor (/home/ubuntu/payment/node_modules/stripe/lib/utils.js:97:13)\n    at Function.StripeError.generate (/home/ubuntu/payment/node_modules/stripe/lib/Error.js:56:14)\n    at IncomingMessage.<anonymous> (/home/ubuntu/payment/node_modules/stripe/lib/StripeResource.js:145:39)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)',
  rawType: 'invalid_request_error',
  code: undefined,
  param: 'name',
  message: 'Received unknown parameter: name',
  detail: undefined,
  raw:
   { type: 'invalid_request_error',
     message: 'Received unknown parameter: name',
     param: 'name',
     statusCode: 400,
     requestId: undefined },
  requestId: undefined,
  statusCode: 400 }
```

**Comment by remi-stripe** [comment]
@damarnez The Create Customer [API](https://stripe.com/docs/api#create_customer) does not have a `name` parameter and, as far as I know, never has. The error you're getting indicates that you're passing a parameter that our API doesn't know about and we're returning an error because of this.

The fact that this changed 3 days ago is likely related to the fact that you've upgraded your API version at that time. It's a guess but that's the most common reason. In the past, we released a API version, [2015-10-12](https://stripe.com/docs/upgrades#2015-10-12), that rejected API requests with unknown parameters. If your code relied on an older API version and you switched it since then you would have started to receive those errors.

**Comment by damarnez** [comment]
Ok @remi-stripe , thanks for your response.

**Comment by Serhioromano** [comment]
I have the same error tещщю ууы you do not have `name` but I pass it in metadata where I can pass any parameter I want.

```php
$customer = \Stripe\Customer::create(array(
	'email'    => $user->get('email'),
	'card'     => $token,
	'metadata' => [
		'username'   => $user->get('username'),
		'name'       => $user->get('name'),
		'registered' => $user->get('registerDate'),
		'user_email' => $user->get('email')
	]
));
```

Why do I get this error?

**Comment by remi-stripe** [comment]
@Serhioromano That error is either different or the one you get is not for this code. I'd recommend talking to our support team directly for this and they can help by looking at your logs: https://support.stripe.com/email

**Comment by Serhioromano** [comment]
@remi-stripe Yes it was from different code, create plan.

**Comment by remi-stripe** [comment]
@Serhioromano glad you figured it out! For any follow-up questions, you can chat with our support team directly!

**Comment by Muneeza93** [comment]
// trying to hit this endpoint via postman added my bearer token(publishable key) as well everything seems fine but i get this error "StripeInvalidRequestError: Received unknown parameter: confrim. Did you mean confirm?". Below is my code on the server side;

app.post("/stripe/charge", cors(), async (req, res) => {
  let { id } = req.body;
  try {
    const payment = await stripe.paymentIntents.create({
      amount: 999,
      currency: "ZK",
      description: "Bedspace",
      payment_method: id,
      payment_method_types: ["card"],
      confrim: true,
    });
    res.status(201).json({
      message: "payment successful",
      success: true,
      data: payment,
    });
  } catch (error) {
    console.log(error);
    res.json({
      message: "payment failed",
      success: false,
    });
  }
});

**Comment by remi-stripe** [comment]
@Muneeza93 the error can not come from this code, so you must be getting the error from a different part of your code. This isn't really the right place to ask for help on a 4 years old github issue. Please make sure to contact our support team instead https://support.stripe.com/contact/email or use Discord https://stripe.com/go/developer-chat

**Comment by Muneeza93** [comment]
on postman i use x-www-fom-urlencoded to pass key value pairs and pass the following;
card[number]: 4242424242424242
card[exp_month]:
card[exp_year]:2024
card[cvc]: 123

**Comment by Muneeza93** [comment]
alright @remi-stripe let me try discord

**Comment by eng10** [comment]
cc

**Comment by eng10** [comment]
please help StripeInvalidRequestError: Received unknown parameters: 0, 3, 1, 2
