### ISSUE TITLE
"operational" error difficult to interpret

### ISSUE THREAD

**Issue by rcwwilliams** [stripe/stripe-node#323]
When I called payInvoice with an undefined invoiceId, the error that came back was difficult to interpret with no error type and all properties hidden.

Here is an example of what each of the properties of the error look like.

"stack=Error: Stripe: Argument \"invoiceId\" required, but got: undefined (on API request to POST function (outputs) {\n        return cleanString.replace(/\\{([\\s\\S]+?)\\}/g
, function($0, $1) {\n          return encodeURIComponent(outputs[$1] || '');\n        });\n      })\n    at Object.<anonymous> (F:\\Development\\MEAN\\SCR\\server\\node_module
s\\stripe\\lib\\StripeMethod.js:53:21)\n    at tryCatcher (F:\\Development\\MEAN\\SCR\\server\\node_modules\\stripe\\node_modules\\bluebird\\js\\main\\util.js:26:23)\n    at Pr
omise._resolveFromResolver (F:\\Development\\MEAN\\SCR\\server\\node_modules\\stripe\\node_modules\\bluebird\\js\\main\\promise.js:483:31)\n    at new Promise (F:\\Development\
\MEAN\\SCR\\server\\node_modules\\stripe\\node_modules\\bluebird\\js\\main\\promise.js:71:37)\n    at Object.pay (F:\\Development\\MEAN\\SCR\\server\\node_modules\\stripe\\lib\
\StripeMethod.js:36:29)\n    at Object.callStripe (F:\\Development\\MEAN\\SCR\\server\\dist\\scrdev\\payments\\stripe\\originalStripeApiUtil.js:107:29)\n    at callStripe (F:\\
Development\\MEAN\\SCR\\server\\dist\\scrdev\\payments\\stripe\\stripeApiUtil.js:93:36)\n    at pingIfNeeded.then.error.errorDetail.stripeErrorDetail.type (F:\\Development\\MEA
N\\SCR\\server\\dist\\scrdev\\payments\\stripe\\originalStripeApiUtil.js:152:16)\n    at _fulfilled (F:\\Development\\MEAN\\SCR\\server\\node_modules\\q\\q.js:794:54)\n    at s
elf.promiseDispatch.done (F:\\Development\\MEAN\\SCR\\server\\node_modules\\q\\q.js:823:30)\n    at Promise.promise.promiseDispatch (F:\\Development\\MEAN\\SCR\\server\\node_mo
dules\\q\\q.js:756:13)\n    at F:\\Development\\MEAN\\SCR\\server\\node_modules\\q\\q.js:817:14\n    at flush (F:\\Development\\MEAN\\SCR\\server\\node_modules\\q\\q.js:110:17)
\n    at process._tickCallback (node.js:442:13)"
"arguments=undefined"
"type=undefined"
"message=Stripe: Argument \"invoiceId\" required, but got: undefined (on API request to POST function (outputs) {\n        return cleanString.replace(/\\{([\\s\\S]+?)\\}/g, fun
ction($0, $1) {\n          return encodeURIComponent(outputs[$1] || '');\n        });\n      })"
"isOperational=true"

**Comment by brandur-stripe** [comment]
Hi @rcwwilliams, would you mind giving us some sample code that we could use to try and reproduce this? Thanks!

**Comment by rcwwilliams** [comment]
Hi Brandur

This isn't exactly code, but it shows the params I passed to the stripe.invoices.pay function: 

31/03/2017 07:57:19.546 stripe.invoices.pay request [
  null,
  {
    expand: [
      "charge",
      "charge.balance_transaction"
    ]
  },
  {
    idempotency_key: "invoices.pay.20170331075719536"
  }
]

I know our code should perhaps not allow us to get as far as making this call without an invoiceId, but I came across it during development.

Please let me know if you need anything else from me.

Thanks

Kind regards

Robin

**Comment by brandur-stripe** [comment]
Oh I see, so it was mostly just that the error for a missing ID is bad right? You're not blocked on anything?

**Comment by rcwwilliams** [comment]
Correct - it just took me a while to work out was going on because the error was difficult to read and unpack.

**Comment by brandur-stripe** [comment]
Cool, thanks for clarifying. I added a fix in #324.
