### ISSUE TITLE
Feature request: Stripe signature verification

### ISSUE THREAD

**Issue by guisehn** [stripe/stripe-node#332]
The section "Verifying signatures using our official libraries" at https://stripe.com/docs/webhooks only provides signature verification examples for Ruby, Python, PHP and Java. It seems this feature is missing for the node library.

**Comment by brandur-stripe** [comment]
Thanks! stripe-node support was added a little later than the other languages which is why it's not in there. We're aware though, and should have that addressed soon. I'll leave this open until it's done.

**Comment by ob-stripe** [comment]
Hey @guisehn, to clarify, the Node.js library already supports checking webhook signatures. We will shortly add sample code for this directly on stripe.com, but you can already check an example here: https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js

**Comment by guisehn** [comment]
@ob-stripe @brandur-stripe thanks! 😄

**Comment by ob-stripe** [comment]
@guisehn The feature is now documented on our official site: https://stripe.com/docs/webhooks#verify-official-libraries

I'm going to close the issue, but please feel free to reply!
