### ISSUE TITLE
Include lastResponse in error object

### ISSUE THREAD

**Issue by rcwwilliams** [stripe/stripe-node#335]
Hi

If a stripe error occurs (e.g. StripeCardError), it would be useful to be able to access the headers within the error object - particularly the date header.

Would it be possible for the error object to include either lastResponse or lastReponse.headers please?

Thanks very much.

Robin

**Comment by brandur-stripe** [comment]
Hi @rcwwilliams, I think you should be able to get these already with `lastResponse.headers`. [See an example in the test suites here](https://github.com/stripe/stripe-node/blob/5d550be589d24c66d99e243364aac755ba77fba3/test/stripe.spec.js#L101).

**Comment by rcwwilliams** [comment]
Hi Brandur

Thanks for your reply.  I have been able to use lastResponse when the call returns a response object, but now when it returns an error object.

Here is an excerpt from StripeResource.js:

          if (response.error) {
            var err;

            // These are now available on the top-level resource's
            // lastResponse, but we keep them here too for backwards
            // compatibility.
            response.error.statusCode = res.statusCode;
            response.error.requestId = res.requestId;

            if (res.statusCode === 401) {
              err = new Error.StripeAuthenticationError(response.error);
            } else if (res.statusCode === 403) {
              err = new Error.StripePermissionError(response.error);
            } else if (res.statusCode === 429) {
              err = new Error.StripeRateLimitError(response.error);
            } else {
              err = Error.StripeError.generate(response.error);
            }
            return callback.call(self, err, null);

Only the err object is passed in the callback and it does not include lastReponse.

So adding

response.error.headers = res.headers;

after

response.error.statusCode = res.statusCode;

would be helpful.

Is that viable?

Thanks very much

Robin

**Comment by brandur-stripe** [comment]
Ah yes! Sorry, I misread the original issue. That makes perfect sense.

I took at stab at this in #339.

**Comment by rcwwilliams** [comment]
Thanks very much Brandur.

I am hoping the date from the header will match the created date of the webhook generated (e.g. for charge.failed).  Please could you confirm if this is the case?

Thanks again.

Robin

**Comment by brandur-stripe** [comment]
> I am hoping the date from the header will match the created date of the webhook generated (e.g. for charge.failed). Please could you confirm if this is the case?

No, I don't think that's guaranteed. If you're trying to cross reference an API request with a received webhook, I'd recommend using `idempotency_key` or `id` with an event's `request` field. [You can see that in the docs here](https://stripe.com/docs/api/curl#event_object-request).

Note that we changed this very recently from a string field to a JSON object, so you may need to upgrade your API version to see your events match what's in the documentation there.

**Comment by rcwwilliams** [comment]
Thanks Brandur

Great that the idempotency_key is there now - thanks for making that happen.

Robin

**Comment by brandur-stripe** [comment]
No worries!

And wow, I didn't make the connection before, but I see that you are probably the same person who asked for this feature via api-discuss@. Glad that we could help :)

**Comment by rcwwilliams** [comment]
Does request id not null and idempotency key null in a webhook mean event was generated by dashboard (assuming we use idempotency keys with all our API requests)?

**Comment by brandur-stripe** [comment]
> Does request id not null and idempotency key null in a webhook mean event was generated by dashboard (assuming we use idempotency keys with all our API requests)?

That heuristic seems to work okay for now (it won't be perfect though, our subscription service may also generate events for example), but I don't think we can guarantee that it will stay true. I was actually a little surprised that our Dashboard doesn't send idempotency keys.

**Comment by rcwwilliams** [comment]
Thanks Brandur

It would be really great if request could include a further field indicating the source of the request - e.g. API or dashboard - is that reasonably manageable?

**Comment by brandur-stripe** [comment]
> It would be really great if request could include a further field indicating the source of the request - e.g. API or dashboard - is that reasonably manageable?

There are a few subtleties here like that Dashboard calls actually are API calls, but there's no technical reason that it couldn't be done.

To be honest though, I might not get to it anytime soon. One possibility to hedge against future change might be to generate your idempotency keys in a particular way like `myapp-<uuid>` so that even if we add idempotency keys from Dashboard, you'll still be able to recognize your own.

**Comment by rcwwilliams** [comment]
Thanks Brandur

Cool suggestion.

Until now, we had implemented an elaborate mechanism to determine if a webhook was from our API or the dashboard, but that mechanism could not cope 100% reliably with communication failures.  But now the idempotency key is there and armed with your excellent suggestion we can do it resiliently without having to maintain a cache at all and just with some simple logic.  I am looking forward to removing the code of ours which is now redundant. :)

Thanks so much.

Kind regards

Robin

**Comment by brandur-stripe** [comment]
> Until now, we had implemented an elaborate mechanism to determine if a webhook was from our API or the dashboard, but that mechanism could not cope 100% reliably with communication failures. But now the idempotency key is there and armed with your excellent suggestion we can do it resiliently without having to maintain a cache at all and just with some simple logic. I am looking forward to removing the code of ours which is now redundant. :)

Amazing, and I'm glad it helped! Thanks for the note :)
