### ISSUE TITLE
stripe.customers.retrieveCard validation errors

### ISSUE THREAD

**Issue by vmarchaud** [stripe/stripe-node#336]
Hello, i'm facing an issue over the method `stripe.customers.retrieveCard` : 
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Stripe: Unknown arguments (). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to GET `/customers/{customerId}/cards/{cardId}`)
    at Constructor.<anonymous> (/home/vmarchaud/xxx/node_modules/stripe/lib/StripeMethod.js:80:19)

```
If i `console.log` the content of [args](https://github.com/stripe/stripe-node/blob/master/lib/StripeMethod.js#L81), it return me : `[ undefined ]`.
I'm using the function like the following (fake data):
```
let customerId = 'cus_AXuuiULDHfsb4z'
let cardId = 'card_1AKUafKc0LtngABhArvUbgNK'
stripe.customers.retrieveCard(customerId, cardId, (err, card) => {})
```

Thanks for the help in advance.

NodeJS version : `7.9.0`
Stripe version: `4.19.0`
Stripe API version: `2017-04-06`

**Comment by jlomas-stripe** [comment]
@vmarchaud I just tried reproducing this - with Node 7.9.0 and Stripe 4.19.0 - and I can't; would you be able to provide me with the whole script (in a Gist or similar) that's failing for you here?

**Comment by vmarchaud** [comment]
@jlomas-stripe After sleeping well i found my mistake, i was giving a `null` callback. 
Is it possible to show a better error when no callback is given tho ?

**Comment by jlomas-stripe** [comment]
@vmarchaud Glad you were able to find it!

Since the function can be used with both callbacks and Promises, the callback isn't actually required here - because Promises don't require a callback - so I don't think there's any opportunity to affect that error.

**Comment by vmarchaud** [comment]
@jlomas-stripe Yeah i see, no problem :)
