### ISSUE TITLE
Cannot set empty array in request body

### ISSUE THREAD

**Issue by joelso** [stripe/stripe-node#337]
Node version: 7.9.0
Stripe node version: 4.15.0

When updating a connected account I need to set `legal_entity.additional_owners` to an empty array (null or undefined has a different meaning). However the default request data processor (`utils.stringifyRequestData`) seems to treat this as an empty value and filter it from request body.

This seems to be the default behaviour of `qs` (https://github.com/ljharb/qs) that is being used.

Should stripe-node handle this, or do I need to create a custom requestDataProcessor for this particular use case?

**Comment by jlomas-stripe** [comment]
To unset `legal_entity.additional_owners`, you need to set it to `null` and the library will convert that into an empty string when it sends the API request - which will cause Stripe to set the `additional_owners` to an empty list for you.
