### ISSUE TITLE
How to implement Payout.

### ISSUE THREAD

**Issue by umair-khanzada** [stripe/stripe-node#342]
How to implement *Payout* using this module I did't get payout object in this module.
stripe provides payout API as well, [see here](https://stripe.com/docs/api/node#create_payout)

**Comment by umair-khanzada** [comment]
Hurry,  found the issue, Transfer Api has been chaged with Payouts, [see here](https://stripe.com/docs/transfer-payout-split)

**Comment by remi-stripe** [comment]
@umair-khanzada  The Payout class was added to the library in https://github.com/stripe/stripe-node/pull/318 on March 31st. It was released on version 4.17.0 per the [Changelog](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md) so you need to upgrade to at least this version to use it.
