### ISSUE TITLE
Constructing Stripe Object Causing Application Crash

### ISSUE THREAD

**Issue by arntzel** [stripe/stripe-node#343]
I'm attempting to integrate stripe using: https://www.npmjs.com/package/stripe. In a js file I am attempting to create the Stripe object like this:

```node
import stripePackage from 'stripe'; 
const stripe = stripePackage('MY_SECRET_KEY');
```

Here is the error message I get:

```
ERROR in ./~/stripe/lib/stripe.js
     Module not found: Error: Can't resolve 'child_process' in '/Users/eliotarntz/Desktop/copernicus/node_modules/stripe/lib'
      @ ./~/stripe/lib/stripe.js 26:11-35
      @ ./src/components/CreditCard/CreditCard.js
      @ ./src/routes/payment/payment.js
      @ ./src/routes/payment/index.js
      @ ./src/routes/index.js
      @ ./src/router.js
      @ ./src/client.js
      @ multi babel-polyfill react-hot-loader/patch webpack-hot-mid
```

I can confirm this is a node application using React JS. Spoke to kaylined in IRC who recommended posting here.

**Comment by ob-stripe** [comment]
@arntzel It looks like the library is unable to import the [`child_process` module](https://nodejs.org/api/child_process.html). Which version of Node are you using?

**Comment by chrisvariety** [comment]
It looks like you are trying to use Stripe on the client side, within the browser. This package should only to be used within Node itself on the server side, not on the client side. You'll want to use Stripe.js on the client side: https://stripe.com/docs/stripe.js

Note your secret key should never be exposed to the client.
