### ISSUE TITLE
'Received unknown parameter: timestamp' on creating an account

### ISSUE THREAD

**Issue by ayagovdik** [stripe/stripe-node#346]
Constantly receiving 'Received unknown parameter: timestamp' error on trying to create managed account.

I dump data right before calling stripe API so I am sure timestamp key is not added by my code

```
logger.error('data', data)
return stripe.accounts.create(data)
```

So I see

```
error: data
{ legal_entity: {},
  country: 'US',
  type: 'custom',
  tos_acceptance: { date: 1496838203, ip: '127.0.0.1' },
  transfer_schedule: { interval: 'monthly', monthly_anchor: 5 } }
```

on Stripe's Dashboard Logs I see the same but with timestamp key added

**Request POST body**

```
{
  "country": "US",
  "type": "custom",
  "tos_acceptance": {
    "date": "1496836904",
    "ip": "127.0.0.1"
  },
  "transfer_schedule": {
    "interval": "monthly",
    "monthly_anchor": "5"
  },
  "timestamp": "2017-06-07T12:01:44.173Z"
}
```

Stripe API complains about excessive timestamp param:

**Response body**

```
{
  "error": {
    "type": "invalid_request_error",
    "message": "Received unknown parameter: timestamp",
    "param": "timestamp"
  }
}
```

Stripe lib v4.22.0
Node v6.9.1

**Comment by remi-stripe** [comment]
@ayagovdik I've tried on my end and with the version 4.22.0 I'm able to create managed accounts without issue. This is unlikely to be a bug in the library as the word [timestamp](https://github.com/stripe/stripe-node/search?utf8=%E2%9C%93&q=timestamp&type=) is only used in the docs or for webhooks. There's something in your code that must be adding that extra parameter incorrectly.

**Comment by skylarmb** [comment]
@ayagovdik solution? You closed this issue but didn't say how you fixed it.

**Comment by skylarmb** [comment]
I figured this out. We were using Winston Logger. We logged the request object right before sending it off to stripe. When you log an object with Winston, it modifies the object you pass it and adds a timestamp field to it. The object is then sent to stripe. This is just poor design on the part of Winston Logger.
