### ISSUE TITLE
How to retrieve the Id of invrc_xxxxxxxxxxxx

### ISSUE THREAD

**Issue by zo-tahiana** [stripe/stripe-node#350]
Hello,

From the Stripe dashboard I can view a receipt (click preview link in invoice details). The receipt is then shown inside a popup but there is a permalink in it, so it can be viewed as a separate page. The URL of an emailed receipt looks like this:

https://dashboard.stripe.com/emails/receipts/invrc_xxxxxxxxxxxx

This URL does not require authentication, and so would be perfect for allowing me to show links to receipt details from inside my app's billing page. Except that there seems to be no way to get the magical invrc_xxxxxxxxxxxx id from the API, so I am unable construct the URL.

There is a way for me to retrieve that Id?

Thanks.

**Comment by remi-stripe** [comment]
@zo-tahiana The Issues on this github repository are here to report bugs in the library itself. This question is more an API question that you should be discussing with our [support team](https://support.stripe.com/email).

To answer your question, this information is not available in the API so you can not access in Node.js or in any other library. It's only available for the end-customer as a link in the email receipt they get.

If you want to display a web version of their receipt, you'll need to build this on your end. We might make this available in the future but we have no plan for this at the moment.
