### ISSUE TITLE
Arguments are not getting URLEncoded

### ISSUE THREAD

**Issue by andrewnelder** [stripe/stripe-node#355]
It looks like arguments are not getting urlencoded, meaning setting things like `receipt_email` on the Create a Charge [1] API Endpoint will actually break if you pass in an email with a `+` symbol.

I ~think the issue is here, but I've not had a lot of time to dig into where it is with absolute certainty:
https://github.com/stripe/stripe-node/blob/ee3e1077295d69ab19f19e032f4fe93c0595d511/lib/utils.js#L26-L28

The `Content-Type`-headers of the request seem to be successfully getting set as `application/x-www-form-urlencoded`; however, the querystring itself isn't actually getting encoded.

**Comment by ob-stripe** [comment]
That's weird -- [qs](https://github.com/ljharb/qs) should take care of URL-encoding the parameters, e.g.:

```node
> var qs = require('qs');
> qs.stringify({receipt_email: 'stripe+test@stripe.com'});
'receipt_email=stripe%2Btest%40stripe.com'
```

I was also able to create a charge like this:
```node
> var stripe = require('stripe')('sk_test_...');
> stripe.charges.create({
  source: 'tok_visa',
  amount: 1099,
  currency: 'eur',
  receipt_email: 'stripe+test@stripe.com'
});
```
and the email address was correctly decoded on the API's end.

Happy to investigate this further with you -- ping me :)
