### ISSUE TITLE
/oauth/token for connect endpoint? 

### ISSUE THREAD

**Issue by stokesbga** [stripe/stripe-node#360]
I cant find a method for the /oauth/token endpoint - specifically for getting an account ID for Connect. https://stripe.com/docs/connect/express-accounts

**Comment by remi-stripe** [comment]
@stokesbga  We don't have such methods in the Node library yet. We'd love a PR if you are open to implement this. Otherwise, you'll need to make the HTTP request yourself as documented [here](https://stripe.com/docs/connect/sample-oauth-apps)

**Comment by stokesbga** [comment]
Ok cool, thanks! Im just making my way through connect docs now, so I'll try to expand my understanding before I PR.

**Comment by Charliekenney23** [comment]
@remi-stripe What would an appropriate path for adding this stripe method? Should this be in a connect namespace, or maybe just `Stripe.OAuth.connectToken`?
