### ISSUE TITLE
Rate limiter

### ISSUE THREAD

**Issue by jpike88** [stripe/stripe-node#362]
This really should have a built in rate limiter function.

**Comment by remi-stripe** [comment]
@jpike88 Would you mind providing a bit more details around what you expect to see in the library exactly? I'm not sure I understand how you would see the feature work in that case.

**Comment by jpike88** [comment]
Stripe presumably has a rate limiter on their API... it's not clear in their documentation what that would be, or if it's even low enough to ever be a concern, but this library should probably have some sort of default rate which is considered 'respectful' to the API, so tests via this library that burst huge amounts of test calls etc don't accidentally trigger problems.

**Comment by remi-stripe** [comment]
@jpike88 Our rate limits are not binary and depends on the activity in your account and what else your integration is doing at the same time. This is not something we can really add to the library as there's no "connection pool" or similar for requests.

We recommend that your integration catches rate limit errors and, if that happens, reduces the frequency of your requests. Each failed request is perfectly safe to retry as they have not been processed. When reducing your request frequency, we recommend an exponential backoff by first waiting one second before trying again. If your request continues to receive the same response, wait two seconds, then four seconds, etc. If you are using an idempotency key with your retries you will continue to receive the same response. You must change the key when retrying the request.
