### ISSUE TITLE
Feature Request: Request & Response logging

### ISSUE THREAD

**Issue by inversion** [stripe/stripe-node#364]
I'd like to propose adding a way of hooking into request and response events so they can logged. My use-case is for post-mortem of failed requests and general analysis. I find the dashboard's Logs view rather lacking (one has to advance through it page-by-page, it's slow, and search by request ID doesn't seem to be implemented).

I could add a separate wrapper around the stripe API functions to do this, but I wanted to gauge if there was any more general interest in this to see if it's worth making a PR.

**Comment by brandur-stripe** [comment]
Hi @inversion,

One thing we're interested in doing is adding a request logging facility to our various libraries including this one. Currently [it's only implemented in stripe-python](https://github.com/stripe/stripe-python/pull/269/files), but it's really just a matter of porting the conventions over to here.

This is a little different than what you're suggesting though in that the logging format would be information, but with a predefined structure and format. Would that be sufficient for your needs?

**Comment by jlomas-stripe** [comment]
I don't know if/how this fits with the approach we're using here (or if it's still relevant in 2017 😂) but it's an approach I've used a bunch - and quite like, since it creates a loosely coupled way of handling this:

I wonder if it might be worth emitting some events - say `request`, `response`, `error`? - on the `stripe` instance object that could be listened to for ... whatever purpose one wanted, up to and including debug logging?

**Comment by inversion** [comment]
I think either approach could work well, but with the logger method it would be preferable if we could avoid a need to scrape JSON out of human-readable strings.

**Comment by brandur-stripe** [comment]
> I wonder if it might be worth emitting some events - say request, response, error? - on the stripe instance object that could be listened to for ... whatever purpose one wanted, up to and including debug logging?

Yeah, that might make sense. I'm working on implementing `STRIPE_LOG` for stripe-ruby right now, and I'll see if I can work this in to have the two features work in relative harmony.

**Comment by jlomas-stripe** [comment]
I've got a first-run at adding the emitter stuff, and of course the first question that comes up is this:

> _What should be emitted for the `request`?_

I'm not sure the raw `http` `request` object quite makes sense - but maybe?  I mean, that's what you'd find in an Express route, for example.  Alternatively, we could just ... figure out what's relevant and compose an object that includes that stuff, I guess?

@brandur-stripe What kinds of things are usually being logged wrt `request` and `response`?

**Comment by brandur-stripe** [comment]
@jlomas-stripe Check this out:
https://github.com/stripe/stripe-ruby/pull/566

Request logging looks something like this:

``` ruby
      Util.log_info("Request to Stripe API",
        api_version: context.api_version,
        idempotency_key: context.idempotency_key,
        method: context.method,
        path: context.path
      )
```

And response:

``` ruby
      Util.log_info("Response from Stripe API",
        api_version: context.api_version,
        elapsed: Time.now - request_start,
        idempotency_key: context.idempotency_key,
        method: context.method,
        path: context.path,
        request_id: context.request_id,
        status: status
      )
```

I'd be in favor of minimizing the interface to just these sorts of specific fields (rather than sending a raw HTTP response) because it would get people 99% of what they need and give us a little more flexibility down the road.

**Comment by jlomas-stripe** [comment]
Sweet.  I can totally duplicate that.  And I think that makes sense to me.

Is that what we're standardizing on in terms of logging content (and that will eventually live in all the libraries)?

**Comment by jlomas-stripe** [comment]
@brandur ...Should those include the `stripe_account` if it was provided as well?

**Comment by brandur-stripe** [comment]
> Is that what we're standardizing on in terms of logging content (and that will eventually live in all the libraries)?

Yeah, I think that this is a good start in terms of what fields to standardize on (although we're nowhere near that yet of course :).

> ...Should those include the stripe_account if it was provided as well?

Yep, great idea. I called it just `account` in stripe-ruby, but have added that in #568. I'll add this and `num_retries` into the code snippets above.

**Comment by jlomas-stripe** [comment]
Awesome.  I'll retitle it to `account`.

...and ... something something `num_retries`. ¯\_(ツ)_/¯ :joy:

**Comment by jlomas-stripe** [comment]
@inversion You can now `stripe.on('request', onRequest);` and `stripe.on('response', onResponse);` in [4.24.0](https://github.com/stripe/stripe-node/releases/tag/v4.24.0).  Just FYI. :)
