### ISSUE TITLE
`jscs` ded.  Can we replace it?

### ISSUE THREAD

**Issue by jlomas-stripe** [stripe/stripe-node#367]
Per [this](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.3qrw9jwnz), jscs is no more.  And ... I end up with a 'JavaScript heap out of memory' error every time I try to run it locally...

Can we move to ESLint?

**Comment by brandur-stripe** [comment]
Yep, make sense to me.

**Comment by jlomas-stripe** [comment]
\o/

Ok, I will take a run at it.  Thanks! :)

**Comment by jlomas-stripe** [comment]
Welp, I don't think that's going to work.  [stripe/eslint-config-stripe](https://github.com/stripe/eslint-config-stripe) is a thing, but it seems to be all ES6y and meant for / coupled with React - i.e., includes some React/JSX-specific dependencies, which definitely don't need to be included in this repo just to get ESLint working.

It would be good to move this repo towards using ESLint, but I'm not sure what the best strategy is here - thoughts?

**Comment by AdriVanHoudt** [comment]
@jlomas-stripe try `eslint --init` ;)

**Comment by deontologician-stripe** [comment]
Looks like @ob-stripe is working on this in #383

**Comment by ob-stripe** [comment]
Closed via #383.
