### ISSUE TITLE
How to use stripe in vue?

### ISSUE THREAD

**Issue by rvasoya** [stripe/stripe-node#370]
I'm having trouble in using charge.
I've successfully generated token with stripe.createToken() which return me token.id.
Now when i try using charge.create() it return not a function.

when i use  "import stripe from 'stripe' "i get the error "child_process in ./~/stripe/lib/stripe.js"

**Comment by remi-stripe** [comment]
@rvasoya This library works on your server not in the browser. You need to install stripe-node on your server if you want the ability to use this library.

You can read more about how charging through Stripe works here: https://stripe.com/docs/tutorials/charges

If you have follow-up questions, I'd recommend chatting with our support team here: https://support.stripe.com/email
