### ISSUE TITLE
Cannot unset personal_id_number in updating managed account in Canada

### ISSUE THREAD

**Issue by msteckyefantis** [stripe/stripe-node#372]
API version: 2017-06-05
node stripe version:  4.22.0

updating stripe custom connect account with the following parameters:
```
{
    "legal_entity": {
        "personal_id_number": null
    }
}
```

returns this error:

```
Error: CA ID numbers must be 9 characters long
```

but [in the documentation it says](https://stripe.com/docs/api#update_account-legal_entity-personal_id_number): 
```
This can be unset by updating the value to null and then saving.
```

Is this is a bug? Because I don't see that I'm doing anything wrong. When I'm setting the value using a tokenized SIN number I am having no issues.

Unless I have to tokenize `null`? I'll try that now.

**EDIT:**  Tokenizing `null` doesn't work and when I try to tokenize the empty string I get the following error:
```
"You passed an empty string for 'pii[personal_id_number]'. We assume empty values are an attempt to unset a parameter; however 'pii[personal_id_number]' cannot be unset. You should remove 'pii[personal_id_number]' from your request or supply a non-empty value."
```

Anyways, any help would be appreciated, thank you very much for your time.

**Comment by remi-stripe** [comment]
@msteckyefantis Unfortunately the docs are incorrect and you can not unset this value. I'll raise to our docs team to make sure this gets fixed.

**Comment by msteckyefantis** [comment]
@remi-stripe Okay thank you for clarifying how this works.👍🏿👍🏻👍🏽

**Comment by tongwa2020** [comment]
> @msteckyefantis Unfortunately the docs are incorrect and you can not unset this value. I'll raise to our docs team to make sure this gets fixed.

We outsourced the development of our app. During testing the ACH on Stripe, we keep getting an error message
"cannot provide both id_number and ssn_last_4 unless they match"

Developers have not been able to figure this message. What are we missing?

**Comment by remi-stripe** [comment]
@tongwa2020 This issue is almost 6 years old and for something different. Please work directly with our support team and they can help you instead: https://support.stripe.com/contact

Just from the error message, it seems you are passing both `id_number` and `ssn_last_4` but they don't match so the first one would be the SSN and the last 4 digits are different from what you pass in `ssn_last_4` but they should match. Our support team can help if you have further questions
