### ISSUE TITLE
Limit parameter in list calls with api key not working

### ISSUE THREAD

**Issue by BenBestmann** [stripe/stripe-node#373]
When using `.list()` with the `api_key` option it seems that the `limit` parameter is being ignored. 

For example `stripe.subscriptions.list({ limit: 100, api_key: 'sk_XXX' }, cb)` will always return 10 subscription items in the data object of the callbacks response.

When I set the key using `const stripe = require('stripe')('sk_XXX')` the call works just fine and returns the desired 100 items.

Stripe Node version: 4.24.0
Node version: v8.1.4

**Comment by remi-stripe** [comment]
@BenBestmann If you want to pass a specific API key and extra parameters you need to separate the two. The code would be
```
stripe.subscriptions.list({ limit: 100}, {api_key: 'sk_XXX' }, cb)
```
