### ISSUE TITLE
Cannot unset identity document when updating connected accounts

### ISSUE THREAD

**Issue by msteckyefantis** [stripe/stripe-node#377]
**Check out #372 first,**
this is pretty much it is the same issue as #372 except the same thing is happening for the verification document. I am wondering if it is for the same reason, because the documentation is incorrect? Or if I am making a mistake?

### The situation I'm facing👷🏿👷🏻👷🏽:

When I have a request body to update a stripe custom connected account like this:
```.js
{
    "legal_entity": {
        "verification": {
            "document": null
         }
     }
}

```

you get the following error:
```
Error: No such file upload:
```

But in the [update account documentation](https://stripe.com/docs/api#update_account), it says:

>This can be unset by updating the value to `null` and then saving.

Like in the case of the personal_id_number, is this the same issue, where the documentation is incorrect? Or am I doing something wrong?

Thank you very much for your time and help with this!

Stripe is #swaggy🐲🐉

**Comment by remi-stripe** [comment]
@msteckyefantis it's a similar limitation. At the moment the documentation is incorrect and I'll work with the team on fixing it!

**Comment by msteckyefantis** [comment]
@remi-stripe Okay thanks for getting back to me!
