### ISSUE TITLE
Typescript object causes error when calling charges.create()

### ISSUE THREAD

**Issue by kylevogt** [stripe/stripe-node#390]
Node version:  8.4.0
Stripe version: 4.23.1

I created a model representing a Stripe Charge object in typescript so we can ensure type safety when building requests. However, when using that Stripe Charge object  when calling charges.create, I get the error: 

>TypeError: Path must be a string. Received undefined

### Relevant Code:

```
// This causes the mentioned error
const paymentRequest = new StripeCharge();
paymentRequest.amount = req.amount;
paymentRequest.currency = req.currency;
paymentRequest.customer = req.customerId;
paymentRequest.source = req.token;

const response: StripeCharge = await this.stripe_client.charges.create(paymentRequest);
```

```
// This does not cause the error
const test: any = {
    amount: req.amount,
    currency: req.currency,
    customer: req.customerId,
    source: req.token
}

const response: StripeCharge = await this.stripe_client.charges.create(test);
```

By debugging the stripe library I was able to narrow it down to `isPlainObject(args[0])` returning false in `getDataFromArgs` inside util.js

```
getDataFromArgs: function(args) {
  if (args.length > 0) {
    if (isPlainObject(args[0]) && !utils.isOptionsHash(args[0])) {
      return args.shift();
    }
  }
  return {};
},
```

I am able to work around this temporarily by importing toPlainObject from lodash, but we have no other use for lodash so I'd much rather not include the unneeded dependency.

**Comment by brandur-stripe** [comment]
Hm, we should improve that error message, but I'm not completely sure that we should change this behavior. Imagine if in another typed you had a 3rd party library with a function, wrote your own parameter class it, and then tried to invoke the function with your class — you'd fully expect it to compile/fail.

It's pretty suboptimal that the primitive in JavaScript is a plain object with no type safety, but that doesn't mean that libraries should be accepting any kind of foreign input. Your workaround above where you convert your custom object to a plain one might be the best way to go about this until we can get some more official Typescript support for the library.

**Comment by kylevogt** [comment]
Personally, I think this is over validation. If the object you pass in has the properties needed, the library should be able to take those values and build the request. But, the work around works for now. I'll be eagerly anticipating more official Typescript support :D

**Comment by brandur-stripe** [comment]
> Personally, I think this is over validation. If the object you pass in has the properties needed, the library should be able to take those values and build the request.

Yeah, I definitely see your point. Is there some kind of middle ground that we could go for like if I could recognize a non-primitive TypeScript object from outside of TypeScript? I notice that it has an `object` type that would work pretty well for this, but I'm not sure whether I'd able to access it from this library.

> But, the work around works for now. I'll be eagerly anticipating more official Typescript support :D

I can't promise anything right away, but I'd seriously love to do this!

**Comment by kylevogt** [comment]
Perhaps you could use toPlainObject() from lodash to strip the object down? I haven't tested what it does to setter/getters but it does strip away functions, etc. Maybe that is enough to "clean" the object before trying to retrieve values from it?

**Comment by ahaverty** [comment]
Hitting the same issue as @kylevogt 
I expected Stripe-node to gracefully handle nulls and undefined values for non-required properties.
`_.toPlainObject(chargeInstance);` _is a nice quick workaround though_ 👌

**Comment by rattrayalex-stripe** [comment]
I don't think `toPlainObject` is quite right here, since that might have unexpected consequences with callbacks, which can be passed there. 

I might recommend using the DefinitelyTyped types, and/or typed objects in its style (eg; https://github.com/DefinitelyTyped/DefinitelyTyped/blob/48cb1f5/types/stripe/index.d.ts#L943)

Closing for now; thanks for reporting!

**Comment by zaksesti-ns8** [comment]
We use the types internally but we don't want to expose them to others consuming our code.  I have my own paired down types.  `Customer`.  When calling `customers.create` I would expect to be able to pass in any object or class that matches the shape of the `ICustomerCreationOptions`.  Instead we get this error.  

Am I understanding the concern?  We fear allowing extra data in calls to the stripe api?  Shouldn't the stripe api validate that?  If I'm not adhering to the spec I don't mind the round trip to point out my error.  If that is the fear then the `isPlainObject` check is an overstep.  I'm not passing any extra parameters but am still unable to call create.  Perhaps I've missed the point but as I understand it this seems like a bug.
