### ISSUE TITLE
customer/cards -> customer/sources

### ISSUE THREAD

**Issue by mathieug** [stripe/stripe-node#391]
In the code (https://github.com/stripe/stripe-node/blob/master/lib/resources/CustomerCards.js#L17), the client targets this endpoint: `DELETE https://api.stripe.com/v1/customers/{CUSTOMER_ID}/cards/{CARD_ID}`
In the documentation (https://stripe.com/docs/api/curl#delete_card), the endpoint is: `DELETE https://api.stripe.com/v1/customers/{CUSTOMER_ID}/sources/{CARD_ID}`
It seems customer/cards has been replaced by customer/sources.

**Comment by remi-stripe** [comment]
@mathieug those endpoints are interchangeable for cards and work the same way. Definitely worth improving in the future but it would not change anything to your integration.

**Comment by mathieug** [comment]
I was mocking (w/ nock) customer/sources instead of customer/cards because the documentation. Maybe I'm not the only one who can be confused :)
