### ISSUE TITLE
Webhooks.constructEvent() returning "No signatures found matching the expected signature for payload"

### ISSUE THREAD

**Issue by danpreece** [stripe/stripe-node#396]
On the current master branch, so version 5.1.1 in Webhooks.js on line 52

```
var signatureFound = !!details.signatures
      .filter(utils.secureCompare.bind(utils, expectedSignature))
      .length;
```

I believe the double exclamation mark is an error. 

I am confident that the details being supplied to the function are correct and when I remove one of the exclamation marks the method works as expected.

If this isn't an error though, then something else is going on in my code so let me know :)

**Comment by ob-stripe** [comment]
@danpreece That line is correct -- the double exclamation mark is just a "trick" to turn the result of `.length` (an integer) into a boolean. I.e. the code does the same thing as:

```node
var signatureFound = details.signatures
      .filter(utils.secureCompare.bind(utils, expectedSignature))
      .length != 0;
```

By removing one of the exclamation marks, you're reversing the condition. This is definitely not what you want :)

A common error is to call `constructEvent` with a payload that was decoded and re-encoded as JSON. The resulting payload would very likely be different from the initial payload sent by Stripe and would cause the signature verification to fail.

I'm closing the issue, but feel free to reply or write to support at https://support.stripe.com/email if you need more help.

**Comment by danpreece** [comment]
@ob-stripe thank you for the prompt response and pointing me in the right direction.

I have returned the second ! and I am now passing the raw body from Stripe into the function without decoding and re-encoding

**Comment by ob-stripe** [comment]
Glad I could help!

**Comment by rachaelshaw** [comment]
@ob-stripe Thanks for the tip!

By the way, in case it helps anyone in the future, it seems the issue when re-stringifying (e.g. after auto-decoding) is that Stripe's API is stringifying empty dictionaries `{}` as `{\n  }`, which would require custom post-processing when using `JSON.stringify()` (or possibly a custom replacer function- we didn't take the time to experiment further).

Here's a quick script that demonstrates that:

```js
// First:
var x = 'the raw, specially-formatted JSON string sent from stripe as the body of the webhook request';

// Then:
var y = JSON.stringify(JSON.parse(x), undefined, 2);
for (let i=0; i<Math.max(x.length, y.length); i++) { if (y[i] !== x[i]) { console.log('Issue detected at character '+i+':', '`'+x[i]+'` vs. `'+y[i]+'`\nContext:\n'+x.slice(i-10, i+10)); break; }  }
```

One other thing:  Rather than re-engineering how you have the body parser in your app set up, another solution which we're using currently, is just to circumvent Stripe's signing altogether and just use your own shared secret as part of the webhook URL itself.  This has worked great for us thus far, with a comparable level of security.  Hope that helps!

cc @mikermcneil

**Comment by inorganik** [comment]
If it helps anyone - I struggled with this error for hours only to discover that somehow my webhook secret had changed.

**Comment by akanksha1909** [comment]
I am using npm stripe version 3.5.0(old version probably 4 years ago) and while verifying the webhook signature, i am getting error **TypeError: Cannot read property 'ConstructEvent' of undefined**. I am using rawBody. i am not sure is the stripe npm version is problem or something else? 
```
function getRawBody(req, res, next) {
  req.rawBody = '';

  req.on('data', function (chunk) {
    req.rawBody += chunk;
  });
  req.on('end', function () {
    next();
  });
}

```
```
app.post('/shook',getRawBody, (request, response) => {
  const sig = request.headers['stripe-signature'];
  let event;
  try {
    event = stripe.webhhoks.constructEvent(request.rawBody, sig, endpointSecret);
  } catch (err) {
    console.log(err)
    return response.status(400).send(`Webhook Error: ${err.message}`);
  }

  // Handle the checkout.session.completed event
  if (event.type === 'checkout.session.completed') {
    const session = event.data.object;
  
    //Complete function here ...
  }

  // Return a response to acknowledge receipt of the event
  response.json({received: true});
});

```

**Comment by olso** [comment]
Just struggled with this for several hours as well, I went all in and then figured it out

<img width="1792" alt="Screenshot 2020-07-04 at 00 33 04" src="https://user-images.githubusercontent.com/7975158/86500198-c7e70300-bd8f-11ea-9b6b-d453187a69ff.png">

I may have missed something in the docs, but whatever.

I didn't notice that the signing secret `stripe-cli` returns is different from the one in the Dashboard...

```
> Ready! Your webhook signing secret is whsec_BVJbVWWKILZjcpoIzr5Et7pPF7JwqxHi (^C to quit)
```

Also these

https://github.com/stripe/stripe-cli/issues/472

https://github.com/stripe/stripe-cli/issues/475

**Comment by mushgev** [comment]
> Just struggled with this for several hours as well, I went all in and then figured it out
> 
> <img alt="Screenshot 2020-07-04 at 00 33 04" width="1792" src="https://user-images.githubusercontent.com/7975158/86500198-c7e70300-bd8f-11ea-9b6b-d453187a69ff.png">
> 
> I didn't notice that the signing secret `stripe-cli` returns is different from the one in the Dashboard...
> 
> ```
> > Ready! Your webhook signing secret is whsec_XXX (^C to quit)
> ```
> 
> I've completely missed this in the docs... https://github.com/stripe/stripe-node/blob/8f3c3ec49634e509f90cb4fd55aedf5dc0a4dfe3/examples/webhook-signing/README.md#setup
> 
> These can help ease the pain maybe
> 
> [stripe/stripe-cli#472](https://github.com/stripe/stripe-cli/issues/472)
> 
> [stripe/stripe-cli#475](https://github.com/stripe/stripe-cli/issues/475)

Thanks for saving me hours!

**Comment by jjb3rd** [comment]
> It was because I was building a connect webhook but using the signing secret for account.
> I also learned that each time you create a new webhook, it gives you a new signing secret specifically for that webhook.

DOH!!!  I just wasted a day and a half on this! Thanks @inorganik

**Comment by nightzirch** [comment]
Glad to see I'm not the only one who wasted precious time only to realize by @olso's comment that the cli spits out a new secret for you to use. Big thanks!
