### ISSUE TITLE
Feature Request - FileUpload should start supporting streams

### ISSUE THREAD

**Issue by mckn** [stripe/stripe-node#401]
Hello,

I would be super happy if you could start to support uploading files to your service by passing a stream. It would increase performance and improve the structure of the code.

Thanks in advance!

**Comment by ob-stripe** [comment]
Hey @mckn! Thanks for the feature request. This does sound like a good idea!

**Comment by ob-stripe** [comment]
This was implemented by @jjsquillante in #471 and released as 6.3.0.
