### ISSUE TITLE
Signature header: TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by immexerxez** [stripe/stripe-node#409]
Using serverless Lambda to consume webhooks and I can't get Signature validation working with the SDK. I am getting the raw body but I keep getting some variation of the Stripe-Signature not being consumed properly. I've tried converting to json string, toString(), creating a buffer, etc but no luck.

**Comment by ob-stripe** [comment]
@immexerxez The raw body _is_ a string. If you're receiving an array or object, then the JSON string has already been deserialized and you will not be able to convert it back to the exact original string.

I don't have experience with Lambda myself, but this comment from another user might be helpful: https://github.com/stripe/stripe-node/issues/356#issuecomment-311658193.

Closing this issue as I don't think it's a bug with the Node library, but feel free to reply here or on the other issue.

**Comment by jaynsw** [comment]
The example is wrong.The endpoint security key should be a buffer type.

let event = stripe.webhooks.constructEvent(req.body, sig, Buffer.from(endpointSecret));

**Comment by jaynsw** [comment]
The node version is 8. My program throws error when it is string. The error is fixed after changing it to buffer Type. The stack trace is below: 

TypeError: Key must be a buffer at new Hmac (crypto.js:117:16) at Object.createHmac (crypto.js:643:10) at Object._computeSignature (/node_modules/stripe/lib/Webhooks.js:24:19) at Object.verifyHeader (/node_modules/stripe/lib/Webhooks.js:55:34) at Object.constructEvent (/node_modules/stripe/lib/Webhooks.js:13:20) at Object.processStripeEvent (/code/service.js:1120:31) at router.post (/code/routes/open.js:159:10) at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5) at next (/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)

**Comment by ob-stripe** [comment]
@jaynsw Node 8 also accepts strings for keys (cf. https://nodejs.org/docs/latest-v8.x/api/crypto.html#crypto_crypto_createhmac_algorithm_key_options), but I think always returns "Key must be a buffer" when the key is of an unexpected type.

Can you check the exact type of your `endpointSecret` variable? E.g. with something like `Object.prototype.toString.call(endpointSecret)`.

**Comment by jaynsw** [comment]
Hi Olivier,

My code is exactly same as the example. The endpoint secret key is hard
coded in string.

The program running on docker node8-slim image.

**Comment by ob-stripe** [comment]
@jaynsw Do you mean the example [in this repo](https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js)? If so, then what's likely happening is that the `WEBHOOK_SECRET` environment variable is not set. This would result in `webhookSecret` being undefined, which in turn causes the error message you're seeing. We could add a check for this case to return a more helpful error.

If you're referring to the example [on Stripe's website](https://stripe.com/docs/webhooks/signatures#verify-official-libraries) and `endpointSecret` is indeed a hardcoded string, then I'm not sure what's happening. There's really no reason for this error to appear if the secret is indeed of type `String`.

**Comment by jaynsw** [comment]
This is the link of example.
https://stripe.com/docs/webhooks/signatures

**Comment by jake-nz** [comment]
I can confirm in Node 8 webhookSecret can be a string, but if it's an empty string you will get "Key must be a buffer"
