### ISSUE TITLE
Calling any `stripe.exchangeRates` result in `Unrecognized request URL` error

### ISSUE THREAD

**Issue by tinovyatkin** [stripe/stripe-node#411]
Anything you had in tests actually results in `Unrecognized request URL` error:

`await stripe.exchangeRates.list()` or `await stripe.exchangeRates.retrieve('USD')`

Is that API released to Node library but not live?

**Comment by ob-stripe** [comment]
Hi @tinovyatkin. That's correct, the `/v1/exchange_rates` endpoint is not publicly available yet. I don't have an ETA for when that will be the case, but you can write to support at https://support.stripe.com/email to inquire about this.

**Comment by tinovyatkin** [comment]
That's some of rarest things I even seen - to release API in helper library, but not release the API actually.

**Comment by brandur-stripe** [comment]
> That's some of rarest things I even seen - to release API in helper library, but not release the API actually.

Although probably better than the reverse :)

We usually try to get the library releases a little closer to the product release, but I think in this case we had to make a few last minute changes server-side.

**Comment by ramseth001** [comment]
Hi. Has this api endpoint been made publicly available?

**Comment by remi-stripe** [comment]
@ramseth001 It has not unfortunately. It stayed in beta and was quickly deprioritized so we aren't giving access to that API for now. I'd recommend discussing this with our support team if you have follow up questions: https://support.stripe.com/contact
