### ISSUE TITLE
Uncaught error: Cannot assign to read only property 'stack' of object 'Error'

### ISSUE THREAD

**Issue by DamodarSojka** [stripe/stripe-node#414]
When calling:

```js
this.Stripe.charges.create({
                    amount: 49900,
                    currency: "GBP",
                    description: "Subscription",
                    source: token,
                })
```

with 4000000000000341 (Attaching this card to a Customer object succeeds, but attempts to charge the customer fail.) I receive the following error:

```
Uncaught error: Cannot assign to read only property 'stack' of object 'Error', stack: TypeError: Uncaught error: Cannot assign to read only property 'stack' of object 'Error'
```

When the code is run with a "normal card" (for example: 4242424242424242) everything works fine.
Stack trace:
```
TypeError: Uncaught error: Cannot assign to read only property 'stack' of object 'Error'
at Constructor.populate (/server/node_modules/stripe/lib/Error.js:36:16)
at Constructor._Error (/server/node_modules/stripe/lib/Error.js:11:17)
at Constructor (/server/node_modules/stripe/lib/utils.js:124:13)
at Constructor (/server/node_modules/stripe/lib/utils.js:124:13)
at IncomingMessage.<anonymous> (/server/node_modules/stripe/lib/StripeResource.js:177:13)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1045:12)
at _combinedTickCallback (internal/process/next_tick.js:102:11)
at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

"stripe": "^5.3.0"
alpine-node:8.1.0

**Comment by ob-stripe** [comment]
@DamodarSojka How are you assigning `this.Stripe`?

**Comment by DamodarSojka** [comment]
I have tried both 
import * as Stripe from "stripe";
...

this.Stripe = new Stripe(API_KEY) ; (with @types/stripe)
and 
this.Stripe = require("stripe")(API_KEY);

**Comment by ob-stripe** [comment]
I cannot seem to reproduce this on my end. Do you think you can provide a minimal example to reproduce the issue? You can use `source: "tok_chargeCustomerFail"` instead of a client-side created token.

**Comment by DamodarSojka** [comment]
Do you think you can provide a minimal example to reproduce the issue? - I would love to! Not sure how to approach that however...

Same issue when using source: "tok_chargeCustomerFail". Btw, I didn't know I can simulate invalid token like that, is there a list of those somewhere?

**Comment by ob-stripe** [comment]
> I would love to! Not sure how to approach that however...

If you can reliably reproduce the issue, try stripping the code until you get to the bare minimum needed to showcase the issue, and share the code here (you can use gist.github.com or pastebin.com if the code is too long).

> Btw, I didn't know I can simulate invalid token like that, is there a list of those somewhere?

Yes, in the [testing](https://stripe.com/docs/testing#cards-responses) doc page, you can click the "Tokens" tab to show static test tokens.

**Comment by DamodarSojka** [comment]
It seems that this code makes the stripe code to fail:
Object.defineProperty(Error.prototype, "stack", {
    configurable: true,
    enumerable: true,
});

It is meant to help with logging in hapi. Read more here: https://github.com/hapijs/hapi/issues/2744

**Comment by ob-stripe** [comment]
Thanks! I was able to reproduce the issue with this code:

```js
Object.defineProperty(Error.prototype, "stack", {
  configurable: true,
  enumerable: true,
});

this.Stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

this.Stripe.charges.create({
  amount: 400,
  currency: 'usd',
  source: 'tok_chargeCustomerFail',
});
```

Simply adding `writable: true` to the list of properties seems to solve the issue:

```js
Object.defineProperty(Error.prototype, "stack", {
  configurable: true,
  enumerable: true,
  writable: true,
});
...
```

Can you give it a try and let me know if that solves the problem for you?

**Comment by DamodarSojka** [comment]
Adding writable: true solves the problem. Thank you very much!
