### ISSUE TITLE
If i want to update connect account details than how can i . 

### ISSUE THREAD

**Issue by manojown** [stripe/stripe-node#419]
whenever i try to update its throw error - { Error: You cannot change `legal_entity[personal_id_number]` via API if an account is verified. Please contact support@stripe.com if you need to change the legal entity information associated with this account.}
2 . when i create account with managed :true and    transfer_schedule: {
"delay_days": 7,
"interval": "daily"
 }, than its also show a error that - Error: Received unknown parameters: managed, transfer_schedule
}
help me to out of this. please

**Comment by remi-stripe** [comment]
If an account is verified, you can not modify most things under the `legal_entity` hash. This means you should not be passing this parameter at all when you call the Update Account [API](https://stripe.com/docs/api#update_account).

As for the account creation, `managed: true` has been deprecated months ago in favor of `type: "custom"` and `transfer_schedule` has been renamed to `payout_schedule`.

If you have any follow up questions, you should reach out to our support team directly. Github issues should be limited to bugs in the library itself. You can talk to them here: https://support.stripe.com/email
