### ISSUE TITLE
Do you have any code-examples for alipay in nodejs?

### ISSUE THREAD

**Issue by medmin** [stripe/stripe-node#420]
Hi, I want to use two payment methods, credit card and alipay. I use "checkout". The credit card is set to be the default method by your example code.

My questions are: 
Can I set the alipay as the default method?
If I have multiple payment methods, do I need to set up multiple URLs for each of these methods? If not, how to process multiple payment methods in one URL? I mean, how to differentiate each payment method in one URL, using if-else?

Thanks.

**Comment by ob-stripe** [comment]
Hi @medmin. GitHub issues are specifically for bugs or feature requests regarding Stripe's Node library, not for general usage questions.

Please send your questions to support using the form at https://support.stripe.com/email.

**Comment by medmin** [comment]
I did write an email. No response. So.....
