### ISSUE TITLE
Need some help with subscription integration 

### ISSUE THREAD

**Issue by keerthikumarsr95** [stripe/stripe-node#421]
I have integrated stripe subscription... 

I need some information 

1.In production mode how long will it take to complete the transaction I.e to get payment successful message via. 

2. In production mode do we need to make our customers wait till we get payment successful confirmation or is it done  in background and updated via other sources..
I just need to know how is this done ideally...

Both questions are related to the stripe subscription...

**Comment by remi-stripe** [comment]
@keerthikumarsr95 the github issues should be limited to bugs on the library itself. For those questions you should reach out to our support team instead: https://support.stripe.com/email
