### ISSUE TITLE
Authenticate express account tokens documentation?

### ISSUE THREAD

**Issue by die20** [stripe/stripe-node#422]
How would I make this request using the stripe-node library?
https://stripe.com/docs/connect/express-accounts#token-request

I can make an http request using the curl params from the link above but I just wanted to make sure I wasn't missing something.

**Comment by remi-stripe** [comment]
@die20 This is not something that the library supports today. It has been added to some of our other libraries so I'm going to tag this as a future enhancement. For now the best solution would be to make your own curl request!

**Comment by samheutmaker** [comment]
Making your own HTTP request is easy enough to do but super inconvenient. This is really something this library should support.

**Comment by abertramds** [comment]
This would be a great addition to the library, and would really cover everything needed to complete the on-boarding of new express accounts.

**Comment by remi-stripe** [comment]
This was released in 6.22.0! cc @die20 @samheutmaker @abertramds
