### ISSUE TITLE
Stripe Connection issues with test keys

### ISSUE THREAD

**Issue by singhravi1979** [stripe/stripe-node#427]
Hi,
 we are getting lot of connection issues while using stripe node package and test stripe keys.
Error details are:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2937): Error: An error occurred with our connection to Stripe

Node Version:6.9.1
Stripe Package :4.23.1

**Comment by remi-stripe** [comment]
@singhravi1979 this looks like a connectivity issue and not a bug with the library itself. I'd recommend checking your connection or talking to your host provider if you're not running the code locally. 

The github issues should be limited to bugs with the library itself so I'd recommend contacting our support team if you have any follow up questions: https://support.stripe.com/email
