### ISSUE TITLE
webhook_endpoints support

### ISSUE THREAD

**Issue by ancil26** [stripe/stripe-node#431]
Hey guys, just wondering if/when this package will add support for webhook_endpoints? 

This would be really useful for us as we have a lot of endpoint urls to add for each environment after deployment. If we can programatically do this through this package that would be great

**Comment by ob-stripe** [comment]
Hi @ancil26. The `/v1/webhook_endpoints` endpoint is not part of the public API and can only be used by the dashboard.

We will likely make the endpoint public in the future, but I don't have an ETA to share just yet. If/when we do release this feature, we will of course update all our client libraries to support the endpoint.

**Comment by flauc** [comment]
I believe this is part of the public API now.

**Comment by ob-stripe** [comment]
@flauc Yes. Support for webhook endpoints was added in version [6.13.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#6130---2018-10-30). You can find code samples in the API reference: https://stripe.com/docs/api/webhook_endpoints

**Comment by flauc** [comment]
@ob-stripe yes, and I'm using it by sending requests directly because this library isn't configured for it, or am I missing something?

**Comment by paulasjes-stripe** [comment]
@flauc What do you mean by that? As long as you are on at least version 6.13.0 of stripe-node you should be able to set up webhook endpoints programmatically.

**Comment by flauc** [comment]
Yes, sorry guys. Looks like it's just missing in typescript definitions.
