### ISSUE TITLE
Intermittent failure when creating a new customer

### ISSUE THREAD

**Issue by jonnycraze** [stripe/stripe-node#432]
Hello all, 

I am sorry if I've missed this issue posted here prior, if I have please point me in the right direction.

I have an intermittent error, and when it occurs i get the following in my logs:
cannot find 'create' of undefined

This is the method i am using:
```stripe.customers.create(user, (err, customer) => { //do stuff })```

Any help on what may be happening is greatly appreciated.

**Comment by ob-stripe** [comment]
Hi @jonnycraze. Hm, that's rather strange, but I don't think it's a bug with the library itself. It sounds like your code is redefining `stripe`, which causes `stripe.customers` to be `undefined`.

Can you reach out to support at https://support.stripe.com/email and include your code? They should be able to help you.

**Comment by jonnycraze** [comment]
@ob-stripe I ended up finding this late last night, and that was exactly it the stripe var got redefined, I felt very derpy.

Thank you for the reply.

**Comment by ob-stripe** [comment]
Haha, it happens to the best of us. Glad you got it sorted out! :)

**Comment by wonderfulazzahra** [comment]
hei @jonnycraze, can i know what you do to fix this. i cannot find 'create' of undefined on Stripe.subscriptions.create :(
