### ISSUE TITLE
 Error: Can't resolve 'child_process'  when trying to use stripe-node server side

### ISSUE THREAD

**Issue by ldevalbray** [stripe/stripe-node#434]
**Hello,**

When trying to install stripe for the server side code,
```
npm install --save stripe
npm run build:dll
```

I got this npm error :

```
ERROR in ./node_modules/stripe/lib/stripe.js
Module not found: Error: Can't resolve 'child_process' in '/home/louis/scotland2018/node_modules/stripe/lib'
```

Would you know what to do ? I searched all over the internet but there does not seem to be any solution. I checked the other opened issues about this subject but I did not find a solution. I want to use stripe-node server side only (I got that it should not be use client side and that Stripe.js is for client side). But still, why can't I build the dependencies ?

**Note: I am using express with react (react-boilerplate) and webpack with dllPlugin. I added stripe to the excluded modules so that it excludes dependencies which are not intended for the browser**

Thank you !

**Comment by ldevalbray** [comment]
It does not work unfortunately ...  But you're right, it must be an issue with my build environment. I should not have opened an issue on strip-node. My bad.
Thank you for your quick response though

**Comment by ob-stripe** [comment]
Hey @ldevalbray, no problem. I'm going to close the issue, but feel free to reply if you have any questions about the library, or if you figure out how to solve the issue! It may be helpful to someone else in the future :)

**Comment by ldevalbray** [comment]
Thanks for your help.
I managed to solve the issue.
See : https://github.com/react-boilerplate/react-boilerplate/issues/2163
Have a good day !

**Comment by mira-thakkar** [comment]
@ob-stripe I am trying to integrate this package in react app built with nextJs and getting the same error as below:

> ERROR in ./node_modules/stripe/lib/stripe.js
Module not found: Error: Can't resolve 'child_process' in '/home/mirathakkar/myproject/node_modules/stripe/lib'

 can you help where am i going wrong?

**Comment by ob-stripe** [comment]
@mira-thakkar stripe-node is a server-side package. You can't integrate in your client-side React code, you must use it server-side with Node.js.

**Comment by rudyhadoux** [comment]
Hi,
I do not understand.
We must use it server-side with Node.js.
OK BUT I do not use NodeJS for my back-end.
I use AWS Amplify.
So how to create a Stripe customer by example ?

**Comment by hzethraeus** [comment]
I had the same problem (Can't resolve 'child_process') when using Stripe on my Next application. I solved it by calling the stripe API in an async getServerSideProps outside my class and returning props to the class. I hope this may help someone who had the same problem.

https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

**Comment by kiily** [comment]
I am trying to solve this issue myself (using Next.js). 

For anyone that this has happened to, it is because somewhere in your app there may be an import or a piece of code that is loading the server-side only library for Stripe into your client, most likely inadvertently. I have a `warn` only on my side which means I seem to be unable to find the actual problem as nothing breaks (which would make it more obvious).

Keep digging for all places where you do use it and hopefully you'll hit the one part of your build system that breaks 👍 

Not sure how much help this is for anyone but since I landed here I thought it was worth reiterating
