### ISSUE TITLE
Consider removing Bluebird

### ISSUE THREAD

**Issue by OrKoN** [stripe/stripe-node#438]
Hi,

I was wondering why do you need Bluebird as a dependency? I am packaging this module for AWS Lambda and want to optimize the size of the final bundle. Here is what I see: stripe-node takes 102 KB, bluebird requires 613 KB!

I think the library may not need such a heavy dependency. Is it possible to remove it?

**Comment by ob-stripe** [comment]
@OrKoN The dependency was introduced when the library needed to support Node 0.x and native ES6 promises weren't available.

Now that the minimum required version is Node 4, I suppose we could remove the dependency in favor of native promises. That said, Bluebird seems to have significantly better performance than native promises (according to https://github.com/petkaantonov/bluebird/tree/master/benchmark) so this is something we'd need to consider carefully.

cc @brandur-stripe @jlomas-stripe, any thoughts on this?

**Comment by OrKoN** [comment]
@ob-stripe I think this info on bluebird's site may be outdated (results are from 2015-01-05). Alternatively, you can optionally accept a different promise implementation if someone wants to use Bluebird.

**Comment by ob-stripe** [comment]
> you can optionally accept a different promise implementation if someone wants to use Bluebird.

I like this! I've prepared a patch in #439.

**Comment by ob-stripe** [comment]
@OrKoN I've just released version 5.6.0 of the library with native ES6 promises instead of Bluebird :) Thanks for the suggestion!
