### ISSUE TITLE
Crashing error on declines

### ISSUE THREAD

**Issue by mfossel** [stripe/stripe-node#440]
Hello, we are occasionally getting a crashing error on declined charges. This does not happen every time a card is declined and we have not been able to recreate it, it only happens in a live production environment.

This is the error
`
Error Your card was declined. 
    /home/ubuntu/server/node_modules/stripe/lib/Error.js:12:17 _Error
    /home/ubuntu/server/node_modules/stripe/lib/utils.js:124:13 Constructor
    /home/ubuntu/server/node_modules/stripe/lib/utils.js:124:13 Constructor
    /home/ubuntu/server/node_modules/stripe/lib/Error.js:55:14 generate
    /home/ubuntu/server/node_modules/stripe/lib/StripeResource.js:170:39 none
    events.js:110:20 emitNone
    events.js:207:7 emit
    _stream_readable.js:1059:12 endReadableNT
    internal/process/next_tick.js:138:11 _combinedTickCallback
    internal/process/next_tick.js:218:9 _tickDomainCallback
`

This is happening on stripe.charges.create() and we are using the exact code from stripe documents to charge. This bug is crashing our server and really causing us huge problems. We can't figure out what we are doing wrong or why this is happening.

**Comment by brandur** [comment]
Hey @mfossel, it looks like you're just running into a card being declined for a charge, which is something that you should expect to happen once in a while as part of any integration. You'll want to put some error handing in place to protect your application against this (and probably pass messages back to your user). There's some information on how to do this [here](https://stripe.com/docs/api#errors) and some specifically for [stripe-node here](https://github.com/stripe/stripe-node/wiki/Error-Handling).

**Comment by mfossel** [comment]
We are handling declines and passing the info to the user and this works most of the time. However we still getting a crashing exception once in a while, say about 1 our of every 10 declines crashes node. 

This is our charge call.

  `stripe.charges.create({
                amount: amount,
                currency: "usd",
                expand: ['balance_transaction'],
                description: description,
                source: token.id
            }, {
                stripe_account: stripe_user_id
            }, function(err, charge) {
                cb(err, charge);
            });` 

I am not sure where we are not handling it, because every time I test it in dev I am getting the error returned as "err" and handling it. I have copied the code from the two sources listed and I am still getting the crash. The only difference being we are using Stripe Connect accounts so we have to add the connected account id, but this code is copied from the Stripe docs.

**Comment by brandur** [comment]
Hm, I'm afraid to say that this still appears to be an application-level bug.

If you check the stack trace you posted, you can see that an API error is being constructed exactly how you'd expect it to be. Here's `lib/Error.js:55` for example:

``` js
StripeError.generate = function(rawStripeError) {
  switch (rawStripeError.type) {
    case 'card_error':
      return new _Error.StripeCardError(rawStripeError);
```

After a few other function calls unwind, you can see at `StripeResource:170` how this will invoke your callback with an `err` value:

``` js
            } else {
              err = Error.StripeError.generate(response.error);
            }
            return callback.call(self, err, null);
```

If you have a theory about what in particular is going wrong with `stripe-node`, I'll definitely take a look, but so far the evidence seems to suggest that an error is getting bubbled up, and somewhere is not being properly handled.

**Comment by chrisschaub** [comment]
I am seeing this same exact behaviour. Declines work fine, even in test, and there is nothing special about this order versus other declines. But occassionally, a declined charge will crash node, and I am trapping for errors, so the crash is happening before I can get it. I'm guessing an error object is being sent by Stripe that is different or malformed, so the library might hard crash. I am using node 6.x, and my library is a bit out of date, but the poster above is having the problem with a much more recent version. Ok, just wanted to throw my 2c in -- very hard to capture problem because the normal decline and failure test cards work fine.
