### ISSUE TITLE
Argument "customerId" required when send request create source from token

### ISSUE THREAD

**Issue by tanphamminh92** [stripe/stripe-node#446]
I'm using MeteorJS and Stripe to build a payment system. In system, I'm trying to create card for user from Stripetoken. Follow this docs: https://stripe.com/docs/api#create_card-source, here my code:

`stripe.customers.createSource (
      stripeUserID,
      {
        source: stripeToken
      }, function(err, card) {
        console.log(err);
      }
    );`

but when I try to run this function, it throw an error to me:

> [Error: Stripe: Argument "customerId" required, but got: undefined (on API request to `POST /customers/{customerId}/sources`)]

How to send Argument "customerId" into request?

My version:
"stripe": "^5.8.0"

**Comment by remi-stripe** [comment]
@tanphamminh92 The customer id (cus_1234) should be the first argument when calling that method. Are you sure that `stripeUserID` is not an undefined variable in your code? Based on the error that seems to be the issue.

**Comment by tanphamminh92** [comment]
Sorry about my issue. My code somethings made `stripeUserID ` is undefined. Thank you so much. Closed
