### ISSUE TITLE
Problem with update method (SubscriptionItems)

### ISSUE THREAD

**Issue by rodrigoreis22** [stripe/stripe-node#447]
Node version: v4.3.2
Stripe version: 5.8.0

I'm trying to change the subscription item for a customer, [your docs](https://stripe.com/docs/api/node#update_subscription_item) says:

```
var stripe = require("stripe")(
  "sk_test_CVN******"
);

stripe.subscriptionItems.update(
  "si_ChUZfj9OELHOkU",
  {
    plan: "plan_ChMqd8a3Xrw5iW",
  },
  function(err, subscriptionItem) {
    // asynchronously called
  }
);
```

My code is:
```
function updateSubscriptionItem(itemId, planId, callback) {
  var client = require('stripe')(config.stripeSecret);
  return client.subscriptionItems.update(itemId, {plan: planId}, callback);
}
```

I'm receiving this error:
```
[Error: Stripe: Unknown arguments (). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to POST `/subscription_items/{id}`)]
```

When I try:
`client.subscriptionItems.update({item: itemId, plan: planId}, callback);` , I get this error:
```
[Error: Stripe: "id" must be a string, but got: object (on API request to `POST /subscription_items/{id}`)]
```

**Comment by remi-stripe** [comment]
@rodrigoreis22 Can you clarify what `callback` is in your code exactly? My guess is that you want to do something like this instead:

```
function updateSubscriptionItem(itemId, planId, callback) {
  var client = require('stripe')(config.stripeSecret);
  return client.subscriptionItems.update(
    itemId,
    {plan: planId},
    function(err, subscriptionItem) {
      callback(err, subscriptionItem);
    });
}
```

**Comment by rodrigoreis22** [comment]
That's exactly it @remi-stripe . It doesn't work. the `update` method doesn't receive a callback.

**Comment by rodrigoreis22** [comment]
@remi-stripe i've found now that it does work, but with promises.

```
function updateSubscriptionItem(itemId, planId, callback) {
  var client = require('stripe')(config.stripeSecret);
  return client.subscriptionItems.update(
      itemId,
      {plan: planId})
    .then(function(subscriptionItem) {
       ....
    });
}
```

**Comment by remi-stripe** [comment]
@rodrigoreis22 Can you clarify what happens when you use my exact code?

**Comment by rodrigoreis22** [comment]
I get this error:
`[Error: Stripe: Unknown arguments (). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to POST `/subscription_items/{id}`)]`

It seems like the `update` method 3rd parameters is expecting an object, but I'm providing a callback (just like the docs and your code above).

**Comment by remi-stripe** [comment]
But there's a difference between passing `callback` and passing ```
    function(err, subscriptionItem) {
      callback(err, subscriptionItem);
    });
```
Can you confirm you explicitly tried my exact code and not a custom version with `callback` as the argument?

**Comment by rodrigoreis22** [comment]
That works @remi-stripe , what's strange is that I've been using this with `callback` for the other calls, just this one doesn't behave the same way.. here's my complete code so far:

```
var config = require('./config')
  , Promise = require('bluebird');

var client = require('stripe')(config.stripeSecret);

function getProducts(options, callback) {
  return client.products.list(options, callback);
}

function getPlans(options, callback) {
  return client.plans.list(options, callback);
}

function createCustomer(customerInfo, callback) {
  return client.customers.create(customerInfo, callback);
}

function createSubscription(customerId, planId, callback) {
  return client.subscriptions.create({
    customer: customerId,
    items: [
      {
        plan: planId
      }
    ]
  }, callback);
}

function updateSubscriptionItem(itemId, planId, callback) {
  return client.subscriptionItems.update(itemId, {plan: planId}, function(err, subscriptionItem) {
    return callback(err, subscriptionItem);
  });
}

function cancelSubscription(subscriptionId) {
  return client.subscriptions.del(subscriptionId, {at_period_end: true});
}

module.exports.getProducts = getProducts;
module.exports.getPlans = getPlans;
module.exports.createCustomer = createCustomer;
module.exports.createSubscription = createSubscription;
module.exports.updateSubscriptionItem = updateSubscriptionItem;
module.exports.cancelSubscription = cancelSubscription;
Promise.promisifyAll(module.exports);
```

**Comment by jlomas-stripe** [comment]
Hey @rodrigoreis22!  I just tried reproducing this with Stripe 5.8.0 on Node 4.3.2, and I unfortunately can't, no matter what I try.

Can you provide the complete stack trace for the error?

**Comment by jlomas-stripe** [comment]
I again tried to reproduce this, and I can't, so I'm going to close this out.  Please do let me know if you can provide some more info to help reproduce it though, as I'm happy to keep digging if I have more to go on!
