### ISSUE TITLE
How to get missed transaction details when my server down ? 

### ISSUE THREAD

**Issue by manojcena** [stripe/stripe-node#450]
Hi i am new to payment gateway integration.

I integrated stripe payment gateway in my hybrid mobile application with node js as server and every thing seems to be working fine. But i have an issue with following scenario when my server receive a payment request from app and my server initiated payment request to stripe and payment successfully completed in stripe and while receiving the response form stripe my server down. How can i get the missed payment details from stripe once my server is up or start running. 

Please help me out to solve this scenario. Thanks in advance.

**Comment by remi-stripe** [comment]
@manojcena Issues should be limited to bugs in the library itself and not used for questions about Stripe's API.

You can talk to our support team about this issue directly here: https://support.stripe.com/email and they can help you handle this properly!
