### ISSUE TITLE
TypeScript definitions for the client JS

### ISSUE THREAD

**Issue by atrauzzi** [stripe/stripe-node#455]
I'm not sure where the best place would be to report this, but I'd love to see TypeScript definitions for the CDN-delivered stripe client.

**Comment by remi-stripe** [comment]
@atrauzzi It's something we've discussed before but we don't have plans to ship those for now. I'm going to close this issue as stripe-node is the server-side library and should not be used client-side.

I'd recommend to discuss this with our support team directly in case you want more details: https://support.stripe.com/email

**Comment by atrauzzi** [comment]
Gotcha. And yeah, for anyone who reads this issue: I obviously don't want to use the node library client side.

I'll try to cross reference any public advocacy I do to this issue. That way people can have somewhere to go. Hopefully you guys can do a little pulling from the inside too! 😉

**Comment by atrauzzi** [comment]
Here's a tweet for people to like and share: https://twitter.com/Omega_/status/991996412358520833?s=19

**Comment by ob-stripe** [comment]
@atrauzzi They're not official and I can't vouch for their quality as I've never used them myself, but there are Typescript definitions for Stripe.js on the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stripe-v3.

**Comment by atrauzzi** [comment]
I'll check them out, thank you for finding this for me. 😅

_(I had done a search, but I think the nodejs library seems to swallow all the air in the search results.)_
