### ISSUE TITLE
transform_usage cannot be combined with tiers

### ISSUE THREAD

**Issue by drmrbrewer** [stripe/stripe-node#461]
When [creating a plan](https://stripe.com/docs/api#create_plan), there is the following restriction in place:

> _transform_usage_: Apply a transformation to the reported usage or set quantity before computing the billed price. **Cannot be combined with tiers**.

This is consistent with the dashboard UI.  But why is this restriction in place?  I would really like to make use of `transform_usage` *and* `tiers`, and it would seem to be pretty simple to implement on stripe's side... I can't see why the restriction is there.  Probably I'm missing something.

**Comment by remi-stripe** [comment]
@drmrbrewer github issues are here to report bugs specific with the stripe-node library. For a question like this, I'd recommend talking to our support team instead and they can help clarify the reason behind this restriction. You can talk to them here: https://support.stripe.com/email

**Comment by drmrbrewer** [comment]
I already did, but they don't know and it then disappears into some black hole.  I thought you might be able to provide some insight as to why it's not technically possible.  Clearly not.

**Comment by remi-stripe** [comment]
I'm sorry but github is to discuss bugs for the library. This is not the right place to discuss this.

Ultimately though, `tiers` and `transform_usage` are quite new as they were released a few weeks ago only. We will continue improving the API and offering more features and likely lift this restriction in the future as we talk to more users and see how the existing APIs are used in the first place.
