### ISSUE TITLE
Docs do not match createRefund arity 

### ISSUE THREAD

**Issue by dalan-stripe** [stripe/stripe-node#464]
https://github.com/stripe/stripe-node/blob/699d1ba05707bb5000989b1b4117178c174094be/lib/resources/ApplicationFees.js#L20-L24

The docs indicate that one is able to provide both `amount` and `metadata` when making this call:

https://stripe.com/docs/api/node#create_fee_refund-amount

**Comment by remi-stripe** [comment]
@dalan-stripe You can pass parameters to that method as documented in our official API documentation which works as expected. The `stripeMethod()` logic handles this automatically for you.

```
stripe.applicationFees.createRefund(
  charge.application_fee,
  {
    amount: 100,
    metadata: {'order_id': '6735'},
  },
  function(err, feeRefund) {
    console.log("Fee refund is:\n", JSON.stringify(feeRefund));
  }
);
```
