### ISSUE TITLE
require is not a function

### ISSUE THREAD

**Issue by murugan1515** [stripe/stripe-node#467]
![image](https://user-images.githubusercontent.com/19861645/40824198-e403937c-6590-11e8-8c98-22559d865b62.png)

error showing "require is not a function". im using 
node version 7.7.1, 
npm version - 6.0.0, 
ionic version - 3.20.0

**Comment by ob-stripe** [comment]
Hi @murugan1515. stripe-node doesn't appear at all in the stacktrace in your screenshot, so I don't think this error is related to the library.

Closing this issue, but feel free to reply if you believe this is an issue with the library. If so, please provide code to reproduce the issue.

**Comment by murugan1515** [comment]
![image](https://user-images.githubusercontent.com/19861645/40831631-1e0daba0-65a7-11e8-8b35-df152d73c61e.png)

i tried "npm install @types/child_process" it can not found in npm install

**Comment by ob-stripe** [comment]
@murugan1515 stripe-node is a server-side library. You cannot use it in frontend code.

GitHub issues are specifically for bugs or feature requests and are not a support channel. Please reach out to Stripe support at https://support.stripe.com/email to receive support about Stripe's API and its libraries.
