### ISSUE TITLE
Unexpected end of input at 1:18515 when running npm install stripe --save

### ISSUE THREAD

**Issue by Sirmorrison** [stripe/stripe-node#470]
[2018-06-13T13_48_53_978Z-debug.log](https://github.com/stripe/stripe-node/files/2098364/2018-06-13T13_48_53_978Z-debug.log)

**Comment by remi-stripe** [comment]
@Sirmorrison You likely want to catch those errors and just retry the request when it happens. It often means that there's an issue with the connection between your server and ours and you got a truncated response.
