### ISSUE TITLE
Exponential Backoff

### ISSUE THREAD

**Issue by MarkHerhold** [stripe/stripe-node#478]
The stripe docs say

>The Stripe Ruby library retries on failure automatically with an idempotency key using increasing backoff times and jitter. The implementation for that is pretty simple, and you can refer to it on GitHub to see exactly how it works.

Does the Stripe Node.js library support retries and exponential backoff?

**Comment by remi-stripe** [comment]
@MarkHerhold It's not something that the library supports out of the box yet unfortunately. Going to tag is as "future" since it's something we should definitely implement at some point (we'd love a PR if you're up for it!).

**Comment by ob-stripe** [comment]
Automatic retries with exponential backoff was added to the library in version [6.25.0](https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#6250---2019-02-13).
