### ISSUE TITLE
Customers batch creation

### ISSUE THREAD

**Issue by ezetaraborelli** [stripe/stripe-node#486]
Hi, is there a way to create multiple customers on a single request? On my app I have to create a team with multiple members, and each member should be added on Stripe as a customer for future charges. Right now I'm making a request for every single member, but on big teams it is taking so much time (~5s for each request).
My second option if what I ask is not possible is to create the customer just before the charge is done, but I'd rather do it on team creation.
Thanks!

**Comment by remi-stripe** [comment]
@ezetaraborelli It's not possible to batch create customers today. You can only create one customer per API request. You can create multiple customers in parallel though so you could change your code to run multiple requests and just wait for all of those to complete.
