### ISSUE TITLE
How can I add a custom stripe backend URL so I can use my mock server?

### ISSUE THREAD

**Issue by jamesone** [stripe/stripe-node#490]
I'm using the following mock server: https://github.com/stripe/stripe-mock

I confirmed that the server is running ✅ When visiting the URL it shows:

```
{"error":{"message":"Please authenticate by specifying an `Authorization` header with any valid looking testmode secret API key. For example, `Authorization: Bearer sk_test_123`. Authorization was ''.","type":"invalid_request_error"}}
```

How can I update the URL for my stripe npm module? I tried the following:

```
stripe.DEFAULT_HOST = 'http://localhost:12111';
stripe._api.host = 'localhost:12111';
```

Without any luck

**Comment by ob-stripe** [comment]
Hi @jamesone, check out https://github.com/stripe/stripe-node/issues/472#issuecomment-400613412 which explains how to set up stripe-node to talk to stripe-mock.
