### ISSUE TITLE
[Docs] Usage record summaries method typo

### ISSUE THREAD

**Issue by svarlamov** [stripe/stripe-node#503]
In the docs [here](https://stripe.com/docs/api/node#usage_record_summary_all) there is a typo that causes the call to fail.

```js
var stripe = require("stripe")("~~~");

stripe.usageRecordSummarys.list(
  { limit: 3 },
  function(err, usageRecordSummarys) {
    // asynchronously called
  }
);
```

Should be replaced with:

```js
var stripe = require("stripe")("~~~");

stripe.usageRecordSummaries.list(
  { limit: 3 },
  function(err, usageRecordSummaries) {
    // asynchronously called
  }
);
```

EDIT: There's also no example of how the subscription item ID should be passed...

**Comment by remi-stripe** [comment]
@svarlamov Thanks for the report, I'll work with the docs team internally to get this fixed. The code should look like this:
```
stripe.usageRecordSummaries.list(
  'si_123',
  { limit: 3 },
  function(err, usageRecordSummaries) {
    // asynchronously called
  }
);
```
