### ISSUE TITLE
Can't find usageRecords

### ISSUE THREAD

**Issue by rodrigoreal** [stripe/stripe-node#505]
I'm trying to use the [usage records](https://stripe.com/docs/api?lang=node#usage_record_create) api, but i can't find it using the 6.12.1 version.
<img width="520" alt="captura de tela 2018-10-06 as 14 38 19" src="https://user-images.githubusercontent.com/8595202/46574147-897fa280-c975-11e8-8597-7a5297d2fb5b.png">

**Comment by remi-stripe** [comment]
@rodrigoreal This is definitely available in that version. We added it back before 6.0 though we changed the prototype on 6.0.0. If you can't see it you are likely relying on an old version of the library

**Comment by rodrigoreal** [comment]
I'm definitely not using an old version, i've just installed using `npm install stripe@latest` to be safe and in my `node_modules/stripe/version` is showing `6.12.1`.
Can you take a look and see if it is available for you?

**Comment by remi-stripe** [comment]
@rodrigoreal I'm sure it is available yes and the code works for me. Do you get an error when you _try_ the code or is it just not part of the auto-completion? Are you using something custom for that such as typescript definitions maybe? Those are not built by Stripe and could be out of sync.

**Comment by rodrigoreal** [comment]
Sorry about that, i was using an old typings version.
I've just updated the typings and it is available now.
