### ISSUE TITLE
invst_{id}

### ISSUE THREAD

**Issue by BuffMcBigHuge** [stripe/stripe-node#506]
I'd like to link the Stripe invoice page on our service for the customer to view. Can we obtain the `invst_{id}` object from the API?

ex: `https://pay.stripe.com/invoice/invst_{id}`

**Comment by remi-stripe** [comment]
@BuffMcBigHuge You can use the following property: https://stripe.com/docs/api#invoice_object-hosted_invoice_url

Github issues should only be used to report bugs in the libraries though and for questions like this you should instead talk to our support team here: https://support.stripe.com/email

**Comment by BuffMcBigHuge** [comment]
Thank you @remi-stripe , acknowledged.
