### ISSUE TITLE
Feature Request: Promise-based autoPagingEach API

### ISSUE THREAD

**Issue by tyscorp** [stripe/stripe-node#511]
I love the new `autoPagingEach` functionality but it would be cool if the API was a bit more intuitive. The callback would either wait for a promise resolving to continue iteration or for a promise rejection to exit.

e.g.
```js
stripe.customers.list().autoPagingEach(async function onItem(customer) {
  const result = await doSomething(customer);
  if (shouldStop(result)) {
    throw new Error('Stop the thing');
  }
});
```

I've been wrapping the iteratees with a helper function[0] to enable this, but it would be cool to have first-class support. This implementation does swallow all errors, though... Maybe have it rethrow the error? Or maybe have a specific error class to exit but not bubble the error?

[0]
```js
const promisifyAutopager = (iteratee) => async (obj, next) => {
  try {
    await iteratee(obj);
  } catch (e) {
    return next(false);
  }
  next();
};
```

**Comment by rattrayalex-stripe** [comment]
Hey @tyscorp , that's an interesting idea – I'll take a look at it. 

We would want a nice way to break without interfering with good error handling. I'm also a bit hesitant to make the api even more overloaded; the docs are already quite complex. 

That said, I do think the example you provide sounds compelling. 

What do you think about returning `false` from an async function (or, equivalently, returning a promise which resolves to false) to break?

**Comment by rattrayalex-stripe** [comment]
It turns out we already have support for this! See https://github.com/stripe/stripe-node/pull/512

Thanks @tyscorp ! Let me know if you have any issues or further feedback. Closing for now but feel free to re-open.

**Comment by tyscorp** [comment]
Lol that's awesome. Cheers! 👍
