### ISSUE TITLE
Plan name on invoice

### ISSUE THREAD

**Issue by reinhardholl** [stripe/stripe-node#522]
Hi,

I have built a stripe integration using stripe-node and it was really easy to do, thanks for that! We have a single product, and multiple plans on this product. One issue I am facing is that the line items on my subscription invoices display the product names, and no trace of the plan name? This is pretty confusing for our customers. Is there anyway I can change this behavior using the api/library?

Thanks!

**Comment by remi-stripe** [comment]
@reinhardholl Github issues should be limited to bugs with our library. For questions about our API or our product, you should instead contact our support team here: https://support.stripe.com/email

The Product name will always be what's shown on the invoice though. The Product is the high level abstraction and then the plans are really multiple versions of that same product, such as for different currencies. If you have different plans that are named differently you likely should instead have one plan per product and have multiple separate products.

I hope this helps, but our support team can help with any follow up questions!

**Comment by reinhardholl** [comment]
Hi @remi-stripe, thanks. I ended up changing to single plan per product.
