### ISSUE TITLE
stripe webpack error

### ISSUE THREAD

**Issue by lephenix1234** [stripe/stripe-node#528]
when I install stripe I have this error 
__webpack_require__(...).createServer is not a function

**Comment by remi-stripe** [comment]
Hey @lephenix1234. This is expected and you can read more in all the past issues in the repo referencing this error such as https://github.com/stripe/stripe-node/issues/265

stripe-node is a server-side library and should not be used client-side so you should not include it in your webpack bundling.

**Comment by maguayo** [comment]
What about cloud based functions that use JS? For example Clouflare Workers?

**Comment by remi-stripe** [comment]
@maguayo I would recommend reaching out to our support team for help with your integration: https://support.stripe.com/contact
