### ISSUE TITLE
You must provide a Stripe Element or a valid token type to create a Token.

### ISSUE THREAD

**Issue by lephenix1234** [stripe/stripe-node#529]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Node library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your Node version and the version of the Stripe Node library you're using, as well as any other details that may be helpful in reproducing the problem.

```node
async payWithStripe() {
  let stripe = Stripe("pk_test_0nfXNmPlsWzBdoRy8x5ebtOw");
  let card = await stripe.createToken({
    card: "4242424242424242",
    exp_month: "02",
    expDate: "21",
    cvc: "999",
    name: "Billy Joe"
  });
}
```

**Comment by ob-stripe** [comment]
Hi @lephenix1234. It looks like you're trying to use [Stripe.js](https://stripe.com/docs/stripe-js), not stripe-node.

Stripe.js is our frontend library for tokenizing payment information. stripe-node is our backend library for integrating Stripe in a Node.js server.

GitHub issues on this repository are specifically for issues with the stripe-node library. You need to reach out to Stripe's support at https://support.stripe.com/email to receive help about using Stripe.js.
