### ISSUE TITLE
"files" entity missing list (and other) methods

### ISSUE THREAD

**Issue by njosefbeck** [stripe/stripe-node#533]
Hello!

First, versions:
**Node version**: 10.13.0
**stripe-node version**: 6.18.0

OK, so I currently work on a [gatsby-source plugin](https://github.com/njosefbeck/gatsby-source-stripe) for Stripe data. When attempting to call `stripe.files.list` as explained in your docs [here](https://stripe.com/docs/api/files/list) I was getting an error that the method wasn't iterable. I found this strange, as all other list methods are iterable (using and LOVING the new for-await-of pagination btw). So I did further digging.

When inspecting the stripe object, I noticed that the list method for "files" seems to be missing:

![screen shot 2018-12-07 at 10 46 26 am](https://user-images.githubusercontent.com/9508002/49661228-23170f00-fa0e-11e8-9958-e877127452a6.png)

And, actually, now that I look at that screenshot more closely, it looks like it's also missing the other methods (like create and retrieve).

Is there any way that this can be fixed? Or, is there a different way I should be trying to access stripe.files.list?

Happy to do further testing if you'd all like! Thanks again for the awesome node library!

**Comment by ob-stripe** [comment]
Hi @njosefbeck. I put together a fix in #534. We'll release an update soon. Thanks for reporting this!

**Comment by njosefbeck** [comment]
Awesome, thanks!

**Comment by ob-stripe** [comment]
Fixed in 6.18.1.

**Comment by njosefbeck** [comment]
@ob-stripe Are you by chance able to `npm install` this latest version? I've been trying to do so for the past couple of hours, with no luck. I keep getting the following error:

![screen shot 2018-12-07 at 3 39 16 pm](https://user-images.githubusercontent.com/9508002/49674087-52417680-fa36-11e8-9d2a-8554d5ea09e4.png)

I can see that npm shows version 6.18.1, so it seems like it should be there. I don't think this is an issue on you all's end, but I am curious if you're able to install / update to the latest version via npm, or if you experience issues as well.

**Comment by remi-stripe** [comment]
I just tried and it installed the version `6.18.1` without issue at least

**Comment by njosefbeck** [comment]
Yeah, I figured that'd be the case. Must be something with my local version of npm or something. I'll give it a couple days and see if it resolves itself. Thanks for confirming that someone can successfully install the new version!
