### ISSUE TITLE
Response Times

### ISSUE THREAD

**Issue by formatically** [stripe/stripe-node#538]
Hello,

Before posting this question here, I chatted with Stripe Support.  I wasn't able to get a definitive answer from them so I am hoping someone can provide some insight here.
   
What are typical response times one can expect from the Stripe API?  I think I am getting some really poor times, but have nothing to compare them too.  

A "Customers Create" request is taking on average 1.5 seconds. 

```
console.time("create")

stripe.customers.create({
	source: token
}, {
	stripe_account: 'account_id'
	},function(err, customer) {
		
		console.timeEnd("create")
				
	});

create: 1475.919ms
```

A "Subscriptions Create" request is taking on average 4.5 seconds.

```
console.time("SubCreate")

stripe.subscriptions.create({
	customer: member.stripeCustomer,
	items: [
		{
		plan: membership.paid.stripeId,
		},
	]
	}, {
	stripe_account: config.stripeAccount
	}, function(err, subscription) {

		console.timeEnd("SubCreate")
             }
	});
SubCreate: 4623.456ms
```

Does 1.5 secs for a customer create and 4.5 secs for subscription create sound reasonable? 

Oh, and the above code was executed on Heroku. 

Thanks,

**Comment by remi-stripe** [comment]
@formatically Sorry to send you back to support but issues should be limited to issues with the libraries itself which isn't really the case here. Our support team is better equipped to answer questions like this.

Ultimately though, some requests will be slower than others, especially if they involve talking to the bank networks. Creating a customer with a card means that we verify that card's validity with the bank which takes time. Creating a subscription requires charging the card itself with the bank and creating multiple related objects (a subscription, a charge and an invoice) which also takes some time.

Hope this helps!
