### ISSUE TITLE
"Sending credit card numbers" error when only using source or token id

### ISSUE THREAD

**Issue by Kretin1** [stripe/stripe-node#550]
I am saving customers and their sources on my platform, and trying to create charges for my connected accounts. I am able to successfully create destination charges, but I'm having trouble with creating direct charges.

I've tried creating a token per: https://stripe.com/docs/connect/shared-customers
If I create a token using just the customer the example, the error is:
'You provided a customer without specifying a source. The default source of the customer is a source and cannot be shared from existing customers.'
Even though the documentation says that you need "The card or bank account ID for that customer, if you want to charge a specific card or bank account rather than the default".
I cannot find a parameter for token.create that lets me specify a source as well or instead of a customer.

I've tried sharing the customer's chosen source with the connected account per: https://stripe.com/docs/sources/connect#shared-card-sources which results in the error:
'Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.'

I tried attaching a test token (tok_visa) to my customer, and creating a charge with that, but that had the same result.

Every time I get close, I end up with the error about sending numbers being unsafe even though I'm only ever sending Stripe's provided token or source ID's.

These are the 2 main things I've tried, although I've tried many combinations of these:

const newToken = await stripe.tokens.create({
        customer: customerId,
    }, {
        stripe_account: stripeAccountId,
    });

and this:

const newToken = await stripe.sources.create({
        customer: customerId,
        usage: 'single_use',
        original_source: sourceId,
      }, {
        stripe_account: stripeAccountId,
      });

The only success I've had is creating the direct charge with a test token (tok_visa), completely bypassing the sharing of tokens/sources. No other combination seems to work. But that leaves me at a loss as to how to get a real shared token when I need it.

The only other thing I can think of is that it's not working because I'm using "Test Data" and a test connected account. But that doesn't explain the error about sending credit card numbers, which I'm clearly not.

Node v8.9.3
Stripe 6.5.0
Here are 2 errors I've received:

{ Error: Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided.
    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)
    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  type: 'StripeInvalidRequestError',
  stack: 'Error: Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided.\n    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)',
  rawType: 'invalid_request_error',
  code: undefined,
  param: 'source',
  message: 'Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided.',
  detail: undefined,
  raw: 
   { message: 'Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided.',
     param: 'source',
     type: 'invalid_request_error',
     headers: 
      { server: 'nginx',
        date: 'Thu, 10 Jan 2019 06:29:51 GMT',
        'content-type': 'application/json',
        'content-length': '223',
        connection: 'close',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'access-control-max-age': '300',
        'cache-control': 'no-cache, no-store',
        'idempotency-key': '-LVqRxbZciMWnogRMlM0',
        'original-request': 'req_ZR8R351Ug6nTqH',
        'request-id': 'req_ZR8R351Ug6nTqH',
        'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
        'stripe-version': '2018-11-08',
        'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
     statusCode: 400,
     requestId: 'req_ZR8R351Ug6nTqH' },
  headers: 
   { server: 'nginx',
     date: 'Thu, 10 Jan 2019 06:29:51 GMT',
     'content-type': 'application/json',
     'content-length': '223',
     connection: 'close',
     'access-control-allow-credentials': 'true',
     'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
     'access-control-max-age': '300',
     'cache-control': 'no-cache, no-store',
     'idempotency-key': '-LVqRxbZciMWnogRMlM0',
     'original-request': 'req_ZR8R351Ug6nTqH',
     'request-id': 'req_ZR8R351Ug6nTqH',
     'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
     'stripe-version': '2018-11-08',
     'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
  requestId: 'req_ZR8R351Ug6nTqH',
  statusCode: 400 }

{ Error: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.
    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)
    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  type: 'StripeInvalidRequestError',
  stack: 'Error: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.\n    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)',
  rawType: 'invalid_request_error',
  code: undefined,
  param: undefined,
  message: 'Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.',
  detail: undefined,
  raw: 
   { message: 'Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.',
     type: 'invalid_request_error',
     headers: 
      { server: 'nginx',
        date: 'Thu, 10 Jan 2019 06:39:15 GMT',
        'content-type': 'application/json',
        'content-length': '260',
        connection: 'close',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'access-control-max-age': '300',
        'cache-control': 'no-cache, no-store',
        'idempotency-key': '-LVqU6GfIlL7qFDmFPqD',
        'original-request': 'req_HrehaCK3HPNzEK',
        'request-id': 'req_HrehaCK3HPNzEK',
        'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
        'stripe-version': '2018-11-08',
        'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
     statusCode: 402,
     requestId: 'req_HrehaCK3HPNzEK' },
  headers: 
   { server: 'nginx',
     date: 'Thu, 10 Jan 2019 06:39:15 GMT',
     'content-type': 'application/json',
     'content-length': '260',
     connection: 'close',
     'access-control-allow-credentials': 'true',
     'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
     'access-control-max-age': '300',
     'cache-control': 'no-cache, no-store',
     'idempotency-key': '-LVqU6GfIlL7qFDmFPqD',
     'original-request': 'req_HrehaCK3HPNzEK',
     'request-id': 'req_HrehaCK3HPNzEK',
     'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
     'stripe-version': '2018-11-08',
     'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
  requestId: 'req_HrehaCK3HPNzEK',
  statusCode: 402 }

**Comment by remi-stripe** [comment]
@Kretin1 The first error is because you are passing a hash in `source` instead of the created token id `tok_123`: 
```
  source: {
    domain: {
      domain: "",
      _eventsCount: "1"
    }
  },
```

If you look at that specific request in your Dashboard [here](https://dashboard.stripe.com/test/logs/req_ZR8R351Ug6nTqH) you can see the shape of the parameters you're sending and why it's failing. It does not fail on the token creation. It fails on the Charge creation too and not on the token creation.

The second error is similar in principle though a bit different. You can see it [here](https://dashboard.stripe.com/test/logs/req_HrehaCK3HPNzEK) and you are passing the entire Source object instead of just the id `src_123` in the `source` parameter of the Charge creation. So it looks like this:
```
  source: {
    id: "src_1234",
    object: "source",
    amount: "",
    card: {
      exp_month: "7",
      exp_year: "2020",
      ...
```

The right fix is to change your charge creation code to take the new Source id `src_123` after it's created.

You also should go with Shared Sources since you are using Sources and not Tokens and Cards in your application. Sources and Cards are completely different/separate objects, though they represent the same concept (a cardholder's card in your case) but Sources handle cards and all the other payment methods. You can read more about Sources here: https://stripe.com/docs/sources/customers

**Comment by Kretin1** [comment]
Thank you for your help. The first error was one of the earlier ones.

Regarding the second, this is my confusion, because I'm not passing the entire source object. I'm only referencing the source ID string. Using the same source ID I can happily create Destination charges without error. However I can see that it's receiving the entire source on Stripe's end.

Can you please tell me what I can change so that it only passes the ID and not the whole source?

Here is my code:
        console.log('Source id = ' + data.source);
        // Share card source to connected account so we can
        // create a direct charge (with a new token id) for that customer
        const newToken = await stripe.sources.create({
            customer: customer,
            usage: 'single_use',
            original_source: data.source,
          }, {
            stripe_account: stripeAccount,
          }).catch((e) => {
            console.log(e);            
        });

and here is the log result: 
Source id = src_1Do0lWJ9FgXIfmLjkZ4PC3Ln 

{ Error: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.
    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)
    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)
    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  type: 'StripeInvalidRequestError',
  stack: 'Error: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.\n    at Constructor._Error (/srv/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at new Constructor (/srv/node_modules/stripe/lib/utils.js:134:13)\n    at Function.StripeError.generate (/srv/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/srv/node_modules/stripe/lib/StripeResource.js:155:39)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)',
  rawType: 'invalid_request_error',
  code: undefined,
  param: undefined,
  message: 'Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.',
  detail: undefined,
  raw: 
   { message: 'Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.',
     type: 'invalid_request_error',
     headers: 
      { server: 'nginx',
        date: 'Fri, 11 Jan 2019 06:26:29 GMT',
        'content-type': 'application/json',
        'content-length': '260',
        connection: 'close',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'access-control-max-age': '300',
        'cache-control': 'no-cache, no-store',
        'idempotency-key': '-LVv_lqqrfj9m8REXmP0',
        'original-request': 'req_FHqt3JQw5vreGA',
        'request-id': 'req_FHqt3JQw5vreGA',
        'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
        'stripe-version': '2018-11-08',
        'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
     statusCode: 402,
     requestId: 'req_FHqt3JQw5vreGA' },
  headers: 
   { server: 'nginx',
     date: 'Fri, 11 Jan 2019 06:26:29 GMT',
     'content-type': 'application/json',
     'content-length': '260',
     connection: 'close',
     'access-control-allow-credentials': 'true',
     'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
     'access-control-max-age': '300',
     'cache-control': 'no-cache, no-store',
     'idempotency-key': '-LVv_lqqrfj9m8REXmP0',
     'original-request': 'req_FHqt3JQw5vreGA',
     'request-id': 'req_FHqt3JQw5vreGA',
     'stripe-account': 'acct_1DnEFHLNuTNejVUJ',
     'stripe-version': '2018-11-08',
     'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
  requestId: 'req_FHqt3JQw5vreGA',
  statusCode: 402 }

**Comment by Kretin1** [comment]
Thank you so much for your help Remi,

I was confused because I was only sending a source ID string, but then I was using the whole newToken instead of just the newToken.id to create the charge. Doh!
