### ISSUE TITLE
Wrong id in line_item of upcoming invoice

### ISSUE THREAD

**Issue by lpgera** [stripe/stripe-node#553]
The result of `stripe.invoices.retrieveUpcoming` returns wrong id's for invoice items. When I call the API with curl, I get line_items with id's starting with `sli_`, but Stripe Node returns the related subscription id (`sub_...`) as the line_item id.

Node version: v8.11.3
Stripe Node version: 6.12.1 (but upgrading to 6.20.0 didn't solve the issue either)

**Comment by remi-stripe** [comment]
@lpgera I don't think this can be an issue with stripe-node, it does not do anything to the data that is returned by the API.

My guess is that this is an issue with the API version on the request as we shipped a change last year in [2018-05-21](https://stripe.com/docs/upgrades#2018-05-21):
> The id field of invoice line items of type=subscription no longer can be interpreted as a subscription ID, but instead is a unique invoice line item ID. It can be used for pagination.

If you force a different API version in your node code you should see the unique id: https://stripe.com/docs/api#versioning

**Comment by lpgera** [comment]
@remi-stripe Thanks for the quick answer!
