### ISSUE TITLE
Feature request: Idempotent retries on API calls

### ISSUE THREAD

**Issue by suchitagarwal** [stripe/stripe-node#558]
In our stripe integration, we sometimes get api errors (StripeAPIError or StripeConnectionError), which are most likely just transient issues and should go away if the API call is just retried. Implementing this on top of the nodejs library right now is hard because we have to manually hijack every single call to the stripe client and implement the retry ourselves.

It'd be great if when setting up the stripe client, I could specify a number of retries, and a max timeout for each api call. 
- As a v1, this could be done just for GET requests, so that the retry logic does not have to worry about idempotency
- Bonus feature request: All API requests can be retried, and are guaranteed to be idempotent as appropriate.

**Comment by remi-stripe** [comment]
We should introduce retry logic as we did in [stripe-php](https://github.com/stripe/stripe-php/pull/428) for example. Assigning to @paulasjes-stripe who mentioned he was interested and tagging as future for now
