### ISSUE TITLE
Reconciling "New Checkout" Session ID with Webhook Event data

### ISSUE THREAD

**Issue by drone1** [stripe/stripe-node#563]
Using node stripe v6.22.0.
Node v10.4.1

I believe this issue falls somewhere in the middle of a bug or feature request.

I've scoured the docs and the web for an answer to this, and dug into event data. It's entirely possible I'm missing something obvious here, but can someone please help me understand how I can reconcile the Session ID returned from stripe.checkout.sessions.create() (with New Checkout enabled) with incoming Webhook events?

As far as I can tell, the Webhooks do not have any reference to a Session ID, and there is no other identifier in the Session that I can use to correlate one to the other.

My code:
```
        stripe.checkout.sessions.create({
            success_url: '...',
            cancel_url: '...',
            allowed_source_types: ["card"],
            line_items: myLineItems,
          },
          { stripe_version: "2018-11-08; checkout_sessions_beta=v1" },
         (err, session) => {
            // session is a Session – https://stripe.com/docs/api/checkout/sessions?lang=node
            // session.id does not relate to any IDs on incoming webhook events
         });
```

The Session ID is 64 or 128 characters whereas all the IDs I see in incoming Webhook events are much shorter, and prefixed with semantic abbreviations for customer/event/transaction/whatever, as I'm sure you know. Anyway, I think you get what I'm asking here – thanks!

**Comment by remi-stripe** [comment]
@drone1 You can pass the parameter `client_reference_id` on Checkout Session creation. This value that you choose will be part of the event we send you once the session is completed to help you with reconciliation.

**Comment by drone1** [comment]
Aha!

**Comment by drone1** [comment]
I'm testing this now with "new Checkout' and although I'm passing in a string for client_reference_id when I create the Session, no client_reference_id is present in the charge.succeeded webhook event that hits my test server.

The client_session_id does show up in the checkout_beta.session_succeeded event, but not the charge.succeeded event.

**checkout_beta.session_succeeded:** (ID= evt_1E1hfMHkfGChL3Y860y85OCu)
```
{
  "object": {
    "object": "checkout_beta",
    "client_reference_id": "gF8JABitJXNSq4Q8s",
    "display_items": null,
    "line_items": [
      {
        "amount": 800,
        "currency": "eur",
        "description": "Dustmite – 7073 – 12" Vinyl + Digital",
        "images": [
          "http://d1e66ciax0ha3z.cloudfront.net/img/templates/catalog_list/sprvd001/m.jpg"
        ],
        "name": "SPRVD001",
        "quantity": 1
      },
      {
        "amount": 339,
        "currency": "eur",
        "description": "Postage & Packaging",
        "images": null,
        "name": "Shipping",
        "quantity": 1
      }
    ],
    "livemode": false,
    "payment_intent": "pi_1E1hf2HkfGChL3Y8WdlFsLDp"
  }
}
```

**charge.succeeded event:** (ID= evt_1E1hfLHkfGChL3Y8nv81pJTZ)
```
{
  "object": {
    "id": "ch_1E1hfKHkfGChL3Y8VcqvWLqh",
    "object": "charge",
    "amount": 1139,
    "amount_refunded": 0,
    "application": null,
    "application_fee": null,
    "application_fee_amount": null,
    "balance_transaction": "txn_1E1hfLHkfGChL3Y8bZRnNOmN",
    "captured": true,
    "created": 1549664266,
    "currency": "eur",
    "customer": "cus_EUh3DPmwaUYpB2",
    "description": null,
    "destination": null,
    "dispute": null,
    "failure_code": null,
    "failure_message": null,
    "fraud_details": {
    },
    "invoice": null,
    "livemode": false,
    "metadata": {
    },
    "on_behalf_of": null,
    "order": null,
    "outcome": {
      "network_status": "approved_by_network",
      "reason": null,
      "risk_level": "normal",
      "risk_score": 36,
      "seller_message": "Payment complete.",
      "type": "authorized"
    },
    "paid": true,
    "payment_intent": "pi_1E1hf2HkfGChL3Y8WdlFsLDp",
    "receipt_email": null,
    "receipt_number": null,
    "receipt_url": "https://pay.stripe.com/receipts/acct_1DyQm1HkfGChL3Y8/ch_1E1hfKHkfGChL3Y8VcqvWLqh/rcpt_EUh3Ciljhy05t2h7f37HuYVpkVfVerz",
    "refunded": false,
    "refunds": {
      "object": "list",
      "data": [
      ],
      "has_more": false,
      "total_count": 0,
      "url": "/v1/charges/ch_1E1hfKHkfGChL3Y8VcqvWLqh/refunds"
    },
    "review": null,
    "shipping": null,
    "source": {
      "id": "src_1E1hfKHkfGChL3Y8BqJJCfbr",
      "object": "source",
      "amount": null,
      "card": {
        "exp_month": 2,
        "exp_year": 2033,
        "last4": "4242",
        "country": "US",
        "brand": "Visa",
        "cvc_check": "pass",
        "funding": "credit",
        "fingerprint": "pzAZvfYaKnEEMmnx",
        "three_d_secure": "optional",
        "name": null,
        "address_line1_check": null,
        "address_zip_check": null,
        "tokenization_method": null,
        "dynamic_last4": null
      },
      "client_secret": "src_client_secret_EUh3WIeWltkrPb4a4gBwkISS",
      "created": 1549664267,
      "currency": null,
      "customer": "cus_EUh3DPmwaUYpB2",
      "flow": "none",
      "livemode": false,
      "metadata": {
      },
      "owner": {
        "address": {
          "city": null,
          "country": "DE",
          "line1": null,
          "line2": null,
          "postal_code": null,
          "state": null
        },
        "email": "a@b.com",
        "name": "a b",
        "phone": null,
        "verified_address": null,
        "verified_email": null,
        "verified_name": null,
        "verified_phone": null
      },
      "statement_descriptor": null,
      "status": "chargeable",
      "type": "card",
      "usage": "reusable"
    },
    "source_transfer": null,
    "statement_descriptor": null,
    "status": "succeeded",
    "transfer_data": null,
    "transfer_group": null
  }
}
```

**Session creation code:**
```
 stripe.checkout.sessions.create({
            success_url: ...,
            cancel_url: ...,
            allowed_source_types: ["card"],
            line_items: lineItems,
            client_reference_id: orderId,
          },
          {
            stripe_version: "2018-11-08; checkout_sessions_beta=v1"
          }, ... )
```

**Comment by remi-stripe** [comment]
@drone1 This is expected though. The value is on the event `checkout_beta.session_succeeded` as documented here: https://stripe.com/docs/payments/checkout/api#add

**Comment by drone1** [comment]
Ah, I was looking at the wrong docs for a second there. My bad. Thank you.

**Comment by hassanazimi** [comment]
I can't get customer_email from webhook when using checkout new version!

**Comment by drone1** [comment]
That sounds like a separate issue.

**Comment by Apokly** [comment]
@remi-stripe From https://stripe.com/docs/payments/checkout/fulfillment#webhooks :

> Stripe sends the checkout.session.completed event when a Checkout payment is successful. The webhook payload includes the Checkout Session object, which contains information about the Customer, PaymentIntent, or Subscription, and optionally the client_reference_id if you provided it when calling redirectToCheckout on the client.

I referenced the `client_reference_id` but my Hook payload looks like `client_reference_id": null`.

What is the problem ?

**Comment by AndreyChernuha** [comment]
Does I can get sessions by client_reference_id? 
Something like this:
sessions = Stripe::Checkout::Session.list({ client_reference_id: 31 })
