### ISSUE TITLE
Format `Date` instances as UNIX timestamps in parameters

### ISSUE THREAD

**Issue by giregk** [stripe/stripe-node#569]
Node version: v8.15.0
Stripe version : 6.21.0

This code does not fetch any charge
```
await stripe.charges.list({ created: { gt: fromDateTimestamp }, limit: 100 }).autoPagingEach(charge => {
         console.log(charge); // is never called
    });
```

whereas this code does fetch charges that were created after `fromDateTimestamp`
```
await stripe.charges.list({ limit: 100 }).autoPagingEach(charge => {
         console.log(charge); // is called
    });
```

I would expect the first code to return filtered values or at least log a warning saying that the created option is not supported.

**Comment by giregk** [comment]
I understood my mistake: Unix Timestamp must be in seconds. I was using `new Date(fromDate).getTime()` which generates milliseconds timestamps. I suggest to update the documentation to make that clearer.

**Comment by ob-stripe** [comment]
Hi @giregk. I'll pass your feedback regarding the docs.

I think it would also be nice if the library automatically formatted `Date` instances as UNIX timestamps, so you could pass them directly for timestamp parameters. We do something similar in most of our other client libraries.

**Comment by ob-stripe** [comment]
As of v6.26.0, you can now pass `Date` instances directly in request parameters, and the library will automatically encode them as Unix timestamps.
