### ISSUE TITLE
Unable to set invoice payment page checkbox

### ISSUE THREAD

**Issue by adamreisnz** [stripe/stripe-node#572]
It seems impossible to change the following setting when creating a subscription via the API:

![image](https://user-images.githubusercontent.com/490562/53389126-f5c97400-39f2-11e9-97ea-10f860f30245.png)

All subscriptions created via API have this checkbox unticked, but I want to enable it.
Is this an API limitation or a Node SDK limitation?

**Comment by remi-stripe** [comment]
@adamreisnz As far as I know you can't force this in the API today so it's similar to the other issue. I would recommend discussing this with our support team too (though I've raised it internally too).

**Comment by adamreisnz** [comment]
Thanks
