### ISSUE TITLE
Module `http` does not exist in the Haste module map

### ISSUE THREAD

**Issue by andriko007** [stripe/stripe-node#573]
>  "react-native": "0.57.8",
> "stripe": "^6.25.1"

When I import 'stripe' I see this issue:
 
`error: bundling failed: Error: Unable to resolve module `http` from `./node_modules/stripe/lib/stripe.js`: Module `http` does not exist in the Haste module map`

**Comment by andriko007** [comment]
I tried to do this steps:

>  1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
>   4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

But it didn't help

**Comment by andriko007** [comment]
this is my fault, I thought that package for client side

**Comment by Ramaraju1992** [comment]
@andriko007 , i am also getting same issue while i am trying to use `var stripe = require("stripe");` ... 
can you please explain me how to fix this...!
Thank you...

**Comment by remi-stripe** [comment]
@Ramaraju1992 The issue likely means that you are trying to use stripe-node client-side in the browser which would not work. stripe-node is a server-side library to make API requests to Stripe.

Client-side, you should instead use [Elements](https://stripe.com/docs/stripe-js#elements) or [Checkout](https://stripe.com/docs/payments/checkout) to collect card details.
