### ISSUE TITLE
Auto Pagination Rate Limiting **Question**

### ISSUE THREAD

**Issue by tbell511** [stripe/stripe-node#575]
Hello, 

Does the auto pagination feature in stripe-node handle rate limiting? For example, can running autoPagingEach on 10000 subscriptions cause stripe to start returning the rate limit error?

Or do we need to manually account for this?

Thanks!

**Comment by remi-stripe** [comment]
@tbell511 It is always possible for this to cause rate limits but that would only happen if other parts of your code are already heavily hitting the API. The auto-pagination behaviour is to do requests sequentially and you're unlikely to hit our rate limits using it.

Your code should still catch any error that this returns though!

**Comment by tbell511** [comment]
Awesome, thanks!

**Comment by yamsellem** [comment]
@remi-stripe may you please provide a sample of how to wrap `autoPagingEach` in a way our code can catch a rate limit and retry from where it left. With this auto method, this seems not immediate to me.

Thanks.

**Comment by paulasjes-stripe** [comment]
@yamsellem You'd want something like this:

```
let lastCustomer = null;

function listAllCustomers(lastCustomer) {
  const params = {
    limit: 3,
  };

  if (lastCustomer !== null) {
    params.starting_after = lastCustomer;
  }

  stripe.customers.list(params).autoPagingEach((customer) => {
    lastCustomer = customer.id;
          
    // Do something with customer      
  }).then(() => {
    // done iterating
  }).catch((err) => {            
    if (err.type === 'StripeRateLimitError') {
      // Back off and restart with `lastCustomer`
      setTimeout(listAllCustomers, 1000, lastCustomer);        
    }
  });  
}

listAllCustomers(lastCustomer);
```

Bear in mind that if you're getting rate limited when hitting a list endpoint then you likely have some inefficiencies in your code that you should look at first. I recommend logging if this happens so you can investigate later.
