### ISSUE TITLE
Subscriptions: Invalid parameter "default_source"

### ISSUE THREAD

**Issue by jlopez994** [stripe/stripe-node#582]
Hello, I'm trying to create a subscription for a customer with a different payment source. The problem is the parameter "default_source" doesn't exist in the interface "ISubscriptionCreationOptions". Instead there is another one called source which doesn't exist in Stripe API so I get this error when I try it: "Received unknown parameter: source".

If you check the Stripe API you can check it out. https://stripe.com/docs/api/subscriptions/create#create_subscription-default_source

**Comment by remi-stripe** [comment]
@jlopez994 The `SubscriptionCreationOptions` class inherits from `SubscriptionSharedOptions` which supports `DefaultSource` so you should be able to set it as expected in your code!
