### ISSUE TITLE
Connect: Multiple bank account as default for currency

### ISSUE THREAD

**Issue by Rc85** [stripe/stripe-node#584]
API version: 2019-03-14

Not sure if this was intended. If I have multiple bank accounts on a Connect account, they can both be default for currency.

To replicate this, add a bank account without the default_for_currency set (it's default to true). Repeat and both bank accounts will have default_for_currency set to true.

**Comment by paulasjes-stripe** [comment]
This isn't an issue related to the Stripe Node bindings but instead an API question. Would you mind contacting Stripe support directly with this? https://support.stripe.com/contact
