### ISSUE TITLE
Feature request: Allow retrieveUpcoming to use only the subscription

### ISSUE THREAD

**Issue by reacuna** [stripe/stripe-node#591]
According the the [docs for version 2019-03-14](https://stripe.com/docs/api/invoices/upcoming?lang=curl#upcoming_invoice-customer) (maybe earlier, I'm not sure), the customer parameter is required only if the subscription parameter is not set.
The implementation however, always uses the first parameter as the customer id: https://github.com/stripe/stripe-node/blob/8b2c36cf2b9ae9d336867293beb4c308c735bd06/lib/resources/Invoices.js#L39
Any chance to allow to use a subscription id without a customer?

**Comment by remi-stripe** [comment]
@reacuna Thanks a lot for the report. I had no idea we hardcoded the customer id in the query params. We'll work on a fix!

**Comment by remi-stripe** [comment]
@reacuna This was fixed in stripe-node 6.30.0!
