### ISSUE TITLE
Export generateHeaderString or similar testing utility

### ISSUE THREAD

**Issue by tatethurston** [stripe/stripe-node#601]
When writing an automated test case to test processing a Stripe webhook, I needed to copy the `generateHeaderString` function (found here: https://github.com/stripe/stripe-node/blob/57d5f09b13973f2134326dabd99762bd66de3bf2/test/Webhook.spec.js#L140).

It would be great to provide this as an exported module, and include a brief example in the readme using it to write tests against a webhook endpoint.

**Comment by paulasjes-stripe** [comment]
Hi there, this should be exposed and ready for use in the next release!
