### ISSUE TITLE
[Typescript] The object "paymentMethods" is missed on definition types

### ISSUE THREAD

**Issue by yaroslavyal** [stripe/stripe-node#603]
Hi! I'm using @types/stripe with version 6.25.11. And there is no object "paymentMethods" in Stripe instance.

**Comment by paulasjes-stripe** [comment]
Those types are maintained on the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo instead of here. You're probably better off creating the issue there as this isn't an issue with the stripe-node library.

**Comment by yaroslavyal** [comment]
Thanks, related with issue [#35155](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35155)
