### ISSUE TITLE
Tax Rates

### ISSUE THREAD

**Issue by tbell511** [stripe/stripe-node#605]
I noticed that the node client doesn't support tax rates yet.

- Create a tax rate
- Retrieve a tax rate
- Update a tax rate
- List all tax rates

Any ideas on a timeframe?

**Comment by robz-stripe** [comment]
Support was added in https://github.com/stripe/stripe-node/commit/a1c629be41c0e6adeb02d898ccc617dddf18da48

Our API docs also have Node examples, e.g. https://stripe.com/docs/api/tax_rates/create?lang=node

**Comment by robz-stripe** [comment]
(you'd need to be using at least https://github.com/stripe/stripe-node/releases/tag/v6.31.0 which is when that commit was released)

**Comment by robz-stripe** [comment]
Closing again since support is there and nothing additional is needed on the repo side.

**Comment by tbell511** [comment]
Awesome, thank you.
