### ISSUE TITLE
Cannot find module '../testUtils'

### ISSUE THREAD

**Issue by schester44** [stripe/stripe-node#616]
Related to PR #609.

I believe the testUtils folder needs whitelisted in .npmignore.

**Comment by remi-stripe** [comment]
@schester44 Thanks for the heads up, we're working on a fix.

**Comment by rattrayalex-stripe** [comment]
We've pulled the 6.33.0 release from npm. We expect to have a fixed version up shortly, but until then, if you encounter this, please reinstall to get 6.32.0.

**Comment by rattrayalex-stripe** [comment]
6.34.0 has been released, addressing this issue. 

Thanks so much for reporting, and apologies for the trouble caused!
