### ISSUE TITLE
`autoPagingToArray` is not a function off of `stripe.invoices.listLineItems`

### ISSUE THREAD

**Issue by mclark-newvistas** [stripe/stripe-node#630]
`invoice.lines.data = await stripe.invoices.listLineItems(invoice.id, { limit: 100 }).autoPagingToArray({ limit: 1000 });` - "TypeError: stripe.invoices.listLineItems(...).autoPagingToArray is not a function" - same w/`autoPagingEach`.

**Comment by mclark-newvistas** [comment]
I'd changed which file I'd intended to test it in, not realizing I'd saved the prior file. The error was generated by the other file.

**Comment by mclark-newvistas** [comment]
Sigh - and it incidentally doesn't work at all off of `listLineItems` anyway :P.

**Comment by ob-stripe** [comment]
@rattrayalex-stripe Can you take a look?

**Comment by paulasjes-stripe** [comment]
I think it might just be a case of adding `methodType: 'list'` here: https://github.com/stripe/stripe-node/blob/master/lib/resources/Invoices.js#L21-L24

**Comment by ob-stripe** [comment]
Oops, yeah, that's probably it. Thanks Paul!

**Comment by rattrayalex-stripe** [comment]
Oops, sorry @ob-stripe - did not get a ping for this.

**Comment by ob-stripe** [comment]
@mclark-newvistas This should be fixed in version 7.0.1.
