### ISSUE TITLE
"No such charge" response for test refund

### ISSUE THREAD

**Issue by dark-swordsman** [stripe/stripe-node#639]
Hello,

Currently testing a new refund feature we are implementing, however, my requests are returned with "No such charge".

Here's my code (for the most part. Had to redact some stuff): 
```js
            stripe.refunds.create({
              charge: chargeId
            }, function(err, refund) {
              const errorResult = handleStripeError(err);
              // if the request had an error, reject with a new Error
              if (!errorResult.error) {
                resolveRefund(refund)
              } else {
                const { rawType, code, param, message } = errorResult;

                rejectRefund(ErrorHandler.report(`Stripe API Error: ${errorResult.type}`, {
                  stripe: {
                    rawType,
                    code,
                    param,
                    message
                  },
                  requestedAmount: `$${roundForDisplay(amount/100, 2)} USD`
                }));
              }
            });
```

Here's the response:
```
  rawType: 'invalid_request_error',
  code: 'resource_missing',
  param: 'id',
  message: 'No such charge: ch_1EhLcdBVKiPpavW9vqD2NWkR',
  detail: undefined,
```

Going into the stripe dashboard, looking at test data, the charge is valid and exists:
![image](https://user-images.githubusercontent.com/7909209/58973861-36692400-877e-11e9-9b18-0f369230b699.png)

And I made sure that our test secret key is passed to the stripe require:
```js
const env = require('../config/env')(process.env.NODE_ENV);
var stripe = require('stripe')(env.stripe.secretKey);
```

Console logging `env.stripe.secretKey` shows the correct secret key.

Node: v8.12.0
Stripe: ^6.23.1

**Comment by remi-stripe** [comment]
@dark-swordsman Github issues should be limited to bugs in the library. For product questions, we recommend that you contact our support team instead: https://support.stripe.com/contact

The issue here seems to be that your code is using the wrong API keys when making the request. The Charge is on Account A, but you are trying to refund it on Account B with the API key from that other account. Just double check that the key you're using matches what the one in the account with that charge.

**Comment by dark-swordsman** [comment]
I see. Thanks for the help. 

It does appear that our API keys are different for some reason. My boss is looking into it, but we've had the same keys for years, but they are all different for some reason.
