### ISSUE TITLE
Issues with retrieving upcoming invoices

### ISSUE THREAD

**Issue by wessberg** [stripe/stripe-node#641]
Hi there,

I'm having issues with using `invoices.retrieveUpcoming`. Specifically, I'm getting this error:

```
When previewing changes to a subscription, you must specify either `subscription` or `subscription_items`
```

...When giving input following the form:

```typescript
await stripe.invoices.retrieveUpcoming({
    customer: "cus_XXXXXXXX",
    subscription: "sub_XXXXXXXX",
    subscription_tax_percent: 25,
    subscription_prorate: true,
    subscription_proration_date: 12345678,
    subscription_items: [
        { plan: "some_plan", quantity: 1 },
        { id: 'si_XXXXXXXX', deleted: true }
    ]
});
```

I'm on v7.1.0.

Am I misunderstanding something? Is there a workaround?

Thanks!

**Comment by ob-stripe** [comment]
Hi @wessberg. I think what's happening here is that you're providing both a customer ID and a subscription ID, but the subscription doesn't belong to that customer, and the API is returning a confusing/unrelated error message.

Can you double-check that the customer is the correct one for the subscription?

**Comment by wessberg** [comment]
Hi @ob-stripe, you're absolutely right. This was embarassing. Although yes, a better error message would have saved me a lot of time. Thanks a lot for the swift response. Closing!

**Comment by ob-stripe** [comment]
No worries at all! I've filed a request for the Billing engineering team to provide a better error message.
