### ISSUE TITLE
How add metadata in payment intent when creating subscription

### ISSUE THREAD

**Issue by franxx32** [stripe/stripe-node#644]
I need to set metadata in every payment intent because i want to receive hook from `payment_intent.created` event always with some fields in meta data. In which way i can do it?

**Comment by paulasjes-stripe** [comment]
You can set metadata when [creating](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-metadata) a Payment Intent but please contact [Stripe support](https://support.stripe.com/contact) about integration problems in the future as this is not an issue with the stripe-node library itself.

**Comment by remi-stripe** [comment]
@kenneth488 Github issues are limited to bugs with the library itself as my colleague mentioned on this issue almost 4 years ago. This is an integration support question and more a feature request for the API itself really and not something that should be filed here.

Overall, there's no plan to support passing the Subscription's metadata down to the PaymentIntent. Our API almost never does "metadata inheritance" like this. We recommend using the Invoice to reconcile data a Subscription so you can go from PaymentIntent to the Invoice if any to the Subscription.

If you have more questions, I do recommend going back to our support team as it's the right place to get help about your own code or integration.

**Comment by kenneth488** [comment]
@remi-stripe you could also just provide developers with the solution that they can simply update the PaymentIntent right after creating the Subscription, thus adding the metadata this way, before any event is fired e.g. PaymentIntent success or failure etc. 

This is what I have done. 

`data := &stripe.PaymentIntentParams{}
	data.AddMetadata("user_id", user.ID)
	data.AddMetadata("subscription_id", subscription.ID)

	_,err = controller.StripeAPI.PaymentIntents.Update(sub.LatestInvoice.PaymentIntent.ID, data)`

**Comment by emrysr** [comment]
> @remi-stripe you could also just provide developers with the solution that they can simply update the PaymentIntent right after creating the Subscription, thus adding the metadata this way, before any event is fired e.g. PaymentIntent success or failure etc.
> 
> This is what I have done in Go.
> 
> `data := &stripe.PaymentIntentParams{}` `data.AddMetadata("user_id", user.ID)` `data.AddMetadata("subscription_id", subscription.ID)` `_,err = controller.StripeAPI.PaymentIntents.Update(sub.LatestInvoice.PaymentIntent.ID, data)`
> 
> In many cases your support team just refers to the docs - without giving any good indication of what to do. Thus, developer might come here, because they know it's usually developers responding.
> 
> Maybe being a bit more helpful would be ideal here - since the support solution is slow and not that optimal always.
> 
> Cheers :-)

what happens when the subsequent payment intents are created by the subscription? will the metadata carry forward?

**Comment by remi-stripe** [comment]
@emrysr No it won't, you have to listen to the `invoice.paid` Events and add metadata after the fact for each future Invoice and its underlying PaymentIntent (if any)
