### ISSUE TITLE
SCA (Strong Customer Authentication) Support

### ISSUE THREAD

**Issue by lorenzosfarra** [stripe/stripe-node#654]
Hi,

I have just received an email by Stripe related to Strong Customer Authentication (SCA) that will start to affect payments starting from 14th of September.
I have just started to have a look at the documentation.
Anyway, in the meantime I was trying to find something related in the commits messages here to understand if it's somehow already supported, but I haven't found anything related.
I would like to ask if it is already supported.
 - Case YES: is there any use-case documentation for it? (Both for one-time payment and subscriptions)
 - Case NO: is there a timetable for its support, in order to better plan our next tasks in our team?

Thanks,
  Lorenzo

**Comment by paulasjes-stripe** [comment]
Hi, this isn't an issue with the stripe-node library so closing this.

SCA is fully supported by this library, for information on how to migrate to SCA, have a look here: https://stripe.com/docs/strong-customer-authentication/migration
