### ISSUE TITLE
Where we can pass card num.  , card expiry details and CVV of the card

### ISSUE THREAD

**Issue by himanshubudhlakoti** [stripe/stripe-node#656]
Hello All,
I am new in stripe can anyone let me know that where we can pass card details in below code,
I am missing card no , CVV, expiry params in below code
`stripe.customers
  .create({
    email: 'foo-customer@example.com',
  })
  .then((customer) => {
    return stripe.customers.createSource(customer.id, {
      source: 'tok_visa',
    });
  })
  .then((source) => {
    return stripe.charges.create({
      amount: 1600,
      currency: 'usd',
      customer: source.customer,
    });
  })
  .then((charge) => {
    // New charge created on a new customer
  })
  .catch((err) => {
    // Deal with an error
  });`

**Comment by ob-stripe** [comment]
Hi @himanshubudhlakoti. Github issues are specifically for bugs or feature requests regarding Stripe's Node.js library and are not a support channel. Please reach out to Stripe's support at https://support.stripe.com/email.

**Comment by egisberto** [comment]
@himanshubudhlakoti , look at this link: https://stripe.com/docs/api/cards/create

You need to create a credit card token and use their return to use in source.
