### ISSUE TITLE
Is Stripe SDK Classes compatible?

### ISSUE THREAD

**Issue by ledniy** [stripe/stripe-node#659]
I just discovered that by default i can't extend Stripe Resources, it just keep the same behaviour. As i understand you don't using default prototype inheritance?

```
const Stripe = require('stripe');
const PaymentIntents = require('stripe/lib/resources/PaymentIntents');

class PaymentIntentsFloat extends PaymentIntents {
	create (data, options) {
		data.amount = convertAmountToSmallestDenomination(data.amount, data.currency);
		return super.create(data, options);
	}
}

class StripeWrapped extends Stripe {
	constructor(...args) {
		super(...args);
		this.paymentIntentsFloat = new PaymentIntentsFloat(this);
	}
}
```

**Comment by rattrayalex-stripe** [comment]
Hi @ledniy , 

You are correct – you can't subclass stripe resources in this way currently. There are some other options for extending the stripe sdk, but I don't think I'd recommend them – probably better to create wrapper functions.

This may be possible when we add support for TS: https://github.com/stripe/stripe-node/issues/296

However, I don't anticipate that we will prioritize work here independently, so I'm going to close this. Will try to keep you posted here if we're able to move things to proper classes.
