### ISSUE TITLE
Cannot find module 'lodash.isplainobject'

### ISSUE THREAD

**Issue by erwanv** [stripe/stripe-node#679]
I have the following error after trying to Maj from 7.3 to 7.8.
I tried clean build (rm node_modules, rm package-lock, node reinstall).
Node version => 11.1
Stripe version => 7.3 ok all is running fine
Stripe version => 7.8, following error :

If you're having general troubError: Cannot find module 'lodash.isplainobject'
[NODE]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
[NODE]     at Function.Module._load (internal/modules/cjs/loader.js:513:25)
[NODE]     at Module.require (internal/modules/cjs/loader.js:643:17)
[NODE]     at require (internal/modules/cjs/helpers.js:22:18)
[NODE]     at Object.<anonymous> (/home/erwan/WebstormProjects/dymafr/express-server/node_modules/stripe/lib/utils.js:9:21)
[NODE]     at Module._compile (internal/modules/cjs/loader.js:707:30)
[NODE]     at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
[NODE]     at Object.require.extensions.(anonymous function) [as .js] (/home/erwan/WebstormProjects/dymafr/node_modules/ts-node/src/index.ts:465:14)
[NODE]     at Module.load (internal/modules/cjs/loader.js:605:32)
[NODE]     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
[NODE]     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
[NODE]     at Module.require (internal/modules/cjs/loader.js:643:17)
[NODE]     at require (internal/modules/cjs/helpers.js:22:18)
[NODE]     at Object.<anonymous> (/home/erwan/WebstormProjects/dymafr/express-server/node_modules/stripe/lib/stripe.js:31:13)
[NODE]     at Module._compile (internal/modules/cjs/loader.js:707:30)
[NODE]     at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
[NODE]     at Object.require.extensions.(anonymous function) [as .js] (/home/erwan/WebstormProjects/dymafr/node_modules/ts-node/src/index.ts:465:14)
[NODE]     at Module.load (internal/modules/cjs/loader.js:605:32)
[NODE]     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
[NODE]     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
[NODE]     at Module.require (internal/modules/cjs/loader.js:643:17)
[NODE]     at require (internal/modules/cjs/helpers.js:22:18)
[NODE]     at Object.<anonymous> (/home/erwan/WebstormProjects/dymafr/express-server/src/controllers/stripeController.ts:11:16)
[NODE]     at Module._compile (internal/modules/cjs/loader.js:707:30)
[NODE]     at Module.m._compile (/home/erwan/WebstormProjects/dymafr/node_modules/ts-node/src/index.ts:473:23)
[NODE]     at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
[NODE]     at Object.require.extensions.(anonymous function) [as .ts] (/home/erwan/WebstormProjects/dymafr/node_modules/ts-node/src/index.ts:476:12)
[NODE]     at Module.load (internal/modules/cjs/loader.js:605:32)

**Comment by richardm-stripe** [comment]
Thanks for the report!

I haven't been able to reproduce this myself yet. We did remove the 'lodash.isplainobject' package recently. I'm wondering if there may something outdated that's not getting cleaned up on your system. You might try `npm cache clean`, or running `ts-node` with the `--no-cache` option (if you're using an older version of ts-node. The newest versions did away with the cache.)

Otherwise, it would be helpful to know:
The contents of your `package.json`, and also the contents of `/home/erwan/WebstormProjects/dymafr/express-server/node_modules/stripe/package.json`)

**Comment by erwanv** [comment]
@richardm-stripe 
Hello, I did the following:
- npm cache verify (I run npm 6.10.3)
- rm -rf node_modules/
- clean install
And it's working thx
