### ISSUE TITLE
Currency and interval fields must match across all plans on this subscription. Found mismatch in interval field.

### ISSUE THREAD

**Issue by jayna456** [stripe/stripe-node#682]
I have one product under two items created monthly and yearly with different price and interval. I am able to create subscription with monthly plan. But when I am going to update i.e. when I want to change my subscription plan to yearly. It is showing me **Currency and interval fields must match across all plans on this subscription. Found mismatch in interval field.**

The error telling that currency and interval must be same. But as I have created plans monthly and yearly. I have to set interval period monthly and yearly.

I have refer [this link](https://stripe.com/docs/billing/subscriptions/upgrading-downgrading)

Node version: 8.11.2
stripe version: 7.4.0

**Comment by ob-stripe** [comment]
Hi @jayna456. This isn't an issue with the stripe-node library, but rather with the way you're using the API. You should reach to Stripe's support at https://support.stripe.com/email to explain the problem. Make sure to mention the IDs of the objects (customer, subscription, etc.).

**Comment by icoloma** [comment]
@ob-stripe Regardless, for those that arrive here searching for a solution to the same problem it would be useful to explain possible causes

**Comment by remi-stripe** [comment]
@icoloma That's fair but Github issues are not a support forum for the API, this would be unfortunately unscalable at the moment. But to unblock you, you can't create a Subscription with multiple prices (or plans) that have a different currency or billing cycle. This is documented here https://stripe.com/docs/billing/subscriptions/multiple-products#restrictions

**Comment by icoloma** [comment]
In my case, I didn't know that I should use the same subscription line id when sending an update, if it's missing Stripe creates a second item (hence the conflict). The comments on [this SO entry](https://stackoverflow.com/questions/57489962/currency-and-interval-fields-must-match-across-all-plans-on-this-subscription-f) helped.

I understand that this is not a support forum, but leaving the top result on Google search answered would be a scalable way to reduce friction on the platform.

**Comment by remi-stripe** [comment]
You're definitely right. I'll also flag internally to see if we can write a support article about this exact error and improve the SEO on it to make it the top result instead!

**Comment by attacomsian** [comment]
For anyone, who is still looking to solve this issue, you have to specify the current subscription item ID while downgrading or upgrading the plan.

Without the existing item ID, it throws an error when the billing interval is different (month <-> year).

```javascript
const subscription = await stripe.subscriptions.retrieve('SUBSCRIPTION_ID');
stripe.subscriptions.update('SUBSCRIPTION_ID', {
  cancel_at_period_end: false,
  proration_behavior: 'create_prorations',
  items: [{
    id: subscription.items.data[0].id,
    price: 'NEW_PRICE_ID',
  }]
});
```

The following line is crucial:

```js
id: subscription.items.data[0].id,
```

Source: [Stripe Docs](https://stripe.com/docs/billing/subscriptions/upgrade-downgrade#changing)

**Comment by remi-stripe** [comment]
The reason you have to do this is because the array is not a "replace" operation but a "merge". So if you are on Price A and B already and you send Price C, you are not on C, you are on A, B and C at the same time.

By passing the explicit id of the SubscriptionItem in your call, you are explicitly saying "replace price A by price B on this item". An alternative would also be to explicitly delete the old item and create a new one in one call like this:

```
const subscription = await stripe.subscriptions.retrieve('SUBSCRIPTION_ID');
stripe.subscriptions.update('SUBSCRIPTION_ID', {
  cancel_at_period_end: false,
  proration_behavior: 'create_prorations',
  items: [{
    id: subscription.items.data[0].id,
    deleted: true
  },{
    price: 'NEW_PRICE_ID',
  }
]
});
```
