### ISSUE TITLE
Unable to query BalanceTransfers and Payouts for connected accounts

### ISSUE THREAD

**Issue by adamreisnz** [stripe/stripe-node#683]
```
Error: This application does not have the required permissions for this endpoint on account 'acct_xxxxxx'. The required permissions are not available for use by Standard Connect applications.
```

Why is this happening? We tested this locally and it was working fine, yet in production we can't show payouts for none of our connected accounts.

When browsing through the dashboard and viewing a connected account there is clearly no permissions issue, as I can see all the payouts just fine. How come then the API doesn't have access to query this data?

**Comment by remi-stripe** [comment]
@adamreisnz This issue seems to be unrelated to listing Transfers or Payouts and my guess is that your code is potentially doing something else. It's hard to say without more context though. Since this is a question about the API, I would recommend talking to our support team: https://support.stripe.com/contact

**Comment by adamreisnz** [comment]
Thank you, I have double checked and this was in fact caused by a call to the external_accounts which we were trying to map to the payouts. My bad, this does not appear possible!

**Comment by adamreisnz** [comment]
@remi-stripe as a follow up, how come in the dashboard, when we click through to a connected Standard account, Stripe is able to display the external account details of where payouts are going to, related to each payout, yet via the API we are not allowed access to this information?

It would seem to me that if it isn't allowed via the API it shouldn't be possible to see this information in the dashboard either?

**Comment by remi-stripe** [comment]
@adamreisnz Different permissions for the Dashboard but this has always been blocked in the API.

**Comment by adamreisnz** [comment]
Ok that's a pity, we would have liked to show the masked account information to the users for reference. Any chance of this becoming possible in the future?

**Comment by remi-stripe** [comment]
No plan to make this available no. I'd recommend discussing this with our support team!

**Comment by adamreisnz** [comment]
Will do, thanks
