### ISSUE TITLE
Type error while adding to subscription_data to a session.

### ISSUE THREAD

**Issue by drdatarulz** [stripe/stripe-node#685]
When creating a new session for a subscription plan I get a static error on items:

Type '{ plan: string; }[]' is missing the following properties from type 'IList<ISubscriptionItem>': object, data, has_more, url;

index.d.ts(6467, 13): The expected type comes from property 'items' which is declared here on type 'ISubscription'
Code below:

        import * as Stripe from 'stripe';
        const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

          stripe.checkout.sessions.create(
            {
              success_url: 'https://example.com/success',
              cancel_url: 'https://example.com/cancel',
              payment_method_types: ['card'],
              customer_email: dummy@example.com 
              subscription_data: {
                 items: [ {plan: subcriptionInfo.name,}],
             },
            function(err, session) {
              // asynchronously called
            }
          );

I was able to get around the error by going to "interface ICheckoutCreationOptions" and changing line 2108 to:
subscription_data?: subscriptions.ISubscription | any;

Is there another way to do this?

**Comment by cdock1029** [comment]
@drdatarulz The method is using the wrong type. I made a pull request to fix.

Temporary workaround:

```typescript
     const subscription_data: subscriptions.ISubscriptionCustCreationOptions = {
        trial_period_days: 7,
        items: [{ plan: config.plans.subscription.monthly, quantity: 1 }],
      }

      const session = await stripe.checkout.sessions.create({
        // used here...
        subscription_data: subscription_data as any,

        customer_email: user.email,
        client_reference_id: user.uid,
        payment_method_types: ['card'],
        billing_address_collection: 'required',
        success_url: 'http://localhost:3000/success',
        cancel_url: 'http://localhost:3000/cancel',
      })
```

**Comment by aguerschu** [comment]
Hi @cdock1029 how are you?

I just came up with the same issue for canceling subscriptions, I guess your PR just fixed the type of the create session.

Do you think your workaround would work for this function as well?

TypeError: stripe.subscriptions.cancel is not a function
