### ISSUE TITLE
Getting error stripe.customers.createTaxIds is not a function

### ISSUE THREAD

**Issue by mritgupta** [stripe/stripe-node#687]
Stripe API Version:- 7.8.0

Docs:- https://stripe.com/docs/api/customer_tax_ids/create

I am getting error

```js
stripe.customers.createTaxIds is not a function
```
Example code
```js
await stripe.customers.createTaxIds({ type: 'eu_vat', value: 'DE123456789' });
````

Note:- I also fell customer as first parameter missing in createTaxIds docs

**Comment by mritgupta** [comment]
I try to use  ```stripe.customers.createTaxId``` this is working

**Comment by ob-stripe** [comment]
Hi @mritgupta, thanks for bringing this to our attention. This is an issue with the API reference, not the library itself. We will fix the examples in the API reference soon.
