### ISSUE TITLE
Unset holder name when update bank account

### ISSUE THREAD

**Issue by zlydenko** [stripe/stripe-node#688]
stripe-node version: ^7.8.0

When updating bank account we can set account_holder_name and account_holder_type to null if we want to unset this properties (https://stripe.com/docs/api/external_account_bank_accounts/update). 

Still when we doing this update
```
await this.stripeAcc.accounts.updateExternalAccount(accountId, bankAccId, {
  account_holder_name: null
});
```
values are not unsetting, and in dashboard logs we see that request POST body to /v1/accounts/accId/external_accounts/bankId is:
```
{
  "account_holder_name": ""
}
```

Not working as expected

**Comment by remi-stripe** [comment]
@zlydenko Sorry for the delays. This is not a bug with the library itself and likely a limitation of the API. I would recommend that you reach out to our support team and provide example request(s) showing this issue and they can help investigate. You can contact them here: https://support.stripe.com/contact
