### ISSUE TITLE
GET requests use request body instead of query parameters

### ISSUE THREAD

**Issue by ajbouh** [stripe/stripe-node#690]
Setting a body for GET requests appears to be a gray area in the HTTP spec.

This can cause many subtle and hard to debug issues. For example, when the request body is not properly submitted to the server, auto pagination logic goes into an infinite loop, since the starting_after parameter is lost/ignored and it will just return the first 10 values over and over again.

A possible fix would be to just append the data to the request path as query parameters. (This appears to be what `curl` does automatically.)

**Comment by ob-stripe** [comment]
Thanks for the report @ajbouh. This was already a known issue but we've been ignoring it for too long. We're working on a fix and will release a new version soon.

**Comment by ob-stripe** [comment]
This was fixed in 7.9.0, courtesy of @richardm-stripe!
