### ISSUE TITLE
paymentIntent.metadata for additional information?

### ISSUE THREAD

**Issue by rwieruch** [stripe/stripe-node#693]
Hello there! Just a general question where I couldn't find any answer in the documentation. 

I have set up the Server-Side Checkout with Express + React over [here](https://github.com/rwieruch/react-express-stripe) for one time payments. Everything works as expected. **My question:** Where can I send an extra payload -- which can be used by me to fulfill the order later in the Stripe Webhook -- when I create the initial session on the server? 

Am I right that I could use the `paymentIntent.metadata` [fields](https://stripe.com/docs/api/checkout/sessions/create) to send arbitrary data which I could [retrieve in the Webhook](https://stripe.com/docs/api/payment_intents/retrieve) to fulfill my customer's order? I am already using the `client_reference_id `, but I need more data to send for my order fulfilment.

**Comment by paulasjes-stripe** [comment]
If `client_reference_id` doesn't suit your requirements, you can pass metadata in on [Checkout Session creation](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-metadata) for the PaymentIntent.

For questions like this please refer to Stripe support (https://support.stripe.com/contact) instead, this repo is for issues relating to the stripe-node package and not Stripe API questions.
