### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by MatteoAntolini** [stripe/stripe-node#694]
Error while creating setupIntents:

`return new Promise(function(resolve, reject) {
  stripe.setupIntents.create({payment_method_types: ['card']
}).then((result) => {Promise.resolve({setupIntentId: result["id"], client_secret: ["client_secret"]});
}).catch((err) => {Promise.reject(new functions.https.HttpsError('invalid-argument', err.message));
});
});`

`TypeError: Cannot read property 'create' of undefined`

stripe variable is not undefined.

Stripe version : 6.36.0

API [Ref](https://stripe.com/docs/api/setup_intents/create)

**Comment by remi-stripe** [comment]
@MatteoAntolini support for `SetupIntent` was added in stripe-node 7.4.0 so you need to upgrade your library: https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#740---2019-06-27
