### ISSUE TITLE
Testing insuficient funds in developer mode

### ISSUE THREAD

**Issue by freynolds** [stripe/stripe-node#695]
Hi, I'm trying to use this card 4000000000009995 and it always gets declined when I try to create the card.
I need to add to a customer a card with no funds so I can check the response data correctly.
This is a pretty normal situation with debit cards
Thanks

**Comment by remi-stripe** [comment]
@freynolds Github issues should be limited to bugs with the library. I'd recommend you contact our support team as this is more a question about the API: https://support.stripe.com/contact

Just in case, you can try `4000008260003178` from https://stripe.com/docs/testing#regulatory-cards maybe?
