### ISSUE TITLE
Test Connect Express accounts cannot successfully set up subscriptions with test customers

### ISSUE THREAD

**Issue by wrrrn** [stripe/stripe-node#698]
I have a system in which users can create a Connect Express account through Stripes provided UI and create monthly plans which other users may subscribe to. However, when in test mode, I am unable to successfully activate a seller account always due to incomplete details (SSN). I sign up using test phone number and bank account details and use the SSN placeholder of "8888". This seller is still marked incomplete. Any subscription a customer may attempt to subscribe to is not active due to seller having incomplete details.

Does Stripe allow seller accounts to ever be fully active?
Does Stripe allow test seller accounts to charge test customers for subscriptions?

Thank you.

Node - 10.16.0
Stripe - 6.22.0

**Comment by remi-stripe** [comment]
@wrrrn Github issues should be limited to bugs with the library. This is a question about the product itself so I would recommend contacting our support team instead: https://support.stripe.com/contact

You can also look at our documentation for test values you can use to verify accounts: https://stripe.com/docs/connect/testing

**Comment by wrrrn** [comment]
Yes, but I have gone to support. They were unable to tell me why the seller account is never marked as 'active' even when I supply Stripe with only "test" data.

**Comment by wrrrn** [comment]
Here is something I didn't mention:

Any account with 'card_payment' capabilities is marked 'inactive' vs accounts which are active and only have 'transfer' capabilities. Anything with both is 'inactive' and always due to "Missing SSN". I always fill SSN with the placeholder "8888" as I wrote above.

**Comment by remi-stripe** [comment]
@wrrrn This is really not an issue with the stripe-node library so it's not something I can help with directly here. You should get back to our support team and provide example account ids that they can investigate for you to figure out what could be causing this

**Comment by wrrrn** [comment]
For anyone who stumbles on this in the future:

The test SSN for the Express sign up flow is `0000`.

Side note as well:
You need to use a real street address otherwise Stripe will keep the account restricted.

Neither of these are listed in the docs. The docs are great, but can tend to be a forrest.

**Comment by wrrrn** [comment]
Heh. It is actually in the docs. But I didn't see it.

Here's the link:
https://stripe.com/docs/connect/testing#test-personal-id-numbers
