### ISSUE TITLE
TypeError: stripe.customers.listCards is not a function

### ISSUE THREAD

**Issue by THPubs** [stripe/stripe-node#704]
The `listCards` function is not working for the customers. The code I tried:

```
import Stripe from 'stripe';

const stripe = new Stripe(STRIPE_SECRET_KEY);
stripe.customers.listCards(stripeCustomerID)
```

What I got is:

```
stripe.customers.listCards is not a function
```

Anyway, the TypeScript definitions say that this is valid. Any idea what's happening?

**Comment by paulasjes-stripe** [comment]
It's likely that you're using the DefinitelyTyped TypeScript definitions, please bear in mind that those are maintained by a 3rd party and can be prone to error.

In this case, `listCards` does not exist on the customer object, you'll likely want to use `listSources` instead: https://github.com/stripe/stripe-node/blob/master/lib/resources/Customers.js#L57-L61
