### ISSUE TITLE
Support for Plan#amount_decimal

### ISSUE THREAD

**Issue by ajbouh** [stripe/stripe-node#708]
I don't see support for Plan#amount_decimal anywhere in the current code base. 

Assuming it's not actually present, I think it should be added. See: https://stripe.com/docs/api/plans/create#create_plan-amount_decimal

**Comment by ob-stripe** [comment]
Hi @ajbouh. We don't declare specific resource fields or request parameters in stripe-node's source code. Rather, the library will accept any parameters you provide, and any fields returned by Stripe's API.

This should work:
```js
stripe.plans.create({
  amount_decimal: 0.001,
  interval: "month",
  product: {
    name: "Gold special"
  },
  currency: "usd",
}, function(err, plan) {
  console.log(plan.amount_decimal);
});
```

If you have more questions, please reach out to Stripe's support at https://support.stripe.com/email.

**Comment by ajbouh** [comment]
Gotcha, seems like my bug should be filed against the @types/stripe package. Thanks!

**Comment by ob-stripe** [comment]
Ah, right. In the future we will provide our own type definitions directly with stripe-node, but right now the type definition package is distinct and maintained by the community, so you'd indeed have to open an issue with them. Thanks!
