### ISSUE TITLE
Setting request timeout per request

### ISSUE THREAD

**Issue by kristijanhusak** [stripe/stripe-node#712]
Hello,

is there a way to set request timeout only for single request?

I want to make certain api calls to timeout earlier, so i can retry them. I would assume something like this:

```javascript
// timeout after 20 sec
stripe.paymentIntents.capture(intentId, { timeout: 20000 });
```

**Comment by paulasjes-stripe** [comment]
Hi there. Unfortunately it's not possible at this time, but it will be very soon. I'm working on adding this for `timeout` and other global settings. You can follow along here: https://github.com/stripe/stripe-node/pull/703
