### ISSUE TITLE
Transaction list filtered by a specific payment method

### ISSUE THREAD

**Issue by zmras** [stripe/stripe-node#715]
Hi guys!

Currently in our app, we are listing all payment methods attached to a customer. One customer may have multiple cards linked to his account.

We'd like to get the transaction list by each payment method of that customer.

Now, we get all transactions related to a customer by using:
`const transactions = await stripe.charges.list({customer: customerId, limit: 100}); // plus ending_before or starting_after for pagination`

But to get the list of transaction for a specific payment method we have to filter the array by payment method. It is tough because some cards had been used a long time ago so we have to send more transaction list request and iterate to find a transaction with that old card.

We are wondering if there is already a parameter to put inside stripe.charges.list() in order to get  the transactions related to a specific payment method only.

Thank you guys.

**Comment by remi-stripe** [comment]
@zmras It's not something the API supports today unfortunately so it can't be added in the library. 

This is more a question about the product and it's not a question or bug about the library itself and github issues are really for improvements and bug reports for the library so I'm going to close this.

Make sure to follow up with our support team https://support.stripe.com/contact to discuss this. I don't think it's something we'd add to the API though and I'd recommend tracking this in your database instead when charges are created.
