### ISSUE TITLE
Typescript error for `stripe.events.list`

### ISSUE THREAD

**Issue by skeie** [stripe/stripe-node#716]
Hey, 

Looking at the documentation for [Passing-Options](https://github.com/stripe/stripe-node/wiki/Passing-Options), there is an example listed there 

```
stripe.events.list({
  limit: 20,
  starting_after: 40
});
```

When I copy-paste that example into my typescript project I get this:

```
No overload matches this call.
  Overload 1 of 4, '(data: IEventListOptions, response?: IResponseFn<IList<IEvent>>): IListPromise<IEvent>', gave the following error.
    Type 'number' is not assignable to type 'string'.
  Overload 2 of 4, '(options: HeaderOptions, response?: IResponseFn<IList<IEvent>>): IListPromise<IEvent>', gave the following error.
    Argument of type '{ limit: number; starting_after: number; }' is not assignable to parameter of type 'HeaderOptions'.
      Object literal may only specify known properties, and 'limit' does not exist in type 'IHeaderOptions'.
  Overload 3 of 4, '(response?: IResponseFn<IList<IEvent>>): IListPromise<IEvent>', gave the following error.
    Argument of type '{ limit: number; starting_after: number; }' is not assignable to parameter of type 'IResponseFn<IList<IEvent>>'.
      Object literal may only specify known properties, and 'limit' does not exist in type 'IResponseFn<IList<IEvent>>'.
```

Because  the `List` type in stripe-types look like this:

```
      list(
                data: events.IEventListOptions,
                options: HeaderOptions,
                response?: IResponseFn<IList<events.IEvent>>,
            ): IListPromise<events.IEvent>;
```
Which specifies that the first argument should be `IEventListOptions`, but according to the docs it states: 
```
For methods where all arguments are optional, e.g. the stripe.events.list() method (documentation), you would simply pass them all in via an object as the first argument:
```

So I think that the stripe-typescript library and this node library is not 100% aligned. So my question is: Is this possible to fix? 
Everything works, but it sucks to add `// @ts-ignore` to our code to run our project.

npm versions:
```
"@types/stripe": "^7.10.60",
"stripe": "^7.10.0",
```

**Comment by robz-stripe** [comment]
@skeie Thanks for the report! The TypeScript definitions are a third-party effort maintained at https://github.com/DefinitelyTyped/DefinitelyTyped and are sometimes out-of-date (especially with new parameters/features) or incomplete. I'd recommend talking to the devs over there to see if/when they can get things updated.
