### ISSUE TITLE
StripeError.type missing from logs

### ISSUE THREAD

**Issue by pushplay** [stripe/stripe-node#718]
Hello,

Logging error objects is a super normal thing to do both in production code and in exploring the API.  With recent StripeError changes `StripeError.type` is defined as a getter which means it's not enumerable and doesn't show up in logging output.  That makes the output rather confusing.

There might be a way to make the getter enumerable so it shows up in logging output but just a regular old property on the object is probably simpler.

**Comment by paulasjes-stripe** [comment]
Looks like this was fixed in #719.
