### ISSUE TITLE
Wiki error page outdated

### ISSUE THREAD

**Issue by techieshark** [stripe/stripe-node#726]
This is feature-request/bug related to the docs of the Stripe Node library.

I'm looking at the error handling wiki page:
https://github.com/stripe/stripe-node/wiki/Error-Handling

And comparing to the [actual implementation](https://github.com/stripe/stripe-node/blob/ba4c5a9f9cb122e63c426ec0bf01b1a286e8a6cc/lib/Error.js#L170)…

It seems the following are undocumented:
```
module.exports.StripePermissionError = StripePermissionError;
module.exports.StripeSignatureVerificationError = StripeSignatureVerificationError;
module.exports.StripeIdempotencyError = StripeIdempotencyError;
module.exports.StripeInvalidGrantError = StripeInvalidGrantError;
```

**Comment by rattrayalex-stripe** [comment]
Thanks @techieshark ! Fixed. 
Note that I did not include `StripeSignatureVerificationError` because it does not occur in a request lifecycle.

**Comment by techieshark** [comment]
Looks great, thanks @rattrayalex-stripe!
