### ISSUE TITLE
List invoices and list all invoice items are not working with the created filter.

### ISSUE THREAD

**Issue by joeandrews** [stripe/stripe-node#73]
The stripe REST api permits you to use a filter on the returned list by filtering on the object created field. The documentation states: " The value can be a string with an exact UTC timestamp, or it can be a object with the following options.." Only the string option seems to work and I can't use any of the greater than or less than methods.

I presume the following logic is correct.

```
stripe.invoiceItems.list({
                customer:data.stripe_customer,
                created:{
                    gt:<UTC TIMESTAMP>
                },
                count:50


            } ,function(err, invoice) {
})
```

**Comment by gowthamrodda** [comment]
Hy, I am facing a similar problem. When there are no invoices in , the response from the callback is unpredictable or unable to handle. My Code:

            stripe
              .invoices
              .list({customer: records[i].customerId , date: records[i].responseObj.created})
              .then((invoiceList) => {
               console.log('no of invoices:'+ invoiceList.data.length); 
               if(invoiceList.data.length !==0) {
                  // do something 
               }
               });
               .catch((err) => {
                  console.log(err);
               });
When there are no invoices for a particular customer, the response from the api call i.e, invoiceList is unpredictable. the console.log statement is not shown up anything. Please help.

**Comment by chrisvariety** [comment]
@gowthamrodda Looks like the same issue as #301
