### ISSUE TITLE
Token from Google Pay API

### ISSUE THREAD

**Issue by vasilisach** [stripe/stripe-node#739]
How can I use token which I get from Google Pay API to continue transaction with Payment Intents API?

First, I create payment method  https://stripe.com/docs/api/payment_methods/create

    let stripe = Stripe(process.env.STRIPE_SK);
    let paymentMethod = await stripe.paymentMethods.create({
      type: 'card',
      card: { token: token }
    })

But I get an error : Invalid token id

Thank you for any help

**Comment by cjavilla-stripe** [comment]
Hey @vasilisach thanks for reaching out, since this isn't really a question specific to stripe-node directly can you reach out to support.stripe.com/contact or on IRC #stripe channel on Freenode (https://webchat.freenode.net/?channel=#stripe).
