### ISSUE TITLE
tax_id_data.type where the country isn't in the type list

### ISSUE THREAD

**Issue by MatteoAntolini** [stripe/stripe-node#741]
I need to insert the tax_id_data.type when I'm creating a new customer. 
For an American customer what I need to insert? I tried to contact Stripe support and they said that I can insert "unknown", but it returns an error.
 
I would like to avoid to insert the tax_id_data.value in a metadata because I can't make two structures, one with metadata and one with tax_id_data also because I need the VAT(or the EIN) in the invoices of my customers

**Comment by remi-stripe** [comment]
@MatteoAntolini Github issues should be limited to bugs with the library. This is a question about our product though so I'm going to close this for now. Instead, you should talk to our support team again and they can help you better understand how this works: https://support.stripe.com/contact

At the moment though, we don't suppose US tax ids for Customers so you can not collect that information in the US, and you can not set `unknown` as you've already confirmed. It's something we're working on and hope to ship in the future.
