### ISSUE TITLE
typescript, export more interfaces

### ISSUE THREAD

**Issue by xenoterracide** [stripe/stripe-node#759]
using the beta for 8.0 of stripe for the typescript interfaces

 specifically I wanted to make a type that configures our payment intents for both stripe and stripe terminal
```ts
const intent = await this.stripe.paymentIntents.create({
  ...payment.paymentMethod.options,
  amount: payment.getAmount(),
  currency: payment.getCurrency(),
  capture_method: 'manual',
});
```
and in one of my payment methods I have
```ts
export default class StripeCardPresent implements PaymentMethod {
  readonly options: { [key: string]: any };

  constructor() {
    this.options = {
      payment_method_types: ['card_present'],
    };
  }
}
```
what'd I'd really like to do is have `PaymentIntentCreateParams` (and any other types that clients consume) exported so that I can make my type generic, and have it return this.

in this way I would be able to ensure options only contains valid fields.

**Comment by rattrayalex-stripe** [comment]
I believe you can accomplish this like so:

```tsx
import Stripe from 'stripe';

const params: Stripe.PaymentIntentCreateParams = {
  amount: 100,
  currency: 'USD',
  payment_method_types: ['card_present'],
}
```

It's possible that you'd need to uninstall `@types/stripe` for this to work. 

Let me know if you run into any issues?

**Comment by xenoterracide** [comment]
this works, but also doesn't work... it doesn't work because amount and currency are not present at this juncture...

**Comment by holylander** [comment]
isnt that package deprecated? 
https://www.npmjs.com/package/@types/stripe

**Comment by holylander** [comment]
thanks @remi-stripe , I will take a look ;)
