### ISSUE TITLE
Incorrect TypeScript types: plan property on Stripe.invoices.IInvoiceLineItem can be null

### ISSUE THREAD

**Issue by hgezim** [stripe/stripe-node#760]
I'm using TypeScript 3.3 and the following code throws on the line `const product = item.lines.data[lastIndex].plan.product`:

```
const stripe = new Stripe(Config.STRIPE_SECRET_KEY)

const invoices = await stripe.invoices.list({
  customer: customerId,
  limit: 100,
});

const productIds = new Set<string>();

invoices.data.forEach(item => {
  const lastIndex = item.lines.data.length - 1;
  const product = item.lines.data[lastIndex].plan.product;
  if (typeof product === 'string') {
    productIds.add(product);
  }
});
```

It compiles fine on TS and it used to work. I'm not sure what changed on your API. I did not update the API version on Stripe either. But I am curious how the TypeScript types in your library deal with API version changes.

The error that's thrown is:

```
TypeError: Cannot read property 'product' of null
     at invoices.data.forEach.item
```

When inspecting the line item returned, it indeed has a null plan:

```
{
    id: 'ii_...',
    object: 'line_item',
    amount: xxx,
    currency: 'usd',
    description: 'xxx',
    discountable: true,
    invoice_item: 'ii_...',
    livemode: true,
    metadata: {},
    period: { end: 1569618693, start: 1569618693 },
    plan: null,
    proration: false,
    quantity: 1,
    subscription: null,
    tax_amounts: [],
    tax_rates: [],
    type: 'invoiceitem',
    unique_id: 'il_...'
  }
```

**Comment by rattrayalex-stripe** [comment]
Thanks for filing this with a code snippet!

This actually does look to be typed as `| null`: 
https://github.com/stripe/stripe-node/blob/master/types/2019-12-03/InvoiceLineItems.d.ts#L54

It looks like you might be using the DefinitelyTyped version of the types. You might need to install `stripe@8.0.1`. I also recommend removing your dependency on `@types/stripe`, though it shouldn't be strictly necessary.
