### ISSUE TITLE
Typescript: AccountUpdateParams should allow dictionary for external_account

### ISSUE THREAD

**Issue by fli** [stripe/stripe-node#761]
For the interface `AccountUpdateParams`, the property `external_account` only takes a string despite the comments specifying that a dictionary can be provided.

```typescript
/**
 * A card or bank account to attach to the account. You can provide either a token, like the ones returned by [Stripe.js](https://stripe.com/docs/stripe.js), or a dictionary, as documented in the `external_account` parameter for [bank account](https://stripe.com/docs/api#account_create_bank_account) creation.
 *
 * By default, providing an external account sets it as the new default external account for its currency, and deletes the old default if one exists. To add additional external accounts without replacing the existing default for the currency, use the bank account or card creation API.
 */
external_account?: string;
```

**Comment by remi-stripe** [comment]
@fli Thanks for reaching out! That one, we did on purpose on our end. While you _can_ send raw bank account details (or card details) via the API, the information is extremely sensitive and something we discourage most developers from trying. For that reason, the Typescript definitions focus on passing a bank account or card token instead of a raw hash.

Hope this clarifies the issue but let us know what you think!

**Comment by fli** [comment]
Thanks @remi-stripe, that makes sense and clarifies it for me 🙂. I think that's fair and I'm happy, but it may be a bit confusing to people without that context

**Comment by remi-stripe** [comment]
Yeah I agree. It's a tricky balance between nudging developers to use the "safer" approach, and fully documenting the API. We'll definitely keep an eye out for confusion on that specific endpoint :)

**Comment by joeythomaschaske** [comment]
Can the [documentation](https://stripe.com/docs/api/external_account_bank_accounts/create) be updated to reflect that the SDK does not support this?

**Comment by remi-stripe** [comment]
@joeythomaschaske The SDK supports this already, just not the TS signatures. It's not something we would show in the API Reference though.

**Comment by RobertCer** [comment]
TS signature still not changed in 8.154.0 version.

**Comment by LuwanKonnect** [comment]
But when we create an account, we can post account details. if you guys encourage user only use token, why don't you do this in create api

**Comment by remi-stripe** [comment]
Just to clarify, we do not plan to document cards in the type. The proper integration path is to create a Token client-side and pass that Token id `tok_123` in the API itself. If you don't want to use that path and pass raw card details instead, it drastically increases your PCI requirements and in that case you would skip types for that calls explicitly.
