### ISSUE TITLE
Type for StripeConfig requires typescript to be true

### ISSUE THREAD

**Issue by bbangert** [stripe/stripe-node#768]
In https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts#L30, the StripeConfig ends up requiring `typescript = true` to be set. Which means that in my JS code (which we are doing some type checking on, and haven't fully migrated to TypeScript), the only way to make the type-checker happy is to include `typescript = undefined` which is odd.

Why not allow this flag to not be included or set to false?

**Comment by cjavilla-stripe** [comment]
Hey @bbangert,

Given the code is partially checked, the recommendation is to set `typescript: true` on `StripeConfig`. 

Another suggestion if this feels odd is to set `typescript: false as true`. This is only used for the user-agent string so doesn't impact your current type checking.

**Comment by rattrayalex-stripe** [comment]
Just to emphasize the last point there, `typescript: true` does not have any runtime affect (apart from the version string) and is safe to use in non-TS files.
