### ISSUE TITLE
Feature Request: Allow telemetry hook for additional metrics reporting

### ISSUE THREAD

**Issue by bbangert** [stripe/stripe-node#770]
The stripe library can capture and send request latency telemetry to Stripe, but it'd be great if a hook was provided so I could easily capture this as well rather than having to wrap my Stripe calls in more code to capture this.

**Comment by cjavilla-stripe** [comment]
Hey @bbangert I think we may have something like this for stripe-ruby.

Is this kinda what you're looking for? https://github.com/stripe/stripe-ruby#instrumentation

**Comment by bbangert** [comment]
@cjavilla-stripe yup, that'd be perfect!

**Comment by cjavilla-stripe** [comment]
Okay cool. Thanks again for the feedback! We'll need to investigate and discuss :)

**Comment by rattrayalex-stripe** [comment]
Hi @bbangert – were you able to try `stripe.on('response', cb)`? https://github.com/stripe/stripe-node#request-and-response-events
Looks like it contains some relevant fields:
```
  elapsed: 445                       // Elapsed time in milliseconds
  request_start_time: 1565125303932  // Unix timestamp in milliseconds
  request_end_time: 1565125304377    // Unix timestamp in milliseconds
```

**Comment by bbangert** [comment]
Hi @rattrayalex-stripe, we added a hook to use the times out of there, thanks!

This could probably be closed.
