### ISSUE TITLE
Feature Request: Support for Cloudflare Workers

### ISSUE THREAD

**Issue by kevmodrome** [stripe/stripe-node#773]
I've been trying to integrate this library in my one of my Cloudflare Workers and I keep running into an issue with `child_process`. It seems this is because Workers run on a V8 isolate rather than process-level containers. Would love to be able to use Stripe when building Worker functions.

**Comment by brandur-stripe** [comment]
Hey Kevin, what exactly happens that prevents your code from running?

We use `child_process`, but it's fenced into an area that's supposed to recover gracefully in case there was an execution error from the subprocess. Is it blowing up on `require('child_process')` or something?

And for general information: we're currently using subprocesses to collect `uname` information for metrics.

**Comment by kevmodrome** [comment]
Hi, yes, it's blowing up on the require, pretty much. I believe the problem is that there is no child_process in the environment that Cloudflare Workers use.

**Comment by brandur-stripe** [comment]
Opened #775, although we're not 100% sure that we're going in this direction quite yet.

**Comment by brandur-stripe** [comment]
Released a fix in 8.6.0.
