### ISSUE TITLE
Package requires @types/node 13 but minimum required node version is 8.1

### ISSUE THREAD

**Issue by SimonSchick** [stripe/stripe-node#783]
This is not a huge deal but it should probably require `@types/node>=8` otherwise a codebase that is still on v10 or v12 will install the typings twice.

**Comment by rattrayalex-stripe** [comment]
Interesting, good catch! On it.

**Comment by SimonSchick** [comment]
That was quick, kudos to y'all!

**Comment by rattrayalex-stripe** [comment]
Released in v8.8.1. Thanks for reporting!
