### ISSUE TITLE
help me ! convert heic to jpg I use heic2any  for angular run production error  

### ISSUE THREAD

**Issue by ice03314** [stripe/stripe-node#791]
Cannot assign to read only property 'stack' of object 'Error: No such file or directory
![image](https://user-images.githubusercontent.com/38200914/73665608-f626c080-46d3-11ea-9af3-7ad33460b9a3.png)

.................................................................... 
Code heic2any in project
![1580750678333](https://user-images.githubusercontent.com/38200914/73675511-1ad76400-46e5-11ea-9d48-8b9bb4ad9cf0.jpg)

**Comment by ob-stripe** [comment]
@ice03314 Are you sure you opened this issue on the correct repository? This is the repository for the Node.js bindings for Stripe's API. Maybe you meant to open this issue on [heic2any's repository](https://github.com/alexcorvi/heic2any)?
