### ISSUE TITLE
API does not reflect "total_count" removal according to ApiList type

### ISSUE THREAD

**Issue by jvandenaardweg** [stripe/stripe-node#805]
`"stripe": "^8.17.0"`
API Version: 2019-12-03 (latest)

Using the Stripe API in test mode.

I'm using this code on my own API endpoint:

```typescript
const subscriptions = await stripe.subscriptions.list({
  customer: stripeCustomerId,
  expand: ['data.plan.product', 'data.customer', 'data.latest_invoice'],
  status: 'all'
});

return subscriptions.data;
```

Which returns an array of subscriptions: `Stripe.Subscription[]`

When I use that response as a mock in my unit tests, and apply the type `Stripe.Subscription[]` to it, it results in these 2 errors:

```
Object literal may only specify known properties, and 
'total_count' does not exist in type 'ApiList<SubscriptionItem>'

Object literal may only specify known properties, and 
'total_count' does not exist in type 'ApiList<InvoiceLineItem>'
```

According to the [ApiList](https://github.com/stripe/stripe-node/blob/ef94d7bf148f18c0f1bc5d7952835ac6f5d61a6f/types/lib.d.ts#L123) type there is indeed no `total_count` with a comment:

```
// Looking for `total_count`? It is deprecated; please do not use it.
```

However, all objects from the Stripe API do return a `total_count`, which seems a bit confusing.

Is the API lagging behind type changes?

Example (I've removed unrelated properties to demonstrate where the problem is)

```typescript
const subscriptionsMock: Stripe.Subscription[] = [
  {
    id: 'XXX',
    object: 'subscription',
    // [...]
    items: {
      object: 'list',
      // [...]
      data: [{}],
      has_more: false,
      total_count: 1, // This gives an error
      url: '/v1/subscription_items?subscription=XXX'
    },
    customer: {
      // [...]
      sources: {
        object: 'list',
        data: [{}],
        has_more: false,
        total_count: 1, // Gives NO error (little weird), as it is using the same ApiList
        url: '/v1/customers/XXX/sources'
      },
    },
    latest_invoice: {
      // [...]
      lines: {
        object: 'list',
        data: [{}],
        has_more: false,
        total_count: 1, // This gives an error
        url: '/v1/invoices/XXX/lines'
      },
      // [...]
    }
  }
]
```

**Comment by remi-stripe** [comment]
@jvandenaardweg Thanks for reaching out. The `total_count` property on sub-lists is considered deprecated. We haven't documented this one for multiple years and we discourage anyone from using it. That's why the Typescript definitions in the library don't support this to ensure developers don't use this directly. We do have plans to remove it entirely in an API version in the future, hopefully this year.

This shouldn't block your code from running. It just raises a type error at compilation if you try to access it to be explicit about this field being deprecated.
