### ISSUE TITLE
Default http timeout changed in Node 13

### ISSUE THREAD

**Issue by jonchurch** [stripe/stripe-node#806]
In Node.js v13.0.0 [the default socket timeout has been set to 0](https://github.com/nodejs/node/pull/27558).

Currently in this Library the default timeout is being set based on [`require('http').createServer().timeout`](https://github.com/stripe/stripe-node/blob/1a6cd581514de22d1561ae68c2401a168485c07d/lib/stripe.js#L11).
https://github.com/stripe/stripe-node/blob/1a6cd581514de22d1561ae68c2401a168485c07d/lib/stripe.js#L11
 The default previously was 120 seconds, under v13 it is no timeout by default aka a value of `0`.

I noticed this when looking into https://github.com/stripe/stripe-node/issues/796

I haven't done any testing with this so I don't know if it represents an actual bug, but wanted to file this issue in case this was something the team was unaware of. 

This timeout was introduced in Node.js v0.9.12 as 120 seconds, and did not change until v13.0.0 when it was switched to 0. There is of course a possibility that this change will be reverted before v14 is released, but it's worth keeping an eye on.

**Comment by ob-stripe** [comment]
Thanks for the heads up @jonchurch!

@brandur-stripe @remi-stripe @richardm-stripe I think we should just change the default timeout to a hardcoded value of 80 seconds like we do in other client libraries. Does that sound good to everyone?

**Comment by brandur-stripe** [comment]
> Does that sound good to everyone?

Strong +1 from me.
