### ISSUE TITLE
Missing key "hosted_invoice_url" on return object of stripe.invoices.retrieveUpcoming

### ISSUE THREAD

**Issue by aragalie** [stripe/stripe-node#808]
As per the [documentation](https://stripe.com/docs/api/invoices/upcoming), the return object should be of type `Invoice`, including therefore also the `hosted_invoice_url` key

But this doesn't seem to be the case for me when calling `stripe.invoices.retrieveUpcoming({ customer: customerId })`

And also the `id` key is missing on the response, along with a few others...

I'm using Node10 with latest API (2019-12-03).

**Comment by remi-stripe** [comment]
@aragalie the upcoming invoice endpoint returns a preview of the next invoice. It's not a real invoice that you can send or visualize on the hosted invoice url. For that reason it has no `hosted_invoice_url` key since that's not something you can share with a customer.

**Comment by aragalie** [comment]
Thanks for the clarification @remi-stripe 

In that case, I suggest the docs be updated accordingly.
