### ISSUE TITLE
[Typescript] Outdated `StripeError` definition

### ISSUE THREAD

**Issue by cah-dunn** [stripe/stripe-node#809]
The current `StripeError` definition includes a `StripeError.populate(...)` method (https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts#L207) which was replaced by a `StripeError.generate(...)` method (https://github.com/stripe/stripe-node/blob/master/lib/Error.js#L33-L48).

My use case is for testing, specifically creating mock error's in my Stripe service stubs. It works correctly, but requires an `@ts-ignore` to compile.

My current work around is something akin to:
```typescript
type MutableStripeError = { -readonly [T in keyof Stripe.StripeError]: Stripe.StripeError[T] }
type RawStripeError = Omit<MutableStripeError, 'type'>

static generate(rawStripeError: RawStripeError & { type: 'card_error' }): Stripe.StripeCardError
static generate(rawStripeError: RawStripeError & { type: 'invalid_request_error' }): Stripe.StripeInvalidRequestError
static generate(rawStripeError: RawStripeError & { type: 'api_error' }): Stripe.StripeAPIError
static generate(rawStripeError: RawStripeError & { type: 'authentication_error' }): Stripe.StripeAuthenticationError
static generate(rawStripeError: RawStripeError & { type: 'idempotency_error' }): Stripe.StripeIdempotencyError
static generate(rawStripeError: RawStripeError & { type: Stripe.RawErrorType }): Stripe.StripeError {...}
```

**Comment by ob-stripe** [comment]
Hi @cah-dunn, thanks for the report and sorry for the lack of communication. Just wanted to let you know that this is still on our radar. Thanks for your patience!

**Comment by cah-dunn** [comment]
@ob-stripe No problem and thanks for the follow-up! I'm just glad you all brought these types in-house, which was a vast improvement.

**Comment by rattrayalex-stripe** [comment]
Out of curiosity, why not instantiate the errors with `new`? Can you share a snippet of how you do the mocking?

**Comment by cah-dunn** [comment]
@rattrayalex-stripe The `constructor` type on `StripeError` also appears to be outdated (non-existent), but I'd otherwise be open to that solution.

I check `instanceof` in my error handling (e.g. `if (error instanceof Stripe.errors.StripeCardError)`) and mock that with:

```typescript
type MutableStripeError = { -readonly [T in keyof Stripe.StripeError]: Stripe.StripeError[T] }
type RawStripeError = Omit<MutableStripeError, 'type' | 'name' | 'stack'>
type RawStripeErrorParam = Partial<RawStripeError>
type RawStripeErrorInput = RawStripeError & { type: Stripe.RawErrorType }

export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: 'card_error' }
): Stripe.StripeCardError
export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: 'invalid_request_error' }
): Stripe.StripeInvalidRequestError
export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: 'api_error' }
): Stripe.StripeAPIError
export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: 'authentication_error' }
): Stripe.StripeAuthenticationError
export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: 'idempotency_error' }
): Stripe.StripeIdempotencyError
export function generateStripeError(
  rawErrorOpts: RawStripeErrorParam & { type: Stripe.RawErrorType }
): Stripe.StripeError {
  const rawError: RawStripeErrorInput = {
    type: rawErrorOpts.type,
    message: anyString(),
    raw: anyObject(),
    rawType: rawErrorOpts.type,
    headers: anyObject(),
    requestId: anyString(),
    ...rawErrorOpts
  }
  rawError.raw = { ...rawError }

  // @ts-ignore
  return Stripe.errors.StripeError.generate(rawError)
}

const expectedStripeChargeFailureCode = 'card_declined'
const expectedStripeChargeId = anyString()
const stripeCardError = generateStripeError({
  type: 'card_error',
  code: expectedStripeChargeFailureCode,
  charge: expectedStripeChargeId
})
mockStripeService.createCharge.withArgs(input).rejects(stripeCardError)
```

**Comment by rattrayalex-stripe** [comment]
Ah, I see – thanks @cah-dunn ! That's extremely helpful. 

I've put up https://github.com/stripe/stripe-node/pull/853 which should eliminate the need for your `generateStripeError` function; you should be able to replace it with `stripe.errors.generate()` or a thin wrapper typed as `typeof Stripe.errors.generate`.  

If you're willing to give it a try, you should be able to `yarn add https://github.com/stripe/stripe-node#ralex/ts-error-generate`. 

Curious if this works for you? Any feedback? (Perhaps best on the PR).
