### ISSUE TITLE
usageRecordSummaries not defined?

### ISSUE THREAD

**Issue by juristr** [stripe/stripe-node#810]
Hey,

I just wanted to use the `usageRecordSummaries` as described [here](https://stripe.com/docs/api/usage_records/subscription_item_summary_list):

```
const stripe = require('stripe')('...');
stripe.usageRecordSummaries.list(
  "...",
  {limit: 3},
  function(err, usageRecordSummaries) {
    // asynchronously called
  }
);
```

For some reason though the stripe object doesn't have a `usageRecordSummaries`, which results to be undefined. Anything I'm missing here?

- Node: 12.14
- `"stripe": "^8.19.0",`

**Comment by juristr** [comment]
Oh, apparently it is defined on the `SubscriptionItems`: https://github.com/stripe/stripe-node/blob/master/lib/resources/SubscriptionItems.js#L16

Which makes sense. Hence it should be used as follows:

```
const usageRecs = await stripeClient.subscriptionItems.listUsageRecordSummaries(
     ...
 );
```
(or the callback equivalent).

So either the docs are wrong or the API here should be updated 🤷‍♂

**Comment by remi-stripe** [comment]
@juristr Thanks for reaching out! The API docs are wrong on that one and I'll make sure to get this fixed for everyone. Closing as you resolved your issue.
