### ISSUE TITLE
stripe.transfers.listTransactions is not a function

### ISSUE THREAD

**Issue by ellenaua** [stripe/stripe-node#812]
We were using `stripe.transfers.listTransactions()` function to retrieve all transactions related to some transfer. But now this function does not exist. As I see, it was deleted in version 7.0.0

How can I get list of transactions related to some Transfer?

I see that list of transactions in Stripe dashboard when I go to transfer details page. Page makes Ajax request to https://dashboard.stripe.com/v1/transfers/[TRANSFER_ID_HERE]/transactions?from_stmt=true&count=20

How can I access the same data using Stripe client for Node.js?

**Comment by ellenaua** [comment]
I am finally able to get that info using this request. Just wondering why that's deleted from Stripe SDK

```
const httpParams = {
        method: 'get',
        url: 'https://api.stripe.com/v1/transfers/' + id + '/transactions',
        headers: {
            'Authorization': 'Bearer ' + process.env.stripeSecret,
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'Stripe/v1 NodeBindings/4.25.0'
        }
    };

    const res = await axios.default.request(httpParams);
```

**Comment by remi-stripe** [comment]
@ellenaua That API method has been deprecated for well over 5 years. Even though it still works on really old API versions, it's not something we want to actively encourage or officially support anymore so it's not in our client libraries.

If you want to list the transactions that are bundled in your Payout (or Transfer if you're on an old API version), you should use the List Balance Transactions [API](https://stripe.com/docs/api/balance_transactions/list) and pass `payout: "po_123"` instead.
