### ISSUE TITLE
[Typescript] StripeError missing "extends Error"

### ISSUE THREAD

**Issue by Unibozu** [stripe/stripe-node#823]
Hi all,

The `StripeError` class doesn't extend `Error` in the typings, leading to errors like `Error:(439, 44) TS2345: Argument of type 'StripeError' is not assignable to parameter of type 'Error'.
  Property 'name' is missing in type 'StripeError'.`

Example

```ts
import {Stripe} from 'stripe';

function test(err: Error) {}

const baseStripeError: Stripe.StripeError = null;

test(baseStripeError);
```

I've checked the sources and the class is actually extending `Error`.

Cheers

**Comment by cjavilla-stripe** [comment]
Thanks for reporting, Unibozu! PR up.

**Comment by Unibozu** [comment]
Amazing efficiency! Thanks, @cjavilla-stripe 

I'll monitor the PR to know what will happen with npm
