### ISSUE TITLE
Unknown arguments is conflicting with TypeScript definitions

### ISSUE THREAD

**Issue by cyrilgandon** [stripe/stripe-node#825]
Look at the definition of [`stripe.accounts.retrieve`](https://github.com/stripe/stripe-node/blob/master/types/2019-12-03/Accounts.d.ts#L1842)

```
retrieve(
    id: string,
    params?: AccountRetrieveParams,
    options?: RequestOptions
): Promise<Stripe.Account>;
```

TypeScript allows this function to be called by `stripe.accounts.retrieve(id, undefined)`.
If I do that, it throws the error 

> Stripe: Unknown arguments (). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to GET `/accounts/{id}`)

So, typically, I find myself writing wrapper like this

```
function getAccount(id: string, params?: Stripe.AccountRetrieveParams): Promise<Stripe.Account> {
    return params ? stripe.accounts.retrieve(id, params) : stripe.accounts.retrieve(id);
}
```

Not very elegant, neither useful. Can we just ignore the params options if it is undefined instead of throwing ?

**Comment by cjavilla-stripe** [comment]
cyrilgandon thanks for reporting. I have a PR up for this now which you can follow along at #827

**Comment by cyrilgandon** [comment]
Just tested it, works fine, thank you!

**Comment by cjavilla-stripe** [comment]
Thanks! Sorry for the delay @cyrilgandon  I had to learn how to write a test for this :D
