### ISSUE TITLE
Received unknown parameter: phases[0][plans][0][start_date]

### ISSUE THREAD

**Issue by fyrejason** [stripe/stripe-node#840]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Node library.

I am attempting to downgrade a subscription by adding it to a schedule, and then updating it by adding a new phase

Here is my code. I'm not sure what i'm doing wrong

```
           const schedule = await stripe.subscriptionSchedules.create({
                from_subscription: subId,
            });
            const updatedSchedule = await stripe.subscriptionSchedules.update(schedule.id, {
                end_behavior: 'release',
                phases: [{
                    plans: [{plan, quantity: 1, start_date: schedule.current_phase.end_date}],
                }]
            })
```

When i try to set the start_date on the schedule instead i get an error about unknown paramtere start_date
```
            const updatedSchedule = await stripe.subscriptionSchedules.update(schedule.id, {
                end_behavior: 'release',
                start_date: schedule.current_phase.end_date
                phases: [{
                    plans: [{plan, quantity: 1}],
                }]
            })
```

**Comment by cjavilla-stripe** [comment]
Hey @fyrejason after you create the schedule, it'll have a "current phase" you need to pass in that current phase, and the new phase you're adding. See the very last example here: https://stripe.com/docs/billing/subscriptions/subscription-schedules
