### ISSUE TITLE
Inconsistent description and TS type in `external_account`

### ISSUE THREAD

**Issue by marceloclp** [stripe/stripe-node#844]
For the `AccountUpdateParams`:

Using the old `@types/stripe` it was possible to define `external_account` as an object, which I think it is the intented behavior, based on the current description of the property, but the only accepted type is `string`.

```ts
/**
 * A card or bank account to attach to the account. You can provide either a token, like the ones returned by [Stripe.js](https://stripe.com/docs/stripe.js), or a dictionary, as documented in the `external_account` parameter for [bank account](https://stripe.com/docs/api#account_create_bank_account) creation.
 *
 * By default, providing an external account sets it as the new default external account for its currency, and deletes the old default if one exists. To add additional external accounts without replacing the existing default for the currency, use the bank account or card creation API.
 */
external_account?: string;
```

Is this a bug or a new behavior?

**Comment by remi-stripe** [comment]
@marceloclp Thanks for reaching out. You can find the longer answer https://github.com/stripe/stripe-node/issues/761 but the summary is that we don't want the types to encourage you to send raw card or bank account details server-side. This information is sensitive, and for cards is protected by PCI. Most integrations should always tokenize client-side and pass the token in that parameter so our types are enforcing this.
