### ISSUE TITLE
Charge Setup fees on Specific Plan for the first time only

### ISSUE THREAD

**Issue by mobeenjalib** [stripe/stripe-node#854]
I want to charge one time setup fees to the customer when the first time a plan is subscribed

Suppose I have 4 Plans A,B,C,D so when user subscribe to Plan A or Plan B I want him to pay setup fees (extra amount 10 dollars more)

Please help me how it can be done using stripe API or even from the dashboard?

**Comment by remi-stripe** [comment]
@mobeenjalib Github issues should be limited to questions and bugs about the library itself. Here you have a question about the product itself.

I'd recommend reaching out to our support team for more help https://support.stripe.com/contact but you can look at this specific documentation: https://stripe.com/docs/billing/invoices/subscription#first-invoice-extra
