### ISSUE TITLE
Stripe official docs on idempotency uses outdated 'idempotency_key'

### ISSUE THREAD

**Issue by guisehn** [stripe/stripe-node#855]
I've just noticed this warning in my terminal while using `idempotency_key`:

```
Stripe: 'idempotency_key' is deprecated; use 'idempotencyKey' instead.
```

However [Stripe docs](https://stripe.com/docs/api/idempotent_requests) still uses `idempotency_key` in the code sample.

<img width="1123" alt="Screen Shot 2020-03-31 at 4 51 35 PM" src="https://user-images.githubusercontent.com/830208/78082425-391db100-7370-11ea-96b0-2d790571a47f.png">

**Comment by remi-stripe** [comment]
@guisehn Thanks for the heads up! I'll make sure we fix this soon!
