### ISSUE TITLE
Typing for `external_account` in ExternalAccountCreateParams does not conform to API docs.

### ISSUE THREAD

**Issue by matthewgonzalez** [stripe/stripe-node#856]
https://github.com/stripe/stripe-node/blob/4a721fa6a6054f647b1cce62b2f10ed544ac554d/types/2020-03-02/ExternalAccounts.d.ts#L7

The type is set to `string` and doesn't allow one to create a new external account by passing in an object of bank account details per the API docs:

https://stripe.com/docs/api/external_account_bank_accounts/create#account_create_bank_account-external_account

**Comment by remi-stripe** [comment]
@matthewgonzalez Thanks for the report! Flagging we discussed this before in https://github.com/stripe/stripe-node/issues/844 and https://github.com/stripe/stripe-node/issues/761

The card and bank account details are really sensitive information and we actively discourage developers from using them. But this is supported in the API if you need this, just not in typed!
