### ISSUE TITLE
Feature Request: Allow initializing the stripeAccount in options

### ISSUE THREAD

**Issue by radiofrequency** [stripe/stripe-node#857]
Currently stripeAccount needs to be specified for each request.   Allow setting stripeAccount in the initial options or provide ability to customize the http headers of all requests.

**Comment by remi-stripe** [comment]
Thanks for the report @radiofrequency! We'll look into what that could look like!

**Comment by lyndonbuckley** [comment]
@richardm-stripe @remi-stripe 
Has there been any progress on this? 
Would you be willing to accept a pull request?

**Comment by lyndonbuckley** [comment]
https://github.com/stripe/stripe-node/pull/1102

**Comment by lyndonbuckley** [comment]
Hi @richardm-stripe @remi-stripe
Just wondering if you've had time to review the submitted pull request?

**Comment by remi-stripe** [comment]
@lyndonbuckley Sorry for delays here, looks like this one slipped through the cracks but we'll have a look this week!

**Comment by lyndonbuckley** [comment]
@remi-stripe any update on this?

**Comment by remi-stripe** [comment]
Really sorry for the delay @lyndonbuckley. I'll do my best to get this reviewed this week!

**Comment by richardm-stripe** [comment]
Fixed in #1102, released in [v8.163.0](https://github.com/stripe/stripe-node/releases/tag/v8.163.0)
