### ISSUE TITLE
Following express example and getting signature error

### ISSUE THREAD

**Issue by joshbedo** [stripe/stripe-node#860]
Following this example to a T and getting "Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing" when trying to test the webhook within the dashboard.

https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/node-express/express.js

Any ideas how to fix this?

**Comment by paulasjes-stripe** [comment]
Can you post your exact code? Mostly likely culprit is that you are setting a `bodyParser` before your app route. See here: https://stackoverflow.com/questions/56145563/getting-exception-on-webhook-from-stripe/56146244#56146244

**Comment by StorytellerCZ** [comment]
Having the same issue, but with Meteor, which uses `connect@3.6.5` under the hood:
```js
WebApp.connectHandlers.use((req, res, next) => {
  if (req.originalUrl === '/wh/stripe') {
    bodyParser.raw({ type: 'application/json' })(req, res, next)
  } else {
    bodyParser.json()(req, res, next)
  }
});

WebApp.connectHandlers.use('/wh/stripe', (request, response) => {
  if (request.method !== 'POST') {
    response.writeHead(404)
    return response.end()
  }
  let event

  try {
    const sig = request.headers['stripe-signature'];
    event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);
  } catch (err) {
    response.writeHead(400)
    return response.end(`Webhook Error: ${err.message}`)
  }
  ...
}
```

**Comment by paulasjes-stripe** [comment]
@StorytellerCZ double check that you aren't setting a bodyparser in any other middleware. Looking at the [connect code](https://github.com/senchalabs/connect/blob/master/index.js#L55) you can use `WebApp.stack` to get an array of all the middleware set. Make sure there isn't one setting a bodyparser that could be affecting your webhook route.

**Comment by StorytellerCZ** [comment]
Possible, I have oauth handlers defined via Meteor and GraphQL setup:
```
I20200511-18:42:05.058(9)? [                  
I20200511-18:42:05.077(9)?   { route: '/_oauth', handle: [Function: handle] },
I20200511-18:42:05.077(9)?   { route: '/_oauth', handle: [Function: handle] },
I20200511-18:42:05.078(9)?   { route: '', handle: [Function: handle] },
I20200511-18:42:05.078(9)?   { route: '', handle: [Function: handle] },
I20200511-18:42:05.078(9)?   { route: '/graphql', handle: [Function: handle] },
I20200511-18:42:05.078(9)?   { route: '', handle: [Function: handle] }
I20200511-18:42:05.078(9)? ]
```
But I did check. I receive the body as a Stream with:
```
WebApp.connectHandlers.use((req, res, next) => {
  if (req.originalUrl === '/wh/stripe') {
    bodyParser.raw({ type: 'application/json' })(req, res, next)
  } else {
    bodyParser.json()(req, res, next)
  }
});
```
Without this code I don't receive the body at all.

**Comment by paulasjes-stripe** [comment]
@StorytellerCZ Can you print out the body of a request that comes in on your webhook route? If it's a raw body you should see something like `<Buffer 7b 0a 20 20 22 69 64>`. If it's JSON then you probably do have a rogue bodyparser somewhere.

**Comment by StorytellerCZ** [comment]
Yes, I get buffer in `request.body`:
```
I20200513-02:35:20.713(9)? Buffer(4598) [Uint8Array] [
I20200513-02:35:20.715(9)?   123,  10,  32,  32,  34, 105, 100,  34,  58,  32,  34, 101,
I20200513-02:35:20.716(9)?   118, 116,  95,  49,  71, 105,  50,  48, 103,  75, 113, 117,
I20200513-02:35:20.716(9)?   114, 106, 100,  80,  87,  79,  69,  65,  74,  65, 109, 122,
I20200513-02:35:20.717(9)?    98,  73,  78,  34,  44,  10,  32,  32,  34, 111,  98, 106,
I20200513-02:35:20.717(9)?   101,  99, 116,  34,  58,  32,  34, 101, 118, 101, 110, 116,
I20200513-02:35:20.718(9)?    34,  44,  10,  32,  32,  34,  97, 112, 105,  95, 118, 101,
I20200513-02:35:20.718(9)?   114, 115, 105, 111, 110,  34,  58,  32,  34,  50,  48,  50,
I20200513-02:35:20.719(9)?    48,  45,  48,  51,  45,  48,  50,  34,  44,  10,  32,  32,
I20200513-02:35:20.720(9)?    34,  99, 114, 101,
I20200513-02:35:20.720(9)?   ... 4498 more items
I20200513-02:35:20.721(9)? ]
```

**Comment by paulasjes-stripe** [comment]
@StorytellerCZ Hmm okay one last thing to try: can you triple check that the webhook signing secret you're using is the correct one for this particular endpoint. You can find the secret assigned to your endpoint in your dashboard settings: https://dashboard.stripe.com/test/webhooks

If that still doesn't do the trick, please write into our support so they can take a closer look and unblock you: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
Closing as we didn't hear back in a while

**Comment by jchu231** [comment]
Thank you so much, @paulasjes-stripe ! you debugging steps helped me fix my similar issue (multiple steps helped me 😂)
