### ISSUE TITLE
apiVersion can only be set to the latest api version?  Can this be set to be latestVersion or string?

### ISSUE THREAD

**Issue by ntegral** [stripe/stripe-node#861]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Node library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your Node version and the version of the Stripe Node library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by remi-stripe** [comment]
@ntegral You can set the API version to any version you want when you make an API request as documented here: https://stripe.com/docs/api/versioning

Please note that if you use Typescript, the Typescript definitions will always be for the latest API version.
