### ISSUE TITLE
TypeScript Stripe import error on AWS Lambda

### ISSUE THREAD

**Issue by angeldima** [stripe/stripe-node#862]
Hi,

I'm trying to use Stripe checkout creating a Checkout Session using an AWS nodejs Lambda. Following the [documentation](https://github.com/stripe/stripe-node) for TypeScript usage, I've imported Stripe as follow:

```javascript
import Stripe from 'stripe';
const stripe = new Stripe('sk_test_...', {
    apiVersion: '2020-03-02',
});

exports.main = async function(event: any, context: any) {
...
}
```
this code does not give a type error, but fails at runtime:

```shell
TypeError: stripe_1.default is not a constructor
```
Is it common to facing this problem?

Relevant properties from tsconfig

- "target": "ES2018",
- "module": "commonjs",
- "moduleResolution": "node"

Other info:

- Lambda runtime: NODEJS_12_X
- "stripe": "^8.39.0"
- "typescript": "~3.7.2"

**Comment by cjavilla-stripe** [comment]
Hey angeldima,

Can you try this without calling Stripe with the `new` keyword before? I believe that might be causing your error:

It'd be invoking `Stripe` "function" style, without `new` rather than "constructor" style:

```
import Stripe from 'stripe';
const stripe = Stripe('sk_test_...', {
    apiVersion: '2020-03-02',
});

exports.main = async function(event: any, context: any) {
...
}
```

**Comment by cjavilla-stripe** [comment]
Turns out I was wrong and this should totally work. Can you share a bit more of your code where the type error is raised?

**Comment by angeldima** [comment]
Hi cjavilla,

finally I found the problem. In the deployment phase of the lambda the node modules (and stripe dependency) was not included in the deployment packet. It was enough to change the structure of my AWS cdk project.
If could be helpful to other people, I could share with you a working sample implementation.

Many thanks for your support!

**Comment by cjavilla-stripe** [comment]
okay great! happy to help.

**Comment by dyllanwli** [comment]
@angeldima Got the same problem running on lambda. It would be grateful if you can present your solution detail.

**Comment by angeldima** [comment]
Hi @dyllanwli and sorry for the late reply. You can find my solution here [https://github.com/angeldima/lambda-aws-cdk-stripe/blob/master/StripeService/resources/stripe_lambda.ts](url).

hope it can help you
