### ISSUE TITLE
Cloudflare Worker  - Webpack "createServer is not a function"

### ISSUE THREAD

**Issue by maguayo** [stripe/stripe-node#871]
I am using Cloudflare Workers and when I try to push the code to the workers I get this error:

```
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught TypeError: r(...).createServer is not a function\n  at line 8\n  at line 8\n  at line 1 in r\n  at line 8\n  at line 1 in r\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}
```

I think this is because of Webpack, but I need webpack in order to bundle the code to push it to Cloudflare. Any tips on how to solve this?

**Comment by paulasjes-stripe** [comment]
Hi @maguayo, Cloudflare Workers don't run node, instead they run on the v8 engine with their own layer on top (see here: https://community.cloudflare.com/t/run-node-js-for-worker/98983). 

This library will only work with a node runtime, so unfortunately I don't think you can use this library with Cloudflare Workers.
