### ISSUE TITLE
Feature request: idempotency for Payment Intents

### ISSUE THREAD

**Issue by tautvilas** [stripe/stripe-node#877]
I can not find in API that Payment intents do support idempotency keys (like charges). This causes potential double-charging situation for me when using off session payments. I am using this code:

```
const paymentIntent = await stripe.paymentIntents.create({
    amount: 1099,
    currency: 'usd',
    customer: '{{CUSTOMER_ID}}',
    payment_method: '{{PAYMENT_METHOD_ID}}',
    off_session: true,
    confirm: true,
  });
```

In case there is a bug in my code and this code gets executed twice - the client would be charged twice. However if I could add some idempotency value that I could pass to intent creation (lets say it could be order id). That would mean that it would be impossible to create two off_session aut-confirmable payment intents for the same order.

**Comment by cjavilla-stripe** [comment]
Hey @tautvilas :wave:

The PaymentIntents API can use idempotency keys [1] too. The idempotency key is passed in the request options object and looks like this:

```js
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 1099,
    currency: 'usd',
    customer: '{{CUSTOMER_ID}}',
    payment_method: '{{PAYMENT_METHOD_ID}}',
    off_session: true,
    confirm: true,
  }, {
    idempotencyKey: "random-key",
  });
```

[1] https://stripe.com/docs/api/idempotent_requests?lang=node

**Comment by tautvilas** [comment]
Thank you for the quick response! I got confused reading all these different API docs :)

**Comment by cjavilla-stripe** [comment]
:) Happy to help.

**Comment by ntbandara3** [comment]
Hi @cjavilla-stripe I am passing the options in the same in the code snippet you've added here. But I'm getting the following error.
`Stripe: Unknown arguments ([object Object]). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to POST `/payment_intents`)`

Could you please let me know why?

**Comment by ntbandara3** [comment]
Figured it out. I've been using an older version of stripe. So there the parameter should be **idempotency_key** instead of **idempotencyKey**.

**Comment by kishan3891** [comment]
how can i pass intent.php      $pi_data = array(
        #"setup_future_usage" => "on_session",
        "amount" => $body["amount"],
        "currency" => $body["currency"],
        "payment_method_types" => array("card"),
        #"receipt_email" => $body["email"],
        "metadata" => $body["metadata"],
        "customer" => $customer->id,
        "statement_descriptor" => exampe,
    );
