### ISSUE TITLE
GraphQL integrations?

### ISSUE THREAD

**Issue by Sphinxs** [stripe/stripe-node#878]
A question: Do you guys currently has some resources to GraphQL APIs, like defined types, directives, etc; or plan to do in the future?

I'm creating a GraphQL API that has different response types, based at the attributes described at the REST API and each one has a huge amount of fields / nested fields that I need to specify manually...

**Comment by brandur-stripe** [comment]
Hey @Sphinxs, we don't really have plans for anything GraphQL-related on the table right now, so you'll be largely on your own if you want to something like that.

One thing that might be of use to you is our OpenAPI spec:
https://github.com/stripe/openapi

You could potentially use that as a way to introspect the fields available in the Stripe API and generate your GraphQL bindings.
