### ISSUE TITLE
external_account type: should be flexible to accept string or object

### ISSUE THREAD

**Issue by alisherk** [stripe/stripe-node#879]
The official stripe documentation mentions external_account accepts token as string and object. Your type expects String only. It should be flexible to accept both types. 

`  const params: Stripe.AccountCreateParams = {
   type: 'custom', 
   country: data.country, 
   email: data.email, 
   requested_capabilities: ['card_payments', 'transfers'],
   business_type: data.businessType, 
   tos_acceptance: {
    date: Math.floor(Date.now() / 1000),
    ip: context.rawRequest.ip,
   },
   
   external_account: {
    object: 'bank_account',
    account_number: data.bankAccount,

  }  
  
  }`

**Comment by richardm-stripe** [comment]
Hi @alisherk, thanks for the report. We're planning on tackling this soon!

**Comment by alisherk** [comment]
Thank you for the great lib

**Comment by dncrews** [comment]
Any chance of movement on this, @alisherk?

**Comment by dncrews** [comment]
Any chance of movement on this @richardm-stripe

**Comment by richardm-stripe** [comment]
Released in [v8.145.0](https://github.com/stripe/stripe-node/releases/tag/v8.145.0).
