### ISSUE TITLE
Plan: wrong decimal_amount

### ISSUE THREAD

**Issue by jchonde** [stripe/stripe-node#885]
When creating an amount_decimal through Stripe UI with `amount_decimal: "0.0001"` (note the three zeros).

This is what `const plans = await stripe.plans.list();` returns.

```
{
  object: "list",
  data: [
    {
      id: "plan_HDWkoFjgoc7xMe",
      object: "plan",
      active: true,
      aggregate_usage: "sum",
      amount: null,
      amount_decimal: "0.01",
      billing_scheme: "per_unit",
      created: 1588604081,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: "test",
      product: "prod_HDWeVRgVi516FD",
      tiers: null,
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "metered"
    }
  ]
}

```

Note the  `amount_decimal: "0.01"` with one zero.
I'm not entirely sure that this is a `stripe-node` issue.

Thanks.

**Comment by remi-stripe** [comment]
@jchonde Thank you for reaching out about this issue. I looked into it and this seems like a Dashboard bug. When I try to reproduce, the API request made by the Dashboard is sending `amount_decimal: "0.01"` instead and then that's what stripe-node (or other libraries) get back.

I'm going to close this issue and follow up internally with the team in charge of that UI. Don't hesitate to contact our support team to report the same issue: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
Okay sorry for the churn here, I just remembered how this works and this is all working as expected, I'm sorry for the confusion.

`amount_decimal` allows you to create a plan that goes below the cent. The idea is that if your plan costs $0.0001 USD a unit, you can not do that with `amount` so you use `amount_decimal`.

The thing to note is that `amount_decimal` is still in **cents** (or the currency’s smallest unit) as it mirrors `amount` but with more precision.

This means that `amount_decimal: "1"` means 1 cent so $0.01. Then `amount_decimal: "0.1"` means a tenth of a cent so $0.001". And `amount_decimal: "0.01"` means a hundredth of a cent so $0.0001 which is the value you are passing.

This just threw me off too so I get how it can be confusing. But all our amount fields are in the small currency unit and if `amount_decimal` worked differently it would be even more confusing.

I hope this clarifies the issue!

**Comment by jchonde** [comment]
Wow thanks for the explanation @remi-stripe! It took me forever to understand that.
