### ISSUE TITLE
typescript : sources.create() problems with sofort

### ISSUE THREAD

**Issue by TheGamerRespow** [stripe/stripe-node#886]
The definition of the function "stripe.sources.create" (ver: 2020-03-02) doesn't  include the fields "sofort[country]" and "sofort[preferred_language]" mentioned in the doc.  This cause a problem because we can build our typescript files.

https://stripe.com/docs/sources/sofort
https://github.com/stripe/stripe-node/blob/master/types/2020-03-02/Sources.d.ts

**Comment by remi-stripe** [comment]
@TheGamerRespow Unfortunately we don't have good types for Source creation parameters at the moment. We're moving all of those to PaymentMethod and when that happens those will be actively documented but on Sources you'll have to disable type checks for that specific call instead.

**Comment by TheGamerRespow** [comment]
Thank you for your answer.

As of now, we just added a definition file to fix this issue because we try to avoid as much as possible the use of ``// @ts-ignore``. 

Looking forward to see and use your new PaymentMethod API.

```typescript
declare module 'stripe' {
  namespace Stripe {
    interface SourceCreateParams {
      sofort?: {
        country: string
        preferred_language?: string
      }
    }
  }
}
```
