### ISSUE TITLE
Passing additional beta options not yet supported by stripe-node

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#892]
Hi Stripe Team!

Is it possible to include custom arbitrary parameters in a request which aren't supported in the current Node.js library?

For example, there's a [beta/early-access feature ](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-allow_promotion_codes) I'd like to start using, but no way to set that one extra parameter in my `checkout.sessions.create(params)` request since it's not "officially" in the library yet.

I thought I could use `RequestOptions` but those only support a fixed set of properties (apiKey, idempotencyKey, etc.) and I can't pass an arbitrary value.

**Comment by remi-stripe** [comment]
stripe-node is dynamically built and can support any parameter today. Are you maybe using Typescript on your end? If so, then you would need to disable Typescript's check for that call using `@ts-ignore` until this parameter becomes actively supported publicly!

**Comment by richardm-stripe** [comment]
Hello, thank you for reaching out!

I think what you mean is that when you try to you set the extra parameter
in `params`, you get an error from Typescript, is that correct?

What we recommend is to use ts-ignore to bypass the type error, and attach
the extra param anyway. Whatever you attach will be passed through to the
API, even if it is not reflected in the type. Will this work for you?
