### ISSUE TITLE
OAuthToken interface members are all optional

### ISSUE THREAD

**Issue by allouis** [stripe/stripe-node#900]
Hey o/

I'm currently working with the Stripe Connect OAuth API and [noticed the types suggest that the properties on it are all optional](http://github.com/stripe/stripe-node/blob/master/types/OAuth.d.ts#L3-L40).

Is this intentional? I can't see in your documentation which circumstances would result in receiving missing properties, but not an error!

Would be great to either find out when that would happen, or to update the types if it would never happen (I have a local branch with the changes, so LMK!)

**Comment by cjavilla-stripe** [comment]
Hey allouis! Thanks for reaching out. I think this is likely the result of us not investing a ton into the OAuth types. That said, the one and only field in the `OAuthToken` object you should care about and use is `stripe_user_id`, and ignore all others. Once you authenticate, you'll use that ID paired with your platform keys to make requests.

**Comment by allouis** [comment]
Ah okay cool - would you accept a PR for updates to the types?

The way we're using the Connect flow is to get the access_token and stripe_publishable_key, as well as the `livemode` flag (So we can choose to display that info our UI) - it's a little cumbersome to `assert` that those three properties exist so that the `tsc` approves!

Like I say, I have a local branch ready to push! :relaxed:

**Comment by cjavilla-stripe** [comment]
These types are actually autogenerated from an open API spec that is also generated internally from our implementation, so unfortunately any changes to types needs to be updated in the autogen code. I'm super hopeful we'll be able to open source that someday, but today it would just get overwritten.

**Comment by allouis** [comment]
Aha, make sense!

Okay cool - thanks for explaining :relaxed:
