### ISSUE TITLE
Interface RedirectToCheckoutClientOptions in Typescript forbid One-time payments with Checkout

### ISSUE THREAD

**Issue by rangzen** [stripe/stripe-node#901]
From https://stripe.com/docs/js/checkout/redirect_to_checkout it seems that One-time payment for checkout with client-only needs line-items and mode set to 'payment' but these definitions are not in 
RedirectToCheckoutClientOptions from checkout.d.ts

So, right now, I can't use Checkout for these particular case, am I right?
And it works for a plan with plan in items[].

Versions:
* Node: 12.16.2
* Angular: 9.1.4
* typescript                        3.8.3
* "@stripe/stripe-js": "^1.5.0",

**Comment by remi-stripe** [comment]
@rangzen Github issues here are limited to issues with the stripe-node library. The method you're discussing is instead in Stripe.js which is separate. I'd recommend following up with our support team about this instead: https://support.stripe.com/contact
