### ISSUE TITLE
Stripe Checkout - creating sessions: is it possible to have discount values (aka negative amount) in the line_items array?

### ISSUE THREAD

**Issue by gatsbyz** [stripe/stripe-node#906]
I want it to show the breakdown of the charge by having the discount value in the line_items. Is that possible? This is a one-time charge, not a subscription

**Comment by remi-stripe** [comment]
@gatsbyz It's not possible to pass a negative amount today. We are working on supporting coupons overall though. I'd recommend discussing this with our support team directly: https://support.stripe.com/contact
