### ISSUE TITLE
[Typescript] Customer is not assignable to type Customer

### ISSUE THREAD

**Issue by chadwtkns** [stripe/stripe-node#907]
Im on version 8.56.0 and Im seeing an error where when I try to retrieve a customer in my sandbox account and typescript is saying that it wont allow Stripe.Customer to be returned.
![Screen Shot 2020-06-01 at 4 20 50 PM](https://user-images.githubusercontent.com/5611546/83460887-b921cf00-a424-11ea-9849-f0ee83cb4e94.png)

**Comment by cjavilla-stripe** [comment]
Hey @chadwtkns :wave:

I can see how this is a little confusing. Technically, the return value for a GET to the API with a Customer ID could either return a full customer object or a deleted customer object. The typesystem is implemented such that if you call retrieve you'll get back something that is a union of `Stripe.Customer` and `Stripe.DeletedCustomer`. In order to specify the type directly you'd need:

```ts
  const customer: Stripe.Customer | Stripe.DeletedCustomer = await stripe.customers.retrieve('cus_xxx');
```

Or to just leave off that explicit type there.

**Comment by madmacc** [comment]
I have the same issue.  I am upgrading to the current API version and I am not sure how to access the value on my customer object as it now just shows the union of the properties.
I am getting the following error:

```
Property 'metadata' does not exist on type 'Customer | DeletedCustomer'.
  Property 'metadata' does not exist on type 'DeletedCustomer'.
```

**Comment by vvo** [comment]
Hey there, even when I use the type union, then I get:
![image](https://user-images.githubusercontent.com/123822/102907036-beed0980-4475-11eb-8797-721d5a23fc24.png)

**Comment by vvo** [comment]
Nevermind, you need to do this:

```js
const stripeCustomer:
      | Stripe.Customer
      | Stripe.DeletedCustomer = await stripe.customers.retrieve(
      organization.stripe.customerId,
    );

    if (stripeCustomer.deleted !== true) {
      console.log(stripeCustomer.name);
    }
```

which is fine :)

**Comment by sindri55** [comment]
Thank you, Thank you, Thank you!
Worked perfectly after 8 hours of research.

> Nevermind, you need to do this:
> 
> ```js
> const stripeCustomer:
>       | Stripe.Customer
>       | Stripe.DeletedCustomer = await stripe.customers.retrieve(
>       organization.stripe.customerId,
>     );
> 
>     if (stripeCustomer.deleted !== true) {
>       console.log(stripeCustomer.name);
>     }
> ```
> 
> which is fine :)
