### ISSUE TITLE
After creating a Subscription Schedule, invoices.retrieveUpcoming(...) returns a draft Invoice object with no id property

### ISSUE THREAD

**Issue by bendiy** [stripe/stripe-node#912]
Node.js Version: 10.16.0
Stripe Node.js Library Version: 8.55.0

I would like to call `stripe.invoices.finalizeInvoice(...)` to immediately charge a customer without the 1 hour delay between creating a Subscription Schedule and creating the Invoice. This is documented here:
https://stripe.com/docs/billing/invoices/overview#finalized

When I call this:
```js
const upcomingInvoice = await stripe.invoices.retrieveUpcoming({
  customer: 'cust_some_id_here',
  // schedule: 'sub_some_id_here', // Also tried with the Subscription Id, same result.
});
```

There is no `id` property on the `upcomingInvoice ` object:
![invoice](https://user-images.githubusercontent.com/571574/83697175-94139480-a5bb-11ea-9d92-2def52135602.png)

I can't call `stripe.invoices.finalizeInvoice(...)` without an `id`. The documentation for `stripe.invoices.retrieveUpcoming(...)` shows an `id` in the `response` object:
https://stripe.com/docs/api/invoices/upcoming#upcoming_invoice

Is this a bug? How else do you finalize an Invoice for a new Subscription Schedule?

**Comment by remi-stripe** [comment]
@bendiy You can not finalize an upcoming invoice. The upcoming invoice is not a real invoice, it simply simulates what the invoice will look like in the future the next time the Subscription renews.

I'd recommend reaching out to our support team directly to discuss this instead: https://support.stripe.com/contact

**Comment by bendiy** [comment]
@remi-stripe Thanks for clarifying.
What I was seeing did not match the documentation. I'll try a different approach.
