### ISSUE TITLE
Faulty types for CustomerUpdateParams

### ISSUE THREAD

**Issue by oakgary** [stripe/stripe-node#915]
Version 8.60.0

The interface CustomerUpdateParams, used in stripe.customers.update, uses the [AdressParam](https://github.com/stripe/stripe-node/blob/master/types/shared.d.ts#L122) interface for its address property.

But the AccountAddressParam interface, which AdressParam inherits from, does not allow null values which are necessary to clear values.

This leads to following snippet showing a type error even though it is valid.
```
await stripe.customers.update('XXX', {description: null})
```

The AccountAddressParam interface is not used anywhere else as far as I can see and could therefore be expanded to allow null values.

**Comment by kamil-stripe** [comment]
`description` field in `CustomerUpdateParams` (https://github.com/stripe/stripe-node/blob/ef86068e/types/2020-08-27/Customers.d.ts#L592) and all fields (except `line1`) in `AccountAddressParam` are now marked as optional (https://github.com/stripe/stripe-node/blame/master/types/shared.d.ts#L122). Thank you for your report!
