### ISSUE TITLE
Get charge object/id from charge failure

### ISSUE THREAD

**Issue by grydstedt** [stripe/stripe-node#92]
Is there any way to get the corresponding charge object or charge id from a failed attempt to call charge.create?

**Comment by ykessler** [comment]
This no longer works. Is there another way?

**Comment by remi-stripe** [comment]
@ykessler This should still work. I'd recommend talking to our support team directly and they can help investigate: https://support.stripe.com/email

**Comment by ykessler** [comment]
I apologize- my issue is with the Ruby API. Please disregard.
