### ISSUE TITLE
TypeError: Cannot read property 'requestContent' of undefined

### ISSUE THREAD

**Issue by yilmazbingo** [stripe/stripe-node#923]
`I` have ssr-react-node-webpack application. I successfully posted transaction however I got below error ont he console. 

 `GEThttps://checkout.stripe.com/api/color?image_url=https%3A%2F%2Fsvgshare.com%2Fi%2FCUz.svg&key=pk_test_9esfXPUUapdcfgk2tr4rZenkDI00Cjdiu3O6&locale=en-US 400`

when I clicked on it, on the sources tab i got this
 `TypeError: Cannot read property 'requestContent' of undefined`

here is my client-side code:

```
`import React from "react";
import StripeCheckout from "react-stripe-checkout";
import axios from "axios";

const StripeCheckoutButton = ({ price }) => {
  const priceForStripe = price * 100;
  const publishableKey = process.env.STRIPE_PUBLIC_API_KEY;
  const onToken = (token) => {
    axios({
      url: "payment",
      method: "post",
      data: { amount: priceForStripe, token: token },
    })
      .then((response) => {
        alert("payment was successful");
      })
      .catch((error) => {
        console.log("payment error", JSON.parse(error));
        alert("there was issue with your payment");
      });
  };

  return (
    <StripeCheckout
      label="Pay Now"
      name="BINGO Wear"
      billingAddress
      shippingAddress
      image="https://svgshare.com/i/CUz.svg"
      amount={priceForStripe}
      description={`Your total is $${price} `}
      panelLabel="Payment time"
      token={onToken}
      stripeKey={publishableKey}
    />
  );
};`

export default StripeCheckoutButton;

Here is the endpoint:

 `server.use(bodyParser.json());
  server.use(bodyParser.urlencoded({ extended: true }));
  server.post("/payment", (req, res) => {
    const body = {
      source: req.body.token.id,
      amount: req.body.amount,
      currency: "usd",
    };
    stripe.charges.create(body, (stripeErr, stripeRes) => {
      if (stripeErr) {
        res.status(500).send({ stripeErr });
      } else {
        res.status(200).send({ success: stripeRes });
      }
    });
  });``
```

**Comment by remi-stripe** [comment]
@yilmazbingo You should just ignore this error, it happens when we try to fetch the image I think. This is unrelated to stripe-node as this happens client-side for Legacy Checkout.

Also, note that you are using Legacy Checkout which has been deprecated actively for well over a year now. You should move to the newer version instead: https://stripe.com/docs/payments/checkout

If you have any follow up questions, I'd recommend talking to our support team directly https://support.stripe.com/contact
