### ISSUE TITLE
Typedef: Checkout.Session.billing_address_collection

### ISSUE THREAD

**Issue by JustinTRoss** [stripe/stripe-node#925]
https://github.com/stripe/stripe-node/blob/8cc596f065ae94d960479113f37eb75b42bfab0d/types/2020-03-02/Checkout/Sessions.d.ts#L23

I believe this could be specified further as the following:

```
billing_address_collection: 'auto' | 'required' | null;
```

**Comment by remi-stripe** [comment]
@JustinTRoss Thanks for reaching out! You're definitely right that we could be more specific. The reason we're not is because this is currently defined as a string, not an enum, in our API. I'll flag this internally so that we can move to an enum and get better types definitions in the future!

**Comment by remi-stripe** [comment]
Closing this one as it has now been fixed https://github.com/stripe/stripe-node/blob/master/types/2020-03-02/Checkout/Sessions.d.ts#L32
