### ISSUE TITLE
Missing instant_available on Stripe.Balance type definition

### ISSUE THREAD

**Issue by stuisme** [stripe/stripe-node#931]
According to https://stripe.com/docs/connect/instant-payouts there should be a property called `instant_available` I have verified this property is returned from the sdk, however it is unavailable in the type definition (https://github.com/stripe/stripe-node/blob/master/types/2020-03-02/Balance.d.ts)

**Comment by remi-stripe** [comment]
@stuisme Thanks for reaching out! This feature was in beta for a long time and it looks like when we shipped it we never shipped the `instant_balance` property in our docs public. We'll work on a fix but this will take a while as the Typescript definitions are generated from our public openapi spec and not done by hand!

**Comment by stuisme** [comment]
Thank you for the quick response. Look forward to the update.

**Comment by kamil-stripe** [comment]
The property was added in https://github.com/stripe/stripe-node/commit/7ff885ec45e739543caee2a6274d35ca2a9824f8. Closing this issue.
