### ISSUE TITLE
"stripe.webhooks.constructEvent" always throwing "No signatures found..." (Using feathersJs)

### ISSUE THREAD

**Issue by DEVtrust** [stripe/stripe-node#932]
I am always getting below error with stripe.webhooks.constructEvent function:
"No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing.

I am using feathersJs web-framework. And trying to verify the stripe webhook signature and following this document https://stripe.com/docs/webhooks/signatures.
I wrote a hook and pass all required parameters in stripe.webhooks.constructEvent(hook.data, sig, endpointSecret), hook code is below:
``` 
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html
​
module.exports = function (options = {}) {
  // eslint-disable-line no-unused-vars
  return function stripeWebhookValidation(hook) {
    let stripeOptions = hook.app.get("stripe");
    const stripe = require("stripe")(stripeOptions.publicKey);
    const { GeneralError } = require("@feathersjs/errors");
    const endpointSecret = stripeOptions.customerEndpointSecret;
    const sig = hook.params.headers["stripe-signature"];
    try {
      //1st parameter of constructEvent need to be req.body
      stripe.webhooks.constructEvent(hook.data, sig, endpointSecret);
    } catch (err) {
      throw new GeneralError(
        `Error getting events -----------: ${err.message}`
      );
    }
    return Promise.resolve(hook);
  };
```

- **Node Version** : v11.10.1
- **Stripe node library version**: 8.67.0
- **Problem Replication steps:** Send a test event to a webhook endpoint ({host}/stripe-customer) and verifying the stripe signature.

**Comment by paulasjes-stripe** [comment]
The most likely thing happening here is that your framework is parsing the body as JSON. `constructEvent` requires the raw, unparsed body you receive from the request to verify the signature. 

If you log out `hook.data`, you'll probably get a JSON blob. To verify you have the raw body you'd get something like `<Buffer 28 72 10...`.

I'm not familiar with feathersJS, but you should look into preventing the framework from parsing the body for this particular endpoint, as we do in this example using express: https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/node-express/express.js#L20

**Comment by remi-stripe** [comment]
Going to close out for now, but let us know if you're still stuck! You can also talk to our support team directly and they can help investigate the issue: https://support.stripe.com/contact

**Comment by dnguyenlearning** [comment]
@DEVtrust you have the solution? I have the same issue with featherjs
