### ISSUE TITLE
'Invalid JSON Received from the Stipe API' - stripe.oauth.token

### ISSUE THREAD

**Issue by Bendrog** [stripe/stripe-node#935]
### Environment
**Node:** Version 12.16.2
**Stripe:** Version 8.67.0 
_______
### The Code

I used the code directly from the [Documentation](https://stripe.com/docs/connect/express-accounts#connect-users)

I tried multiple ways but still stuck here. Is it a probem from the API or do I just miss-use it ?

**Controller**
```javascript
    async getAuthStripe(ctx) {
        const stripe = require('stripe')(process.env.STRIPE_SK_TEST);

        const response = await stripe.oauth.token({
            grant_type: 'authorization_code',
            code: process.env.STRIPE_CLIENT_ID,
          });
          console.log(response);

        return response.stripe_user_id;
    }
```

The code breakes before the `console.log()`, and there is no way to log this response
**Console Error**
```
error Error: Invalid JSON received from the Stripe API
```

_______
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Node library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your Node version and the version of the Stripe Node library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by cjavilla-stripe** [comment]
Hey @Bendrog Thanks for question. I'm surprised you're seeing that error, but also. The value for `code` here should not be the Connect Client ID, but rather the authorization code returned in the OAuth flow. That would not be stored in environment variables, would start with `ac_` and is passed back to you via the redirect URI as shown in Step 3 of the guide you've linked.

I just tried to reproduce this with the same version of  stripe-node and was unable.

Can you try wrapping the call to token in a try/catch block?

```js
  try {
    const response = await stripe.oauth.token({
	grant_type: 'authorization_code',
	code: 'ac_xxx', // this is from the query string parameters on your redirect_uri
    });
    console.log(response);
    var connected_account_id = response.stripe_user_id;
  } catch(e) {
   console.log(e);
  }
```

**Comment by Bendrog** [comment]
I completely miss understood how to use the API. 
Thanks for your fast answer.

I am thinking of not doing anything with this code returned from _STRIPE_ after being redirected, and get the stripe_user_id from a webhook
