### ISSUE TITLE
Stripe transfer insufficient funds

### ISSUE THREAD

**Issue by samtjong23** [stripe/stripe-node#936]
Hi

I am using stripe transfer in my own personal project where I am making a marketplace kind of application to provide sellers with a platform to sell their products. How I envision the payment system to work is that buyers will make payment to the platform (me) and once payment is completed I will make transfers to sellers accordingly.

I am using stripe checkout also and when I want to charge buyers, it will create a paymentintent object. The problem is, once I receive the update that the buyer has made payment, it will be added to my stripe balance but I cannot transfer the funds straightaway as it seems that I will have to wait a few days before I can actually use the it.

As such, I cannot transfer the money to sellers straightaway. I also found out that theres this source transaction field which when I provide with id of the charge object used to charge the buyer, will help to transfer the funds immediately when it becomes available regardless of whether my balance is sufficient or not at the time the transfer object is created.

However im not using charge object, I am using paymenintent object instead since stripe checkout tells me to use paymentintent. May I know if theres a similar method as source transaction but for paymentintent? Or any other alternative solution that can help me to make transfer to sellers immediately when the buyer makes payment?

Any help is greatly appreciated thanks!

**Comment by remi-stripe** [comment]
@samtjong23 Thanks for reaching out! Github issues should be limited to bugs and feature requests with the stripe-node library. Your question is more of a product question on how to use Stripe which would be better suited for our support team. I'm going to close this ask and you can contact our support team directly here instead: https://support.stripe.com/contact

Just to unblock you: even though you use `PaymentIntent`, that still creates a `Charge` object. And so you can create a Transfer and pass `source_transaction: "ch_123"` which would come from the PaymentIntent's `charges` collection: https://stripe.com/docs/api/payment_intents/object#payment_intent_object-charges

**Comment by samtjong23** [comment]
Alright thanks a  lot for helping!
