### ISSUE TITLE
detaching a payment method creates a new payment method (????)

### ISSUE THREAD

**Issue by appjitsu** [stripe/stripe-node#943]
node: v12.14.0
stripe: v8.63.0

I use the following call to get a list of payment methods for a customer and display those in my ui.

```
const paymentMethods = await stripe.paymentMethods.list({
      customer: customerId,
      type: 'card',
    });
```

Clicking "delete" on a payment method calls:

`const detach = await stripe.paymentMethods.detach(methodId);`

which returns:

```
{
  "id": "pm_..............................................",
  "object": "payment_method",
  "billing_details": {},
  "card": {},
  "country": "US",
  "exp_month": 4,
  "exp_year": 2024,
  "fingerprint": "................",
  "funding": "credit",
  "generated_from": null,
  "last4": "4242",
  "networks": {},
  "created": 1591728022,
  "customer": null,
  "livemode": false,
  "metadata": {},
  "type": "card"
}
```

Which shows customer === null

When I call paymentMethods.list again the same payment method is still there. How can I delete the payment method?

Thanks!

**Comment by appjitsu** [comment]
Well its not the exact same payment method. After detaching the id of the payment method id is changing.

Like from "pm_1GsCHZDSHonWMPISVUzFHz7f" pre-detach, to "pm_1GsAM2DSHonWMPISw8uzAXqN" post-detach.

**Comment by appjitsu** [comment]
the netlify function code

```
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY, {
  maxNetworkRetries: 10 // retry any requests if there is a connection problem
});

exports.handler = async (event, context) => {
  console.log('stripe-detach-payment-method -> event', event.body);
  const { methodId } = JSON.parse(event.body);
  console.log('stripe-detach-payment-method -> methodId', methodId);

  if (!methodId) {
    return {
      statusCode: 400,
      body: JSON.stringify({
        error: 'missing methodId',
      }),
    };
  }

  try {
    const detach = await stripe.paymentMethods.detach(methodId);
    console.log('stripe-detach-payment-method -> detach', JSON.stringify(detach));
    if (detach.error) {
      throw new Error(detach.error);
    }

    return {
      statusCode: 200,
      body: JSON.stringify({
        success: true,
      }),
    };
  } catch (error) {
    console.log('send-email -> error', error);
    return {
      statusCode: 200,
      body: JSON.stringify({
        error: error.message,
      }),
    };
  }
};
```

**Comment by remi-stripe** [comment]
@appjitsu This doesn't look like a bug with stripe-node. Looking into the PaymentMethods you mentioned, your code just seems to explicitly confirm a SetupIntent each time and this will attach the new PaymentMethod by default after it succeeds since you passed `usage: "off_session"`.

It's a bit tricky to say what's going on with only a small part of your code unfortunately but the customer has many active cards right now and so you likely just didn't notice they kept being added?

I'd recommend talking to our support team directly for help instead though and you can contact them here: https://support.stripe.com/contact
