### ISSUE TITLE
Typedef for assert_capabilities in OAuthTokenParams

### ISSUE THREAD

**Issue by vahidfazelrezai** [stripe/stripe-node#944]
It seems `assert_capabilities` on the `OAuthTokenParams` is typed as an optional `string` here:

https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/types/OAuth.d.ts#L323

Meanwhile [in documentation](https://stripe.com/docs/connect/express-accounts#verify-the-accounts-capability) it appears to be `string[]`. I believe the typedef should be updated to match the documentation.

**Comment by remi-stripe** [comment]
@vahidfazelrezai Thanks for the heads up and sorry for the mixup on that one! @paulasjes-stripe will prepare a fix and we'll get this released tomorrow!
