### ISSUE TITLE
You must pass one of plan, price, or price_data ?

### ISSUE THREAD

**Issue by harvey56** [stripe/stripe-node#945]
_If you are reporting a bug, please include your Node version and the version of the Stripe Node library you're using, as well as any other details that may be helpful in reproducing the problem._

I'm unable to create a subscription for a customer. Here's the create subscription code :

```
const newSubscription = await stripe.subscriptions.create({
      customer: customer_id,
      items: [{ plan: premium_plan.id }, { quantity: 1 }],
    });

```

premium_plan is successfully retrieved just before. I tried to use price instead of plan. Same error message. Are there some new breaking changes with stripe ?

```
message: 'You must pass one of plan, price, or price_data.',
type: 'invalid_request_error'
```

node v. 10.16.0 // stripe v.8.68.0

**Comment by remi-stripe** [comment]
@harvey56 The problem with your code is that you should be passing `quantity` and `plan` in the same hash, not separately. Your code should be:

```
const newSubscription = await stripe.subscriptions.create({
  customer: customer_id,
  items: [
    { plan: premium_plan.id, quantity: 1 }
  ],
});
```
