### ISSUE TITLE
Vue: stripe.elements() is not a function

### ISSUE THREAD

**Issue by mattfrey6** [stripe/stripe-node#949]
Hey there,

So I am trying to implement adding client card info in a component, and my function is the same as shown in the docs to create it, and then I was intending on using v-html on a div to render the HTML.

**When run:** `stripe.elements() is not a function`

### JS
```
<script>
 import Stripe from 'stripe';

.....
data:() => {
 cardElement: null
...
},
methods: {
generateCardElement() {
        const stripe = Stripe(process.env.VUE_APP_PK);
        const elements = stripe.elements();
        const cardElement = elements.create('card');
        this.cardElement = cardElement;
}
...
</script>
```

### HTML
```
<div v-if="cardElement" v-html="cardElement"></div>
```

### What I have tried

- using the `cardElement.mount('#cardElement')` in the function and adding the id `cardElement` to the div instead of `v-html`
- loading the script from `js.stripe.com/v3/` instead of the NPM package.

Any suggestions on this? My next thought is to import stripe though the `main.js` file. 

Thanks!

**Comment by mattfrey6** [comment]
Also, I had read on Stackoverflow that this message usually means that Stripe isn't loaded

**Comment by richardm-stripe** [comment]
Hi @mattfrey6
I think your intention is to use the client-side [stripe.js](https://github.com/stripe/stripe-js) not stripe-node, the server-side stripe-node SDK.
Try doing
```shell
npm install @stripe/stripe-js
```
and 
```javascript
import Stripe from '@stripe/stripe-js`
```

**Comment by mattfrey6** [comment]
@richardm-stripe :thumbsup: Thanks! I just added it and am getting a different error now: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

So just trying to work through that.

**Comment by mattfrey6** [comment]
Get an error: `Error in callback for watcher "formPhase": "TypeError: Object(...) is not a function"` when importing as import Stripe from '@stripe/stripe-js`
