### ISSUE TITLE
stripe.subscriptions.create Missing required param: customer.

### ISSUE THREAD

**Issue by hamza39460** [stripe/stripe-node#964]
Hi,
I am following the Stripe guide to create subscription using destination charges (https://stripe.com/docs/connect/subscriptions) but I am getting error  Missing required param: customer. I have checked the logs @ stripe dashboard the request post body for subscriptions.create is also empty following is my code
`exports.createSubscription = functions.https.onCall(async (data,context)=>{
const subscription = await  stripe.subscriptions.create(
{
customer: data.buyersID,
items : [{price:data.priceID}],
application_fee_percent:10,
default_payment_method: data.paymentMethod_id,
stripe_account: data.stripe_user_id
}
).then((value)=>value);
return subscription;
});`

**Comment by paulasjes-stripe** [comment]
Hi there, this issues page is for bugs and problems with the stripe-node library specifically. In your case this seems to be related to the Stripe API instead so I'm closing this.

Please reach out to Stripe support directly and provide them with your code and a request ID (looks like req_123) so they can look into this and help you figure out what went wrong: https://support.stripe.com/contact
