### ISSUE TITLE
Expand param is not working (ProductListParams)

### ISSUE THREAD

**Issue by mykolavorobiov** [stripe/stripe-node#971]
I'm trying to use `expand` param. Validation is working, but I don't receive prices in product objects.
Code from example:
`stripe.products.list(
  {
    limit: 3,
    expand: ['data.prices']
  },
  function(err, response) {
    if (err) {
      return console.log(err);
    }
    console.log(response)
  }
);`.
p.s.
https://stripe.com/docs/api/expanding_objects

**Comment by cjavilla-stripe** [comment]
Hey there @mykolavorobiov!

Thanks for writing in. The Product object [1] does not currently support expanding related prices. Instead you'll need to iterate over each product and fetch the list of related prices.

```js
const prices = [];
stripe.products.list({limit: 20})
  .autoPagingEach(function(product) {
    stripe.prices.list({limit: 20, product: product.id})
      .autoPagingEach(function(price) {
        prices.push(price);
      });
  });
```
[1] https://stripe.com/docs/api/products/object
