### ISSUE TITLE
Missing type definitions for balanceTransaction.retrieve method

### ISSUE THREAD

**Issue by trurl-master** [stripe/stripe-node#978]
The correct way of retrieving a transaction, according to the Docs is as follows:
```javascript
stripe.balanceTransactions.retrieve(
  transactionId,
  function(err, balanceTransaction) {
    // asynchronously called
  }
);
```

Which gives the following type error:
```
No overload matches this call.
  Overload 1 of 2, '(id: string, params?: BalanceTransactionRetrieveParams | undefined, options?: RequestOptions | undefined): Promise<BalanceTransaction>', gave the following error.
    Type '(err: any, balanceTransaction: any) => void' has no properties in common with type 'BalanceTransactionRetrieveParams'.
  Overload 2 of 2, '(id: string, options?: RequestOptions | undefined): Promise<BalanceTransaction>', gave the following error.
    Type '(err: any, balanceTransaction: any) => void' has no properties in common with type 'RequestOptions'.ts(2769)
Parameter 'balanceTransaction' implicitly has an 'any' type.ts(7006)
```

After looking at the https://github.com/stripe/stripe-node/blob/master/types/2020-03-02/BalanceTransactions.d.ts I think it may give a similar error for the `list` method also

**Comment by cjavilla-stripe** [comment]
Hey @trurl-master! 

Thanks for the feedback. You're totally right that the docs and the type definitions are a bit out of line right now. This is true in any case the callback function is used. This callback style is something we're moving away from and instead recommending the async/await pattern.

I expect we'll update the docs soon, but for now, the best approach would be to use the following, which should match either of those definitions.

```js
const balanceTransaction = await stripe.balanceTransactions.retrieve(
  transactionId,
);
```
