### ISSUE TITLE
Typescript access to `lastResponse` headers

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-node#983]
```
stripe@8.86.0
Node v10.10.0
```

Hi Stripe team,

Is there a way in typescript to get the response headers? For example, in the [docs](https://stripe.com/docs/api/request_ids?lang=node) it specifies:

```javascript
var customer = await stripe.customers.create();
console.log(customer.lastResponse.requestId);
```

But in my application, `lastResponse` isn't part of the typescript definitions:

![image](https://user-images.githubusercontent.com/7410770/90317936-c1a18600-defa-11ea-901c-6716e6e807e0.png)

Am I accessing those properties incorrectly, or is that not supported (yet) for the Typescript integration?

**Comment by remi-stripe** [comment]
@davidbielik It's not something we've added to the Typescript definitions for now as we focused those definitions on the core API parameters and properties. I'm going to tag this as a future improvement though and sync internally to see if we could implement this!
