### ISSUE TITLE
Using Internal Coins with the subscription to get the discount

### ISSUE THREAD

**Issue by Amaanuddin** [stripe/stripe-node#985]
We are having an internal coin/credit system. Users can use those coins and get a discount.

But in stripe, the only way to get the discount is by using coupons.

It would be great if there is an support for internal coins because there are lot of applications that have internal coins and user can use that to get a discount on subscription.

**Comment by paulasjes-stripe** [comment]
I'm closing this as this isn't an issue with the stripe-node library but instead a feature request for the Stripe API. Please direct those suggestions and questions to Stripe support instead: https://support.stripe.com/contact
