### ISSUE TITLE
constructEvent is not working in the example

### ISSUE THREAD

**Issue by stanleyyuenyiu** [stripe/stripe-node#989]
im using the provided example https://github.com/stripe/stripe-node/tree/master/examples/webhook-signing to check the sign (without changing any code, but just put the correct secret

**here is my test body that grep from the webhook request**
`{
    "id": "evt_1HI8Y3G18iuNs10OgnHen3OH",
    "object": "event",
    "api_version": "2020-03-02",
    "created": 1597909859,
    "data": {
        "object": {
            "id": "pi_1HI8Y3G18iuNs10OOPlF55v4",
            "object": "payment_intent",
            "amount": 21000,
            "amount_capturable": 0,
            "amount_received": 0,
            "application": null,
            "application_fee_amount": null,
            "canceled_at": null,
            "cancellation_reason": null,
            "capture_method": "automatic",
            "charges": {
                "object": "list",
                "data": [],
                "has_more": false,
                "total_count": 0,
                "url": "/v1/charges?payment_intent=pi_1HI8Y3G18iuNs10OOPlF55v4"
            },
            "client_secret": "pi_1HI8Y3G18iuNs10OOPlF55v4_secret_fBJ4VKg0NttX3X5wbN1BHmfoL",
            "confirmation_method": "automatic",
            "created": 1597909859,
            "currency": "hkd",
            "customer": null,
            "description": "Order #: SMY1597909859",
            "invoice": null,
            "last_payment_error": null,
            "livemode": false,
            "metadata": {},
            "next_action": null,
            "on_behalf_of": null,
            "payment_method": null,
            "payment_method_options": {
                "card": {
                    "installments": null,
                    "network": null,
                    "request_three_d_secure": "any"
                }
            },
            "payment_method_types": [
                "card"
            ],
            "receipt_email": null,
            "review": null,
            "setup_future_usage": null,
            "shipping": null,
            "source": null,
            "statement_descriptor": null,
            "statement_descriptor_suffix": null,
            "status": "requires_payment_method",
            "transfer_data": null,
            "transfer_group": null
        }
    },
    "livemode": false,
    "pending_webhooks": 2,
    "request": {
        "id": "req_OEtzgZwvwBtLpK",
        "idempotency_key": null
    },
    "type": "payment_intent.created"
}`

**here is the stripe-signature**
t=1597909859,v1=97c7b3cd1fb89cc553c5347fe2599be12d343819922502c2a6c3fece9c672133,v0=bda62fb3e5e6aeeba70a6c3882348c75b848ef99bc6855739cdc95c5639f2a0b

**here is error**
Webhook signature verification failed. StripeSignatureVerificationError: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node

the interesting thing is if i using generateTestHeaderString with the same body and timestamp
if pass the verification

**Comment by paulasjes-stripe** [comment]
Hi stanleyyuenyiu, that webhook event body has been parsed, which means that you aren't passing the raw body to the `constructEvent` function.

Are you definitely running the _exact_ code from https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/node-express/express.js or did you add some middleware somewhere?

**Comment by stanleyyuenyiu** [comment]
im 100% using the same code

becoz i just clone it and run, except i put my env var

**Comment by stanleyyuenyiu** [comment]
beside i just open the stripe lib to check, it can either raw body (buffer) or a json string, and  it just combine timestamp + "." + jsonstring (as it will convert from buffer to utf8 string), and final run this code

  crypto
      .createHmac('sha256', secret)
      .update(payload, 'utf8')
      .digest('hex');

**Comment by paulasjes-stripe** [comment]
If you're using postman to send the event to your local server, then you are probably missing the `stripe-signature` header. A better way to test would be to use the Stripe CLI to trigger events: https://github.com/stripe/stripe-node/tree/master/examples/webhook-signing#install-and-run

**Comment by stanleyyuenyiu** [comment]
as i said, i have, if i missing, how can i provide at the top

**Comment by stanleyyuenyiu** [comment]
the payload i capture by stripe dashboard, and header, i direct capture from server that callback from stripe, so do you clear my question??

**Comment by stanleyyuenyiu** [comment]
if u missing stripe-signature, the error will be  'Unable to extract timestamp and signatures from header' or 'No signatures found with expected scheme', my error is 


 'No signatures found matching the expected signature for payload.' +
          ' Are you passing the raw request body you received from Stripe?' +
          ' https://github.com/stripe/stripe-node#webhook-signing',

**Comment by paulasjes-stripe** [comment]
What happens when you send a test webhook via the dashboard at https://dashboard.stripe.com/test/webhooks ?

**Comment by stanleyyuenyiu** [comment]
No error for test webhook

Have error when stripe trigger other webhook (still under test mode, and using testing card to pay)

**Comment by stanleyyuenyiu** [comment]
let me try PHP version, see if they are same result

**Comment by stanleyyuenyiu** [comment]
findout something, if the version of the webhook is "2017-06-05", it work, if the version is "2020-03-02" , it doesnt work,

**Comment by stanleyyuenyiu** [comment]
somehow it work fine again, can close it, sorry for the trouble i made
